### ISSUE TITLE
LocalDateTime.ToString("ddd", CultureInfo.CurrentUICulture) includes trailing period on Mac

### ISSUE THREAD

**Issue by kentcb** [nodatime/nodatime#1001]
Here's a weird one. The following test works on Windows but fails on Mac:

```C#
[UseCulture("en-AU")]
[Fact]
public void repro()
{
    var localDateValue = new LocalDate(2017, 08, 01);
    var output = localDateValue.ToString("ddd", CultureInfo.CurrentUICulture);

    // on Mac, this fails because output is "Tue."
    Assert.Equal("Tue", output);
}
```

Note that using `CultureInfo.InvariantCulture` _does_ work on both platforms.

Honestly not too sure whether this is anything to do with NodaTime, but thought I'd start here.

**Comment by jskeet** [comment]
I strongly suspect that's just the abbreviated day name in that culture.

Could you log `new DateTime(2017, 8, 1).ToString("ddd", CultureInfo.CurrentUICulture)`?

**Comment by kentcb** [comment]
```C#
Information("Culture name '{0}', display name '{1}'.", CultureInfo.CurrentUICulture.Name, CultureInfo.CurrentUICulture.DisplayName);
Information("ddd DateTime: {0}", new DateTime(2017, 8, 1).ToString("ddd", CultureInfo.CurrentUICulture));
```
Output:
```
Culture name 'en-US', display name 'English (United States)'.
ddd DateTime: Tue
```
However, this is running in Bitrise. I am seeing the same code failing unit tests sometimes and not others. I'm wondering whether the server might be in different regions - will keep digging.

**Comment by jskeet** [comment]
That's using en-US though - isn't your failing test using en-AU?

**Comment by jskeet** [comment]
Maybe add a BCL-based test along with the Noda Time test? Then I'd expect both to behave the same way.

**Comment by kentcb** [comment]
Ah, my bad, I misunderstood your request and confused myself due to another issue I'm currently looking into.

OK, so I added these two tests to my suite:
```C#
[UseCulture("en-AU")]
[Fact]
public void enAU()
{
    Assert.Equal("en-AU", CultureInfo.CurrentUICulture.Name);
    var result = new DateTime(2017, 8, 1).ToString("ddd", CultureInfo.CurrentUICulture);

    Assert.Equal("Tue", result);
}

[UseCulture("en-US")]
[Fact]
public void enUS()
{
    Assert.Equal("en-US", CultureInfo.CurrentUICulture.Name);
    var result = new DateTime(2017, 8, 1).ToString("ddd", CultureInfo.CurrentUICulture);

    Assert.Equal("Tue", result);
}
```
Executing these on my Windows machine is 💯 but executing them on Bitrise fails with:
```
XXX.UnitTests.TempFixture.enAU [FAIL]
  Assert.Equal() Failure
			   ↓ (pos 3)
  Expected: Tue
  Actual:   Tue.
			   ↑ (pos 3)
  Stack Trace:
	  at XXX.UnitTests.TempFixture.enAU () [0x00033] in <7a738da6c1d54419b85c51d8b4b377b6>:0 
	  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
	  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <ac812cae460544af83bd6cf54c5eee87>:0 
```

**Comment by jskeet** [comment]
Right - in that case, it looks like the Bitrise machines are configured with an abbreviation including the "." for en-AU. Given that Noda Time is now behaving the same way as the BCL, I'm going to close this as a non-issue. Of course, you may want to talk to Bitrise about where that's coming from...

**Comment by kentcb** [comment]
Thanks Jon - appreciate your assist.
