### ISSUE TITLE
"NodaTime-All" solution won't compile under VS 2017

### ISSUE THREAD

**Issue by carlosschults** [nodatime/nodatime#1004]
Creating new issue as asked by @jskeet on #918.

Hi, all.

I recently cloned the nodatime project and tried to build the main solution and run the tests, but I had no luck.

I'm currently getting almost 4 thousand errors, mainly related to the "BenchmarkDotNet" namespace, which can't be found.

When I try to build project by project, everything works fine, except for:

- **NodaTime.Benchmarks**: I get errors related to the "BenchmarkDotNet" namespace not being found;
- **NodaTime.Test**: It seems that NUnit is missing (?).

I **did** manage to build using .NET Core SDK, and it worked just fine.

I'm running Visual Studio Community 2017, under Windows 10. I have .NET Core SDK version 2.0 installed.

Appreciate any help. Thanks :)

**Comment by jskeet** [comment]
Sounds like it's not restoring nuget packages. Maybe there's a "trust projects" setting or something? Will try from a fresh clone when I'm back home.

**Comment by carlosschults** [comment]
Yeah, that's right. Just closed and reopened the solution and set the output window to show the messages for Nuget. This is what I get:

> VS2017 The operation failed as details for project NodaTime.NzdPrinter could not be loaded.

> VS2017 The operation failed as details for project NodaTime.Testing could not be loaded.

**Comment by carlosschults** [comment]
OK, as it turned out, this was a bug in Visual Studio, and it's already fixed. I've upgraded my VS to version 15.4.1 and now everything is building :D

**Comment by jskeet** [comment]
Glad to hear it :) Closing.
