### ISSUE TITLE
Consider adding a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by carlosschults** [nodatime/nodatime#1026]
...and/or updating the docs to provide a little bit more help for first-time contributors.

(The [developer guide](https://nodatime.org/developer/) has useful information, but IMHO could use a little improvement, particularly the "Building and Testing" page.)

Topics that could be covered:
- talk (briefly) about the project's structure, how things are organized, etc.
- usage and purpose of the attributes.
- tests: how to run, preferred naming conventions, etc
- general guidelines: how granular should PRs/commits be? Should every PR require an issue?, etc
- basic github tips (forking, cloning, setting an upstream, etc)

[Example of a nice contributing.md file](https://github.com/octokit/octokit.net/blob/master/CONTRIBUTING.md)

**Comment by jskeet** [comment]
Sorry, I didn't see this before for some reason.

Yes, the developer guide is fairly badly out of date. (One problem with more documentation is that whenever we change the structure a bit, I need to remember which files to update :)

I think the "basic github tips" may be a part I'd push back on - it feels like the kind of thing where we could guess which specific bits of git people aren't used to, but always get it wrong. Certainly something around the expectation being "fork in github, create a branch off master, create PR from that" would be worth doing though.

**Comment by jskeet** [comment]
We might want to work out a way to show the same file (or most of it?) in the web site too...

**Comment by carlosschults** [comment]
> One problem with more documentation is that whenever we change the structure a bit, I need to remember which files to update

I'd happily help with that :)

> Certainly something around the expectation being "fork in github, create a branch off master, create PR from that" would be worth doing though.

Yeah, that's basically what I had in mind.

So.....can I send a PR? :)

**Comment by jskeet** [comment]
Of course! (If the PR deals with the dev guide as well, that would be even better - but that one may be more appropriate for me to tackle...)

**Comment by carlosschults** [comment]
I guess I'll just deal with the CONTRIBUTING file for now, since it seems the easiest to quickly solve and get it out the way.

So, what do you think should definitely be in the file?

**Comment by jskeet** [comment]
Your set of topics sounded reasonable to me - although I wouldn't say very much about the attributes, other than to mention that they exist. They probably merit a separate page (or just refer to the documentation).

**Comment by carlosschults** [comment]
So, regarding the tests. I try to use NUnitTestAdapter (both the Visual Studio extension and the Nuget package) to run the tests and failed. 

I don't fully understand the reason for that. Does NUnit have an issue with .net core apps? Do you have some suggestion on how to document this in the contributing guidelines?

**Comment by jskeet** [comment]
NUnit used to. I've managed to get it working with the test adapter (at least so that I could run dotnet test) but there were issues in terms of filtering. (We still have an issue to revisit that - #967.) For the moment I think it's simplest just to document that the tests are run as a .NET Core console app.

**Comment by jskeet** [comment]
This was fixed in #1036.
