### ISSUE TITLE
NodaTime 2.2.2 NuGet package appears to be built "non-optimized"

### ISSUE THREAD

**Issue by jdaigle** [nodatime/nodatime#1027]
After upgrading to the NodaTime 2.2.2 NuGet package, our [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet) tests fail with the following error:

    // Validating benchmarks:
    Assembly Foo which defines benchmarks references non-optimized NodaTime

Reverting to any previous version works.

**Comment by jskeet** [comment]
Thanks for reporting this. I'll look into it as soon as I can. It may be a problem with the build scripts used when there's a new version of TZDB. (If that's the case, it'll mean rebuilding 2.1.1 and 2.0.4 as well...)

**Comment by jskeet** [comment]
Confirmed it's the debug build, by looking in ildasm - if `NodaTime.Utility.DebugPreconditionException` exists, it's the debug build.

It looks like the 1.x releases are okay, fortunately.

**Comment by jskeet** [comment]
Right, found the problem. It's easy to fix in the update scripts, but it'll need a little care when doing the releases, to get appropriate commit messages.

**Comment by jskeet** [comment]
All the new packages have now been pushed - if you update to latest, it should fix the problem. Obviously if it doesn't, please shout!
