### ISSUE TITLE
Tests are dependent on computer's Short Date format

### ISSUE THREAD

**Issue by glittle** [nodatime/nodatime#1028]
A number of the tests for dates expect a format with slashes like `6/15/2009`.  However, my computer (Windows 10) is set to Region "Canada" with a Language of "en-US" and a Short Date of "yyyy-MM-dd". I've found that when a format specifies "-" the output will be "-". However, when a format specifies "/", it seems that the output will be "-" or "/" according to the computer's settings.

For example, for the test defined in `nodatime/src/NodaTime.Test/Text/LocalDateTimePatternTest.cs` line 91: 

````
new Data(MsdnStandardExampleNoSeconds) { Pattern = "g", Text = "6/15/2009 1:45 PM", Culture = Cultures.EnUs },
```` 

I get this:

````
Failed: NodaTime.Test.Text.LocalDateTimePatternTest.AppendFormat
  Expected: x6/15/2009 1:45 PM
   But was: x6-15-2009 1:45 PM
````

As a workaround, I've changed my computer's Short Date to a format that uses "/" instead of "-" and the tests now pass.

I'm not sure if anything needs to be changed in the code, but wanted to make note that the tests may fail on computers with a different Short Date format.

**Comment by jskeet** [comment]
The language should just be "en" - "en-US" means "English in the United States". 

To clarify, have you manually changed your regional settings? Because yes, we rely on "en-US" meaning "the normal en-US rules" which I think is fairly reasonable. (The tests might also fail if you've manually changed Windows time zone data, too...)

Having said that, we do have a few cultures that are hard-coded in a particular way, so we could do that for Cultures.EnUs as well.

**Comment by glittle** [comment]
I have a fairly standard Canadian setup. I've temporary changed my Short Date format so that the tests will run okay. My only point is that relying on a system date format with "/" will not work on all computers. It's too bad that the tests are so dependent on the underlying computer's current regional settings.

**Comment by jskeet** [comment]
But I still don't understand what's going on - you having your computer set up as Canadian shouldn't affect the en-US CultureInfo. Instead, it should just be using the en-CA CultureInfo. That's the whole point of having region-specific culture info.

If you run this code, what does it print?

```csharp
Console.WriteLine(new CultureInfo("en-US").DateTimeFormat.DateSeparator);
Console.WriteLine(new CultureInfo("en-CA").DateTimeFormat.DateSeparator);
```

It *should* print "/" then "-".

**Comment by glittle** [comment]
If I set my system Short Date to "MM/dd/yyyy" or any with "/", then I get the expected "/" and "-".

If I set my system Short Date to "yyyy-MM-dd" or "dd-MMM-yy", then I get "-" and "-"!

**Comment by jskeet** [comment]
Fundamentally, it sounds like the problem is that you've got your computer set up as "I'm in the US, but with these Canadian settings" rather than "I'm in Canada". The latter is what I'd expect an actual standard Canadian setup to be, with no tweaking of short date formats required.

**Comment by glittle** [comment]
Yeah, I've seen this problem with date formats before. In any case, just a heads-up and no action required.
