### ISSUE TITLE
Investigate C# 7.2 benefits

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#1033]
It's not clear to me what the versioning implications are yet, but this could be good.

https://docs.microsoft.com/en-gb/dotnet/csharp/reference-semantics-with-value-types

**Comment by oriash93** [comment]
I'm not sure if C# 7 features are used, but I made a PR for inline out variables (#1098).
Also, in lack of a better issue to mention this, I also applied Remove and Sort Usings throught the solution, so another PR (#1099). 😃

**Comment by jskeet** [comment]
Thanks for the PRs. We can definitely use C# 7 features - the SDK is currently pinned to 2.1.4, but I can update that if necessary.

I'll try to get to the PRs in the next couple of days - sorry not to be able to review them immediately.

**Comment by oriash93** [comment]
@jskeet All good. If you're already at it, take a look at #1100.
I saw a TODO comment about a method being rewritten exactly the same 3-4 times, so I extracted it to a helper class.
(Sorry again for the lack of a better place to mention this 😀)

**Comment by oriash93** [comment]
I swear 😆 #1104

**Comment by jskeet** [comment]
Readonly structs have immediately improved the performance of some benchmarks that were using static readonly fields. We may want to use `in` parameters within the implementation (but not in the API, as I view them as dangerous) but that requires further investigation.

**Comment by jskeet** [comment]
Just tried using `in` parameters for formatting, and it made things worse - but it's possible that I didn't do it hard enough...

**Comment by jskeet** [comment]
After trying harder, it doesn't make things worse any more - but there's almost no benefit, and the code is much more complex. Closing as "we've done all we need to for C# 7.2 benefits for now."

**Comment by oriash93** [comment]
>Closing as "we've done all we need to for C# 7.2 benefits for now."

What about C# 7.3?

**Comment by jskeet** [comment]
@oriash93: I don't think there's anything in C# 7.3 that particularly affects Noda Time.
