### ISSUE TITLE
Determine and document support lifetime policy

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#1042]
In particular, we *may* need the following to be handled differently:

- Minor (in impact) bugfixes
- Major (in impact) bugfixes
- TZDB updates

Initial proposal:

We expect users within a major version to update within a year of a new minor version becoming available. After that time, the previous minor version is unsupported. For example, 1.4.0 was released on July 8th 2017, so from July 8th 2018 we won't supply new patch versions of 1.3.x.

We can probably say that minor bugfixes will only be applied to the current minor version in each major version, whereas major bugfixes and TZDB updates will be applied to all the supported minor versions.

The point at which we decide not to support 1.x at all is a whole other decision.

**Comment by malcolmr** [comment]
Seems reasonable to me (I possibly would even have gone for six months rather than 12).

Does this go in the user guide or somewhere else on the website? It's not really version-dependent, but the user guide seems like the right place?

**Comment by jskeet** [comment]
NuGet download stats (whatever they mean...) 15 days after the release of the 2018c build:

- 2.2.4: 9198
- 2.1.3: 40
- 2.0.6: 55
- 1.4.3: 314
- 1.3.6: 46

That suggests that Malcolm's 6 month suggestion is reasonable - most users who upgrade regularly appear to be on 2.2.x already, and those stuck on 1.x are on 1.4.x.  Maybe we should stop releasing 1.3.x, 2.0.x and 2.1.x builds from now...

**Comment by jskeet** [comment]
Now that the 2018d releases have just gone out, here are the "final tallies" for the 2018c releases before the later patches:

- 2.2.4: 62.381
- 2.1.3: 56
- 2.0.6: 83
- 1.4.3: 1,240
- 1.3.6: 189

It certainly looks like we could stop releasing 2.0.x and 2.1.x without disrupting many users.

**Comment by jskeet** [comment]
Okay, I think the 6 month rule is going to be the most appropriate. So:

- Latest version of all major versions will continue to get TZDB updates (at least until 1.x becomes too hard to support)
- Non-latest minor versions will get TZDB updates for 6 months after the release of their replacement

We need to work out where to document this (at bottom of the version history page, with a link from the top, maybe?) and implement it.

The consequences for now:

- 1.4 and 2.3 will continue to get updates
- 1.3, 2.0 and 2.1 will immediately cease to get updates
- 2.2 will get updates until November 20th 2018
