### ISSUE TITLE
JsonSerializer and ZonedDateTime

### ISSUE THREAD

**Issue by johnknoop** [nodatime/nodatime#1054]
Hi

When using the NodaTime JSON.net serializer, a ZonedDateTime is serialized like this:

> 2017-12-23T15:31:00+01 Europe/Stockholm

However, neither momentjs nor the plain JS Date can parse this, due to the tzdb id at the end. Now I'm not sure what would be a good solution to this. Removing the tzdb id makes it parsable, but would make it an OffsetDateTime rather than a ZonedDateTime. But at the same time, serializing to something that can't be deserialized by any standard feels equally bad.

What is your thinking around this?

**Comment by jskeet** [comment]
Well a JS Date is just an instant in time anyway... so `Instant` would be the most reasonable format to use.

Fundamentally there *is* no JSON standard for a `ZonedDateTime`, so you need to choose between not using a standard format, or not using `ZonedDateTime`. I can't really suggest a particular approach without knowing what you're trying to achieve.

**Comment by johnknoop** [comment]
Actually, a JS Date is more like an OffsetDateTime, with the offset always being the same as in your local timezone. But you can construct it using UTC or using any other offset.

I ended up changing my object model to use OffsetDateTime instead, because I had no real use for the actual tz in this case, but one idea I had was to serialize to this expression: (since I'm using moment in the frontend)

moment.tz("2017-12-21T15:34:00+01:00", "Europe/Stockholm")

Merry Christmas!

**Comment by jskeet** [comment]
I'm pretty sure a JS Date really is like a Java Date - it just stores millis since the Unix epoch, without storing an offset. Don't be fooled by the default string representation which uses the local time zone.

But I'm glad you've sorted out what you need.

**Comment by johnknoop** [comment]
I might be wrong, but it seems to have some notion of offset, since it can translate a set date with different offsets to different dates with the same offset:

```
> new Date("2017-12-23T15:31:00+05:00")
< Sat Dec 23 2017 11:31:00 GMT+0100 (W. Europe Standard Time)
> new Date("2017-12-23T15:31:00+06:00")
< Sat Dec 23 2017 10:31:00 GMT+0100 (W. Europe Standard Time)
```

Note that it always shows the date in with my local offset, but it can parse a date with any offset and translate it.

**Comment by jskeet** [comment]
Yes, you can create it via any offset - but it still only represents an instant in time. The offset isn't preserved. It's like an integer - it's just a number without any specific base, but you could parse it from hex or decimal. It's always important to understand the information in a type vs how it's constructed or its string representation.
