### ISSUE TITLE
Add web job to refresh certificate

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#1056]
For some reason I thought the Let's Encrypt extension autoupdated - it doesn't.

It's easy to do with a web job, but I don't have time right now - I'll manually refresh if that's simple, but this issue is to keep track of it needing doing. Here's the guide I'll follow eventually:

https://www.troyhunt.com/everything-you-need-to-know-about-loading-a-free-lets-encrypt-certificate-into-an-azure-website/

**Comment by jskeet** [comment]
Turns out those web jobs *are* included automatically - but I hadn't configured a couple of connection strings. The functions to renew the certs have now completed - I'm not seeing the change in my browser yet, so I'll keep this issue open until I've seen it actually take effect, but I think it should be okay.

**Comment by jskeet** [comment]
Looks like it's there now. Closing.

**Comment by malcolmr** [comment]
Monitoring concurs. Thanks for fixing :)
