### ISSUE TITLE
2018b TZDB release.

### ISSUE THREAD

**Issue by Tronald** [nodatime/nodatime#1061]
With the TZDB 2018b release, do you plan on pushing another version of 2.2 before 2.3, or are we going to have to wait for 2.3 before we receive the updated database? I am just curious how long the wait time will be. 

Love NodaTime, Thanks for all you do!

**Comment by jskeet** [comment]
Thanks for a reminder - I need to send an email to the list about what's going on with the time zone database.

But in terms of 2.3, there's still some work to be done in at least documentation, I believe. (And I think there may be some outstanding items - I need to think a bit more. Sorry, I've just finished two weeks of almost back-to-back conferences, and I'm somewhat exhausted.)

**Comment by jskeet** [comment]
(Closing this now, as hopefully that's answered the question to your satisfaction. I'll add more if I can remember what else I wanted to do before a 2.3.0 release.)
