### ISSUE TITLE
Suggested changes to Noda Time recipes page

### ISSUE THREAD

**Issue by aidanwhitehall** [nodatime/nodatime#1062]
Based on my recent initial use of Noda Time, I'd like to propose two changes to the [recipes page](https://nodatime.org/2.2.x/userguide/recipes).

In the example **How old is Jon?** replace
	`ZonedClock clock = SystemClock.Instance.InZone(zone);`
with
	`ZonedClock clock = ClockExtensions.InZone(SystemClock.Instance, zone);`
and add
	`using NodaTime.Extensions`

In the example **How can I truncate a time to a particular unit?** replace
   `LocalDateTime now = new LocalDate(2014, 6, 27, 7, 14, 25, 500);`
   `LocalDateTime now = now.With(TimeAdjusters.TruncateToMinute); // 2014-06-27T07:14:00`
with
   `LocalDateTime now = new LocalDateTime(2014, 6, 27, 7, 14, 25, 500);`
   `LocalDateTime thisMinute = now.With(TimeAdjusters.TruncateToMinute); // 2014-06-27T07:14:00`

Thanks.

**Comment by jskeet** [comment]
No to the first suggestion - the point of `InZone` being an extension method is so that you can call it on a clock. (Although adding a `using NodaTime.Extensions;` would make sense.)

Fine for the second suggestion.

Would you be happy to put together a pull request?

**Comment by aidanwhitehall** [comment]
Sorry Jon; I didn't realise the first example compiles as-is with just the addition of **using NodaTime.Extensions;**

Re: a pull request, will do.

Thanks.
