### ISSUE TITLE
LocalDate + Period addition is not documented as adding period components individually

### ISSUE THREAD

**Issue by hvdijk** [nodatime/nodatime#1084]
new LocalDate(2016, 2, 29).Plus(Period.FromYears(1) + Period.FromMonths(1))

My initial expectation was that this would produce Mar 29, 2017. Instead, it produces Mar 28, 2017, because it adds a year first, and only then adds a month. I'd have to normalise this to a period of 13 months (with the understanding that this doesn't work in other calendar systems) to get the result I was expecting.

For `LocalDateTime`, this is sort of documented:

https://nodatime.org/2.2.x/api/NodaTime.LocalDateTime.html

> **Addition(LocalDateTime, Period)**  
> Adds a period to a local date/time. Fields are added in the order provided by the period. This is a convenience operator over the Plus(Period) method.

and

> **Plus(Period)**  
> Adds a period to this local date/time. Fields are added in the order provided by the period.

I don't see what "the order provided by the period" is, but at least it tells that there's a gotcha.

For `LocalDate`, this documentation is missing:

https://nodatime.org/2.2.x/api/NodaTime.LocalDate.html

> **Addition(LocalDate, Period)**  
> Adds the specified period to the date. 

and

> **Plus(Period)**  
> Adds the specified period to this date. Fluent alternative to operator+().

**Comment by jskeet** [comment]
This is documented in https://nodatime.org/2.2.x/userguide/arithmetic - I'll improve the API reference documentation though.

**Comment by hvdijk** [comment]
Thanks for the reference. Not sure if it says something about the docs or about myself that I found it in the code before finding that. :)

BTW, I find it interesting that that description applies equally to PostgreSQL interval types, but because those only really have three components (months, days, seconds: years/hours/minutes are computed for display purposes as needed), the results are still different. Because PostgreSQL doesn't have to support multiple calendar systems, it can treat 1 year as a synonym for 12 months.
