### ISSUE TITLE
Could DateInterval implement IEnumerable<LocalDate>?

### ISSUE THREAD

**Issue by djcarter85** [nodatime/nodatime#1111]
I'm currently working on something where I want to foreach over all the dates between a start and end.

It would be useful if I could use the DateInterval class to do this, rather than having to write a helper function to do it. The benefit of this is that DateInterval already ensures the dates are in the correct order (start <= end) and in the same calendar. It seems (to me, anyway) to be a natural operation on this object.

This could be done using a property on the class:

`IEnumerable<LocalDate> Dates { get; }`

or by making the class implement IEnumerable<LocalDate>:

`class DateInterval : IEnumerable<LocalDate>`

**Comment by jskeet** [comment]
Makes sense to me, and is reasonably trivial to implement.

@mj1856 @malcolmr Any preferences as to whether it should implement it directly or have a property? I'm tempted to just implement it directly.

**Comment by malcolmr** [comment]
Looking around, the only type we have that currently implements `IEnumerable` directly is `CompositePatternBuilder` (which looks pretty weird and may have been a mistake).

`Interval` itself isn't enumerable, but that sorta makes sense: it has the option of being unbounded, and in any case enumerating all instants within an interval usually isn't useful.

`DateInterval` is always bounded, and is defined to mean solely a range of dates: I think it would be completely fine to implement `IEnumerable<LocalDate>` directly.
