### ISSUE TITLE
Remove NodaTime.TimeZones.DateTimeZoneNotFoundException?

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime#1132]
`DateTimeZoneNotFoundException` only exists because `TimeZoneNotFoundException` didn't exist in the PCL (and then in netstandard1.x); in 1.0.x, we had `IDateTimeZoneProvider[zone]` throw `TimeZoneNotFoundException` directly.

3.0 will require netstandard2.0, which has `TimeZoneNotFoundException`. Should we remove `DateTimeZoneNotFoundException` now?

**Comment by jskeet** [comment]
I've been thinking about this in relation to #1350, and I think I'd like 3.0.0 to be as compatible as possible, while removing things we *really* want to remove (such as binary serialization, and targeting anything other than netstandard2.0). Closing.
