### ISSUE TITLE
Extract an interface from ZonedClock

### ISSUE THREAD

**Issue by SeanFarrow** [nodatime/nodatime#1138]
It would be useful for testing and dependency injection to have an interface for the ZonedClock type.

Ideally, the new interface should not derive from IClock, but should implement the members of this interface, so as to avoid circular dependencies within DI containers.

A FakeZonedClock should probably be provided for testing if this is demed necessary.

**Comment by jskeet** [comment]
The point of `ZonedClock` is that it's just a convenient combination of an `IClock` and a zone. There's pretty much nothing to fake. Inject a *real* `ZonedClock` with a fake clock and (if you want) a fake time zone.

Adding interfaces and fakes for absolutely verything is an anti-pattern, IMO. I'm much more in favour of working out the right small pieces to abstract (in this case `IClock` and `DateTimeZone`) and then make other things concrete.

On the other hand, I'm happy to listen to requests... could you give me details of what you can't accomplish by injecting a real `ZonedClock` created from a fake clock and time zone?

**Comment by SeanFarrow** [comment]
It’s more the testing aspect I’m concerned with, given that ZonedClock exists, people will want to mock it—being able to use it with a DI framework is a bonus.
Passing FakeClock in is definitely an option, and in my view the required way to go, but I have seen developers who say, we have an interface so let’s just mock it.
I agree with your principle though, so would ask, given this is just a convenience class, is it really needed?

**Comment by jskeet** [comment]
> given that ZonedClock exists, people will want to mock it

Why though? I don't see that it's useful to do so. `System.String` exists, but I hope people don't want to mock that. They can't mock `LocalDate`, or `Instant` etc either.

You can easily test without it:

- Depend on `ZonedClock` (put that in the constructor)
- In tests, create a `FakeClock` (or mock `IClock`) and create a `ZonedClock` from that to pass into the class you're testing.

> I agree with your principle though, so would ask, given this is just a convenience class, is it really needed?

It avoids many developers creating the same thing. It doesn't *need* to exist, but it's a helpful aggregation, IMO. But that's really *all* it is: an aggregation. As such, there's no logic to mock, and I'd argue against people *trying* to mock it.

**Comment by SeanFarrow** [comment]
That makes sense, the only question I would ask is would you assume the iso calendar system  as per other defaults and have this as an optional parameter to the CreateClock method?
If yes, I’ll start work on a ZonedClockHelper class.

**Comment by jskeet** [comment]
Unless you specify an `Instant`, you'd be passing in a value with a calendar system in already (e.g. a `LocalDate`) so I'd expect the helper to take that as the calendar system to use. 

Note that this only helps for the situation where a single value is adequate for the whole test. If you need a clock that auto-advances or similar, we'd need to look at that separately.

One benefit in doing all of this in a test-only helper class: while I'll add it to NodaTime.Testing in the master branch, you should be able to keep a copy in your own project until there's a release you can use it in. Compare that with change to Noda Time itself, where you'd need a release (or a local fork of Noda Time itself) before you could use it.

**Comment by SeanFarrow** [comment]
Makes sense.

I’ll work on this over the next few days, let’s get the single instance per test done first, we can always add to this later.

**Comment by jskeet** [comment]
Any update on this? If you've taken a different approach, we could just close this issue.

**Comment by jskeet** [comment]
Closing for the moment. @SeanFarrow if you ever feel it worthwhile to come back to this, just add a comment and I'll reopen.

**Comment by eldhenn** [comment]
Hi @jskeet, I'm starting to use NodaTime and I have a related question.
Is registering zoned clock as ASP.NET Core service qualify as antipattern? Do I need to inject clock and timezone separately?

**Comment by jskeet** [comment]
@eldhenn: I'd say that's fine... just inject it. It's still plenty testable, given that you can create a `ZonedClock` from a `FakeClock` and any `DateTimeZone` including the ones from `NodaTime.Testing`.
