### ISSUE TITLE
'NpgsqlDbContextOptionsBuilder' does not contain a definition for 'NodaTime' 

### ISSUE THREAD

**Issue by viveknuna** [nodatime/nodatime#1143]
I cannot use NodaTime() in my code. Getting the below error.

> 'NpgsqlDbContextOptionsBuilder' does not contain a definition for 'NodaTime' and no extension method 'NodaTime' accepting a first argument of type 'NpgsqlDbContextOptionsBuilder

**Code:**

`builder.UseNpgsql(connectionString, o => o.NodaTime());`

NodaTime: 2.3.0
NodaTime.Serialization.JsonNet: 2.0.0
EF Core: 2.0.1

**Comment by jskeet** [comment]
That doesn't sound like something that should be reported here - it should be in the Npgsql repo.
