### ISSUE TITLE
Documentation incorrect for OffsetDateTime pattern

### ISSUE THREAD

**Issue by nzbart** [nodatime/nodatime#1183]
The documentation for [Patterns for OffsetDateTime values](https://nodatime.org/2.2.x/userguide/offsetdatetime-patterns) gives an example custom pattern that appears to be incorrect:

>The "o" specifier must always be followed by a pattern for Offset within angle brackets. The pattern may be a standard pattern or a custom pattern. For example, a pattern of uuuu-MM-dd HH:mm:ss o<G> might produce output of "2013-07-17 06:20:35 Z" or "2013-07-17 07:20:35 +01:00".

This indirectly conflicts with the following test, which says that `01:00` should be truncated to `01` because the standard `o` format uses `o<G>` for the offset part:
* [ToString_WholeHourOffset](https://github.com/nodatime/nodatime/blob/9b53ea4d3fd48f2536bc7cffac53c54d0795bc53/src/NodaTime.Test/OffsetDateTimeTest.cs#L193)

It also conflicts with the documentation here:
* [Patterns for Offset values](https://nodatime.org/1.1.x/userguide/offset-patterns)

This confused me for a while, because I wasn't sure why my own code was formatting differently to what the documentation does. What I really needed in my case was a custom format with the `o<m>` offset. 

I think the solution could be as simple as updating the example custom pattern to `2013-07-17 07:20:35 +01` instead of `2013-07-17 07:20:35 +01:00`.

**Comment by jskeet** [comment]
Thanks, I believe you're right - I'll fix this now.

**Comment by nzbart** [comment]
@jskeet That was quick; thanks!
