### ISSUE TITLE
Post retirement notice on https://blog.nodatime.org/ ? 

### ISSUE THREAD

**Issue by jean** [nodatime/nodatime#1201]
I came across the blog via a web search, and got the wrong impression that the last release was from 2015. The latest post is:

> **Tuesday, 10 March 2015**
> Noda Time v1.3.1 released

**Comment by jskeet** [comment]
Yes, we need to update the blog... It's just a matter of finding time.

**Comment by jean** [comment]
Maybe post a link to this issue as the last post and close the blog to new
posts? ;-)

**Comment by jskeet** [comment]
No, we still want the blog to be available for posting interesting articles. I may post saying that it won't be updated with every new release though.

**Comment by jskeet** [comment]
[Done](https://blog.nodatime.org/2018/08/lots-of-releases-not-lot-of-blog-posts.html).
