### ISSUE TITLE
Mark NodaTime structures as Serializable In netcoreapp2.0 / netstandard2.0

### ISSUE THREAD

**Issue by damiensawyer** [nodatime/nodatime#1203]
[See](https://github.com/nodatime/nodatime/issues/226) Mark NodaTime structures as Serializable. 

This appears to be working for me in a Framework461 project, however not in a netcoreapp2.0 referring to a class in a netstandard2.0 dll. 

Am I doing something wrong or is it a framework related issue?

Thanks.

**Comment by jskeet** [comment]
The netstandard2.0 build is the same as netstandard1.3 - it doesn't support binary serialization. (Note that binary serialization is discouraged by MS, and will be entirely gone in Noda Time 3.)

I was under the impression that it wouldn't work in .NET Core anyway (that the types were present but would always throw), but I could be wrong about that.

**Comment by jskeet** [comment]
(Just tried serializing a string in a .NET Core 2.1 console app, and that does work - but we don't intend to support it in Noda Time.)

**Comment by damiensawyer** [comment]
Thanks very much Jon. :-)
