### ISSUE TITLE
Wrong zone interval info

### ISSUE THREAD

**Issue by uday15** [nodatime/nodatime#1204]
Hi, 

I'm using NodaTime v2.2.5 to pull timezone info for certain time zone, this has been working till absolutely fine however recently this been showing wrong info for certain country for instance, for  America/Lost_Angeles the _GetZoneInterval(instant).Name_ returns **PDT** which is correct. However for Asia/Singapore the _GetZoneInterval(instant).Name_ returns **+08**.

See code below, 

```
public static string GetTimeZoneTitle(string ianaZone)
        {
            var zone = GetTimeZone(ianaZone);
            var instant = Instant.FromDateTimeUtc(DateTime.UtcNow);
            return zone.GetZoneInterval(instant).Name;

        }


        public static DateTimeZone GetTimeZone(string ianaCode)
        {
            try
            {
                return DateTimeZoneProviders.Tzdb[ianaCode];
            }
            catch (Exception)
            {
                return null;
            }
        }
```

See result : https://ibb.co/fZmMLU

**Comment by jskeet** [comment]
Yes, that's because +08 is the only name we have for Asia/Singapore at that point in time. Here's the [source in the IANA database](https://github.com/eggert/tz/blob/da31293a319ba5227342e236bcdadaf5d288e1f3/asia#L3000):

```text
Zone	Asia/Singapore	6:55:25 -	LMT	1901 Jan  1
			6:55:25	-	SMT	1905 Jun  1 # Singapore M.T.
			7:00	-	+07	1933 Jan  1
			7:00	0:20	+0720	1936 Jan  1
			7:20	-	+0720	1941 Sep  1
			7:30	-	+0730	1942 Feb 16
			9:00	-	+09	1945 Sep 12
			7:30	-	+0730	1982 Jan  1
			8:00	-	+08
```

So Noda Time is doing exactly the right thing.

**Comment by uday15** [comment]
Thanks for reply. 

How comes this use to work before ? in fact .net fiddle same code out puts different result, 

https://dotnetfiddle.net/IkwC5x#&togetherjs=oJPx8MzOT7

Screenshot : [https://ibb.co/mmEp79](url)

**Comment by jskeet** [comment]
That's probably using an old version of Noda Time with an old version of the IANA data which used "SGT". This was changed in IANA in January 2017 in [this commit](https://github.com/eggert/tz/commit/1b99dcde6342dd10969041b32b00b813d4f4a36e#diff-cffe819d4413b95dd8c35c0085930789)
