### ISSUE TITLE
[Question] What's the purpose of LocalDate.With method

### ISSUE THREAD

**Issue by FDUdannychen** [nodatime/nodatime#1206]
Since the struct is immutable, what's the purpose of this method other than its constructor? Is it only used to make the method calls chained?

**Comment by jskeet** [comment]
Yes, it allows method call chaining. But more importantly, it allows a consistent approach to be used for multiple types. There's a `With` method in `LocalDateTime` that also accepts a date adjuster, for example. So you could use:

```csharp
// Operate on a date
LocalDate date = ...;
LocalDate startOfMonth1 = date.With(DateAdjusters.StartOfMonth);

// Operate on a date and time
LocalDateTime dateTime = ...;
LocalDateTime startOfMonth2 = dateTime.With(DateAdjusters.StartOfMonth);
```

This improves consistency.
