### ISSUE TITLE
Method names are out of date on the website's "type choices" diagram

### ISSUE THREAD

**Issue by djcarter85** [nodatime/nodatime#1208]
Not sure if this issue belongs in this repository or another one, but the method names on the diagram on https://nodatime.org/2.4.x/userguide/type-choices are out of date. For example, I think `AtExactly()` is now called `AtStrictly()`.

**Comment by jskeet** [comment]
Thanks, I'll take a look when I get a chance.

**Comment by djcarter85** [comment]
I usually use the methods on `LocalDateTime` rather than the ones on `DateTimeZone`. It may be worth adding both sets of methods to the diagram.

Really helpful diagram, by the way!
