### ISSUE TITLE
Web page with benchmarks doesn't work.

### ISSUE THREAD

**Issue by rafcioki** [nodatime/nodatime#1213]
Web page that (I believe) should display benchmarks doesn't display them.

To reproduce:
1) Open https://nodatime.org/benchmarks

**Actual result**: "Benchmark environments" table is empty.
**Expected result**: "Benchmark environments" table displays benchmark results.

**Environment**: Windows 10, checked on latest chrome (70.0.3538.77) and firefox (63.0). 

There's also a JS error in the console:
```
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at HTMLDocument.<anonymous>
```

**Comment by jskeet** [comment]
Hmm. That's interesting. Thanks, will have a look. The Javascript error may well be entirely separate, given that I haven't written any Javascript of my own for the banchmarks page.

(I won't be able to look at any of this until Monday probably, as I'm travelling.)

**Comment by jskeet** [comment]
Just checked and the benchmarks themselves are all still there, so that's a start...

**Comment by jskeet** [comment]
Fixed, but it'll take about half an hour to go through automated build and push. Thanks for spotting it!
