### ISSUE TITLE
SystemEvents.TimeChanged - Changing current system timezone - not seen in NodaTime

### ISSUE THREAD

**Issue by evilman666** [nodatime/nodatime#1222]
I am currently intercepting the "TimeChanged" event in my application to detect whether the user decides to change the timezone in the Windows settings.
When the user changes the system timezone, the event below is correctly fired.

`            SystemEvents.TimeChanged += SystemEvents_TimeChanged;`

Now my problem is to get the "new" timezone value.
The below calls will always show the timezone value that was selected when the app was started, and not the NEW timezone that the user selected.
Any suggestions? I am using Windows 8.1 with .NET 4.5.

```csharp
private void SystemEvents_TimeChanged(object sender, EventArgs e) {            `
    DateTimeZone tzSystem = DateTimeZoneProviders.Tzdb.GetSystemDefault();
    TimeZoneInfo info = TimeZoneInfo.Local;
    Debug.Print(info.ToString());
    Debug.Print(tzSystem.ToString());
}
```

**Comment by jskeet** [comment]
Have you tried calling `TimeZoneInfo.ClearCachedData()` at the start of that code? I suspect that would fix it. (Noda Time just uses `TimeZoneInfo.Local`, so if that hasn't changed, Noda Time won't see anything.)

**Comment by evilman666** [comment]
I have tested it, and YES, I confirm this resolves the problem.

Thank you for your help!
