### ISSUE TITLE
Bad Offsets Returned in ZonedDataTime

### ISSUE THREAD

**Issue by CoachMike66** [nodatime/nodatime#1225]
Our product is experiencing a problem where by and offset is changing in certain timezones after adding a very small Period/Duration to it, sometimes even 0 seconds. For example, Using "Antarctica/Casey" and the current DateTime (offset is +11). Our code, takes that ZonedDateTime (zdt1), converts to Instant, adds -1 days to get another Instant and then converts that into another ZonedDateTime (zdt2). Problem is that the Offset in zdt2 is now +08 (should still be +11). There are historical ZoneIntervals for Antarctica where the offset is +08, but right now, it's +11. 

Of course I tried to write a small C# console app to duplicate that to display here, but it's not working exactly like this, although it is showing wierd behavior.

Here is the sample code - I know this isn't the problem I describe above, but I wonder if it might provide a clue as to what our problem might be??

         string zoneID = "Antarctica/Casey";
         DateTimeZone zone = NodaTime.DateTimeZoneProviders.Tzdb[zoneID];

         **// Work with the current time - Nov 15, 2018 EST (Toronto)**
         DateTime netDT_UTC = DateTime.UtcNow;
         Instant instant = Instant.FromDateTimeUtc(netDT_UTC);

         // check the zone interval - note that the Offset from the zone is +08 - According to 
         // timeanddate.com, this should be +11, for Nov 15, 2018
         ZoneInterval zoneInt = zone.GetZoneInterval(instant);

         // convert the Instant to ZonedDateTime, using the Antarctica Zone
         ZonedDateTime zonedTime = new ZonedDateTime(instant, zone);

         // This offset is also +08
         Offset offset1 = zonedTime.Offset;

**Comment by jskeet** [comment]
The rules at https://github.com/eggert/tz/blob/master/antarctica#L74 show that it should be +08.
The relevant change (in github) in March this year: https://github.com/eggert/tz/commit/a77c2e66f9d9b7ebe124601a95aae9cc22b41788

Both https://www.worldtimeserver.com/current_time_in_AQ-BP.aspx?city=Casey_Station and http://www.timezoneconverter.com/cgi-bin/zoneinfo?tz=Antarctica/Casey agree with that.

I don't know why https://www.timeanddate.com/time/zone/antarctica/casey thinks it's +11, but it doesn't look like it should be to me.

So that certainly explains the code you've shown so far. And it's also entirely reasonable that subtracting a day would change the offset from +8 to +11 or vice versa, as that's happened at various times in history.

If you could pin down what you're concerned about in the first paragraph further, that would be very helpful.

**Comment by CoachMike66** [comment]
OK - thanks for that clarification - weird!! I'll concentrate on trying to get a simple scenario show the problem like I described in the first paragraph.

In the meantime, this is kinda vague I know, but in our product this is what I'm seeing from a customer in Turkey:
- Zone is "Europe/Istanbul"
- They are presently +03, I think anyway :-)
- Build a ZonedDateTime for the current date and verify that it's +03
- Subtract a year from it, in the same way that my code sample does it above and the result is +02, which it shouldn't be - should still be +03 - again I think :-)
- That didn't show an obvious problem to the user yet - it's only when this date has it's components pulled apart later one and then rebuild as a ZonedDateTime with offset +02, the NodaTime throws an exception.

**Comment by jskeet** [comment]
This is the first time you've mentioned an exception - what's the exception?

And which version of Noda Time are you using? If you're using an old version, that might have old time zone rules. Once I know the version, I'll try to reproduce as you've suggested, although it would be easier to help with actual code samples I can run, to remove guesswork.

**Comment by jskeet** [comment]
Version 1.3.2 is over two and a half years old. There have been many, many changes to time zone rules since then.

But again, rather than *describing* the code, please just provide a short but complete console app that *demonstrates* the problem. That will avoid a lot of back and forth.

**Comment by jskeet** [comment]
"Offset changing with a small duration added" is entirely to be expected though - there's always an instant at which offsets change, for any non-fixed time zones. The "smallness" of the duration added is irrelevant - if you could never change offset by adding 1 second, then you could never change offset at all, because you could add 1 second, add 1 second etc millions of times, to get to any instant in time you wanted.

**Comment by CoachMike66** [comment]
Yes, I realize that you could Add/Subtract some amount and the result could be in a different ZoneInteval, in which case the Offset will be different, but I don't think that's happening here. 

In our scenario in Turkey, they are taking the current DateTime and subtracting 1 year. As far as I know, Turkey is +03 now and has been since summer 2016 - but we end up building a ZonedDateTime instance of Nov, 2017 (Now - 1 year) with an offset of +02 - and that eventually leads to the exception.

**Comment by jskeet** [comment]
Right, you basically shouldn't be constructing a ZonedDateTime by providing the offset unless you're really sure it's correct. Instead:

- Take the LocalDateTime part of the original ZonedDateTime
- Subtract a year
- Convert that into a ZonedDateTIme using InZoneStrictly or InZoneLeniently (or just InZone with a mapping function) - carefully considering what happens if you end up in the middle of a DST transition.

**Comment by CoachMike66** [comment]
Sorry - this is turning into more of a conversation rather than a bug report, but I hope it gives me insight into the problem we're seeing.

OK - I might have it down to three lines that show a potential problem with how it's behaving in our product (incorrectly) vs in a test app (correctly). The 3 lines are:

         Instant instant = Instant.FromDateTimeUtc(utc);
         ZonedDateTime zonedDateTime = new ZonedDateTime(instant, zone);
         return zonedDateTime;

In both cases, I'm using version 2.4.2 of NodaTime.

where the incoming utc value is DateTime.UtcNow and the zone is Africa/Casablanca which right now is +01 offset.

While debugging our product in the 3 lines, I've taken a screen shot with some watch windows - here is the image:

![ourproduct_bad](https://user-images.githubusercontent.com/45073699/48578565-fdec2080-e8e7-11e8-8bc3-3a518dc5e1e7.jpg)

You'll see that the offset coming back from the new ZonedDateTime() is 0 - I think this might be the source of my problem in our product - it should be +1

Executing the same lines in a small test app (30 minutes later - notice the difference in times) - I get this:

![testapp_good](https://user-images.githubusercontent.com/45073699/48578632-3855bd80-e8e8-11e8-83f3-c6944d103d00.jpg)

The offset of the new ZonedDateTime() is as it should be +01.

Not sure this is of any relevance - my test app is pure C# - the lines in our application are from a C# Managed assembly, but the application itself is composed of Native DLL's and Managed Assemblies.

**Comment by jskeet** [comment]
*Please* could you write a simple console app that shows this, in an easy to replicate way? It's *so* much easier to tell what's going on - and reproduce that - than try to interpret screenshots.

Here's the sort of thing I mean:

```csharp
using System;
using NodaTime;

class Program
{
    static void Main()
    {
        var now = SystemClock.Instance.GetCurrentInstant();
        var zone = DateTimeZoneProviders.Tzdb["Africa/Casablanca"];
        // Note: I'd generally use now.InZone(zone) instead
        var zoned = new ZonedDateTime(now, zone);
        Console.WriteLine(zoned.Offset);
    }
}
```

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NodaTime" Version="2.4.2" />
  </ItemGroup>

</Project>
```

That's *everything* you need to reproduce the result (which is +01 as expected).

I *strongly* suspect that actually you're not using 2.4.2 on the broken system. Any older version would default to older time zone data - which would (correctly with its data) show an offset of 0. Change the 2.4.2 to 2.4.1 for example, and you get output of +00.

So where you're seeing a problem, I'd very strongly encourage you to double and triple check the version of Noda Time you're using.

**Comment by CoachMike66** [comment]
Thanks - the second bitmap above is from my small test app - but it is working correctly. I'll take your advice for now and double and triple check the version of both the DLL and the DB - I expect them to be the latest.

**Comment by CoachMike66** [comment]
Hi Jon,

Bit of an update - for our product, we store the NodaTime DB in a blob field within our application DB -turns out that NodaTime DB in the blob was different than the 2018g version of the DB that my test app was using - that explains the different behavior. Thanks for the "double triple check" suggestion.

I still have to figure out what is going on with our customer in Turkey - they are using Version 1.3.2 of the DLL and I suspect a version of the NodaTime DB from sometime this summer, but I'm not sure.

Thanks for all your help and the discussion. - I'll close this issue
