### ISSUE TITLE
Very small improvements for DateInterval.Contains(DateInterval)

### ISSUE THREAD

**Issue by chtoucas** [nodatime/nodatime#1228]
I think that inside the method `DateInterval.Contains(DateInterval interval)`, instead of writing
```csharp
return Contains(interval.Start) && Contains(interval.End);
```
one can simply write
```csharp
return Start <= interval.Start && interval.End <= End;
```
this should remove two unnecessary comparisons.

**Comment by jskeet** [comment]
Possibly. I'll see what the benchmarks show.
