### ISSUE TITLE
Custom Binary Serializer

### ISSUE THREAD

**Issue by mikernet** [nodatime/nodatime#1235]
I want to make NodaTime the official de-facto method of storing dates/times in my entity/database engine but I need to write custom binary serializers for each type to make that happen. I have a couple questions:

a) Do you foresee changes to any of the existing types in NodaTime that may require additional fields to fully capture the state of the objects for serialization in the future? I guess what I'm asking is: which types do you think it is prudent to include a "version" tag for in the serialized data to allow for serialization versioning, and which ones do you think are "finalized" in terms of the fields that they will store? 

b) I'm trying to use the `ISerializable` implementations as a template to assist me with writing the serializers properly. After a quick scan over everything I don't think I'll have many issues, the only thing I've run into so far is that I'm not sure the best way to serialize the calendar system as it uses internals to do that. What's your recommendation here? I'm far from an expert in calendar systems so I want to make sure I do this properly.

c) What is the range of values allowed for month/day/year that will cover all possible calendar systems? I don't want to store 4 bytes per value if that's not necessary.

I might have more questions as I go but I think that should do it for now.

**Comment by mikernet** [comment]
For (b) I think I'm going to have to make my own `byte` ID to calendar system dictionary and just use that as far as I can tell, I want to avoid having serialized strings for every date value in the DB. Either that or use some compiled expressions to tap into the existing ordinal stuff but I don't want things to break if you ever rename things.

**Comment by jskeet** [comment]
a) I would be surprised if there were extra information required for the core state, but the implementation details may change. (I'm definitely not going to promise that it won't.)

b) I would suggest using the `Id` property to detect which calendar it is - but yes, using your own byte value for that makes sense. I don't want to expose the ordinals publicly.

c) If you're going to include the calendar ID, I doubt that you'll be able to store everything in less than 4 bytes. The `DayMonthYearCalendar` struct is pretty tightly packed. You could potentially save space by storing "days since the Unix epoch" instead of separating the year/month/day values.

**Comment by mikernet** [comment]
In terms of the 4 bytes I meant using 4 bytes each for the day, month and year. I was looking at the `ISerializable` implementation which stores them each as individual `Int32` values and wanted to pack it tighter than that. 

I see the bit packing you did now in `DayMonthYearCalendar` and I guess that answers my question as to what the possible range of values is for each component of the date. I'll probably just duplicate the bit packing logic you have going on there unless you think there may be some future changes (i.e. adding a different calendar system) that will result in values not fitting within that bit packing strategy.

**Comment by jskeet** [comment]
We basically can't change the bit packing system now without breaking compatibility for the 2.x binary serialisation format. Not that 3.x will support binary serialisation anyway...

**Comment by mikernet** [comment]
Doesn't the binary serializer in 2.4 store each value separately as a 32 bit int? Or are you talking something different than `ISerializable` / am I missing something?

**Comment by jskeet** [comment]
It's possible it does - I haven't looked at the code, whereas it sounds like you have :) But I don't anticipate any changes.

**Comment by mikernet** [comment]
Thanks for your help and thanks for this lovely library, I don't know what I would do without it. I think that should get me on my way for now!
