### ISSUE TITLE
Logical inversion in documentation

### ISSUE THREAD

**Issue by DanielSWolf** [nodatime/nodatime#1258]
The [documentation for Duration](https://nodatime.org/2.4.x/api/NodaTime.Duration.html) says:

> negative durations are valid, and may occur naturally when e.g. subtracting an earlier Instant from a later one.

Shouldn't that be the other way around? "when e.g. subtracting a *later* Instant from an *earlier* one"

**Comment by jskeet** [comment]
Whoops, absolutely. Will fix, thanks!

**Comment by jskeet** [comment]
Hmm... as this is API documentation rather than conceptual documentation, I can't *easily* fix it across older versions. I'll have to see what I can do. I'll fix the master first.

**Comment by jskeet** [comment]
It's genuinely fixed now :) Although the "latest" API docs are still a bit broken in general :(
