### ISSUE TITLE
Instant not being serialized while using 

### ISSUE THREAD

**Issue by eparizzi** [nodatime/nodatime#1309]
I've an ASP.NET Core 2.2 MVC project running JSON.NET version 11,  NodaTime v2.4.4 and NodaTime.Serialization.JsonNet v.2.1.0.

When returning an `IEnumerable<MyClass>` from an action method the `Timestamp` is not being serialized properly. The JSON array returned contains `{}` (empty object) for all the timestamps.

```
public class MyClass
    {
        public Instant Timestamp { get; set; }

        public double Value { get; set; }
    }
```

The `ConfigureServices()` method contains the following:

```csharp
services
                .AddMvcCore(config =>
                {
                    AuthorizationPolicy policy = new AuthorizationPolicyBuilder()
                        .RequireAuthenticatedUser()
                        .Build();

                    config.Filters.Add(new AuthorizeFilter(policy)); // global authorize filter
                })
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_2)
                .AddAuthorization()
                .AddJsonFormatters();
```

Is there anything else that needs to be done here? Maybe something inside `AddJsonFormatters()`?

**Comment by jskeet** [comment]
I don't see anywhere that you're configuring the Json.NET serialization for use with Noda Time. I think you want:

```csharp
.AddJsonFormatters(settings => settings.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb))
```

**Comment by eparizzi** [comment]
Great, that worked. Thanks!

I guess that line should be added in the docs here: https://nodatime.org/2.4.x/userguide/serialization (or is it anywhere else I missed?)

**Comment by jskeet** [comment]
I can put it there, but there will always be new frameworks etc that need configuring. It's more about understanding that you need to configure Json.NET, and which extension methods to use to do that.
