### ISSUE TITLE
Consider excluding tzdb from HTTPS redirects

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#1319]
We get a lot of requests for `/tzdb/latest.txt` - I suspect these are automated from applications.

Currently, we're redirecting those requests to HTTPS, but if we can work out a way of excluding `/tzdb/*` then that's probably worth doing.

**Comment by jskeet** [comment]
(I believe this was the case when we were on Azure, so I don't think it's anything new anyway.)

**Comment by malcolmr** [comment]
I think it'd be a little bit weird to have a mixture of redirecting and non-redirecting paths. Ideally, clients should switch to HTTPS.

Plus, if we enable HTTP Strict-Transport-Security, we'd be in a position where browsers (and other HSTS-supporting UAs) would auto-redirect to HTTPS, but other UAs wouldn't, which would be even more weird, and be ~impossible to test.

**Comment by jskeet** [comment]
Righto. Will close for now, and reopen if we ever decide we want to do this after all, e.g. if application authors run into issues.
