### ISSUE TITLE
Method ForId for TzdbDateTimeZoneSource seems to be case sensitive.

### ISSUE THREAD

**Issue by zlatinal** [nodatime/nodatime#1329]
Method ForId for TzdbDateTimeZoneSource seems to be case sensitive. Just wondering if this is the expected behaviour.

Error message: Time zone with ID europe/london not found in source 2018e (mapping: 13923)

**Comment by jskeet** [comment]
Yes, it's expected behaviour. IDs are expected to be opaque strings, effectively - I wouldn't want to apply any casing rules on them.
I would be very *surprised* to find that any zones only differ in case, but I don't think it's prohibited.

**Comment by zlatinal** [comment]
Fair enough, thanks for the clarification. Issue can be closed.
