### ISSUE TITLE
Incorrect Tail zone entries for Europe/Dublin

### ISSUE THREAD

**Issue by bobowla** [nodatime/nodatime#1331]
I ran NodaTime.Demo and noticed that this test failed:
NodaTime.Demo.ZonedDateTimeDemo.IsDaylightSavingTime
I investigated and found that the test was (incorrectly) failing because of an error in the Time Zone database entries for Europe/Dublin. I believe the Standard Time and Daylight time entries have been transposed. They currently are:
    **Standard time: ZoneYearOffset[mode:Utc monthOfYear:3 dayOfMonth:-1 dayOfWeek:7 advance:False timeOfDay:01:00:00 addDay:False]; offset: +01; name: IST
    Daylight time: ZoneYearOffset[mode:Utc monthOfYear:10 dayOfMonth:-1 dayOfWeek:7 advance:False timeOfDay:01:00:00 addDay:False]; offset: +00; name: GMT**
Implying that daylight saving begins in October and ends in March
This change happened in version 2018e of Tzdb; in version 2018d the lines were as follows:
    **Standard time: ZoneYearOffset[mode:Utc monthOfYear:10 dayOfMonth:-1 dayOfWeek:7 advance:False timeOfDay:01:00:00 addDay:False]; offset: +00; name: GMT
    Daylight time: ZoneYearOffset[mode:Utc monthOfYear:3 dayOfMonth:-1 dayOfWeek:7 advance:False timeOfDay:01:00:00 addDay:False]; offset: +01; name: IST**
Which correctly has daylight saving beginning in March and ending in October

**Comment by jskeet** [comment]
The test is incorrect, the data is correct - although I agree it's surprising.

Ireland has curious rules, in that it considers summer to be its standard time, and winter to be its "savings" time, with a savings offset of -1.
I'll update NodaTime.Demo to reflect this (with a comment).
