### ISSUE TITLE
What is the difference between Americas/Chicago and US/Central in Noda Time

### ISSUE THREAD

**Issue by ttaylor29** [nodatime/nodatime#1342]
What is the difference between Americas/Chicago and US/Central in Noda Time?

I'm using US/Central, but when I call:

`           DateTimeZone zone = DateTimeZoneProviders.Tzdb.GetSystemDefault();`

It is giving me: "Americas/Chicago"

Are they technically the same? Can they be used vice versa?

**Comment by jskeet** [comment]
I assume you're on Windows? If so, `TimeZoneInfo.Default.Id` probably returns "Central Standard Time", which [maps to](https://github.com/nodatime/nodatime/blob/master/data/cldr/windowsZones-33.xml#L95) "America/Chicago" (note that it's America, not Americas - there are no time zones using "Americas" as a prefix.

In terms of the differences between US/Central and America/Chicago, there aren't any. US/Central is an *alias* for America/Chicago - but America/Chicago is the canonical name. There are several "links" like this in the [backward](https://github.com/eggert/tz/blob/master/backward) file IANA provides. For the US:

```text
Link	America/Anchorage	US/Alaska
Link	America/Adak		US/Aleutian
Link	America/Phoenix		US/Arizona
Link	America/Chicago		US/Central
Link	America/Indiana/Indianapolis	US/East-Indiana
Link	America/New_York	US/Eastern
Link	Pacific/Honolulu	US/Hawaii
Link	America/Indiana/Knox	US/Indiana-Starke
Link	America/Detroit		US/Michigan
Link	America/Denver		US/Mountain
Link	America/Los_Angeles	US/Pacific
Link	Pacific/Pago_Pago	US/Samoa
```

**Comment by ttaylor29** [comment]
Yes I am on Windows!

And thanks for the clarification on the Americas etc.  That was a mistype on my part.

Thanks for the link table and the description and that there is no per say difference!

This is what I have now for my code:

```
        public static List<NodaTimeTimeZoneEqualDto> GetAmericasNodaTimeZoneEqualInfo()
        {
            List<NodaTimeTimeZoneEqualDto> nodaTimeTimeZoneEquals = new List<NodaTimeTimeZoneEqualDto>();

            nodaTimeTimeZoneEquals.Add(new NodaTimeTimeZoneEqualDto { NodaTimeZoneOneTxt = "America/New_York", NodaTimeZoneTwoTxt = "US/Eastern", BaseballWebSiteNodaTimeZoneTxt = "ET" });
            nodaTimeTimeZoneEquals.Add(new NodaTimeTimeZoneEqualDto { NodaTimeZoneOneTxt = "America/Chicago", NodaTimeZoneTwoTxt = "US/Central", BaseballWebSiteNodaTimeZoneTxt = "CT" });
            nodaTimeTimeZoneEquals.Add(new NodaTimeTimeZoneEqualDto { NodaTimeZoneOneTxt = "America/Denver", NodaTimeZoneTwoTxt = "US/Mountain", BaseballWebSiteNodaTimeZoneTxt = "MT" });
            nodaTimeTimeZoneEquals.Add(new NodaTimeTimeZoneEqualDto { NodaTimeZoneOneTxt = "America/Los_Angeles", NodaTimeZoneTwoTxt = "US/Pacific", BaseballWebSiteNodaTimeZoneTxt = "PT" });

            return nodaTimeTimeZoneEquals;
}
```
So I was on the right path!  Thanks again.

**Comment by CaptainPalapa** [comment]
> US/Central is an _alias_ for America/Chicago - but America/Chicago is the canonical name.>

Just ran across this, attempting to confirm.  But, we HAVE to all agree, this is horrible.   Chicago should be an alias to Central.  When Chicago (or Illinois) decides to drop DST, man... what a Y2K mess.

**Comment by jskeet** [comment]
> Chicago should be an alias to Central. 

No, that's not how the time zone database works.

> When Chicago (or Illinois) decides to drop DST, man... what a Y2K mess.

I would argue that that would cause problems however things are organised, but I'd be reluctant to suggest that the US should be organised differently to the rest of the IANA database, or that the rest of the IANA database should be organised in a US-centric way. It's certainly a mess - almost anything with historical baggage is - but we can disagree on the remedy.

https://data.iana.org/time-zones/theory.html is the place to look for more background on the IANA database.
