### ISSUE TITLE
Add Zone property to ZonedClock that returns DateTimeZone of the clock

### ISSUE THREAD

**Issue by Rody66** [nodatime/nodatime#1362]
Hi there. It came as a surprise to me that ZonedClock don't have its DateTimeZone public property.
Sometimes we need to get know the timezone of given clock, please consider to add this property:
```csharp
public DateTimeZone Zone => zone;
```

**Comment by jskeet** [comment]
I'll consider it, but could you give me more information about the use case? (That will help me work out whether we also need to expose the clock and the calendar as well.)

As a workaround for the moment, you could always call `GetCurrentZonedDateTime()` and check the time zone of that.

**Comment by Rody66** [comment]
Actually I wanted to use as a part of my extension `ToStringRelatively`, that returns relatively string of the given interval (for instance `Today 14:00 - 15:00`), so it requires clock to get current time and timezone to convert Instants to Zoned/Local date time, since I use ZonedClock I had to duplicate time zone, because ZonedClock doesn't have this property.

**Comment by jskeet** [comment]
So does the method actually ask the `ZonedClock` for the current instant *in its time zone*? If you're not calling any of the time-zone-specific methods from `ZonedClock`, I think that taking an `IClock` and a `DateTimeZone` separately would be clearer. (It's like if you want a date and a time, but you're not actually referring to a specific `LocalDateTime` - I wouldn't recommend using `LocalDateTime` in that scenario just because it happens to combine the two.)

**Comment by jskeet** [comment]
Any more information on this? I'd really like to understand scenarios where accepting a `ZonedClock` and then accessing the `Zone` is really the best approach.

**Comment by Rody66** [comment]
Hi John! I'm sorry for delay. Actually I solved this issue converting two `Interval`s to my own class LocalInterval (consisted of two` LocalDateTime`s) like this: `LocalInterval.FromInstants(itervalStart, itervalEnd, tz)`. So, it solved my use case. If I met similar issue again, I'll post it here. For now it solved. Anyway I think it's worth to just open `Zone` field to `ZonedClock`, I assume it's logical and it may make life easier to someone.

**Comment by Rody66** [comment]
Thank you!
