### ISSUE TITLE
Add LocalTime.FromMinutesSinceMidnight

### ISSUE THREAD

**Issue by DanCarterGMSL** [nodatime/nodatime#1366]
`LocalTime` has methods the following factory methods:

- `FromSecondsSinceMidnight()`
- `FromMillisecondsSinceMidnight()`
- `FromTicksSinceMidnight()`

Could a `FromMinutesSinceMidnight()` method be added? It would be useful for something I am trying to do (we currently store a local time in minutes since midnight in our DB, so this method would make the conversion from DB types into NodaTime types easier).

A `FromHoursSinceMidnight()` method would complete the set, but I can't see it being as useful because you can just call the hour/minute ctor with `0` minutes.

**Comment by jskeet** [comment]
Yes, we can do this. Presumably you're now just using `FromSecondsSinceMidnight(minutes * NodaConstants.SecondsPerHour)` which seems reasonable to me. I'm not going to backport this to 2.x or anything like that, but we might as well make it simple.
I probably *will* include FromHoursSinceMidnight just for consistency. (In particular, that means it could be used in a method group conversion in a LINQ query - compare `hoursList.Select(LocalTime.FromHoursSinceMidnight)` vs `hoursList.Select(h => new LocalTime(h, 0))` in terms of readability.)

**Comment by DanCarterGMSL** [comment]
`NodaConstants.SecondsPerMinute`, but yes!

**Comment by jskeet** [comment]
Doh :) (And that's why it's worth having as a method, of course, to prevent stupid mistakes like that...)
