### ISSUE TITLE
BclDateTimeZoneSource Missing from netstandard2.0 build

### ISSUE THREAD

**Issue by adamkirkton** [nodatime/nodatime#1394]
It appears that the BclDateTimeZoneSource class is not included in the netstandard2.0 NuGet package even though the documentation indicates it should be. I have a simple netcoreapp2.1 project which I added the NodaTime NuGet package to, and Rider can't find the type and Assembly interrogation also doesn't list it as a type.

**Comment by jskeet** [comment]
Could you clarify which documentation says it should be, and which version you're using?

I'd expect it to be in any 3.x build, but *not* in 2.4 builds - when we added netstandard2.0 support, we explicitly did so in a way that meant the netstandard2.0 target is exactly the same as the netstandard1.3 target.

**Comment by adamkirkton** [comment]
@jskeet Ah, I apologize. I was not following the docs: https://nodatime.org/unstable/api/NodaTime.TimeZones.BclDateTimeZoneSource.html as being changes since 2.4. I will grab a 3.x build beta. I didn't realize those were out there. Thanks!
