### ISSUE TITLE
DateTimeZoneProviders.Tzdb.GetZoneOrNull(null) Throws

### ISSUE THREAD

**Issue by craigeddy** [nodatime/nodatime#1395]
Would like to propose that `DateTimeZoneProviders.Tzdb.GetZoneOrNull(null)` should return a null just like `DateTimeZoneProviders.Tzdb.GetZoneOrNull(string.Empty)` does.

And would be happy to do so via a pull request.

**Comment by jskeet** [comment]
No, I don't think so - particularly not with the upcoming C# 8 nullable reference types. A null reference can never, ever be a valid time zone ID - and while the empty string can't either, that's a different kind of failure IMO.

If you ever end up passing a null reference into `GetZoneOrNull`, that's a bug in your code - so you should definitely get an exception.

**Comment by craigeddy** [comment]
OK. Understood. 

Our use case is that we have data stored in a schema-less database. So some of the records have-a `Timezone` property, others don't. Rather than imposing `string.Empty` on the rows that actually don't express a timezone, the `string` property stays null.

**Comment by jskeet** [comment]
Just don't call the method for records without a time zone:

```csharp
var zone = record.ZoneId == null ? null : DateTimeZoneProviders.Tzdb.GetZoneOrNull(record.ZoneId);
```

At that point you may even want to just use the indexer, so you can tell if you've got a non-null zone ID which the zone provider doesn't know about.

You could always build your own extra method - even an extension method - to do this. But I believe the out-of-the-box behaviour is the most suitable choice for the library.

**Comment by craigeddy** [comment]
Yeah...have an extension method that wraps the GetZoneOrNull call, just wasn't checking inside that for a `null` value of the `id` parameter. 

So modified that to:

```
public static DateTime InTimezone(this DateTime value, string timezone)
{
    var zone = DateTimeZoneProviders.Tzdb.GetZoneOrNull(timezone ?? string.Empty);
    if (zone != null)
    {
        return value.ToInstant().InZone(zone).ToDateTimeUnspecified();
    }
    return value;
}
```

Thanks for your help.
