### ISSUE TITLE
Missing the month/day formatting pattern

### ISSUE THREAD

**Issue by AlexanderMelchers** [nodatime/nodatime#1408]
Hi all,

We recently started building a new mobile app using Noda Time and one of the first things we're working of requires us to format a date and time into a string. Now, part of this string should have a format including day (non-padded) and month name. As such, this is exactly what the [standard month/day](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#MonthDay) `DateTime` formatting [pattern "M"](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings) does.

Obviously, this format can only be used by itself, as otherwise it would cause confusion with the month number format specifier. And, true, I could exit Noda Time to revert to an unspecified `DateTime` to apply this formatting. But to me this seems like a missing feature that would be a great addition to Noda Time.

All the best,
Alexander.

**Comment by jskeet** [comment]
Definitely a missing feature, thanks - and it probably won't be too hard to fix.

I expect I'll only add it to `LocalDate` formatting (I'm not sure it's even a good idea for `OffsetDate`) - does that work for you?

For the moment you could probably work around this by creating a `LocalDatePattern` using the relevant [DateTimeFormatInfo.MonthDayPattern](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo.monthdaypattern) - that's what we'll do internally anyway.

**Comment by jskeet** [comment]
(It might make sense to add year/month at the same time, and add support to YearMonthPattern.)

**Comment by AlexanderMelchers** [comment]
Yes, that would definitely work for us, and I'll look into your suggestion too. Thanks!

Not wanting to push my luck here, as I'm not sure how much work this next one would involve, but another nice-to-have would be a standard pattern for day-of-week/month/day, kind of as in "Friday, August 12", as I believe especially the comma part differs per culture... But, as said, nice-to-have. You'd really already help us out heaps with the month/day-pattern!

**Comment by jskeet** [comment]
It's not just the comma part that differs - it could easily differ between "Friday, August 12" or "Friday, 12 August". Basically this is the sort of thing we rely on DateTimeFormatInfo for - if it doesn't expose it, we can't use it, I'm afraid :(

**Comment by AlexanderMelchers** [comment]
No worries. I anticipated as much. Hence, my current solution is to use two formatting passes: "dddd, " and then an "M". However, with your tip from above, I think we can probably reduce this to $"dddd, {DateTimeFormatInfo.MonthDayPattern}". But thanks anyway!

**Comment by jskeet** [comment]
You might want to review the MonthDayPattern in all the cultures you care about. You may find that *some* MonthDay patterns already include the day of week!

**Comment by jskeet** [comment]
Had forgotten about this - will try to implement this later today.
