### ISSUE TITLE
Supporting Full ISO-8601 Pattern for LocalTime

### ISSUE THREAD

**Issue by lundmikkel** [nodatime/nodatime#1411]
I'm trying to find/make a `LocalTime` pattern that parses all of [the extended ISO-8601 formats for time](https://en.wikipedia.org/wiki/ISO_8601#Times), but only formats them as the full extended ISO pattern with hours, minutes, seconds and optional fractional seconds. The pattern should be used for public APIs that allow a wide range of ISO-defined inputs, while only returning a single format.

I'm having problems finding support for it. All the ISO-8601 time formats look something like this:

1. HH':'mm':'ss;FFFFFFFFF
2. HH':'mm
3. HH
4. HH':'mm;FFFFFFFFF
5. HH;FFFFFFFFF
6. 24':'00':'00;000000000 (9 or fewer decimal zeroes)
7. 24':'00;000000000 (9 or fewer decimal zeroes)
8. 24;000000000 (9 or fewer decimal zeroes)

There doesn't seem to be any default pattern supporting them all, but some of it can be supported using a `CompositePatternBuilder`.

The first pattern is just `LocalTimePattern.ExtendedIso`. The second and third can easily be implemented with `LocalTimePattern.CreateWithInvariantCulture()`.

However, the fourth and fifth pattern don't seem to be supported at all. Having fractional hours or minutes just results in the `LocalTime` having zeroes for anything below hours/minutes.

The last three are just variations on the above, but for the special case of the late midnight, aka. 24:00:00, which should simply translate to `LocalTime.Midnight`. As long as the hours is 24 it should be possible to use all the other patterns with pure zeroes in any combination. It is possible to use `LocalTimePattern.CreateWithInvariantCulture()` here as well, it just requires you to define all the patterns individually (and that doesn't even support the fractional hours/minutes:

- 24
- 24':'00
- 24':'00':'00
- 24':'00':'00;0
- 24':'00':'00;00
- 24':'00':'00;000
- 24':'00':'00;0000
- 24':'00':'00;00000
- 24':'00':'00;000000
- 24':'00':'00;0000000
- 24':'00':'00;00000000
- 24':'00':'00;000000000

So the first three are easy, the fourth and fifth are currently not possible, and the last 24-hour cases are cumbersome.

**Comment by jskeet** [comment]
Yes, we don't support "fractional minutes" or "fractional hours", which is basically what all of these boil down to.
While those are theoretically required by ISO-8601, I don't think I've *ever* seen this used. Do you have any examples of data where it *is* used, or is this more for absolute completeness?

To be honest, I think it's unlikely that I'd want to implement this - it's likely to make the code rather more complicated for the far, far more common case. I could be persuaded with evidence of it being useful though.

**Comment by lundmikkel** [comment]
Yes, it is a question of completeness, and no, I don't have any data examples using it :)

I'm mainly interested in the three first patterns, since they do make working with manual data input a lot easier. The others where more from trying to get the full specification supported.

**Comment by jskeet** [comment]
Righto. I'll leave this open for a bit, but I don't think it's worth making *useful* code harder to maintain for benefits that would only be theoretical. I suspect that most input of the form (say) 12:34.5 is actually an error in the input rather than intending to mean 12:34:30...

**Comment by jskeet** [comment]
Closing as there hasn't been any further interest. If there's ever a genuine use case beyond completeness, we can reopen.
