### ISSUE TITLE
Make AnnualDate implement IComparable

### ISSUE THREAD

**Issue by lundmikkel** [nodatime/nodatime#1432]
I doesn't seem like [`AnnualDate`](https://github.com/nodatime/nodatime/blob/master/src/NodaTime/AnnualDate.cs) implements the non-generic [`IComparable`](https://docs.microsoft.com/en-us/dotnet/api/system.icomparable) interface, like [`LocalDate`](https://github.com/nodatime/nodatime/blob/master/src/NodaTime/LocalDate.cs) and the rest of the comparable types do. I'm guessing this is just an oversight, but it could be really nice to have :)

**Comment by jskeet** [comment]
True, will fix.

**Comment by carlosschults** [comment]
@jskeet Have you started working on this already? Because in case you haven't, I'd like to give it a try, if you wouldn't mind.

**Comment by jskeet** [comment]
Not yet - feel free!

**Comment by lundmikkel** [comment]
Thanks @WardenUnleashed. Very much appreciated.
