### ISSUE TITLE
CalendarSystem Equality?

### ISSUE THREAD

**Issue by mikernet** [nodatime/nodatime#1440]
It's possible that I'm missing something obvious but `CalendarSystem.ForId()` states:

> Fetches a calendar system by its unique identifier. This provides full round-tripping of a calendar
> system. It is not guaranteed that calling this method twice with the same identifier will return
> identical references, but the references objects will be equal.

I don't see any `GetHashCode` or `Equals` overrides in `CalendarSystem` though. That might cause me some heisenbugs in my serializer's CalendarSystem to ordinal mapping code if that's the case.

I would think hash code and equality testing should be based off of the calendar ordinal.

**Comment by jskeet** [comment]
I suspect the comment was written quite a long time ago. We *did* used to override GetHashCode and Equals a long time ago, I believe - but it was fiddly in some scenarios.

I believe using ForId *will* always give the same reference in fact. I'll do some research about what the current code does, then look at 2.x code.

Is there a particular version you're interested in?

**Comment by mikernet** [comment]
2.x+ is supported and it looks like the behavior is the same in all the versions since then so I'll trust that the comment is just outdated and reference equality will work fine. Based on my skimming it looks like the `CalendarSystem` value is always pulled from static initialized fields so it should always return the same reference.

Thank you!

**Comment by mikernet** [comment]
One more thing - I believe the calendar ID for Badi in [this list](https://nodatime.org/2.4.x/api/NodaTime.CalendarSystem.html#NodaTime_CalendarSystem_Id) should not have the special characters and should just be "Badi".
