### ISSUE TITLE
Incorrect Calendar ID

### ISSUE THREAD

**Issue by mikernet** [nodatime/nodatime#1441]
The ID returned for the "Persian Astronomical" calendar is "Persian Algorithmic", which doesn't seem intentional given that [this table](https://nodatime.org/2.4.x/api/NodaTime.CalendarSystem.html#NodaTime_CalendarSystem_Id) says the ID should be "Persian Astronomical".

I hesitate to suggest changing it now as that will create backwards compat issues but perhaps the correct ID should be documented in the docs?

**Comment by mikernet** [comment]
Actually I take that back...as long as the `CalendarSystem.ForId()` method accepts both variations then I'll be fine, but I can't speak for other serializers that might not like a different ID being returned from the `Calendar.Id` property.

**Comment by jskeet** [comment]
Will try to look into this today.

I don't want to expose CalendarOrdinal if possible though - that's changed quite a bit over time, and I don't want to guarantee its stability.

**Comment by jskeet** [comment]
Hmm. I think that fixing it, but making it accept both could cause problems if there were two systems interchanging data.

I'll document that this is basically a mistake, but one that needs to be preserved forever, unfortunately. Thanks very much for spotting this!

**Comment by jskeet** [comment]
(I'll open a separate feature request for CalendarOrdinal.)
