### ISSUE TITLE
LocalDatePattern.Iso is ambiguously named

### ISSUE THREAD

**Issue by DanCarterGMSL** [nodatime/nodatime#1448]
According to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Calendar_dates) (at least the Wikipedia article on it), there are two allowed format for calendar dates:

- Basic, `YYYYMMDD`
- Extended, `YYYY-MM-DD`

It seems that `LocalDatePattern.Iso` uses the extended format.

This seems perfectly reasonable to me as it is the most widely used as far as I can tell. My question is whether it should be named `ExtendedIso` to make it clear (you could also add `BasicIso`).

This would make it consistent with `InstantPattern.ExtendedIso` too.

**Comment by jskeet** [comment]
I don't want to rename the existing property, but we could add new ones.

**Comment by jskeet** [comment]
It's worth noting that `InstantPattern.ExtendedIso` is about extending into fractions of a second, rather than adding the delimiters, mind you.

**Comment by DanCarterGMSL** [comment]
> It's worth noting that `InstantPattern.ExtendedIso` is about extending into fractions of a second, rather than adding the delimiters, mind you.

Ah that's interesting to know. Hadn't spotted that.

To be clear this isn't causing me too much trouble. I think the main thing was that I only just realised that I'd been referring to `YYYY-MM-DD` as "the ISO format", without knowing that ISO 8601 actually specifies two formats.

**Comment by jskeet** [comment]
I'm going to close this for now, as I suspect that introducing "basic ISO" in a way that doesn't really mirror "extended ISO" would cause more confusion than clarity. (This is my fault for calling the property ExtendedIso in the first place, but I don't want to break folks now for the sake of that.)
