### ISSUE TITLE
[API Suggestion] Add ToString(string patternText) for LocalDate and LocalDateTime 

### ISSUE THREAD

**Issue by Kahbazi** [nodatime/nodatime#1461]

**Comment by jskeet** [comment]
We originally *did* have those. But we removed them before the 1.0 launch, for two reasons:

- We want to encourage the use of patterns as far as possible
- We want to make it really obvious that the culture is relevant to formatting

In very many cases, the current culture *isn't* the one that should be used - it should be the invariant culture instead. (Not *all* cases, but many.) But the culture used by `ToString(string)` *is* conventionally the current culture, so we'd be effectively encouraging a dangerous practice. If you really want to use the current culture, you can just pass `null` as the format provider.

I'll leave this request open for now, to encourage you to provide more justification for why you think we should add these overloads (not just to LocalDate and LocalDateTime - I want to be consistent across all the types that provide custom formatting), but my gut feeling is that we'll need a fair amount of persuading.

**Comment by Kahbazi** [comment]
I'm convinced!

I was passing null for format provider, and wanted to have a _cleaner_ code and also don't like to write my own extension method. Although I wasn't passing any pattern that is different in current culture and invariant culture, I'm now passing invariant culture for all `ToString` method.

Feel free to close this issue, as I'm not need it anymore.

**Comment by jskeet** [comment]
Great, thanks very much for replying so quickly :)
