### ISSUE TITLE
Add YearMonth.AtDayOfMonth

### ISSUE THREAD

**Issue by Neme12** [nodatime/nodatime#1469]
I think there should be a convenience method on `YearMonth` to create a `LocalDate` from a day of month - it might be called `AtDay` or `AtDayOfMonth`.

**Comment by jskeet** [comment]
This shouldn't be too difficult, once we've decided on the right names. Alternative names to consider:

- WithDay (like LocalDateTime.WithOffset)
- OnDay

**Comment by Neme12** [comment]
@jskeet In my opinion, I don't think `With` is the right name here. This method is used to essentially specify more info or "add more precision" to an existing value, much like `LocalDate.At`, without changing the nature of the data type (like `WithOffset`). `With` is also used for adjusters to modify an existing value, which also makes me think it's not really appropriate here.

`On` might be more gramatically correct, but I think consistency is more important and it would be nice to have a convention where going from a data type that represents a wider range of values to a more specific type (by adding more precision) would always use the `At` prefix. This is the convention used in java.time so it should also be familiar to users:

https://docs.oracle.com/javase/8/docs/api/java/time/Year.html (`Year` has methods like `atDay`, `atMonth` and `atMonthDay`),
https://docs.oracle.com/javase/8/docs/api/java/time/YearMonth.html (`YearMonth` has methods like `atDay` and `atEndOfMonth`).

The last one reminds me that `atEndOfMonth` would be useful as well. Do you think it adds enough value to add this method too?

**Comment by jskeet** [comment]
@neiesc : I don't follow your first comment. `LocalDateTime.WithOffset` feels very much like `YearMonth.WithDayOfMonth` to me. Both change the type and add more information.

`OnDayOfMonth` *definitely* feels nicer to me than `AtDayOfMonth`. I think Java made the wrong call here. I believe `OnDayOfMonth` will be more discoverable, although `WithDayOfMonth` would be quite discoverable too. Using a name which just doesn't fit with what any English speaker would say feels like a bad call to me.

I could live with either `On` or `With`, but I'm very far from convinced that `At` is the right way to go. You can keep trying to convince me, but don't get your hopes up. Ironically, `AtEndOfMonth` *does* feel reasonably correct - but I don't want to add that, at least not yet.

**Comment by Neme12** [comment]
>  I don't follow your first comment. LocalDateTime.WithOffset feels very much like YearMonth.WithDayOfMonth to me. Both change the type and add more information.

What I mean is that there's a conceptual difference between dealing with a local date/time, an offset date/time or an instant. By adding an offset, I'm not just adding more precision. I get a value that I need to treat differently. Some operations no longer make sense, like subtraction or comparisons (or I need to think about how I want to compare them). It's not really like adding more precision to pinpoint the data more precisely, like adding a day to a `YearMonth` or adding a time to a `LocalDate` is, where I initially know the data to the nearest month/day and then add information about what part of that month/day it is. Whereas by introducing an offset, I'm sort of adding "another dimension"? 😄 At least that's how I think about it and we can disagree.

**Comment by jskeet** [comment]
While I can *sort* of see what you mean, I'd note that the set of operations you can perform with `YearMonth` is very different to the set of operations you can perform with `LocalDate`. I don't think the difference is really that significant - certainly not compared with the "urgh" jolt I get from the idea of `AtDayOfMonth` which sounds very, very wrong to my ears.

If your preference list goes "At, With, On" and mine goes "On, With, At" maybe we should just settle on With as a common second-best option.

**Comment by Neme12** [comment]
Actually my preference list goes "At, On, With", but I don't want to suggest that my opinion has just as much importance as yours or that the great Jon Skeet should make a compromise for a library used by thousands if not millions with 1 random person on the internet 😀

**Comment by jskeet** [comment]
Okay. Let's see what @malcolmr reckons when he reviews the PR :)

**Comment by malcolmr** [comment]
This does seem more similar to existing methods like `LocalDate.At*()` (and to some extent `DateTimeZone.At*()`) which add additional finer-grained context to an existing type, than to `LocalTime.On(LocalDate)`/`OffsetTime.On(LocalDate)`, which provide a surrounding higher-level context. (Also, those are the only `On*()` methods we have, I think.)

_On the other hand..._ `yearMonth.AtDayOfMonth(d)` really doesn't read very well, so perhaps `yearMonth.OnDayOfMonth(d)` would be okay.

(It's definitely _not_ `With*()`, because — with one exception — all `T.With*()` methods return a `T`. I think `LocalDateTime.WithOffset()`→`OffsetDateTime` was a mistake in that respect, as the only exception to that.)

**Comment by jskeet** [comment]
Personally I'm still okay with `WithOffset`, but I prefer `OnDayOfMonth` to `AtDayOfMonth`. Merged #1471.
