### ISSUE TITLE
Is there a package for Cosmos DB?

### ISSUE THREAD

**Issue by AKlaus** [nodatime/nodatime#1477]
Perhaps, it's a wrong forum, so I ask for forgiveness.
Is there a package for integrating the NodaTime with Comsos DB either via the Entity Framework Core, Cosmonaut or Azure Cosmos DB .NET SDK?

**Comment by jskeet** [comment]
No problem, this is fine. I don't know of any extensions specifically for Cosmos DB itself (there's [this logging one](https://www.nuget.org/packages/Cosmos.Logging.Extensions.NodaTime/) but I doubt that that's what you're after).

Looking at NuGet packages resulting from a search for NodaTime, it doesn't look like there's currently anything, I'm afraid. There *are* packages supporting Noda Time for EFCore with Postgres and SQL Server though, so if you wanted to create your own one, they'd probably be good starting points.

**Comment by BrandonWilliamsCS** [comment]
For others in a similar boat, note that the Cosmos SDK for .NET lets you provide a custom serializer, which you likely wish to do anyway if you have any sort of custom types. In that case, using the existing Json.Net or System.Text.Json serialization packages should be enough to add NodaTime support.
