### ISSUE TITLE
Timezone id mismatch on Mac

### ISSUE THREAD

**Issue by ltvan** [nodatime/nodatime#1479]
I tried this on Mac, netcore 3.1:

```csharp
            var list = TzdbDateTimeZoneSource.Default.ZoneLocations.Select(l => l.ZoneId).OrderBy(l => l).ToList();
            var currentTimezone = DateTimeZoneProviders.Tzdb.GetSystemDefault();
            Console.WriteLine("Hello World! " + currentTimezone.Id);
            list.ForEach(l => Console.WriteLine(l));
```

The curent timezone id is "Asia/Saigon", while the correspondent id in ZoneLocations named "Asia/Ho_Chi_Minh", there is no "Asia/Saigon" in the collection. I search through this repository and found nothing related to "Asia/Ho_Chi_Minh", just found "Asia/Saigon" in the CLDR database. Where does "Asia/Ho_Chi_Minh" come from?

**Comment by jskeet** [comment]
CLDR isn't the source of truth here: IANA is. See the [asia file in the GitHub repository used by the maintainers](https://github.com/eggert/tz/blob/master/asia). There's no Asia/Saigon there, only Asia/Ho_Chi_Minh. So Asia/Ho_Chi_Minh is the *canonical* ID. Asia/Saigon [does appear in the backward file](https://github.com/eggert/tz/blob/master/backward#L43), showing that Asia/Saigon is an *alias* for Asia/Ho_Chi_Minh.

You haven't said what the output of your application was (or which version of Noda Time you're using), so it's hard to know whether or not Noda Time is behaving as expected. But I'd expect to see a time zone ID of "Asia/Saigon", but only see "Asia/Ho_Chi_Minh" in ZoneLocations, as that's the canonical ID. Please clarify whether that's what you actually see.

**Comment by ltvan** [comment]
I'm using version 2.4.7. I'm trying to select the current timezone on a dropdown list. Because the timezond id in ZoneLocations is "Asia/Ho_Chi_Minh", which does not matched with GetSystemDefaultId(), the dropdown does not select correct active timezone.

**Comment by jskeet** [comment]
It sounds like you basically need to get the canonical ID associated with the system default ID, which you can do using `TzdbDateTimeZoneSource.CanonicalIdMap`.

**Comment by ltvan** [comment]
Oh great! Thank you very much.👍

**Comment by jskeet** [comment]
Righto, will close this now.
