### ISSUE TITLE
How to parse LocalDate for/in specific Calendar?

### ISSUE THREAD

**Issue by behzadian** [nodatime/nodatime#1481]
I have a text representing a date in Persian calendar "1398/12/8", but when I parse it using below code:
`LocalDatePattern.CreateWithInvariantCulture("yyyy/M/d,c").Parse(text)`
I got a true text "" but with invalid value.
`.Value` is equal to `{شنبه, 8 اسفند 1398}` (that is true) 
but 
`.Value.AtMidnight().InUtc().ToInstant().ToUnixTimeMilliseconds()` is `-18021052800000` which is NOT correct. (parser assumed 1398 as Gregorian year)

How can I say parser that input text must be parsed with Persian calendar?

**Comment by jskeet** [comment]
I wouldn't expect that code to parse "1398/12/8" anyway, due to the ",c" part in your pattern. But you can specify the calendar system in the template value. For example:

```csharp
var template = new LocalDate(2000, 1, 1).WithCalendar(CalendarSystem.PersianArithmetic);
var pattern = LocalDatePattern.CreateWithInvariantCulture("yyyy/M/d/").WithTemplateValue(template);
// Now use the pattern
```

**Comment by behzadian** [comment]
That `c` was mistake :)
But I found better way, after creating pattern, call WithCalendar like below:
`LocalDatePattern.CreateWithInvariantCulture("yyyy/M/d").WithCalendar(calendar).Parse(text);`

**Comment by jskeet** [comment]
Right, had missed that we'd got that :) Closing now.
