### ISSUE TITLE
Is there any way to use localized version of timezone name instead of English name?

### ISSUE THREAD

**Issue by behzadian** [nodatime/nodatime#1482]
Hi.
I used below format text display a ZonedDateTime:
`dddd d MMMM yyyy ساعت HH:mm به وقت z` that will produce below:
`شنبه 5 بهمن 1398 ساعت 00:00 به وقت Asia/Tehran`

I need to use localized (Persian translated) version of `Asia/Tehran` like `آسیا/تهران`

is there anyway?

**Comment by jskeet** [comment]
No, these are identifiers - they're not really intended for "user" consumption, so much as developer consumption. At some point we may include data from CLDR for time zone info, but at the moment that only goes as far as Windows ID mapping.

**Comment by jskeet** [comment]
I'm going to close this issue for now as we already have #997 as a broad "include localization information from CLDR" feature.
