### ISSUE TITLE
List of ZoneInterval names

### ISSUE THREAD

**Issue by Smoovsky** [nodatime/nodatime#1483]
Hi all,

I found that the timezone name in ZoneInterval is more familiar to us:
![image](https://user-images.githubusercontent.com/34542126/75850448-74919200-5e3b-11ea-9021-4b3b457fe1ab.png)

But unlike Tzdb timezones, I can't find a list for them. 
Where may I find them?

Thank.

**Comment by jskeet** [comment]
These come from the IANA database. I don't believe there's a comprehensive list - and even if there were, it wouldn't be terribly useful IMO, as there are ambiguities. For example, "CST" is generally UTC-6 in the US, but UTC+8 in Asia.

If you want to come up with a complete list, you'd basically iterate over all time zones, and all zone intervals within each zone (I'd suggest putting an upper limit of, say, 2030 when finding zone intervals), then add the names to a set.

**Comment by Smoovsky** [comment]
> These come from the IANA database. I don't believe there's a comprehensive list - and even if there were, it wouldn't be terribly useful IMO, as there are ambiguities. For example, "CST" is generally UTC-6 in the US, but UTC+8 in Asia.
> 
> If you want to come up with a complete list, you'd basically iterate over all time zones, and all zone intervals within each zone (I'd suggest putting an upper limit of, say, 2030 when finding zone intervals), then add the names to a set.

Much appreciated!
