### ISSUE TITLE
DateTimeZoneProviders throwing Type Initializer Exception 

### ISSUE THREAD

**Issue by jmc-crash** [nodatime/nodatime#1485]
I have integrated NodaTime with a Unity project. This is mostly working except that I am building for WebGL which is incompatible with any threading libraries. For this reason I have been unable to use System's TimeZoneInfo structures to convert between timezones. 

I am running the following NodaTime code:

```
DateTimeZone siteTimeZone = DateTimeZoneProviders.Tzdb["America/New_York"];
ZonedDateTime zonedSiteDT = siteTimeZone.AtStrictly(new LocalDateTime(year, month, day, hour, minute));

returnTime = zonedSiteDT.ToDateTimeUtc();
```

And the first line is throwing an exception: "The type initializer for 'NodaTime.DateTimeZoneProviders.TzdbHolder' threw an exception"

which has an inner exception message: "The type initializer for 'NodaTime.TimeZones.TzdbDateTimeZoneSource.DefaultHolder' threw an exception"

**Comment by jskeet** [comment]
And does *that* have an inner exception? There should be a real exception somewhere at the bottom...

**Comment by jmc-crash** [comment]
It goes one more deep but is almost just as cryptic. 

1st Inner Exception: "The type initializer for NodaTime.TimeZones.TzdbDateTimeZoneSource.DefaultHolder' threw an exception"

2nd Inner Exception: "Value cannot be null. Parameter name: stream"

**Comment by jskeet** [comment]
Okay, I understand what that is - that basically means it's failed to load the embedded data within the assembly.

You can *potentially* fetch a .nzd file from nodatime.org (see https://nodatime.org/tzdb/latest.txt for the latest URL) and then use `TzdbDateTimeZoneSource.FromStream` to load the source - see https://nodatime.org/2.4.x/userguide/tzdb for a bit more code to help with this.

I have no idea why Unity would fail to load the stream, but this is the code it uses:

```csharp
using (Stream stream = assembly.GetManifestResourceStream("NodaTime.TimeZones.Tzdb.nzd"))
```

... so you probably want to look at any caveats around `Assembly.GetManifestResourceStream` for Unity.

**Comment by jmc-crash** [comment]
Aha I see. My guess is that it uses a threaded process to read the tzdb file. That is exactly where the .net implementation failed as well (albeit in a slightly different manner). Unity's WebGL builds aren't compatible with threaded processes. 

I will try using a web request to get the nzd file that way and see if it works.

**Comment by jskeet** [comment]
There's no explicit threading there - not in the NodaTime code. Maybe there's something deep in the framework though...

**Comment by jmc-crash** [comment]
Yeah I had to dig pretty deep into the Mono source to find the call to Interlocked so it is likely under the hood. I'll post here if the solution works.

**Comment by jmc-crash** [comment]
I have it set up but once again another WebGL quirk...I'm getting a CORS error. Apparently CORS needs to be allowed on the host server for WebGL to be able to access it (see WebRequest classes in WebGL): https://docs.unity3d.com/Manual/webgl-networking.html

I'm guessing the server hosting the nzd files does not have this enabled? I'm accessing https://nodatime.org/tzdb/tzdb2019c.nzd.

**Comment by jskeet** [comment]
No, and I'd be loathe to add a global pass on that without significant thought first. But it would probably be simplest for you to host the nzd file yourself, then you can update it after testing, etc.

**Comment by jmc-crash** [comment]
Yes, understandably. Just a heads up for anyone else that might have this niche problem! 

Thanks!

**Comment by jmc-crash** [comment]
In addition:

I managed to implement streaming the file from my own server and have managed to access it. I am trying to get the DateTimeZone for "America/New_York" and now I get two Inner Exceptions:

First: The type initializer for 'NodaTime.Text.OffsetPattern' threw an exception

Second (deepest): Could not find any resources appropriate for the specified culture or the neutral culture.

Is it possible the file has streamed in incorrectly? I based my implementation on the example provided here: https://nodatime.org/2.4.x/userguide/tzdb. But instead of using OpenRead, I use a MemoryStream to read the stream the download as a binary stream and give that stream to the source.

**Comment by jskeet** [comment]
That sounds like it's a different problem now. The full stack trace would help, but basically it's more failure to load resources. I *suspect* you'll find the exception talks about `PatternResources.ResourceManager`, which tries to load `PatternResources.resx`.

It sounds like the WebGL platform just isn't suitable for libraries which assume normal .NET capabilities.

Closing this issue now as I don't believe this is really a NodaTime problem.
