### ISSUE TITLE
Support for XML Schema Definition

### ISSUE THREAD

**Issue by 0xced** [nodatime/nodatime#1496]
Are you planing to release version 3.0 soon? I have been working on adding support for XML Schema Definition in NodaTime and I think it would be a good feature to have in version 3.

The pull request is almost ready, sneak peek: https://github.com/0xced/nodatime/tree/XmlSchemaDefinition

**Comment by jskeet** [comment]
I was hoping to - recent events have somewhat changed my ability to plan anything.

Some options:

- I release 3.0, and you rebase to that, getting the change into 3.1
- I wait and merge the change, then release 3.0
- I wait and merge the change, then release another beta

I'm tempted to go for the last option, but I'm interested in your opinion.

If you could make it clear what impact this has, that would be really useful :)

**Comment by 0xced** [comment]
I would love to see it in 3.0. The pull request is up in #1500. Let's continue the discussion in the pull request.

**Comment by jskeet** [comment]
Reopening to leave this as the *feature request* that's hopefully implemented by the PR.

**Comment by jskeet** [comment]
Closing now as it's implemented.
