### ISSUE TITLE
Cut down our TODO list

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nodatime/nodatime#150]
```
At the time of this writing (November 11th 2012, shortly post v1.0) we have 72 
TODO items.

It would be nice to get this down to (say) half by the time we ship v1.1.

(This issue exists to nag us, essentially. We should create a new one - or 
update this one - on each release, to keep track of how we're doing.)
```

Original issue reported on code.google.com by `jonathan.skeet` on 11 Nov 2012 at 10:06

**Comment by jskeet** [comment]
We're now up to 41 in the NodaTime project. Will try to work through them and at least reduce them significantly before 2.0.

**Comment by jskeet** [comment]
We also have 11 FIXMEs which obviously need addressing...

**Comment by jskeet** [comment]
Removing the 2.0 milestone now, as I think we're fine for the time being.

**Comment by jskeet** [comment]
Prior to proposed 2.3.0 release:

- NodaTime: 22 TODOs
- NodaTime.Demo: 5 TODOs
- NodaTime.Test: 9 TODOs
- NodaTime.Testing: 1 TODO
- NodaTime.TzdbCompiler: 1 TODO
- NodaTime.TzValidate.NodaDump: 2 TODOs
- NodaTime.TzValidate.NzdCompatibility: 2 TODOs

We have a single FIXME, but it doesn't *need* fixing - it just *could* be fixed. (More thought needed about whether it should be fixed or not though.)

**Comment by jskeet** [comment]
None of the TODOs are urgent, btw. Most are old.

**Comment by jskeet** [comment]
Closing this now as I doubt that we'll ever get down to 0, and I do periodically check anyway. Quite a large proportion of the ones in the NodaTime project are now the same thing around an XmlSchema method, and entirely unimportant :)
