### ISSUE TITLE
America/Cuiaba no longer observes DST

### ISSUE THREAD

**Issue by prazi** [nodatime/nodatime#1507]
America/Cuiaba no longer observes DST so the nodatime database should be updated.
https://www.timeanddate.com/time/change/brazil/cuiaba

**Comment by jskeet** [comment]
Sounds like you're probably using an old version of Noda Time, or an old version of the database - if you use the latest version of the database (2019c) you'll see it's already there:
https://nodatime.org/tzvalidate/generate?zone=America/Cuiaba
