### ISSUE TITLE
Set period to half a month for semi-monthly periods?

### ISSUE THREAD

**Issue by SonofNun15** [nodatime/nodatime#1533]
Does Noda currently support semi-monthly time periods... i.e. half a month?

There's a bit of complexity here that I would love to abstract away as half a month in some months is 15 / 16 days and in other months it is consistently 15 days. Or February... where it could be 14 or maybe 15.

Looks like Periods take the number of months as an integer so I'm assuming this is not supported. In basic .NET, we solved like so:

```
case RecurrenceFrequency.SemiMonthly:
    var days = DateTime.DaysInMonth(date.Year, date.Month);
    var halfMonth = days / 2;

    if ((days % 2) != 0 && date.Day > halfMonth)
    {
        halfMonth++;
    }

return date.AddDays(halfMonth);
```

**Comment by jskeet** [comment]
No, we don't have anything like this - and I wouldn't expect to introduce
it, to be honest. I'm afraid you'll need to do that part yourself.

Note that it's potentially not as simple as the code you've given. If
you're adding half a month to February 28th in a non-leap year, for
example, should you add 14 days, or 16? Every day you add is within March,
and March has 31 days...

Jon

**Comment by SonofNun15** [comment]
Fair enough. Thanks for the quick response!
