### ISSUE TITLE
YearMonth should have a TypeConverter

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime#1539]
I'm looking at the changes between 2.3 and 3.0-beta, and one such is #1237, in which we added TypeConverter support for all public types, using ISO patterns or otherwise.

We later added `YearMonth`, but we didn't go back and add a TypeConverter for `YearMonth`, even though `YearMonthPattern.Iso` exists.

Should we? (and should we for 3.0?)

**Comment by jskeet** [comment]
Good question. I think it's probably simple enough to be worth doing for 3.0.
