### ISSUE TITLE
Provide TypeConverters for Duration and Instant

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nodatime/nodatime#154]
```
*What situation does this request make simpler?*

    This would make porting existing code that makes use of TypeConverters for System.DateTime and System.TimeSpan over to NodaTime simpler (generic string conversions for example).

*Can you provide a straw-man example of what you'd want the API to look
like?*

    No direct API is necessary. I believe it's a matter of implementing the TypeConverters in NodaTime, and decorating the Instant and Timespan classes with the TypeConverter attribute. 

What I would like to see is the following:

```

TypeConverter converter = TypeDescriptor.GetConverter(typeof(Instant));
Assert.IsTrue(converter.CanConvertFrom(typeof(string)));
Assert.IsTrue(converter.CanConvertTo(typeof(string)));
Assert.IsTrue(converter.CanConvertFrom(typeof(System.DateTimeOffset)));
Assert.IsTrue(converter.CanConvertTo(typeof(System.DateTimeOffset)));
string dateTimeString = "..."; // <- this would be any string accepted by 
DateTimeOffset.Parse()
Instant instant = converter.ConvertFrom(dateTimeString);

```

For durations, the same thing as above would apply, but the string would be any 
valid System.Timespan string.
```

Original issue reported on code.google.com by `bryanjam...@gmail.com` on 29 Nov 2012 at 9:48

**Comment by austindrenski** [comment]
@jskeet Is anyone currently working on this?

**Comment by jskeet** [comment]
I'm not - I don't know enough about TypeConverters to make the right decisions. If you do (or want to research until you do) that would be great.

**Comment by austindrenski** [comment]
I'll take a look and see if I can put together a PR in the next few days.

For some context: 

Initially, I'm looking to support a `TypeConverter` for `LocalDate`. The @npgsql project integrates NodaTime through a plugin model for ADO.NET and EF Core. PostgreSQL range types (e.g. `daterange`) are mapped to CLR range types (e.g. `NpgsqlRange<LocalDate>`). 

The `TypeConverter` for `NpgsqlRange<T>` assumes that a `TypeConverter` for `T` will be available for bound parsing, and when one isn't available, the operation throws. (This impacts various aspects of the MVC framework, model binding, etc.)

**Comment by sfmskywalker** [comment]
Any updates on this?

**Comment by austindrenski** [comment]
@sfmskywalker I still need to write some unit tests, but you can take a look at #1237 for the general idea.

**Comment by sfmskywalker** [comment]
Nice work. Looking forward to it getting merged in so I can get rid of my own type converters 👍

**Comment by jskeet** [comment]
@sfmskywalker: Just to reiterate, even once it's merged, there won't be a release containing this code for some time, unless I decide to create a 2.5 release, which I'm somewhat reluctant to do.
(If there's some *other* reason to create a 2.5 release, I may include it in that.)

**Comment by sfmskywalker** [comment]
Understood.

**Comment by oskardudycz** [comment]
@jskeet is it possible to do `2.5.0` release with those changes? In Marten we have issue: https://github.com/JasperFx/marten/issues/1276 - Looking at the discussion this plus https://github.com/nodatime/nodatime/pull/1237 shouls solve the issue.

**Comment by jskeet** [comment]
@oskardudycz: It's a pretty significant amount of effort, that I certainly don't have time to do right now. I would definitely *prefer* not to. I'll bear the request in mind next time I happen to have several hours with nothing better to do, but I wouldn't expect it imminently.

**Comment by oskardudycz** [comment]
Thank you for the feedback. 
I'll try to hack it with custom `JsonConverter` suited for this case and revisit that when the release is out.
