### ISSUE TITLE
Parsing Two Digits Years

### ISSUE THREAD

**Issue by imranbaloch** [nodatime/nodatime#1556]
We are parsing MRZ https://en.wikipedia.org/wiki/Machine-readable_passport but unfortunately, the year is 2 digits long. So we are not sure whether 70 is 1970 or 2070 but I feel maybe there is something common for handling 2 digit years. Does NodaTime have something common that can handle the 2 digits years optimistically?

**Comment by jskeet** [comment]
I'm not sure what you mean by "optimistically", but currently the cut-off is hardcoded to 30. From the [LocalDate pattern user guide](https://nodatime.org/3.0.x/userguide/localdate-patterns):

> Two digit year of era, in the range 0-99. When parsing, the "base century" is chosen from the template value; if the two-digit year is greater than 30, the corresponding year in the previous century is used, unless the century of the template value is already the first century of the era.

We have a long-standing TODO to make this configurable, but we haven't actually had any demand for it so far.

**Comment by imranbaloch** [comment]
Thanks, Jon found some interesting discussion at https://github.com/evermeer/PassportScanner/issues/30

So, in short I assume it's all about the context where 2 years digits is used and we need to adjust it accordingly.

**Comment by jskeet** [comment]
@imranbaloch: I don't really understand your second sentence. Are you saying you *do* need this as a feature in NodaTime, or that you'll adjust in your code? (For reference, if you need anything in the nearish future, you'll need to do the adjustment in your code. I don't expect to find time to work on this and then do a release within the next few months.)

**Comment by imranbaloch** [comment]
Yes Jon thanks, yes I mean for now I will adjust the code using TwoDigitYearMax (https://docs.microsoft.com/en-us/dotnet/api/system.globalization.calendar.twodigityearmax?view=netcore-3.1). Thanks for your help.
