### ISSUE TITLE
Suggestion to add SafeStart and SafeEnd extension methods to Interval

### ISSUE THREAD

**Issue by rexcfnghk** [nodatime/nodatime#1558]
Currently, we have usages of the `Interval` struct involving missing `Start`/`End`. The code eventually consolidates the presence/absence of these `Instant` values into separate fields. However, boilerplate checks have to be added before accessing `Interval.Start` or `Interval.End` because of the potential `InvalidOperationException`.

We have thus implemented convenience methods for these scenarios:

```c#
public static T SafeStart<T>(
    this Interval interval,
    Func<Instant, T> startInstantSelector,
    T replace = default) => interval.HasStart
    ? startInstantSelector(interval.Start)
    : replace;

public static T SafeEnd<T>(
    this Interval interval,
    Func<Instant, T> endInstantSelector,
    T replace = default) => interval.HasEnd
    ? endInstantSelector(interval.End)
    : end;
```
I suspect this is a very common use case and these methods are generic enough to be included in the NodaTime library itself.

**Comment by jskeet** [comment]
I don't remember ever wanting something like this myself - that's not to say others don't want it, but I haven't seen evidence that it's a "very common use case".

Let's leave this feature request up and see if anyone else wants it - if not, presumably you're fine sticking to your own extension methods.

**Comment by jskeet** [comment]
As an update - rather than those methods, would `StartOrNull` and `EndOrNull` (or maybe `SafeStart` and `SafeEnd`) properties which use null to convey "infinite" be acceptable? I think they would be more general purpose than those methods.

**Comment by jskeet** [comment]
Oh, and we could add `SafeDuration` too.

**Comment by rexcfnghk** [comment]
I personally don't really like using `null`s to represent 'infinite' but I see your point of using properties being more general purpose.

The use case for me to add these `SafeStart` and `SafeEnd` methods is I need a way for my scheduling system to make a decision on events that do not have definite start/end dates. I like NodaTime being explicit about representing instants extending to the ends of timelines by having `BeforeMinValue`/`AfterMaxValue` but I do not like it crashing when I access these instants with `Start` and `End`.

It would be great if NodaTime can allow the caller to decide what to do with these cases. Instead of returning `null`, perhaps considering exposing `BeforeMinValue`/`AfterMaxValue` or have a wrapper type that encapsulates both 'valid' instants and instants extending beyond the termini of timelines?

**Comment by jskeet** [comment]
No, I *definitely* don't want to expose `BeforeMinValue` and `AfterMaxValue`. They are not instants that can be used like any other instants - they don't represent instants in time. We're taking great care to avoid those ever leaking into user code, where they could do significant harm. 

I think using null is actually reasonable here: "What's the start point of this interval? Oh, there isn't one." It's using null to represent the absence of a concrete value. I think it's also reasonable that if code *expects* a regular instant and there isn't one, an exception is thrown.

> It would be great if NodaTime can allow the caller to decide what to do with these cases.

We already do, via `HasStart` and `HasEnd`. It's not like you have to just catch the exception.

**Comment by rexcfnghk** [comment]
I see. You are probably right about using `null` to represent the absence of intervals.

> We already do, via HasStart and HasEnd. It's not like you have to just catch the exception.

While that is true, it still relies on the developer to remember to perform the `HasStart`/`HasEnd` check before accessing `Start`/`End`. I think your suggestion of having a new API that returns `Instant?` would solve this problem because the return type clearly indicates to the developer there is a possibility of `null`.

**Comment by jskeet** [comment]
Right. Note that developers would still need to remember to use `StartOrNull` or `SafeStart` or whatever we call it - I wouldn't be changing the _existing_ properties (as that would be a breaking change).

**Comment by rexcfnghk** [comment]
Would you like me to make a PR to add `SafeStart` and `SafeEnd`? (I personally like the `SafeX` variant more 😄 )

**Comment by malcolmr** [comment]
-0.5 to calling this `SafeStart`, fwiw; it's not really any more or less safe than the existing methods. `StartOrNull` seems reasonable.

I do wonder how much a method like this would end up being used, and whether it's worth expanding the API to do so (and writing private extension methods to add those two methods are pretty straightforward).

**Comment by jskeet** [comment]
Not having seen any traffic on this issue for over 4 years, I'm minded to close it. @rexcfnghk is this still something you're keen on?

**Comment by rexcfnghk** [comment]
> Not having seen any traffic on this issue for over 4 years, I'm minded to close it. @rexcfnghk is this still something you're keen on?

Given the discussion it's probably best to leave the code as is and close this issue. Thanks! 🙏

**Comment by jskeet** [comment]
Thanks for the quick response! Much appreciated :)
