### ISSUE TITLE
Months Names with Different cultures

### ISSUE THREAD

**Issue by fahadabdulaziz** [nodatime/nodatime#1561]
Hello,
When using `.ToString("yyyy MMMM dd", SomeCulture)` to show the date with month name, in some cases it shows the month name wrong.

```csharp
LocalDate _myBirthDate = new LocalDate(1920, 5, 19);
LocalDate _myBirthDateHijri = _myBirthDate.WithCalendar(CalendarSystem.UmAlQura);
Console.WriteLine($"My Birth date: {_myBirthDate.ToString("yyyy MMMM dd", CultureInfo.GetCultureInfo("ar"))}");
Console.WriteLine($"My Birth date in Hijri: {_myBirthDateHijri.ToString("yyyy MMMM dd", CultureInfo.GetCultureInfo("ar"))}");
Console.WriteLine($"My Birth date: {_myBirthDate.ToString("yyyy MMMM dd", CultureInfo.GetCultureInfo("en"))}");
Console.WriteLine($"My Birth date in Hijri: {_myBirthDateHijri.ToString("yyyy MMMM dd", CultureInfo.GetCultureInfo("en"))}");
```

The result is:
```
My Birth date: 1920 جمادى الأولى 19 << Wrong Hijri name with Gregorian Calendar
My Birth date in Hijri: 1338 رمضان 01 << Right Hijri name with Hijri Calendar
My Birth date: 1920 May 19 << Right Gregorian name with Gregorian Calendar
My Birth date in Hijri: 1338 September 01 << Wrong Gregorian name with Hijri Calendar
```

**Comment by jskeet** [comment]
Yes - this is unfortunate, but we don't have a good way round it at the moment, without taking on a *huge* burden of understanding and copying CLDR data. Basically at the moment it's up to you to make sure that the CultureInfo you provide uses the same calendar system as the date you're formatting.

While I would *like* to fix that (and Hebrew month name formatting, which is a particularly tricky part) it's certainly beyond the scope of what I have time to work on any time soon.

What I *can* do is add more information about that in the user guide (e.g. at https://nodatime.org/3.0.x/userguide/text)

**Comment by fahadabdulaziz** [comment]
Thank you Jon for the quick response,
Why not make every calendar has its months names in English instead of using DateTimeFormat from the culture.
The BCL they convert the date to the culture's primary calendar so the DateTimeFormat is working with them.

**Comment by jskeet** [comment]
> Why not make every calendar has its months names in English instead of using DateTimeFormat from the culture.

Because then it's impossible to use in any culture other than English. When someone has said "I want to use French" it would be very odd to use English instead.

**Comment by fahadabdulaziz** [comment]
At least it's better than wrong ones :-)

Just a suggestion, In DatePatternHelper.CreateMonthOfYearHandler method, if could reach the calendar of the date, we could find the right culture.
Let's say we have a Gregorian date but the use asked for "ar" we could find a culture has the Gregorian as primary calendar and use its months names, if we don't find one, just fall back the English names built in calendars (Assuming we put English name list)

**Comment by jskeet** [comment]
> At least it's better than wrong ones :-)

Where it *would* be wrong. But your suggestion would break a lot of currently-correct situations. I'd suggest that "specifying a non-English culture matching the calendar system of the date being formatted" is more common than "specifying an English culture for a non-Gregorian date."

The second proposal sounds very heuristic in a way that's hard for users to predict. (What if we asked "en" but for a non-Gregorian date? Your fourth case from the first comment would still be broken.)

Just to be up-front about the conditions I'd want any PR to meet:

- Behaviour of existing code should not be changed. (Users upgrading from NodaTime 3.0 to NodaTime 3.1 shouldn't see a change to their date formatting.)
- Additional members can be added to the Pattern classes to opt into new behaviour.
- Performance of existing code shouldn't be impacted very significantly - it might be okay to have *some* impact, but it would need to be small.

As an example of a new API, I can imagine new methods of "WithEnglishNames" that would keep the *patterns* of whatever culture is being used, but force English names based on the calendar system of the date being formatted (or parsed, presumably). Note that I'd expect "WithEnglishNames().WithCulture(...)" to be equivalent to "WithCulture()" - because the culture does specify the names.

**Comment by fahadabdulaziz** [comment]
I tried writing this code but a huge failure :-D

```csharp
            Console.WriteLine(GetMonthName(5, new UmAlQuraCalendar(), CultureInfo.GetCultureInfo("ar-eg")));
            Console.WriteLine(GetMonthName(5, new HijriCalendar(), CultureInfo.GetCultureInfo("ar-eg")));
            Console.WriteLine(GetMonthName(5, new HebrewCalendar(), CultureInfo.GetCultureInfo("ar-eg")));
            Console.WriteLine(GetMonthName(5, new GregorianCalendar(), CultureInfo.GetCultureInfo("ar-eg")));
            Console.WriteLine(GetMonthName(5, new JulianCalendar(), CultureInfo.GetCultureInfo("ar-eg")));
            Console.WriteLine(GetMonthName(5, new PersianCalendar(), CultureInfo.GetCultureInfo("ar-eg")));

            Console.WriteLine(GetMonthName(5, new UmAlQuraCalendar(), CultureInfo.GetCultureInfo("en")));
            Console.WriteLine(GetMonthName(5, new HijriCalendar(), CultureInfo.GetCultureInfo("en")));
            Console.WriteLine(GetMonthName(5, new HebrewCalendar(), CultureInfo.GetCultureInfo("en")));
            Console.WriteLine(GetMonthName(5, new GregorianCalendar(), CultureInfo.GetCultureInfo("en")));
            Console.WriteLine(GetMonthName(5, new JulianCalendar(), CultureInfo.GetCultureInfo("en")));
            Console.WriteLine(GetMonthName(5, new PersianCalendar(), CultureInfo.GetCultureInfo("en")));

            Console.WriteLine(GetMonthName(5, new UmAlQuraCalendar(), CultureInfo.GetCultureInfo("fr-ca")));
            Console.WriteLine(GetMonthName(5, new HijriCalendar(), CultureInfo.GetCultureInfo("fr-ca")));
            Console.WriteLine(GetMonthName(5, new HebrewCalendar(), CultureInfo.GetCultureInfo("fr-ca")));
            Console.WriteLine(GetMonthName(5, new GregorianCalendar(), CultureInfo.GetCultureInfo("fr-ca")));
            Console.WriteLine(GetMonthName(5, new JulianCalendar(), CultureInfo.GetCultureInfo("fr-ca")));
            Console.WriteLine(GetMonthName(5, new PersianCalendar(), CultureInfo.GetCultureInfo("fr-ca")));

        private static string GetMonthName(int month, Calendar calendar, CultureInfo culture)
        {
            if (culture.Calendar.GetType() == calendar.GetType())
                return $"!!! {calendar.GetType().Name} has a match culture! ({culture.Name})"; // return culture.DateTimeFormat.MonthNames[month];
            else
            {
                CultureInfo[] cultures = CultureInfo.GetCultures(CultureTypes.AllCultures);

                for (int i = 0; i < cultures.Length; i++)
                {
                    if(cultures[i].TwoLetterISOLanguageName == culture.TwoLetterISOLanguageName)
                        if (cultures[i].Calendar.GetType() == calendar.GetType())
                            return $"!!! {calendar.GetType().Name} has a match culture! ({culture.Name})"; // culture.DateTimeFormat.MonthNames[month];
                }
            }

            return $"{calendar.GetType().Name} has no match culture! ({culture.Name})";
        }
```

The result

```
!!! UmAlQuraCalendar has a match culture! (ar-EG)
HijriCalendar has no match culture! (ar-EG)
HebrewCalendar has no match culture! (ar-EG)
!!! GregorianCalendar has a match culture! (ar-EG)
JulianCalendar has no match culture! (ar-EG)
PersianCalendar has no match culture! (ar-EG)
UmAlQuraCalendar has no match culture! (en)
HijriCalendar has no match culture! (en)
HebrewCalendar has no match culture! (en)
!!! GregorianCalendar has a match culture! (en)
JulianCalendar has no match culture! (en)
PersianCalendar has no match culture! (en)
UmAlQuraCalendar has no match culture! (fr-CA)
HijriCalendar has no match culture! (fr-CA)
HebrewCalendar has no match culture! (fr-CA)
!!! GregorianCalendar has a match culture! (fr-CA)
JulianCalendar has no match culture! (fr-CA)
PersianCalendar has no match culture! (fr-CA)
```

**Comment by fahadabdulaziz** [comment]
After further research on this, I can confirm it's Mission Impossible :-D
It needs huge work to localize these calendars as it has some mixing names like gregorian calendar every month has four names in Arabic (and not including Gaddafi names of months) differs between cultures! (https://en.wikipedia.org/wiki/Arabic_names_of_Gregorian_months)

Sorry @jskeet for bothering you on this..

**Comment by fahadabdulaziz** [comment]
Just for reference I used this method to localize months names.
https://gist.github.com/fahadabdulaziz/0d53ee67ad112cbd9173eedcb325c46c
