### ISSUE TITLE
UTC and FixedDateTimeZone with Several System.InvalidOperationExceptions

### ISSUE THREAD

**Issue by PaoloOranges** [nodatime/nodatime#1563]
`FixedDateTimeZone` is built and initialized with 
```
interval = new ZoneInterval(name, Instant.BeforeMinValue, Instant.AfterMaxValue, offset, Offset.Zero);
```
using `Instant.BeforeMinValue` and ` Instant.AfterMaxValue` in `ZoneInterval` makes `ZoneInterval.RawStart` and `ZoneInterval.RawEnd` throwing an exception on accessing any of the following Properties:
```
ZoneInterval.Start;
ZoneInterval.End;
ZoneInterval.Duration;
ZoneInterval.Start;
ZoneInterval.IsoLocalStart;
ZoneInterval.IsoLocalEnd;
```

that because on both `Start` and `End` properties there's: `Preconditions.CheckState(RawEnd.IsValid, "Zone interval extends to the end of time");` that fails and throw `System.InvalidOperationExceptions`.

This behaviour is making `FixedDateTimeZone` and, more important "UTC" `DateTimeZone` from `DateTimeZoneProviders.Tzdb["UTC"]` throwing that exception on accessing any of the mentioned properties.

Is this the correct behaviour?

**Comment by jskeet** [comment]
Will look at this tomorrow. It's not clear what *your* code is that's throwing though - a complete example would be helpful.

**Comment by PaoloOranges** [comment]
Hi! true. This is a snippet to test reproduce the issue, it is very similar to the code I'm using, the only difference is that Instants are hard-written.
```
            DateTime startTime = DateTime.SpecifyKind(new DateTime(2020, 08, 30), DateTimeKind.Utc); 
            DateTime endTime =  DateTime.SpecifyKind(new DateTime(2020, 09, 2), DateTimeKind.Utc);

            DateTimeZone dtz = DateTimeZoneProviders.Tzdb["Europe/London"];
            var zoneIntervals = dtz.GetZoneIntervals(Instant.FromDateTimeUtc(startTime), Instant.FromDateTimeUtc(endTime)).ToList();
            if (zoneIntervals.Count == 1 && zoneIntervals[0].Start == Instant.MinValue && zoneIntervals[0].End == Instant.MaxValue)
            {
                System.Console.WriteLine("Do something here");
            }

            dtz = DateTimeZoneProviders.Tzdb["UTC"];
            zoneIntervals = dtz.GetZoneIntervals(Instant.FromDateTimeUtc(startTime), Instant.FromDateTimeUtc(endTime)).ToList();

            // Exception thrown in the following statement
            if (zoneIntervals.Count == 1 && zoneIntervals[0].Start == Instant.MinValue && zoneIntervals[0].End == Instant.MaxValue)
            {
                System.Console.WriteLine("Do something here");
            }
```
accessing `zoneIntervals[0].Start` or `zoneIntervals[0].End` throws on the second if condition.

**Comment by jskeet** [comment]
Right. Basically, this is by design - you should use `HasStart` and `HasEnd` to detect if the `ZoneInterval` has an actual start/end point. It looks like `Start` doesn't have the exception documented, but `End`, `IsoLocalStart`, `IsoLocalEnd` and `Duration` are already documented.

If we implement #1558 which relates to `Interval`, we could do the same for `ZoneInterval` at the same time.
I'll definitely fix the lack of documentation for the exception in `Start`, but the current *behavior* is correct.

**Comment by PaoloOranges** [comment]
I see. `HasStart` and `HasEnd` works perfectly. Thanks for clarification and sorry for the "false positive".

**Comment by jskeet** [comment]
Not a problem - I'd always rather answer a question than have users confused :)
