### ISSUE TITLE
Global IClock instance

### ISSUE THREAD

**Issue by michal-ciechan** [nodatime/nodatime#1566]
Would you be open to adding a "Global" `IClock` singleton instance to use which defaults to SystemClock? With a big caveat telling people they should be injecting IClock rather than using this static singleton version. (for newcomers who may not understand the downsides)

E.g.

```csharp
public static class Clock 
{
   public static IClock Default { get; set; } = SystemClock.Instance;
}
```

This would ease testing for a number of our scenarios, as trying to inject an IClock instance is not feasible/overkill in simple scenarios such as trying to timestamp a DTO during deserialization.

I find that either

 1. There is a different global instance in each app, which can be named/located differently per developer/team. This makes it painful when you want to share code which doesn't necessarily want to inject IClock (its our own foot we are shooting I know)
 2. Have our own shared library which contains a global `IClock` instance. Again, not every team agrees, and some teams have their own.

In my (mainly CRUD enterprise) experience, most work does not need multiple individual clocks per test, and if needed can change the code which does need different clocks for whatever reason to either:

1. Inject IClock instance where needed in these edge cases as per best practice
2. Custom implementation of IClock which returns different clocks depending on async context or whatever other reasons there are.

Often we have objects timestamped with their creation time, and used in deserialization, unless we change our serializers all the way down the stack to start using DI just to inject IClock, we have to resort to our own IClock singleton.

**Comment by jskeet** [comment]
> Would you be open to adding a "Global" IClock singleton instance to use which defaults to SystemClock?

No. Global mutable state is basically a bad idea IMO, and I don't want to encourage it in Noda Time. If your company wants to disagree with me, it's absolutely trivial for you to create your own shared library for that, and use that as widely or narrowly as you want to... but I definitely don't want to add it into Noda Time directly.

**Comment by jskeet** [comment]
(Just to clarify, do feel free to make other similar suggestions in the future - I don't want to give the impression that I'm averse to suggestions for change in general. I just definitely don't want to do this particular one :)
