### ISSUE TITLE
IZoneIntervalMap and IZoneIntervalMapWithMinMax violate code analysis rule CA2119

### ISSUE THREAD

**Issue by stack111** [nodatime/nodatime#1583]
Hi there, we have internal tooling which identified the following [interfaces](https://github.com/nodatime/nodatime/blob/master/src/NodaTime/TimeZones/IZoneIntervalMap.cs) as violating a severe vulnerability from Microsoft's code analysis triage process. The specific rule is [CA2119](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2119).

There are many ways to fix this issue, as described in the link I provided. As it currently is implemented the code is open to manipulation from outside of the library through `internal` `interface` plus `abstract`. So if the original intent is to use interface could we consider marking the following interfaces as public anyways. 

Alternatively, other implementations are welcome but also could result in downstream breaking changes.

**Comment by stack111** [comment]
> I definitely don't want to make those interfaces public though.
Understood

To be fair, we happen to have an older folk of this repo (historically for whatever reason). So there is a good chance this issue may have been resolved which latest version of this code. So my plan is to clone and see if I can apply the code analyzer and catch a repro. 

Hopefully I can repro the [analyzer](https://github.com/dotnet/roslyn-analyzers/pull/757) but if not it likely is being triggered from one the derived classes from the interface which contain `virtual` or `abstract`. I'm actually not familiar with this code base.

**Comment by jskeet** [comment]
This hasn't changed for ages. And yes, `DateTimeZone.GetZoneInterval` is still abstract - but I don't see how that's a problem, given that the expectations of the interface are the same as the expectations of the abstract method. I think this is *effectively* just a false positive from the analyzer - not in a way that suggests it's broken, just in that it isn't always a problem.

**Comment by stack111** [comment]
`public abstract DateTimeZone` is implying a downstream consumer can implement a derived instance.
`internal interface IZoneIntervalMap` is restricts the polymorphism to the local assembly. 

Internally in the library, I could provide malicious behavior of my derived `DateTimeZone` which internal nodatime library components would depend on. It's a remote vulnerability in that sense. Granted I'm not a security expert, I'm sharing what I know and hoping that we don't see this as just false positive (maybe it is and I'm incorrect?).

In terms of impact of injecting behavior on a DateTimeZone implementation, I can't give a qualified assessment of that. One of the possible fixes would be to apply `DateTimeZone` as `internal` not `public`.

**Comment by jskeet** [comment]
I'm afraid I'm still having a really hard time understanding what you believe the problem is.

> `public abstract DateTimeZone` is implying a downstream consumer can implement a derived instance.

Yes, and they can.

> `internal interface IZoneIntervalMap` is restricts the polymorphism to the local assembly.

Can you clarify *exactly* what you mean by "restricts the polymorphism"?

> Internally in the library

Sorry, which library? 

> I could provide malicious behavior of my derived DateTimeZone which internal nodatime library components would depend on. 

Well you could provide a broken implementation of `GetZoneInterval`, yes - and yes, the rest of NodaTime depends on you doing that correctly, just as if you provide a broken implementation of `IComparer<T>` and use that for sorting, you'll get bad results.

I don't see how making the `IZoneIntervalMap` interface public changes that at all.

> It's a remote vulnerability in that sense.

"Remote" in what sense? Certainly not network-remote - if you're using this in some very precise security researcher sense, I'd be grateful if you'd clarify it, because for a lot of people, saying that NodaTime has a "remote vulnerability" would imply that if you use NodaTime in your system, attackers can penetrate your system via network requests.

> One of the possible fixes would be to apply DateTimeZone as internal not public.

Um, no. That's like saying `System.String` should be internal. `DateTimeZone` is one of the fundamental types in NodaTime. We don't expect many people *will* create their own `DateTimeZone` implementation, but we don't want to stop them from doing so.

As a comparison, `System.IO.Stream` has abstract methods too - someone could write a malicious implementation of `System.IO.Stream`... how is `DateTimeZone` worse than that, and what does the internal interface have to do with it? It's not like we use the `IZoneIntervalMap` interface as a way of saying "This code must be absolutely fine."

To give a concrete example of a workaround which I suspect would pacify the analyser without having *any* real world benefits, suppose I change the method name in `IZoneIntervalMap`:

```csharp
internal interface IZoneIntervalMap
{
    ZoneInterval GetZoneIntervalInternal(Instant instant);
}
```

Then implement that in `DateTimeZone` like this:

```csharp
public class DateTimeZone : IZoneIntervalMap
{
    // Interface implementation is now *not* virtual or abstract, but just delegates to an abstract method.
    ZoneInterval IZoneIntervalMap.GetZoneIntervalInternal(Instant instant) => GetZoneInterval(instant);

    // Existing abstract method
    public abstract ZoneInterval GetZoneInterval(Instant instant);
}
```

What's the benefit of doing that? Or with the other suggestion of making the interfaces public, what would the benefit of *that* be? Can you give an example of a security vulnerability that would be avoided by either of those approaches?

Sorry if I'm sounding a bit defensive here, but a message of "your library has a severe security vulnerability" really needs to be backed up with concrete evidence IMO.

**Comment by jskeet** [comment]
And of course, if there really *is* a severe security vulnerability, I want to know... but I can't see how this is one beyond the risk you *always* get with having library code execute "code from elsewhere" via virtual methods, abstract methods, interfaces or delegates.

**Comment by jskeet** [comment]
I've created a pull request in https://github.com/nodatime/nodatime/pull/1584

If you're able to run the analyzer on that branch, I'd be interested to hear the results.

**Comment by stack111** [comment]
I've [forked the repo](https://github.com/stack111/nodatime) and [installed the analyzer](https://github.com/stack111/nodatime/commit/702d083ad5125ebb43ee1f3d275241a89f0d437a) and built the project. 
`CA2119` is not showing. This probably means the bug was fixed in somewhere in the git history. 

Unfortunately, I did not decide to fork the library at the time, it was done in 2017 or earlier. These types of issues are sometimes the result of forking libraries in general. If I'm given enough time I would prefer us to take a package dependency from NuGet. However, the amount time time required may triple or more due to the breaking changes and unknowns.

In any case, apologies if you are offended in any way by use of "severe", genuinely that is what our tooling classifies the issue as. You and I are comparing against source repository (here) and a older fork (our repo). So I would really appreciate less hostile responses, some patience, and assumption of positive intent. All I'm trying to do is help contribute to a library we depend on. 

The purpose of raising the issue was to get a better understanding of the design of this library so I can use the knowledge to help make a better informed decision about what to do with the bug.

For the benefit of the code you can see the results of the analyzers and use the results as you see fit:

These are the errors for `NodaTime.csproj`, I won't include warnings as some of these may constitute design opinions.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CA1801	Parameter message of method .ctor is never used. Remove the parameter or use it in the method body.	NodaTime	C:\Repos\stack111-nodatime\src\NodaTime\Annotations\TestExemptionAttribute.cs	18	Active
Error	CA1823	Unused field 'DaysPerLeapCycle'.	NodaTime	C:\Repos\stack111-nodatime\src\NodaTime\Calendars\PersianYearMonthDayCalculator.cs	119	Active
Error	CA1801	Parameter noValidation of method .ctor is never used. Remove the parameter or use it in the method body.	NodaTime	C:\Repos\stack111-nodatime\src\NodaTime\Duration.cs	132	Active
Error	CA1822	Member 'ConvertGenitiveMonthArray' does not access instance data and can be marked as static	NodaTime	C:\Repos\stack111-nodatime\src\NodaTime\Globalization\NodaFormatInfo.cs	177	Active
Error	CA1801	Parameter deliberatelyInvalid of method .ctor is never used. Remove the parameter or use it in the method body.	NodaTime	C:\Repos\stack111-nodatime\src\NodaTime\Instant.cs	79	Active
Error	CA1801	Parameter deliberatelyInvalid of method .ctor is never used. Remove the parameter or use it in the method body.	NodaTime	C:\Repos\stack111-nodatime\src\NodaTime\LocalInstant.cs	30	Active
Error	CA1822	Member 'TryParseFixedZone' does not access instance data and can be marked as static	NodaTime	C:\Repos\stack111-nodatime\src\NodaTime\Text\ZonedDateTimePatternParser.cs	164	Active
Error	CA1822	Member 'ForId' does not access instance data and can be marked as static	NodaTime	C:\Repos\stack111-nodatime\src\NodaTime\TimeZones\BclDateTimeZoneSource.cs	107	Active
Error	CA1822	Member 'CheckSingleField' does not access instance data and can be marked as static	NodaTime	C:\Repos\stack111-nodatime\src\NodaTime\TimeZones\IO\TzdbStreamData.cs	239	Active
Error	CA1724	The type name Resolvers conflicts in whole or in part with the namespace name 'System.Xml.Resolvers'. Change either name to eliminate the conflict.	NodaTime	C:\Repos\stack111-nodatime\src\NodaTime\TimeZones\Resolvers.cs	23	Active
Error	CA1822	Member 'GuessZoneIdByTransitionsUncached' does not access instance data and can be marked as static	NodaTime	C:\Repos\stack111-nodatime\src\NodaTime\TimeZones\TzdbDateTimeZoneSource.cs	308	Active
Error	CA1822	Member 'Name' does not access instance data and can be marked as static	NodaTime	C:\Repos\stack111-nodatime\src\NodaTime\TimeZones\ZoneInterval.cs	142	Active
Error	CA1822	Member 'WallOffset' does not access instance data and can be marked as static	NodaTime	C:\Repos\stack111-nodatime\src\NodaTime\TimeZones\ZoneInterval.cs	148	Active
Error	CA1822	Member 'Savings' does not access instance data and can be marked as static	NodaTime	C:\Repos\stack111-nodatime\src\NodaTime\TimeZones\ZoneInterval.cs	154	Active
```

**Comment by jskeet** [comment]
> So I would really appreciate less hostile responses, some patience, and assumption of positive intent. All I'm trying to do is help contribute to a library we depend on.

While I can sort of appreciate that, I'd suggest you review your initial issue comment, and try to put yourself in my shoes. I have **no context** (for example, that this is a library you depend on) and this looks like a pretty serious accusation of sloppy coding ("we have internal tooling which identified the following interfaces as violating a severe vulnerability") in a library that I've poured thousands of hours into. More context from the outset, along with an explanation that "violating a severe vulnerability" doesn't really mean "the code is vulnerable" but "it's *possible* that the code is vulnerable, we'd appreciate it if you'd investigate this" would really have helped. We should both probably have done better here.

I still don't understand *why* the analyzer triggered before but doesn't now, though. I don't think that aspect of the code has changed for ages - and as described, it really *is* still "vulnerable". I don't actually want to change the current code, but I'd like to understand it better.

I'll readily put a bit of time into working that out myself - is the installation of Microsoft.CodeAnalysis.FxCopAnalyzers all that's required? (In your first comment you refer to internal tooling, which I inferred to mean "non-public" tooling.) If this is just standard FxCop, I'll happily look into it.

I'll review the other errors as well - thanks for those.

**Comment by jskeet** [comment]
Reflecting on all of this further, I really do apologize for the hostility.

**Comment by stack111** [comment]
> While I can sort of appreciate that, I'd suggest you review your initial issue comment, and try to put yourself in my shoes. I have **no context** (for example, that this is a library you depend on) and this looks like a pretty serious accusation of sloppy coding ("we have internal tooling which identified the following interfaces as violating a severe vulnerability") in a library that I've poured thousands of hours into. More context from the outset, along with an explanation that "violating a severe vulnerability" doesn't really mean "the code is vulnerable" but "it's _possible_ that the code is vulnerable, we'd appreciate it if you'd investigate this" would really have helped. We should both probably have done better here.

Understood, thank you for the feedback, I definitely did not intend to insult especially with respect to the amount of hours we work on our code. Yes it is my mistake to be more communicative and clear in a sense of what we treat as severe is not the same to others as well as what exactly is the ask initially.  

> I still don't understand _why_ the analyzer triggered before but doesn't now, though. I don't think that aspect of the code has changed for ages - and as described, it really _is_ still "vulnerable". I don't actually want to change the current code, but I'd like to understand it better.

I haven't gone through the git history, but there is a good chance any changes to derived classes over the time may have actually solved the problem. I don't recommend changing anything here either since it doesn't reproduce any result. 

> I'll readily put a bit of time into working that out myself - is the installation of Microsoft.CodeAnalysis.FxCopAnalyzers all that's required? (In your first comment you refer to internal tooling, which I inferred to mean "non-public" tooling.) If this is just standard FxCop, I'll happily look into it.

The standard the ruleset treats it CA2119 as warning, on our build system apparently we treat this severe error and must fix. But in any case if you need a reference to [how I ran the analyzer](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019). I need to understand why our process is considering this as a significant issue. I do suspect tooling to the be the problem here not the code.

**Comment by jskeet** [comment]
Great - let's move forward together :)

Do you know which version of the analyzer you ran that showed the problem? (I know you ran it against an old version of the code, but I don't know whether that's because you *recently* ran it against a fork from a while ago, or whether you're going through results of an analysis that took place a long time ago.)

I'll try it against old versions of the NodaTime code (just by tag, initially) and report the results here as I go.

**Comment by jskeet** [comment]
Using FxCop 3.3.1:

- 2.0.x branch - warning not present
- 2.1.x branch - warning not present
- 2.2.x branch - warning not present
- 2.3.x branch - warning not present
- 2.4.x branch - warning not present

Trying to build against the 1.4.x branch fails entirely - I suspect I'd need to use an older version of MSBuild etc. Next step, older versions of FxCop against 2.0.x...

**Comment by jskeet** [comment]
Okay, using the 2.0.x branch:

- FxCop 1.2.0-beta01: build failed
- FxCop 2.0.0-beta02: warning not present
- FxCop 2.3.0-beta01: warning not present
- FxCop 2.6.0: warning not present
- FxCop 2.9.12: warning not present
- FxCop 3.0.0: warning not present

So now I'm just confused :(

I *can* reproduce the warning with the code in the [rule description](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2119) so my next step is to work out exactly what makes it not trigger for the NodaTime code... (I'll create a new project to repro that.)

**Comment by jskeet** [comment]
Got it! It's because there are two interfaces involved, and only the "super" interface has a method that's not sealed, but the type only explicitly declares that it implements the "sub" interface.

I've filed https://github.com/dotnet/roslyn-analyzers/issues/4406

That does leave the question of what to do with the warning in NodaTime though - because once the bug is fixed, the warning will be raised again.
(My guess is that you were analyzing version 1.4, which [doesn't have IZoneIntervalMapWithMinMax](https://github.com/nodatime/nodatime/blob/1.4.x/src/NodaTime/DateTimeZone.cs).)

I could suppress the warning in the project file - which I may end up doing for some other FxCop warnings anyway. (This issue has caused me to have another look at everything... there are some things I don't want to change, but others that I do...)

**Comment by stack111** [comment]
Based on what I've seen in our code, we do have `IZoneIntervalMapWithMinMax` so my guess is we forked from NuGet version 2.0.2 or greater. Sadly we made pretty drastic design changes which resulted in making `TzdbStreamData` public as an example. So appears that we would have to unravel large set of changes to switch over to using the published NuGet.

Suppressing might be fine in this case, I still can't come up with a reason why it's being marked as must fix.

**Comment by jskeet** [comment]
Ah, interesting. If you would ever like me to help get you back to the main release stream, I'd be happy to do whatever I can. (Note that staying on the vanilla NuGet releases means you get TZDB updates for free too - but you can always update those yourself with the nzd file either from GitHub or downloaded from nodatime.org.)
