### ISSUE TITLE
Incorrect timezone for America/Chicago

### ISSUE THREAD

**Issue by VitaliiIsaenko** [nodatime/nodatime#1587]
Hi! 
I noticed that the time returned for the timezoneId `America/Chicago` is not correct. When I google it, it tells me that [the current time there is UTC-6](https://www.zeitverschiebung.net/en/timezone/america--chicago). However, using `Tzdb` provider I get UTC-5 for the timezone. 
I have `NodaTime 3.0.3` installed and I saw the commit about updating to the latest version of iana database `2020d`. So I'm confused whether I need to do something extra to apply this new change or it's just iana problem? (I downloaded and checked the file with timezone rules from iana for Chicago and it seems they have -6 as the latest rule - not sure I could read it right, pretty confusing format).
[According to the docs](https://nodatime.org/3.0.x/userguide/tzdb) it looks like the new database is simply updated to every new patch release with the minor version update (where 3.0.3 is the latest)

Maybe I just don't use it correctly (though I'm not sure since it works for other timezones like `Europe/Germany` that also uses Daylight Saving Time). I convert it like this in the automapper (I insert `IDateTimeZoneProvider in the context of the mapping as the third param `p`):
```
.ForMember(evm => evm.EndTime, mo => mo.MapFromWithLocale(
                    (e, l, p) => LocalDateTime.FromDateTime(e.EndTime).InZoneStrictly(p[e.TimezoneId])
```
where `e.EndTime` is just 'wall time' + `e.TimezoneId` is a string with the timezone as [recommended in your blog post](https://codeblog.jonskeet.uk/2019/03/27/storing-utc-is-not-a-silver-bullet/) (I use `DateTime` in the model to map easier with my database through EntityFramework)

Can you help me to achieve the right time for the `America/Chicago` timezone as well?

EDIT:
Okay, I just created a small testing project and there it actually works correctly with -06 for `America/Chicago` so it's definitely not the database/NodaTime problem... Then I guess it's the way I'm using it and again some problem with `DateTime` -> `LocalDateTime` conversion. 

Thank you for the great project :)

**Comment by jskeet** [comment]
Okay, I'll close it now as I don't think there's anything wrong with NodaTime here. Given the partial code you've shown, I wonder whether this is really just a matter of `e.EndTime` being in summer time, in which case UTC-05 is entirely correct...

**Comment by VitaliiIsaenko** [comment]
That is totally current what you say, I used the 27th of October (stored in Postman that I played with) and in Chicago they change the time on 1st of November but in Germany they change on 25th of October (example that I said works correctly for me - that brought confusion). 
That datetime domain is tough to get into :smile: 
Thank you for help!
