### ISSUE TITLE
DateInterval should allow to specify end day inclusive or exclusive

### ISSUE THREAD

**Issue by buvinghausen** [nodatime/nodatime#1588]
@jskeet I work in Insurance and policy term dates are always expressed in an end date exclusive fashion ex
![Quote Snapshot](https://user-images.githubusercontent.com/1130210/99094504-87975d00-2599-11eb-8c85-c7852ffdc6a8.png)

I want to use the DateInterval class to represent it because it perfectly encapsulates the term notion but there is no way I can build a UI that shows dates differently because that's how this dinosaur industry has operated for ages.

I think it would be a pretty minimal impact to the code but the biggest question I have is on the deserialization side since we'd need a way to hydrate the exclusive override when chosen.  My default assumption would be to add a nullable boolean property where exclusivity is only triggered when the value is set to true and the other two states default to inclusivity as presently designed.

The rest of the code would be very straightforward as there really would only be three changes

1. Set the == operator to compare start date & length rather than end date
2. Contains just choose between < or <=
3. Length then just add 1 or 0 days

Let me know what your thoughts are and I'm happy to take a stab at a PR if you're amenable to the suggestion.

**Comment by jskeet** [comment]
We discussed this extensively before DateInterval was first actually included in a release - initially it was configurable via a constructor parameter. The result of the discussion was to make `DateInterval` always end-inclusive.

While changing that wouldn't be a lot of code, I would regard it as effectively a breaking change - code that was based on the documentation of the current implementation could reasonably assume that the documentation still held true, and miss the "it's sometimes end-exclusive" aspect. So whether or not making `DateInterval` always inclusive to start with was actually the right call, it's not something I want to change now.

Instead, I would suggest that you wrap `DateInterval` in your own `EndExclusiveDateInterval` type. That should be quite easy to do - and you only need to handle serialization and text formatting as far as you need it yourself, of course.

**Comment by buvinghausen** [comment]
Gotcha thanks for the context.  Have a great weekend!
