### ISSUE TITLE
OffsetDateTime gets generated as String by svcutil

### ISSUE THREAD

**Issue by panthus** [nodatime/nodatime#1597]
When generating data contracts with `svcutil` any property of type `OffsetDateTime` will get generated as a `string` instead of `OffsetDateTime`. I attached a simple project that reproduces the problem:
1. Install Nuget packages and build the project
2. Run `Run.bat` (it expects that .NET Framework 4.7.2 SDK tools are installed).
3. The outputted `Client.cs` file has string as the type of property `Test1` of class `Test` instead of type `NodaTime.OffsetDateTime`.

I think this happens because the Xml schema of `OffsetDatetime` [XmlSchemaDefinition.cs#L100](https://github.com/nodatime/nodatime/blob/master/src/NodaTime/Xml/XmlSchemaDefinition.cs#L100) is defined as a pattern and does not have a `calendarRestriction` like for example [XmlSchemaDefinition.cs#L111](https://github.com/nodatime/nodatime/blob/master/src/NodaTime/Xml/XmlSchemaDefinition.cs#L111). 

At least if I manually change the `nodatime.org.api.xsd` file that `svcutil` generates to include the `calendarRestriction` then it works as expected.

[NodaTime3SvcUtilOffsetDateTime.zip](https://github.com/nodatime/nodatime/files/5617338/NodaTime3SvcUtilOffsetDateTime.zip)

**Comment by jskeet** [comment]
cc @0xced who knows about this stuff - I really don't know anything about the XmlSchemaDefinition side of things.

**Comment by 0xced** [comment]
@panthus

> At least if I manually change the `nodatime.org.api.xsd` file that `svcutil` generates to include the `calendarRestriction` then it works as expected.

Could you please elaborate on this please? How *exactly* are you modifying the generated `nodatime.org.api.xsd` file?

**Comment by panthus** [comment]
Of course, attached the original `nodatime.org.api.xsd` and my modified version.

`Run.bat` consists of two `svcutil` commands the first generates the `xsd` files. I then modified `nodatime.org.api.xsd`. The second command then generates the correct code given the modified `nodatime.org.api.xsd`.

[Metadata.zip](https://github.com/nodatime/nodatime/files/5618632/Metadata.zip)

**Comment by panthus** [comment]
I cleaned it up a bit more and included the `xsd` for `LocalDate` as that originally contained the definition for the calendar type. Attached the original `xsd` for `LocalDate` and the clean-up modified `xsd` for `OffsetDateTime`. I did notice that this creates a `calendar` enum type in the generated `Client.cs` so that is a bit weird, but for the rest is all works correctly.

[Metadata-modified.zip](https://github.com/nodatime/nodatime/files/5618735/Metadata-modified.zip)

**Comment by 0xced** [comment]
I have refined the NodaTime XML schema in my branch: [xml-schema-complex-types](https://github.com/0xced/nodatime/tree/xml-schema-complex-types). All XML schema types are now complex types, which should solve the issue of `svcutil` producing strings instead of NodaTime types.

Are you comfortable to test your project with NodaTime compiled from source on my branch or do you need help?
