### ISSUE TITLE
ZonedDateTime.Hour seems to not be 0-based as the desc suggests

### ISSUE THREAD

**Issue by benmccallum** [nodatime/nodatime#1599]
Potentially I'm missing something super obvious, but the description on `ZonedDateTime.Hour` says:
> Gets the hour of day of this zoned date and time, in the range 0 to 23 inclusive.

So I wrote my code under that assumption, making sure to `+1` before comparing to what we'd understand as humans as the clock hour:
```c#
public bool IsWithinReasonableBusinessHours(string ianaTimeZone)
{
    var tz = _tzProvider.GetZoneOrNull(ianaTimeZone)
        ?? throw new ArgumentOutOfRangeException(nameof(ianaTimeZone));

    var now = _clock.GetCurrentInstant();
    var nowInTz = now.InZone(tz);

    var nowHour = nowInTz.Hour + 1; // since it's 0-based
    return nowHour >= 8 && nowHour <= 18; // 8am - 6pm
}
```

Then I wrote some tests, of which the 18 hr ones fails, as `nowInTz.Hour` above is actually saying 18, not 17 as I was lead to believe.
```c#
[Theory]
[InlineData("Australia/Brisbane", 8, 0, true)]
[InlineData("Australia/Brisbane", 12, 0, true)]
[InlineData("Australia/Brisbane", 18, 0, true)]
[InlineData("Australia/Brisbane", 19, 0, false)]
[InlineData("Australia/Sydney", 8, 0, true)]
[InlineData("Australia/Sydney", 12, 0, true)]
[InlineData("Australia/Sydney", 18, 0, true)]
[InlineData("Australia/Sydney", 19, 0, false)]
[InlineData("Australia/Perth", 8, 0, true)]
[InlineData("Australia/Perth", 12, 0, true)]
[InlineData("Australia/Perth", 18, 0, true)]
[InlineData("Australia/Perth", 19, 0, false)]
public void IsWithinReasonableBusinessHours_Works(
    string ianaTz, 
    int currentHourInTz,
    int currentMinuteInTz,
    bool expected)
{
    // Arrange
    var tzProvider = DateTimeZoneProviders.Tzdb;
    var nowInTz = tzProvider[ianaTz].AtStrictly(
        new LocalDateTime(2020, 1, 1, currentHourInTz, currentMinuteInTz));
    var clock = new FakeClock(nowInTz.ToInstant());
    var service = new BusinessHoursService(tzProvider, clock);

    // Act
    var actual = service.IsWithinReasonableBusinessHours(ianaTz);

    // Assert
    expected.ShouldBe(actual);
}
```

Again, sorry if I'm doing something stupid. Checking `LocalDateTime`'s ctor param descs seems to say that year is "absolute" but doesn't mention the month being zero-based, just that it's "The hour.". Also notable is that the tzs I'm doing it across, some have Daylight Savings, some don't so that's not it.

So I guess I'm just wondering if the desc on the Hour property is wrong? Cheers!

**Comment by jskeet** [comment]
> So I wrote my code under that assumption, making sure to +1 before comparing to what we'd understand as humans as the clock hour

That's the problem. You shouldn't be adding 1. It's 0-based in that "12 midnight" is 0, but "1am" is still 1am. 11pm is 23. This is just the normal 24-hour clock, which goes from 0-23.

**Comment by jskeet** [comment]
To put it another way: humans use 0-based hours as well - and 0-based minutes and 0-based seconds. We just rename 0 to 12 on the clock-face for some reason. But's not *truly* 1-based in the same way that it would be if the first hour of the day started at 1am.

**Comment by jskeet** [comment]
(Closing as I don't believe there's anything to be done in codebase. Happy to still go back and forth in comments, but this isn't an issue that needs attention, so to speak.)

**Comment by benmccallum** [comment]
Thanks @jskeet, great explanation and that all makes 100% sense. Silly me - we do work zero-based as humans; not sure where my brain was at :P 

And thanks for noticing that bug too! In this case exclusive will be enough for me as this is just a rough boundary to not spam people with SMSs outside reasonable business hours. 

Cheers!
