### ISSUE TITLE
BclDateTimeZone in 2.4.x for netstandard 2.0

### ISSUE THREAD

**Issue by Pvlerick** [nodatime/nodatime#1602]
Hi there,

We are currently using version 2.4.x in our based netstandard2.0 codebase, but we would like to use the BclDateTimeZone that is not available.  As this is used in a package that is used in a lot of places, upgrading to 3.x is a bit painful and we'd prefer to defer that to later. I stumbled upon this thread https://github.com/nodatime/nodatime/issues/1400 that implies that it would possible to backport the class from 3.x to 2.4.x

I guess what I'm asking is if you would be open to the idea for this or not. I/we would be happy to work on a PR for this :-)

**Comment by jskeet** [comment]
I would strongly prefer not to do that, to be honest. It would require a 2.5.0 release (as it's a new feature) which introduces quite a significant amount of work in terms of the web site, TZDB updates etc. While it's feasible, I don't expect to have enough time to do that release until *at least* the end of January.

Upgrading to 3.x shouldn't be difficult unless you're using binary serialization. Could you give details about why you believe it would be "a bit painful"?

**Comment by Pvlerick** [comment]
It is used a central package that references NodaTime like this: ```[2.4.6, 3.0.0)```. If we change this, ideally we need to make a major version of our packages, which are used all over the places in services. We didn't plan to make a major version this soon as we are quite happy with the current one.

Our other option is to change the references to ```[2.4.6, 4.0.0)``` as I'm pretty sure nobody is using anything that has changed from 2 to 3. We'll go with that then.

In any event, the last thing I wanted was to create work for you, so I guess you answered the question :-)

**Comment by jskeet** [comment]
Thanks for being understanding about that - apologies for it being work either way. Good luck with updating. (Completely agree with your reasoning about a major version for your own package. Dependencies and SemVer are awkward.)
