### ISSUE TITLE
NodaTime 3.0.4 and 2.4.12 publishing to nuget

### ISSUE THREAD

**Issue by mr-russ** [nodatime/nodatime#1610]
The latest versions of NodaTime are not available on nuget.  I know the changes in the tzdb are small between 2020d and 2020e/f.  But those changes were released some time ago and I am wondering when these might be published to nuget to make it easier to use them in other packages.

Thanks for a great time library.

Russell

**Comment by jskeet** [comment]
Gosh - thanks for pointing that out. I must have been trying to do too many things that morning. Fortunately as it happens, I still have the nupkg files that were built (but not pushed). Pushing now...

**Comment by jskeet** [comment]
Pushed. Just need to wait for them to go through validation etc. Should be available soon.
Thanks so much for pointing this out!
