### ISSUE TITLE
Brazil no longer using DST

### ISSUE THREAD

**Issue by jholovacs** [nodatime/nodatime#1614]
It looks like Brazil has abolished Daylight Savings Time altogether in 2019 (see https://en.wikipedia.org/wiki/Daylight_saving_time_in_Brazil), but NodaTime still seems to reference it as respecting DST.

America/Sao_Paulo and others likely affected.  According to https://nodatime.org/TimeZones it's still on DST.

**Comment by jskeet** [comment]
No, that's not what the page shows. As per the notes (at the bottom of the page, linked from the column title):

> The offsets for each zone are the ones which are effective (in the specified version) in the interval [2000-01-01T00:00, 2040-01-01T00:00). May time zones observed a wider range of offsets earlier than the year 2000. There's nothing special about the year 2000 here; it's just an arbitrary cutoff that is likely to give enough information for most uses. Of course, using Noda Time directly you can find all the offsets ever observed.

If you look at https://nodatime.org/tzvalidate/generate?version=2021a&zone=America/Sao_Paulo you'll see there are no transitions later than February 2019, as expected.
