### ISSUE TITLE
"Canada/East-Saskatchewan" Timezone not found in DateTimeZoneProviders.Tzdb

### ISSUE THREAD

**Issue by erwan-joly** [nodatime/nodatime#1615]
HI I've been trying to resolve the Tzdb for the timezone  `Canada/East-Saskatchewan` I'm getting from https://github.com/mj1856/TimeZoneConverter and it doesn't seems to resolve.
Is that timezoneId still suppose to be supported ?

CF https://github.com/mj1856/TimeZoneConverter/issues/89

**Comment by mj1856** [comment]
This was removed in the IANA 2017c data.  I wouldn't expect it to be in Noda Time's TZDB provider.

**Comment by jskeet** [comment]
Thanks for digging, Matt - closing as this isn't a problem in Noda Time.

Note that https://nodatime.org/tzvalidate/generate?version=2017b shows the zone *was* present (as expected) in 2017b.
