### ISSUE TITLE
Provide a way to distinguish fixed-offset timezone from "real" ones

### ISSUE THREAD

**Issue by gha-zund** [nodatime/nodatime#1617]
Hi!

I'm currently developing an API where I want to provide time zone information. I use NodaTime in the backend. The Fronted uses date-fns-tz to parse the identifier provided by the API.
Now, date-fns-tz cannot deal with e.g. "UTC+01".

I need fixed-offset zone in my API as a fallback (created by a local timestamp), when the actual time zone is not present.

Now, I have to implement a conversion for those fixed-offset zones. It's a pitty that neither DateTimeZone.IsFixed nor FixedDateTimeZone is accessible, since the property / the class is internal. But that would be very convenient (and less error prone).
Now I'm checking the identifier of the DateTimeZone, if it starts with "UTC" but is not equal to DateTimeOffset.Utc to find out, if it's a fixed-offset zone. I think that's not very beautiful.

**Comment by jskeet** [comment]
It's not clear to me from the description what you're actually trying to do. You can find out whether a zone always observes the same offset using `zone.MaxOffset == zone.MinOffset`. Strictly speaking, that wouldn't mean it's guaranteed to do so forever - a zone which has never had any transitions *yet* could still change to have one in the future, but perhaps that doesn't matter for your use case?

**Comment by gha-zund** [comment]
Since I want to use built-in types only in the API, the time zone is provided as a string.
For me it's a valid case to also provide fixed-offset time zones in the API.

The Frontend (consumer of the API) uses a library which says "UTC+01" is not a valid time zone identifier. But the same library can work with offsets directly. So I want to provide "+01:00" instead of "UTC+01" for the time zone string value.
Do do that, I must distinguish real time zones from fixe-offset ones.

I think I will use zone.MaxOffset == zone.MinOffset, but in combination with .StartWith("UTC").
Sidenote: for that, it would also be convenient too if DateTimeZone.UtcId would be public.

**Comment by jskeet** [comment]
> Sidenote: for that, it would also be convenient too if DateTimeZone.UtcId would be public.

I don't think that would provide any *concrete* benefit beyond you writing a similar constant in your code. We might do it at some point, but it would only ever have the value "UTC" so you're safe to include it yourself.

I'll close this feature request now, as I don't anticipate making API changes for it unless we receive more feature requests for it.

**Comment by gha-zund** [comment]
alright. Thanks for the quick answers anyways! :)
