### ISSUE TITLE
Provide an option to get time zone by id ignoring casing

### ISSUE THREAD

**Issue by gha-zund** [nodatime/nodatime#1618]
At the moment, identifier checks are case-sensitive.
It would be nice to have at least an option to ignore the casing, so that e.g. "utc" is recognized as "UTC" or "europe/zurich" as "Europe/Zurich" correctly.

**Comment by jskeet** [comment]
I would rather not add that complexity for a fairly niche use case.

You can ask a `DateTimeZoneProvider` for all the IDs it supports, so you can build your own `Dictionary<string, string>` using a case-insensitive comparer to map the string insensitively to the correct ID. You'd need to special-case "UTC" and values starting with "UTC+" or "UTC-" (case-insensitively) but that would be pretty easy to do.

**Comment by jskeet** [comment]
Closing as I still don't want to do this, and the workaround seems okay.
