### ISSUE TITLE
Make "slow" tests opt-in instead of opt-out

### ISSUE THREAD

**Issue by eatdrinksleepcode** [nodatime/nodatime#1625]
(Copied from [#1182](https://github.com/nodatime/nodatime/issues/1182#issuecomment-751635345))

CI skips "slow" tests (the ones which verify an entire calendar), which are apparently only run prior to release. However, the instructions for running the tests don't mention the "NoSlowTests.runsettings" file, which on my machine drops the time for "dotnet test NodaTime.Test" from about 2.5 minutes to 40 seconds. It's also not necessarily easy to skip the slow tests when running through an IDE's test runner, and doing so would be IDE-specific.

It would be great if running these slow tests were opt-in instead of opt-out, which would make skipping them the default for developers. This could be achieved using the Explicit attribute instead of Category, or possibly by using Assert.Ignore (based on an environment variable?).

**Comment by jskeet** [comment]
If we use the `Explicit` attribute, is it easy to opt into *all* the slow tests? I'm fine with that - I don't want to have to know about all the tests individually, if you see what I mean. It feels like we want a category that is "off by default"...

The workaround of using `Assert.Ignore` based on an environment variable does sound like an interesting option.
