### ISSUE TITLE
How to send client timezone from javascript and convert utc time in database using nodatime on server and make sure that dst changes apply

### ISSUE THREAD

**Issue by pantonis** [nodatime/nodatime#1626]
I have been searching and could not find an example of the most basic scenario of how to get the timezone from a javascript client send it to server and convert a time that is in utc stored in database using NodaTime but one that includes the DST changes
Is there any example out there?

**Comment by jskeet** [comment]
Well, there are two parts there: getting the time zone ID from the client, and performing the conversion in Noda Time once you've done that. Which part are you stuck on, and what have you tried so far?

**Comment by pantonis** [comment]
both lol :) 

Actually I managed to get the timezone using moment-timezone ```moment.tz.guess();``` but I dont know if there are any browser compatibilities (e.g a browser returns a name and another browser returns different name).

Apart from my times in db are in utc and I want to convert them to clients timezone but I cannot find how to di it using Nodatime

**Comment by jskeet** [comment]
I would expect browsers to use TZDB (aka IANA) IDs, e.g. "Europe/London".

You should then be able to use:

```csharp
string id = ...; // From the browser
Instant instant = ...; // Wherever you get the UTC date/time from
DateTimeZone zone = DateTimeZoneProviders.Tzdb[id];
ZonedDateTime zonedDateTime = instant.InZone(zone);
```

**Comment by pantonis** [comment]
Thanks
