### ISSUE TITLE
Period.Between for YearMonth

### ISSUE THREAD

**Issue by lilinus** [nodatime/nodatime#1632]
Had to write my own Period.Between for YearMonth when I noticed there wasn't any in the library.

If it was added I would expect it to look something like:
- Works in the same way as for LocalDates with rounding to start, exceptions etc.
- Allowed units are years and months.
- Could be implemented using YearMonth.StartDate?
- Method without units defaults to units year and month

I could make a PR for this if it seems like something that could be added to NodaTime

**Comment by jskeet** [comment]
Yes, that sounds very reasonable to me - would welcome a PR. Thanks!

**Comment by jskeet** [comment]
Fixed by #1633
