### ISSUE TITLE
[Not an Issue] Designed Decision ZonedDateTime and Instant

### ISSUE THREAD

**Issue by goforgold** [nodatime/nodatime#1637]
Hi @jskeet 

I like to understand the factors behind design decision so that `Instant` have only one default constructor and plenty of static `From(...)` but `ZonedDateTime` have several constructor overloads but only one static `FromDateTimeOffset(...)`.

What are some general guidelines you have followed to decide between having a constructor or static creator methods?

Thanks!

**Comment by jskeet** [comment]
The general rule is "If there's only one interpretation of what a particular parameter or set of parameters means, it's fine to have a constructor". For `Instant`, there are lots of factory methods that accept a single number - and there, the factory method name really helps to clarify what that means. While we _could_ potentially have `Instant(DateTime)` and `Instance(DateTimeOffset)` constructors, I feel the factory methods are clearer there - particularly as they already exist for the *other* ways of creating an `Instant`. It's worth noting that one of the breaking changes from Noda Time 1.x to 2.x was the removal of an `Instantl(long)` constructor - it was ambiguous, and inflexible in the face of changing the precision of Noda Time as a whole.

For `ZonedDateTime`, the constructors effectively provide the natural constituent parts of a `ZonedDateTime`, or ways that make it clear how to derive them. They feel more "inherent" constructors to me.

Does that make sense?

**Comment by goforgold** [comment]
That makes perfect sense.

`NodaTime` has proven to be a life saviour for me while dealing with the stock market data across the geographies. Especially with historical data.

**Comment by jskeet** [comment]
Excellent - glad to hear it :) Will close this issue now, but do feel free to ask similar questions... aside from anything else, it's healthy for me to have to justify decisions (or admit that they're non-ideal).
