### ISSUE TITLE
Incorrect timezone conversion for 1901-12-31 4:00:00 PM (UTC) when working with "Asia/Singapore" timezone

### ISSUE THREAD

**Issue by dwcai** [nodatime/nodatime#1639]
The following code will return an invalid value when the timezone is "Asia/Singapore", and the input utcTime variable is 1901-12-31 4:00:00 PM. 
`Instant.FromDateTimeUtc(DateTime.SpecifyKind(utcTime, DateTimeKind.Utc)).InZone(timezone).ToDateTimeUnspecified();`

The returned value is 1901-12-31 10:55:25 PM, the correct value should be 1902-01-01 12:00:00 AM.

**Comment by malcolmr** [comment]
(According to TZDB) Asia/Singapore followed Singapore Local Mean time from 1901 (officially) until June 1905, when it switched to UTC+7, so I think the behaviour you're seeing is actually correct.

Local mean time is just based on longitude, and for Singapore that puts it at UTC+06:55:25, with no daylight savings. (This is similar to the way that London ran on London Mean Time, UTC-00:01:15, until 1847.)

TZDB points to https://web.archive.org/web/20190822231045/http://www.math.nus.edu.sg/~mathelmr/teaching/timezone.html as their canonical source for Singapore's time zones.

Please reopen if I've missed something, but I believe what you're seeing is correct, if surprising.
