### ISSUE TITLE
Converting to NodaTime types from ASP NET Core forms

### ISSUE THREAD

**Issue by Evengard** [nodatime/nodatime#1645]
Hello!

I'm having trouble understanding how to support automatic conversion of strings passed in ASP NET Core form models into actual NodaTime type values. For now I'm just getting "nulls".
Eg consider this:
```csharp
public class FormModel
{
public ZonedDateTime? SomeTime {get; set;} 
// Some other fields
}
```
And a controller method:
```csharp
[HttpPost]
[Route("~/someroute")]
public async Task<IActionResult> SomeActionAsync(FormModel model)
{
var date = model.SomeTime; // "date" is always null no matter what I pass as the value
return View();
}
```

**Comment by jskeet** [comment]
Have you configured whatever JSON serializer you're using? Please give more details of how you've configured it. See https://nodatime.org/3.0.x/userguide/serialization for more info.

**Comment by Evengard** [comment]
Yes, I've configured Json serializer like this:
```csharp
services.AddControllersWithViews()
                .AddJsonOptions(options =>
                {
                    options.JsonSerializerOptions.DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull;
                    options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
                    options.JsonSerializerOptions.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);
                });
```
But I'm not actually using JSON, it is not a WebAPI, but a razor view with a form in it, such as:
```csharp
@model FormModel
@using (Html.BeginForm("AddPlan", "ClericalPlanFacts", FormMethod.Post))
{
    @Html.LabelFor(f => f.SomeTime)
    @Html.TextBoxFor(f => f.SomeTime)
    <br />
// Some other fields
    <input type="submit" value="Create" />
}
```

**Comment by Evengard** [comment]
All I could find is that it should be somehow related to https://github.com/nodatime/nodatime/pull/1237, but this seems to be merged and so should work "out of the box" and I am using NodaTime 3.

**Comment by jskeet** [comment]
Okay, so have you debugger what your request looks like, exactly? (It would need to be *exactly* the format that the TypeConverter expects.)

**Comment by Evengard** [comment]
Could you provide a "known working" formatted date for a ZonedDateTime? I'll test it right away.

**Comment by jskeet** [comment]
I don't have much time right now, but the tests in https://github.com/nodatime/nodatime/blob/master/src/NodaTime.Test/Text/TypeConvertersTest.cs should be a good starting point.

**Comment by Evengard** [comment]
Thanks, apparently it was indeed the input format which was invalid. The testcase values worked just fine. Apparently the TypeConverter is really strict about this...

**Comment by jskeet** [comment]
"Apparently the TypeConverter is really strict about this..." - Yes, it's not designed to be for human input, particularly... just a reliable string conversion.
