### ISSUE TITLE
Improved error message when using mismatched pattern strings?

### ISSUE THREAD

**Issue by djeikyb** [nodatime/nodatime#1646]
I'm trying to write a System.Text.Json converter for a custom date time format, and I want the deserialized field to be an Instant. I found this pattern on the page ["Patterns for OffsetDateTime values"](https://nodatime.org/3.0.x/userguide/offsetdatetime-patterns).

> G: General invariant ISO-8601 pattern, down to the second. This corresponds to the custom pattern uuuu'-'MM'-'dd'T'HH':'mm':'sso<G>. This is the default format pattern.

```c#
public class ExampleNullableInstant
{
  [JsonPropertyName("created_time")]
  public Instant? CreatedTime { get; init; }
}
```

I figured this would be a good start. Iterate from here to the custom pattern I need:

```c#
var pattern = InstantPattern.CreateWithInvariantCulture("uuuu'-'MM'-'dd'T'HH':'mm':'sso<G>");
```

And of course, this causes an exception:

```
Unhandled exception. NodaTime.Text.InvalidPatternException: The character o is not a format specifier, and should be quoted to act as a literal.
   at NodaTime.Text.Patterns.SteppedPatternBuilder`2.ParseCustomPattern(String patternText, Dictionary`2 characterHandlers)
   at NodaTime.Text.LocalDateTimePatternParser.<>c__DisplayClass4_0.<ParsePattern>g__ParseNoStandardExpansion|0(String patternTextLocal)
   at NodaTime.Text.LocalDateTimePatternParser.ParsePattern(String patternText, NodaFormatInfo formatInfo)
   at NodaTime.Text.FixedFormatInfoPatternParser`1.<>c__DisplayClass2_0.<.ctor>b__0(String patternText)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at NodaTime.Utility.Cache`2.GetOrAdd(TKey key)
   at NodaTime.Text.FixedFormatInfoPatternParser`1.ParsePattern(String pattern)
   at NodaTime.Text.LocalDateTimePattern.Create(String patternText, NodaFormatInfo formatInfo, LocalDateTime templateValue)
   at NodaTime.Text.InstantPatternParser.ParsePattern(String patternText, NodaFormatInfo formatInfo)
   at NodaTime.Text.InstantPattern.Create(String patternText, NodaFormatInfo formatInfo, Instant templateValue)
   at NodaTime.Text.InstantPattern.CreateWithInvariantCulture(String patternText)
   at tmp.Program.Main(String[] args) in /.../tmp/Program.cs:line 12
```

Some while later, I decided the docs are just wrong and started writing a bug report for the docs. Right before hitting "Submit new issue" I got this idea that maybe because instants are free of the notion of time zones, that maybe you can't parse a string of a date with a time and an offset straight into an Instant. Maybe I'd need to parse into an OffsetDateTime and convert that into an Instant. And then it hit me: the documented patterns are extremely type-specific.

So here I am rewriting my bug report into a feature request! When patterns for one type are misused for another type, could the exception message say so? It'd be useful to get something like:

> Unhandled exception. NodaTime.Text.InvalidPatternException: The character o is not a format specifier for an InstantPattern, and should be quoted to act as a literal. Instants don't have offsets. Did you mean to use OffsetDatePattern or ZonedDateTimePattern?

or

> Unhandled exception. NodaTime.Text.InvalidPatternException: The character o is not a format specifier, and should be quoted to act as a literal. The character o is a format specifier for: OffsetDatePattern, ZonedDateTimePattern

and whatever else it's valid for.

**Comment by jskeet** [comment]
Thanks for the issue report. I suspect that trying to make it that specific would be really brittle - it would be very easy to add a format specifier in one place and forget to specify it in all the relevant exception messages.

If we just added something like "Please check that you're looking at the documentation for the right pattern" - not exactly that, but it's too early in the morning for me to be wordsmithing. Would that still have been enough to have helped you? If not, I can *try* to work out some non-brittle way of getting to the kind of pattern you're considering, but it's not simple.

(It's also tricky because when there are "embedded" patterns, you need to have the right type for that. And sometimes the code doesn't even know properly what the target type is - Instant patterns are actually parsed using LocalDateTime patterns internally, and then treated as UTC. I'm not sure how feasible it is to plumb all the right information through the system.)

**Comment by djeikyb** [comment]
Ah, I figured this might be a tricky request! I agree a broader message would be helpful even without the ability to reference the exact type.

> Unhandled exception. NodaTime.Text.InvalidPatternException: The character o is not a format specifier for this pattern type, and should be quoted to act as a literal. Each pattern class has its own format specifiers.

**Comment by jskeet** [comment]
Great - I'll do something like that, and it'll go out (eventually) in 3.1.0. (I keep meaning to do a 3.1.0 release, but it's always lower priority than some other urgent thing.)

Thanks very much for raising this.
