### ISSUE TITLE
Noda Issue with the 2038 problem in linux containers

### ISSUE THREAD

**Issue by vikramjb** [nodatime/nodatime#1663]
Hi I was running a sample code on a linux container that has dotnet 3.1 and it would seem NodaTime cannot parse any date after 2038 March 3 :16 AM. Online sources say the linux kernel > 5.6 should have the fix for this problem. I am currently using 5.10 so it should work. However NodaTime consistently crashes in this regard. Here's a sample code

`            Duration duration = Duration.FromDays(365*17);
            Instant now = SystemClock.Instance.GetCurrentInstant();
            Console.WriteLine(now);
            Instant future = now + duration; // Or now.Plus(duration)
            Console.WriteLine(future);

            DateTime from = new DateTime(2037, 1, 1, 1, 1, 1, 1, DateTimeKind.Utc);
            DateTime to = new DateTime(2040, 1, 1, 1, 1, 1, 1, DateTimeKind.Utc);
            string timeZoneString ="AUS Eastern Standard Time";
            Console.WriteLine("Original Timezone {0}", timeZoneString);
            var dateTimeZone = NodaTime.DateTimeZoneProviders.Bcl.GetZoneOrNull(timeZoneString);

            if (dateTimeZone == null)
            {
                string result = TZConvert.WindowsToIana(timeZoneString);
                Console.WriteLine("IANA Timezone {0}", result);
                dateTimeZone = NodaTime.DateTimeZoneProviders.Bcl.GetZoneOrNull(result);
            }

            var intervals = dateTimeZone.GetZoneIntervals(NodaTime.Instant.FromDateTimeUtc(from), NodaTime.Instant.FromDateTimeUtc(to)).ToList();

            foreach (ZoneInterval item in intervals.Where(x => x.Savings.Ticks > 0))
            {
                Console.WriteLine("Start -> {0}", item.Start);
                Console.WriteLine("End-> {0}", item.End);
            }

            Console.WriteLine("Done!");
            Console.ReadLine();`

The above code runs fine in windows without any issues and this is what I get when running on windows.

`2021-11-02T22:26:15Z
2038-10-29T22:26:15Z
Original Timezone AUS Eastern Standard Time
Start -> 2036-10-04T16:00:00Z
End-> 2037-04-04T16:00:00Z
Start -> 2037-10-03T16:00:00Z
End-> 2038-04-03T16:00:00Z
Start -> 2038-10-02T16:00:00Z
End-> 2039-04-02T16:00:00Z
Start -> 2039-10-01T16:00:00Z
End-> 2040-03-31T16:00:00Z
Done!`

However when I run it in linux I get the following error

`2021-11-02T22:25:21Z

2038-10-29T22:25:21Z

Original Timezone AUS Eastern Standard Time

IANA Timezone Australia/Sydney

Start -> 2036-10-04T16:00:00Z

End-> 2037-04-04T16:00:00Z

Start -> 2037-10-03T16:00:00Z

Unhandled exception. System.InvalidOperationException: Zone interval extends to the end of time

   at NodaTime.Utility.Preconditions.CheckState(Boolean expression, String message)

   at NodaTime.TimeZones.ZoneInterval.get_End()

   at LinuxConsoleTest.Program.Main(String[] args) in C:\Projects\SourceTrials\LinuxConsoleTest\Program.cs:line 39`

I get an end of time message when running this in a docker container which runs in linux.

**Comment by jskeet** [comment]
I'll have to check tomorrow, but I very strongly suspect that you're basically seeing problems in TimeZoneInfo being faithfully replicated in NodaTime.

Just use `DateTimeZoneProviders.Tzdb` and I'd be very surprised if you see the same problem.

**Comment by vikramjb** [comment]
@jskeet I will test TzDB as well and get back to you.

**Comment by vikramjb** [comment]
@jskeet You are correct. With TzDb that problem does not seem to occur. Is there a helper method in NodaTime which has a windows to Iana ? Currently I am using a different library but would prefer to use NodaTime itself to reduce dependencies.

**Comment by jskeet** [comment]
> With TzDb that problem does not seem to occur

Right. In that case I'm pretty sure it's just TimeZoneInfo reporting the wrong information. I don't know what framework you're using on Linux, but it could be that a newer version fixes it. Here's a short program you can run to check:

```csharp
using System;
using System.Globalization;
using System.Linq;

class Test
{
    static void Main(string[] args)
    {
        if (args.Length != 1)
        {
            Console.WriteLine("Arguments: <time-zone-id>");
            return;
        }
        var zone = TimeZoneInfo.FindSystemTimeZoneById(args[0]);
        var rules = zone.GetAdjustmentRules();
        Console.WriteLine($"{zone.Id}:");
        Console.WriteLine($"{rules.Length} rules");
        Console.WriteLine($"Earliest rule: {rules.First().DateStart} - {rules.First().DateEnd}");
        Console.WriteLine($"Latest rule: {rules.Last().DateStart} - {rules.Last().DateEnd}");
    }
}
```

Please post the output of that (for Australia/Sydney in the specific case you're using) on the machine with the problem.

> Is there a helper method in NodaTime which has a windows to Iana ?

"Has a windows to Iana" is too vague to really answer without more information. Are you talking about converting a Windows time zone ID to an IANA ID? If so, you can use `TzdbDateTimeZoneSource.Default` to get the `TzdbDateTimeZoneSource` used by `DateTimeZoneProviders.Tzdb`, and then use the [`WindowsToTzdbIds` property](https://nodatime.org/3.0.x/api/NodaTime.TimeZones.TzdbDateTimeZoneSource.html#NodaTime_TimeZones_TzdbDateTimeZoneSource_WindowsToTzdbIds) to get a dictionary from Windows time zone ID to IANA canonical ID.


As an aside, I find it hard to see how you get from the problem you've described to "it would seem NodaTime cannot parse any date after 2038 March 3 :16 AM".

**Comment by vikramjb** [comment]
Let me check it out and get back to you. Thanks for the help.

**Comment by jskeet** [comment]
Apologies for not responding before - I didn't see this comment.

I'm not surprised that didn't work, because prior to .NET 6, `TimeZoneInfo.FindSystemTimeZoneById` doesn't automatically convert Windows time zone names to TZDB names.

Fundamentally, I'd advise against using Windows IDs on Linux - certainly prior to .NET 6.
Note that `DateTimeZoneProviders.Bcl` doesn't mean "Windows-ID-based time zones" - it means "TimeZoneInfo-based time zones".

I'm closing this as I don't believe there's any problem with Noda Time here.

**Comment by vikramjb** [comment]
Thank you @jskeet we have worked around for it now. We have identified this as an issue to be dealt with when we migrate to .net 6. Thank you for your support :) Appreciate it.
