### ISSUE TITLE
Can not get zone by "Eastern Standard Time"

### ISSUE THREAD

**Issue by cookie9052** [nodatime/nodatime#1664]
Today I execute the funcation GetZoneOrNull with the timezondId "Eastern Standard Time", but response the Null.
I remember this value was worked before. So is there anything update and make it not foundable?
Thx !

**Comment by jskeet** [comment]
Please provide your code, and tell us which platform you're running on.

**Comment by jskeet** [comment]
Closing due to lack of information.
