### ISSUE TITLE
How to get PST time not PDT in standard way?

### ISSUE THREAD

**Issue by wujun4code** [nodatime/nodatime#1668]
> Pacific Daylight Time (PDT) is a North American time zone in use from the second Sunday in March to the first Sunday in November during Daylight Saving Time (DST). Pacific Standard Time (PST) is used during the remainder of the year.

PDT use winter or summer time but PST always use GMT -8.  

Which timezone should I choose to get PST not PDT from the following TimeZone list : https://nodatime.org/TimeZones?

Thanks.

**Comment by jskeet** [comment]
What you're looking for isn't really a regular time zone as such (neither PST nor PDT are time zones really - they're aspects which are observed *in* certain time zones). There are two options here:

- Create a time zone using `DateTimeZone.ForOffset`
- Use an ID = "UTC-08" with any `IDateTimeZoneProvider`

Sample code:

```csharp
var zone1 = DateTimeZone.ForOffset(Offset.FromHours(-8));
var zone2 = DateTimeZoneProviders.Tzdb["UTC-08"];
```
