### ISSUE TITLE
Add default ToString() or Debugger Display for YearMonth

### ISSUE THREAD

**Issue by mungojam** [nodatime/nodatime#1670]
I've just started using NodaTime (thanks for the great library!).

I had a set of parsed YearMonth values that I was debugging, but I could easily tell what any of them were because there isn't a default `ToString` or a Debugger Display value set.

**Comment by jskeet** [comment]
Thanks - I'll have a look at this when I get a chance. It should be easy to add this, so long as we're okay with just always using the ISO year-month format rather than trying to be culture-sensitive as we are with other types.

**Comment by mungojam** [comment]
> Thanks - I'll have a look at this when I get a chance. It should be easy to add this, so long as we're okay with just always using the ISO year-month format rather than trying to be culture-sensitive as we are with other types.

that would certainly work for me, but that may be because it fits my own culture (British). Or can you use the system culture if one is set?

**Comment by jskeet** [comment]
Gosh, it turns out there *is* a `YearMonthPattern` member for `DateTimeFormatInfo` - so I should be able to use that. I never knew...

**Comment by jskeet** [comment]
We even have support for all of this with an overload of ToString... we just don't override the default one. This should be very straightforward :) (Then there's the matter of getting round to a release, of course...)
