### ISSUE TITLE
What is the equivalent to System.TimeZoneInfo.GetUtcOffset

### ISSUE THREAD

**Issue by faramos** [nodatime/nodatime#1673]
When using the standard .NET TimeZoneInfo, we can get the offset of a specific dateTime considering the daylight saving time.
Are any equivalent to it in nodatime?

```
        /// <summary>
        /// Returns the Universal Coordinated Time (UTC) Offset for the current TimeZoneInfo instance.
        /// </summary>
        public TimeSpan GetUtcOffset(DateTime dateTime) =>
            GetUtcOffset(dateTime, TimeZoneInfoOptions.NoThrowOnInvalidTime, s_cachedData);
```

Thanks in advance.

**Comment by jskeet** [comment]
The equivalent is `DateTimeZone.GetUtcOffset(Instant)`. (If you don't have an `Instant`, please give more details of what you *do* have. If you genuinely only have a `DateTime`, there's `Instant.FromDateTimeUtc` - but if you don't have a `DateTime` with a `Kind` of `Utc`, there's already a problem.)
