### ISSUE TITLE
Implement the appropriate C# 11 generic math interfaces

### ISSUE THREAD

**Issue by roji** [nodatime/nodatime#1693]
C# 11 is introducing [generic math](https://devblogs.microsoft.com/dotnet/preview-features-in-net-6-generic-math/), which allows writing generic code that can apply operators on numbers and number-like types. The NodaTime types can implement the appropriate interfaces, unlocking some interesting possibilities. For example, a generic Sum method could add up Duration instances.

Type(s)               | Possible generic math interfaces
--------------------- | --------------------------------
Duration/Period       | IAdditionOperators, ISubtractionOperators, IUnaryNegationOperators, IUnaryPlusOperators, IComparisonOperators, IEqualityOperators, IMinMaxValue, IAdditiveIdentity, IMultiplicativeIdentity
Others (e.g. Instant) | IComparisonOperators, IEqualityOperators, IMinMaxValue

/cc @tannergooding

**Comment by jskeet** [comment]
Hmm... Maybe. I'll need to look into this more, particularly in terms of what it will mean for dependencies/targeting. Thanks for raising it though.

**Comment by roji** [comment]
Yeah, this means Nodatime would have to multitarget net7.0 (but IIRC you already multitarget).

**Comment by jskeet** [comment]
Yes, we already multitarget - but only LTS versions I believe. I'm nervous about targeting non-LTS versions, because of the awkward decisions it introduces in a couple of years. Not saying no - just saying there's stuff to think about.

**Comment by roji** [comment]
Sure. FWIW you'll have the same awkward decision for 6.0, just a couple years further down the road... Anyway.

**Comment by roji** [comment]
Just noting here that IAdditionOperators and others can be defined over heterogeneous types, so stuff like Instant + Duration can be represented as well.

**Comment by lilinus** [comment]
Do we have any thoughts on getting this implemented?

Generic math is in .NET 8.

I can give a shot at implementing it, if it is something we want for. Just not sure how to conditionalise it for  v8 and above.

**Comment by jskeet** [comment]
@lilinus: Feel free to have a go, yes. Conditionalizing it should be as simple as `#if NET8_0_OR_GREATER`. I haven't had a chance to look at this, and I'm unlikely to any time soon.

**Comment by MineMaarten** [comment]
@lilinus As I saw no progress on your fork, I took the liberty to start work on this, see https://github.com/nodatime/nodatime/pull/1802 . I hope that's ok for you :).
