### ISSUE TITLE
Update System.Runtime.CompilerServices.Unsafe to version 6+

### ISSUE THREAD

**Issue by SonofNun15** [nodatime/nodatime#1697]
Because NuGet only resolves one version of each dependency, NodaTime is making it complicated to update other dependencies that rely on System.Runtime.CompilerServices.Unsafe and want version 6+. Would be useful if NodaTime moved to this version as well. Thanks!

**Comment by jskeet** [comment]
I'll have a look when I get a chance, but I'd expect you to be able to just depend on a later version and nuget will resolve to the most recent. Can you give a sample project file and what errors it's causing?

**Comment by SonofNun15** [comment]
NU1605 errors. We may just need to turn these into warnings...

https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1605?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NU1605)%26rd%3Dtrue

**Comment by SonofNun15** [comment]
We're referencing Microsoft.Extensions.Http version 6.0.0, which needs System.Runtime.CompilerServices.Unsafe >=6.0.0. As you said, I think NuGet should be able to deal with this, but it's just unhappy because of the version discrepancies.

**Comment by jskeet** [comment]
What happens if you just add a dependency to System.Runtime.CompilerServices.Unsafe version 6 on your project?

**Comment by SonofNun15** [comment]
We'll be fine. Had to explicitly add `<WarningsAsErrors />` to our project files to get Visual Studio to stop displaying these warnings as errors. I may look into your suggestion about explicitly adding that reference just to limit the warnings.
