### ISSUE TITLE
Upgraded to VS 2022 - No other changes. Now, Serializer errors out.

### ISSUE THREAD

**Issue by du8die** [nodatime/nodatime#1706]
Hi,

I recently upgraded to Visual Studio 2022. I've made no other changes to the code. Still using 4.6.2 of the framework. Nothing has changed. 

But, when I go to deserialize a JSON string (that is pulled from an API) - I'm getting the following error:

Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'NodaTime.LocalDate' because the type requires a JSON string value to deserialize correctly.
To fix this error either change the JSON to a JSON string value or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path '[0].day_events[0].date.year', line 21, position 17.

Any insight would be helpful.

**Comment by jskeet** [comment]
It's very hard to help without seeing either the JSON or the code you're using. If you could provide a minimal complete example, including the JSON, that would make it much easier to help you. (I would be surprised to see JSON that included the year as a separate value though - the canonical JSON representation of Noda Time values is always a single string, as per https://nodatime.org/3.1.x/userguide/serialization, other than for `Interval`.

**Comment by du8die** [comment]
You know - I should have known better. Sorry!

OK. Here's my scenario.

I'm accessing a NodaTime object through an API. The API is correctly serializing the object before it gets sent over the wire. What is being transmitted over the wire is the serialized version. 

```
{
"checkin_date": {
          "$type": "NodaTime.LocalDate, NodaTime",
          "year": 2021,
          "month": 9,
          "day": 15,
          "calendar": 0
        },
}
```

Prior to my upgrade to VS2022 - I could simply deserialize the string that was pulled back - and it would be correct. Now, in 2022 - it gives me the refereneced error. I'm not aware that I've made any framework or other version changes to anything that would create this issuue. 

Is that helpful?

**Comment by jskeet** [comment]
What JSON library are you using to serialize and deserialize? It looks like it's basically accessing the type's *private* members via reflection - never, ever a good idea. If I'd felt like changing the names of the private fields between minor versions of Noda Time, that should be absolutely fine - but would break serialized data like this.

Basically, I would very strongly advise you to use the NodaTime.Serialization.JsonNet or NodaTime.Serialization.SystemTextJson libraries instead.

**Comment by du8die** [comment]
It looks like I'm using https://github.com/AndyBeverlySchool/MongoDb.Bson.NodaTime

I'll try moving to the NodaTime.Serialization.JsonNet package and see what happens. 

Thanks!

**Comment by jskeet** [comment]
It really doesn't look like you're serializing with that - otherwise I believe you'd still end up with a value of something like "2022-08-26" instead of the object representation you've got there... I haven't used that package myself, but [LocalDateSerializer](https://github.com/AndyBeverlySchool/MongoDb.Bson.NodaTime/blob/master/src/MongoDb.Bson.NodaTime/LocalDateSerializer.cs) and [PatternSerializer](https://github.com/AndyBeverlySchool/MongoDb.Bson.NodaTime/blob/master/src/MongoDb.Bson.NodaTime/PatternSerializer.cs) really look like they should be generating single string representations.

**Comment by du8die** [comment]
OK. Then I'm not sure what's going on. I'll start digging deeper..

Thanks!

**Comment by jskeet** [comment]
Any updates on this?

**Comment by jskeet** [comment]
Closing due to lack of information.
