### ISSUE TITLE
Update two timezones

### ISSUE THREAD

**Issue by 0xLaileb** [nodatime/nodatime#1707]
UTC:
America/St_Johns -> actual: `-02:30`, but lib gives me `-01:30`
Antarctica/Macquarie -> actual: `+11:00`, but lib gives me `+10:00`

Actual information: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones and other services

Last info with v3.1.2.

**Comment by jskeet** [comment]
Please specify which instant in time you're talking about - both of these are time zones with DST... and I can't reproduce America/St_Johns returning -01:30 at all, except in 1988, which is correct for a [period of double-daylight-saving](https://github.com/eggert/tz/blob/a339d366d3b9de1ae0b50bafba65b5a7b2078862/northamerica#L1447):

```csharp
using NodaTime;

var zone = DateTimeZoneProviders.Tzdb["America/St_Johns"];
// Take two instants (start of January and start of July, UTC)
// in each year between 1900 and 2025 inclusive.
for (int year = 1900; year <= 2025; year++)
{
    for (int month = 1; month <= 12; month += 6)
    {
        var instant = Instant.FromUtc(year, month, 1, 0, 0);
        Console.WriteLine($"{instant:yyyy-MM-dd}: {zone.GetUtcOffset(instant)}");
    }
}
```

The data in 3.1.2 is 2022c, which is the most recent IANA release, so I'd be very surprised to actually see any problems there.

**Comment by 0xLaileb** [comment]
Oh, sorry, `America/St_Johns` is valid, but i get `-01:30` from `Offset.FromHoursAndMinutes(-2, 30)` 🤔

**Comment by jskeet** [comment]
> Oh, sorry, America/St_Johns is valid, but i get -01:30 from Offset.FromHoursAndMinutes(-2, 30)

Yes, because that's -2 hours, +30 minutes. If you want -2:30, you need `Offset.FromHoursAndMinutes(-2, -30)`.

From the [documentation](https://nodatime.org/3.1.x/api/NodaTime.Offset.html#NodaTime_Offset_FromHoursAndMinutes_System_Int32_System_Int32_):

> The result simply takes the hours and minutes and converts each component into milliseconds separately. As a result, a negative offset should usually be obtained by making both arguments negative.

Next:

> And Antarctica/Macquarie is invalid 😢, i convert local time to this zone and get +10:
> 2022-07-01: +10

That's the correct offset. See https://www.timeanddate.com/time/zone/australia/macquarie-island - between 2022-04-10 and 2022-10-02, the UTC offset is +10.

**Comment by 0xLaileb** [comment]
Oh, thanks, you're right! 😘
