### ISSUE TITLE
Europe/Kiyv throws exception at the same time as Europe/Kiev retrieves fine.

### ISSUE THREAD

**Issue by MaksimShuldiner** [nodatime/nodatime#1710]
IANA released rename of the `Europe/Kiev` to `Europe/Kiyv` timezone in the 2022b release. 

https://mm.icann.org/pipermail/tz/2022-April/031376.html
https://stackoverflow.com/questions/71829570/how-and-where-should-i-suggest-a-rename-of-an-existing-timezone-name

However, when trying to retrieve `Europe/Kiyv`, **NodaTime** throws the exception saying that this timezone does not exist. `Europe/Kiev `works fine. 

Can anyone please double-check?

![image](https://user-images.githubusercontent.com/67012537/190998564-40823313-1d5f-483c-99ed-b4b185e824d8.png)

**Comment by jskeet** [comment]
The correct ID is Europe/Kyiv, not Europe/Kiyv.
