### ISSUE TITLE
Extend ISO 8601 to Support for 2 A and 2 B hours for LocalDateTime to solve ambiguity

### ISSUE THREAD

**Issue by KillerBoogie** [nodatime/nodatime#1714]
I'm aware that the ISO 8601 does not support this notion, but in Germany the daylight saving act from July 12, 2001 states that at the end of daylight saving time the first occurence of the hour 2 is called 2 A and the second 2 B. This solves easily the ambiguity. E.g. a client can let the user choose 2A:30 (or 02:30A) or 2B:30 (or 02:30B). 

A mapping from UTC to local time would correctly output 2 A or 2 B for the first or second occurence of the hour.

**Comment by KillerBoogie** [comment]
Thanks, for the quick answer. I was going to implement my own pattern, but thought that it might be a great solution to the ambiguity problem for everyone. I don't understand why ISO does not use the A and B approach that is common in Germany.

**Comment by KillerBoogie** [comment]
I tried to create two extension mehods that can handle the A and B to mark hours in overlapping `ZoneIntervals` and are based on the `MapZone() `method. I don't want to use a arbitrary algorithm that takes the first occurence, but have the user specify the correct time.

All of my tests are working, but I don't know if I overlooked some strange TimeZone bahaviour. If someone with more experience can let me know if the algorithm idea is sound I would appreciate it a lot. 

(The TimeDescriptor is ignored right now if it is not required, but entered. I also just return a tuple so I was able to test the idea easily. In my code I don't use exceptions, but a `result` object.  ) 

```
public enum TimeDiscriminator
{
    A,
    B
}

public static class NodaTimeExtensions
{
  public static ZonedDateTime ConvertToGlobal(this LocalDateTime localDateTime, DateTimeZone dateTimeZone, TimeDiscriminator? timeDiscriminator = null)
  {
      ZoneLocalMapping localZones = dateTimeZone.MapLocal(localDateTime);

      if (localZones.Count == 0)
      {
          throw new ArgumentException("The hour does not exists, because the clock was turned forward, e.g. by a change to daylight savings time or a general time change for that zone.");
      }
      else if (localZones.Count == 1)
      {
          return new ZonedDateTime(localDateTime, dateTimeZone, localZones.EarlyInterval.WallOffset);
      }
      else if (localZones.Count == 2)
      {
          ZoneInterval early = localZones.EarlyInterval;
          ZoneInterval late = localZones.LateInterval;

          if (timeDiscriminator is null)
          {
              throw new ArgumentException("The hour exists twice, because the clock was turned back. You need to specifiy if the hour belongs to the first (A) or the second (B) period.");
          }
          if (timeDiscriminator == TimeDiscriminator.A)
          {
              return new ZonedDateTime(localDateTime, dateTimeZone, early.WallOffset);
          }
          else
          {
              return new ZonedDateTime(localDateTime, dateTimeZone, late.WallOffset);
          }
      }
  }

public static (LocalDateTime, TimeDiscriminator?) ConvertToLocal(this Instant instant, DateTimeZone dateTimeZone)
{
    ZonedDateTime zonedDateTime = new ZonedDateTime(instant, dateTimeZone);

    LocalDateTime localDateTime = zonedDateTime.LocalDateTime;

    ZoneLocalMapping localZones = dateTimeZone.MapLocal(localDateTime);

    TimeDiscriminator? timeDiscriminator = null;

    if (localZones.Count == 2)
    {
        ZoneInterval early = localZones.EarlyInterval;

        if (early.WallOffset == zonedDateTime.Offset)
        {
            timeDiscriminator = TimeDiscriminator.A;
        }
        else
        {
            timeDiscriminator = TimeDiscriminator.B;
        }
    }
    return (localDateTime, timeDiscriminator);
}

```

**Comment by jskeet** [comment]
Those look reasonable to me.

**Comment by jskeet** [comment]
Closing as I think it's highly unlikely we'll ever implement this. I hope your own implementation is still working for you.
