### ISSUE TITLE
| should be replaced by ||

### ISSUE THREAD

**Issue by viveknuna** [nodatime/nodatime#1716]
the below code DateTimeOffsetBenchmarks.cs files should be fixed, Please correct me If I am wrong.

        [Benchmark]
        public bool Comparison_Operators() => (sample < earlier) | (sample < sample) | (sample < later);
It should be changed to

        [Benchmark]
        public bool Comparison_Operators() => (sample < earlier) || (sample < later);

**Comment by jskeet** [comment]
No, it shouldn't. The point is to benchmark how long it takes to perform all three comparison situations - equality, left side greater, right side greater.

**Comment by viveknuna** [comment]
@jskeet thank you for the clarification
