### ISSUE TITLE
2 digit year parsing as we approach 2031

### ISSUE THREAD

**Issue by scottstephens** [nodatime/nodatime#1720]
Migrated from mailing list:

I dug into the template argument of `LocalDatePattern.Create` for the first time today and stumbled across two behaviors I found fairly surprising: 
* The default template is fixed at 1 Jan 2000, regardless of the current date.
* Century rollover happens at year of century 31.

The consequence of this is that if, on 1 Jan 2031, we run 
`    LocalDatePattern.CreateWithInvariantCulture("MM/dd/yy").Parse("01/01/31").Value`
we will get 
`    Thursday, January 1, 1931`
which is fairly unintuitive to me.

I'm wondering if anyone else finds this surprising, and if so, if there's something we can do, either code or documentation, to nudge users into not firing this footgun.

When I'm writing APIs dealing with two digit years I usually require the user to pass in a "reference year", and then I choose the century to be that which when combined with the year of century is as close as possible to the reference year. That forces the user to explicitly think about how to determine the appropriate century, and is easy to implement in the two most common cases I see, where a two digit year is assumed to be close to the current time, or close to the time at which the data with the two digit year in it was created.

It's not a great fit with the existing parsing methods though, since the same methods are used whether you're dealing with 2 digit or 4 digit years.

**Comment by scottstephens** [comment]
@jskeet 's response on the mailing list:

I will say that I want to stick to "the current date doesn't change things" - I really hate the idea of code changing its behavior based on the current date. (We do that in one place at the moment - only if we don't have a system time zone ID.)

**Comment by jskeet** [comment]
While I happen to have it handy, this is basically the thing we'd make configurable:

https://github.com/nodatime/nodatime/blob/main/src/NodaTime/Text/LocalDatePatternParser.cs#L25

(The century is already configurable via the template.)

So basically we could have something like `LocalDatePattern.WithTwoDigitYearMax(int)` (returning another `LocalDatePattern`) - and the same for all the various other patterns.

As @scottstephens pointed out, the general pattern API makes it hard to *require* that anyone calls the method though.

We should also consider integrating with [`Calendar.TwoDigitYearMax`](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.calendar.twodigityearmax?view=net-6.0) somehow...

**Comment by scottstephens** [comment]
> we could have something like `LocalDatePattern.WithTwoDigitYearMax(int)`

Yeah, that would work. Some other suggestions:

```
// year in [refYear -49, refYear+50]
LocalDatePattern.WithTwoDigitYear(int refYear)

// year in [refYear - (100-futureYears-1), refYear + futureYears]
LocalDatePattern.WithTwoDigitYear(int refYear, int futureYears)

// year in [maxYear-99, maxYear]
LocalDatePattern.WithTwoDigitYear(int maxYear)
```

**Comment by jskeet** [comment]
Definitely happy to talk precise API options when we've nailed down the general approach. If you have any suggestions for alternatives to our normal "call a method on an existing pattern to create a new one", that would be fine too.

(How would you feel about having `AppContext.SetSwitch("NodaTime.Text.FailForImplicitTwoDigitYears", true)` or something similar? I'm generally not happy about global state, but something like that which could be opted into in a single place to set the safety on the footgun seems fairly reasonable...)

**Comment by jskeet** [comment]
@scottstephens: Please could you have a look at https://github.com/nodatime/nodatime/pull/1721 and see whether you think it's going in the right direction?

**Comment by scottstephens** [comment]
> How would you feel about having `AppContext.SetSwitch("NodaTime.Text.FailForImplicitTwoDigitYears", true)` or something similar?

I think I like it. The main downside I see is that if you're consuming a third-party library that does it correctly while using an implicit century you could get some false positives that you can't directly fix. But you can always turn it off if that's a problem

> have a look at https://github.com/nodatime/nodatime/pull/1721

I think you're on the right track. Here's the difference between what I do under the current API vs the new:

Current
```
var culture = CultureInfo.GetCultureInfo("en_us");
var pattern = LocalDatePattern.Create("MM/dd/yy", culture);
var result0 = pattern.Parse("01/01/31").Value;

var refYear = SystemClock.Instance.GetCurrentInstant().InUtc().Year;
var maxYear = refYear + 50;
var resolvedYear = (maxYear / 100)*100 + (result0.Year % 100) ;
if (resolvedYear > maxYear)
    resolvedYear -= 100;
var result = new LocalDate(resolvedYear, result0.Month, result0.Day);
```

New
```csharp
var culture = CultureInfo.GetCultureInfo("en_us");
var refYear = SystemClock.Instance.GetCurrentInstant().InUtc().Year;
var template = new LocalDate(refYear + 50, 1,1);
var pattern = LocalDatePattern.Create("MM/dd/yy", culture, template)
    .WithTwoDigitYearMax((refYear + 50) % 100);

var result = pattern.Parse("01/01/31").Value;

```

Could maybe use some syntactic sugar, but it avoids the necessity to post-process the parse output.

**Comment by malcolmr** [comment]
We could perhaps also add `WithTwoDigitYearMaxFromCalendar()` if we wanted to opt in to using the value from the pattern's `Calendar.TwoDigitYearMax`.

Alternatively, doing that by default might be a reasonable replacement for our hardcoded `30` anyway (unless there's some reason that would be a bad idea?), but obviously we can't make that change in 3.x.

**Comment by lassevk** [comment]
To be honest, if in 9 years time, in 2031, we're still trying to try to "figure out" what people meant when they were giving us incomplete data, I feel like we've failed on a completely different level.

Why, in 2031, are we still allowing people to input years as two digits?

And yes, I fully understand the problem will appear much sooner than in 9 years, because people want to input dates into the future, but why oh why don't we just *require* them to be specific? All systems that try to figure out what people actually meant are invariably going to get it wrong. That's why we make systems ask more specific questions.

I hope that before 9 years have passed, we've made 2-digit years obsolete. 

And yes, this is a rant. Please ignore it completely, or take it to heart. Your choice. I will just sulk in a corner in the meantime.
