### ISSUE TITLE
Persian calendars are confused with each other in the documentation

### ISSUE THREAD

**Issue by Anonymous87549236** [nodatime/nodatime#1733]
Except for a simple calendar.
https://nodatime.org/unstable/userguide/calendars

> The "astronomical" calendar ... matches the behaviour of the BCL PersianCalendar from .NET 4.6 onwards
> The "arithmetic" (or algorithmic) calendar proposed by Ahmad Birashk

https://nodatime.org/unstable/api/NodaTime.CalendarSystem.html

<html>
<body>

Persian Arithmetic | PersianArithmetic
-- | --
Persian Algorithmic | PersianAstronomical (see note)

</body>
</html>

> PersianArithmetic
> ...implementing the behaviour of the BCL PersianCalendar from .NET 4.6 onwards

> PersianAstronomical
> ...implementing the behaviour proposed by Ahmad Birashk

**Comment by jskeet** [comment]
I don't follow what you're proposing here - please could you edit your comment to clarify it?

I agree there's confusion here, but a concrete proposal would be helpful. I also need to check whether the actual implementations are the wrong way round, too. The ID of "Persian Algorithmic" for the property PersianAstronomical is already explained in a note though.

**Comment by Anonymous87549236** [comment]
Corect information.
According to the source code, I can build the following mental associations:
1. Astronomical == Algorithmic == BCL 4.6 == avoids complex arithmetic for midday in Tehran.
2. Arithmetic == Birashk's == organizes leap years in cycles of 2820 years.
So, the information in the https://nodatime.org/unstable/api/NodaTime.CalendarSystem.html#NodaTime_CalendarSystem_Id table is correct.

Wrong information:
1. https://nodatime.org/unstable/userguide/calendars web page says that Astronomical != Algorithmic, instead Arithmetic == Algorithmic. To make the information correct, you should move "(or algorithmic)" from "The "arithmetic" (or algorithmic) calendar" to "The "astronomical" calendar". Then they become "The "astronomical" (or algorithmic) calendar" & "The "arithmetic" calendar".
I propose to add the following to the end of the paragraph about "The "arithmetic" calendar" to keep consistency: "This calendar starts on March 19th 622 CE (Julian)."
I couldn't check if this sentence is in the right place: "where each new year begins on the midnight between the two consecutive solar noons which include the instant of the Northern spring equinox, when the sun enters the northern hemisphere."

2. https://nodatime.org/unstable/api/NodaTime.CalendarSystem.html web page says the following:
2.1. Arithmetic == BCL 4.6, Arithmetic == Astronomical, Arithmetic == avoids complex arithmetic for midday in Tehran.
2.2. Astronomical == Birashk's, Astronomical == organizes leap years in cycles of 2820 years.
To make the information correct, you should write the following:

PersianArithmetic
Returns a Persian (also known as Solar Hijri) calendar system implementing the behaviour proposed by Ahmad Birashk with nested cycles of years determining which years are leap years.
Since 2.0.x
Availability net6.0, netstandard2.0
Declaration
public static CalendarSystem PersianArithmetic { get; }
Property Value
Type	Description
CalendarSystem	A Persian calendar system using cycles-within-cycles of years to determine leap years.

PersianAstronomical
Returns a Persian (also known as Solar Hijri) calendar system implementing the behaviour of the BCL PersianCalendar from .NET 4.6 onwards (and Windows 10), and the astronomical system described in Wikipedia and Calendrical Calculations.
Since 2.0.x
Availability net6.0, netstandard2.0
Declaration
public static CalendarSystem PersianAstronomical { get; }
Property Value
Type	Description
CalendarSystem	A Persian calendar system using astronomical calculations to determine leap years.
Remarks
This implementation uses data derived from the .NET 4.6 implementation (with the data built into Noda Time, so there's no BCL dependency) for simplicity; the actual implementation involves computing the time of noon in Iran, and is complex.
This calendar is also known as the algorithmic Solar Hijri calendar.

**Comment by jskeet** [comment]
Okay, thanks - I'll see what I can do later this week.

**Comment by jskeet** [comment]
Okay, so it looks like in the nodatime repo really this is *just* swapping the documentation for `PersianArithmetic` and `PersianAstronomical` - nothing more than that.

I'll then make a separate change in the nodatime.org repo.

**Comment by jskeet** [comment]
Please review #1735; I'll merge if I haven't seen any feedback in the next few days.

**Comment by jskeet** [comment]
> https://nodatime.org/unstable/userguide/calendars web page says that Astronomical != Algorithmic, instead Arithmetic == Algorithmic. To make the information correct, you should move "(or algorithmic)" from "The "arithmetic" (or algorithmic) calendar" to "The "astronomical" calendar". Then they become "The "astronomical" (or algorithmic) calendar" & "The "arithmetic" calendar".

No, the information is correct. Algorithmic and arithmetic are effectively synonyms here. The only way in which the astronomical calendar is the algorithmic calendar is in terms of the mistake with the calendar ID property. I'll note that separately.

**Comment by jskeet** [comment]
The documentation fixes are in https://github.com/nodatime/nodatime.org/pull/144

**Comment by Anonymous87549236** [comment]
> the information is correct
Then the new associations look like this:
Astronomical == BCL 4.6 == avoids complex arithmetic for midday in Tehran.
Arithmetic == Algorithmic == Birashk's == organizes leap years in cycles of 2820 years.

**Comment by jskeet** [comment]
Yes, that's basically it.

**Comment by Anonymous87549236** [comment]
> Please review https://github.com/nodatime/nodatime/pull/1735

I reviewed and I think that everything is correct there.

**Comment by Anonymous87549236** [comment]
> The documentation fixes are in [nodatime/nodatime.org#144](https://github.com/nodatime/nodatime.org/pull/144)

Don't forget to update https://nodatime.org/unstable/api/NodaTime.CalendarSystem.html as follows:

PersianArithmetic
Returns a Persian (also known as Solar Hijri) calendar system implementing the behaviour proposed by Ahmad Birashk with nested cycles of years determining which years are leap years.
Since 2.0.x
Availability net6.0, netstandard2.0
Declaration
public static CalendarSystem PersianArithmetic { get; }
Property Value
Type Description
CalendarSystem A Persian calendar system using cycles-within-cycles of years to determine leap years.
Remarks
This calendar is also known as the algorithmic Solar Hijri calendar.

PersianAstronomical
Returns a Persian (also known as Solar Hijri) calendar system implementing the behaviour of the BCL PersianCalendar from .NET 4.6 onwards (and Windows 10), and the astronomical system described in Wikipedia and Calendrical Calculations.
Since 2.0.x
Availability net6.0, netstandard2.0
Declaration
public static CalendarSystem PersianAstronomical { get; }
Property Value
Type Description
CalendarSystem A Persian calendar system using astronomical calculations to determine leap years.
Remarks
This implementation uses data derived from the .NET 4.6 implementation (with the data built into Noda Time, so there's no BCL dependency) for simplicity; the actual implementation involves computing the time of noon in Iran, and is complex.

**Comment by jskeet** [comment]
That's all documentation which is generated from this code.
