### ISSUE TITLE
Add a format for Duration

### ISSUE THREAD

**Issue by vbjay** [nodatime/nodatime#1743]
Add a shortened format that results in a format of non 0 values only.

```c#
public void Main()
    {
        // Create a Duration objects representing different durations
        var durations =new Duration[]
        {
            Duration.FromHours(0),
            Duration.FromDays(3) + Duration.FromHours(2) + Duration.FromMinutes(30) + Duration.FromSeconds(15),
            Duration.FromDays(-1) + Duration.FromHours(3)
        };

        durations.Select(d => new { Duration = d, Formatted = GetFormatted(d) }).Dump();
    }

    // Define other methods and classes here
    public string GetFormatted(Duration HowLong)
    {
        // Format the duration in the Jira duration syntax
        string formattedDuration = (HowLong < Duration.Zero ? "-" : null) +
		(HowLong.Days != 0 ? HowLong.ToString("D'd '", CultureInfo.CurrentCulture) : null) +
		(HowLong.Hours != 0 ? HowLong.ToString("h'h '", CultureInfo.CurrentCulture) : null) +
		(HowLong.Minutes != 0 ? HowLong.ToString("m'm '", CultureInfo.CurrentCulture) : null) +
		(HowLong.Seconds != 0 ? HowLong.ToString("s's'", CultureInfo.CurrentCulture) : null);


	return string.IsNullOrEmpty(formattedDuration) ? "0s" : formattedDuration;
}
```
As shown in linqpad run
![image](https://user-images.githubusercontent.com/3629489/229363135-c2e9cc94-81fd-413b-bc02-474b2108e554.png)

Do the same for interval too.

**Comment by jskeet** [comment]
This would make little sense for `Interval`, which is a start/end pair of instants, and *shouldn't* be formatted as a `Duration`.

You could implement this as an `IPattern<Duration>` yourself, I suspect... if you want it to be in the NodaTime package itself, I doubt that I'm going to have the time to do this myself, but would welcome a PR - complete with parsing and tests, of course.

**Comment by vbjay** [comment]
Right. I think I was confusing another type than interval.  Thanks for the suggestion on where to go though.

**Comment by jskeet** [comment]
Closing as it sounds like we don't need to put this into NodaTime.
