### ISSUE TITLE
Unrecognized time zone

### ISSUE THREAD

**Issue by DanPatten** [nodatime/nodatime#1744]
I am currently on NodaTime 3.1.9 and the following time zones are not working.

`System.ArgumentException: 'Unrecognized time zone id Norway Standard Time`

(I just upgraded from 3.0.0 because had this same issue with some of these other time zones, upgrading added more support)

Are the following time zones supported?
- Maldives Standard Time
- Eastern Caribbean Standard Time
- Hong Kong Time
- Maldives Standard Time
- Indonesia Standard Time
- Norway Standard Time

**Comment by jskeet** [comment]
Please provide the code you're using. It's not clear which time zone provider you're using, to start with.

**Comment by DanPatten** [comment]
I figured out the issue, I was using incorrect time zones.
