### ISSUE TITLE
Need for latest version of IANA zones DB

### ISSUE THREAD

**Issue by nypen** [nodatime/nodatime#1745]
Using the latest version of NodaTime: `3.1.9` and `DateTimeZoneProviders.Tzdb` the version of the db retrieved is `"TZDB: 2020a (mapping: $Revision$)"`
```
            var tz = DateTimeZoneProviders.Tzdb.VersionId;
```
This year DST changes were applied for the timezone `Africa/Cairo` and we can't get the updated info for this tz via `NodaTime`.

- Are there any plans to support the latest DB version [2023c](https://www.iana.org/time-zones) ?
- Is there any way to externally define the version of IANA needed?

Thanks!

**Comment by jskeet** [comment]
I can't reproduce this. I suspect you're using 3.1.7

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NodaTime" Version="3.1.9" />
  </ItemGroup>

</Project>
```

Program.cs:

```csharp
using NodaTime;

Console.WriteLine(DateTimeZoneProviders.Tzdb.VersionId);
```

Output:

TZDB: 2023c (mapping: $Revision$)

**Comment by nypen** [comment]
@jskeet Thanks for your reply! I was indeed using a prior version.
