### ISSUE TITLE
ZonedDateTime can also have []

### ISSUE THREAD

**Issue by rsr-maersk** [nodatime/nodatime#1749]
Hi, Awesome package, thankyou!

For ZonedDateTime there is this
![image](https://github.com/nodatime/nodatime/assets/76153851/717c1f18-659b-4ba1-953f-c56dee140f8f)

but e.g. on this and many other polaces i see:
https://docs.oracle.com/javase/8/docs/api/java/time/ZonedDateTime.html

![image](https://github.com/nodatime/nodatime/assets/76153851/9744f925-6925-453f-b6da-fe67638849a6)

the test / converter only shows without [] and the [] does not appear to work.
https://github.com/oferns/System.Text.Json.NodaTime/blob/08f56ee8f8b37e8ebf50de19ae9c107a41f4d8ea/src/System.Text.Json.NodaTime.Tests/NodaConvertersTests.cs#L203

Should the converters accept [] around the zone?

**Comment by jskeet** [comment]
> Should the converters accept [] around the zone?

No, the standard patterns don't support this as far as I remember, and I'm not going to change the standard patterns to comply with other arbitrary standards.

However, it's easy for you to specify your own ZonedDateTimePattern that uses square brackets.

**Comment by jskeet** [comment]
Now I'm back on a laptop, here's a quick sample:

```csharp
using NodaTime;
using NodaTime.Text;

var instant = Instant.FromUtc(2007, 12, 3, 9, 15, 30);
var zoned = instant.InZone(DateTimeZoneProviders.Tzdb["Europe/Paris"]);
var pattern = ZonedDateTimePattern.CreateWithInvariantCulture(
    "uuuu'-'MM'-'dd'T'HH':'mm':'ss;FFFFFFFFFo<m>'['z']'",
    DateTimeZoneProviders.Tzdb);
Console.WriteLine(pattern.Format(zoned));
```

Output: 2007-12-03T10:15:30+01:00[Europe/Paris]

(Note that this will always use HH:mm in the offset.)

**Comment by jskeet** [comment]
(Closing as I don't expect to make any further changes in the repo. Feel free to comment further though.)
