### ISSUE TITLE
ZonedDateTime.IsDaylightSavingTime is broken since .NET 6

### ISSUE THREAD

**Issue by Kermel** [nodatime/nodatime#1750]
I'm upgrading an old system from .NET 4.7.x to .NET 7 and one of the updated libraries is NodaTime (from version 2.0.0 to the lastest version 3.1.9). One of the unit tests started to fail and the reason seem to be inside this library:

We have the following setup:
`DateTime bstDateUtc = DateTime.SpecifyKind(new DateTime(2017, 10,1), DateTimeKind.Utc);
var instant = bstDateUtc .ToInstant();
var zone = DateTimeZoneProviders.Tzdb["Europe/Dublin"];
var zonedDateTime = new ZonedDateTime(instant , zone);
`

1.10.2017 is in the DST interval (this interval starts from last sunday in March and lasts till the last sunday of October). Despite this, the following assertion fails:
`Assert.That(zonedDateTime .IsDaylightSavingTime());`
![assertion_failure](https://github.com/nodatime/nodatime/assets/17484152/3eb4f8d8-c51b-4697-8e6d-a4ba90000f61)

I have checked what happens inside and the IsDaylightSavingTime() method only checks the following:
`public bool IsDaylightSavingTime() => GetZoneInterval().Savings != Offset.Zero;`

The GetZoneInterval() method leads all the way to the CachingZoneIntervalMap class where there is a difference between behavior of the library v 2.0.0 and the newest one (please see screenshots).

GetZoneInterval in 2.0.0:
![GetZoneInterval_2 0 0](https://github.com/nodatime/nodatime/assets/17484152/5432b44a-c0f2-41d7-a8f7-938145f047ce)

GetZoneInterval in 3.1.9:
![GetZoneInterval_3 1 9](https://github.com/nodatime/nodatime/assets/17484152/8386037d-93cc-4ea8-b8e6-73077da39c01)

As can be seen from the screenshots, the value of the properties "Savings" is +00 in library 3.1.9 which casues that the interval is not resolved as being the DST but it is +01 in library 2.0.0 which then correctly recognizes as the DST interval

**Comment by jskeet** [comment]
The code is working fine - but the time zone database was updated some time between 2017 and 2023 (I can't find out when just now as I'm on holiday) to use negative DST - the winter uses DST, and summer is the standard time. That may defy your expectations, but that's how the Irish government has defined it.

**Comment by jskeet** [comment]
Here's the commit to TZDB that changed it: https://github.com/eggert/tz/commit/127b4af7219e6df9253b34e390797c5527b8cc66

I'll close this issue now as this isn't a problem with Noda Time.

**Comment by Kermel** [comment]
Ah, OK.
Thank you for the explanation, I will update the tests then :)
