### ISSUE TITLE
Plans for TimeProvider in .NET 8

### ISSUE THREAD

**Issue by jennings** [nodatime/nodatime#1751]
[.NET 8 introduces a new abstraction of time called TimeProvider](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#time-abstraction), and I'm wondering if NodaTime already has plans to integrate with it.

# What is TimeProvider?

TimeProvider has the following API:

```csharp
public abstract class TimeProvider
{
    // Clock methods
    public virtual DateTimeOffset GetUtcNow();
    public virtual TimeZoneInfo LocalTimeZone { get; }

    // Stopwatch methods
    public virtual long TimestampFrequency { get; }
    public virtual long GetTimestamp();

    // Timers
    public virtual ITimer CreateTimer(TimerCallback callback, object? state, TimeSpan dueTime, TimeSpan period);

    // Other non-virtual methods (implemented via the virtual methods)
    public DateTimeOffset GetLocalNow();
    public TimeSpan GetElapsedTime();
    public TimeSpan GetElapsedTime(long startingTimestamp);
}
```

This abstraction seems to combine the following functionality:

- Get the current time, optionally in a preconfigured time zone (similar to `ZonedClock`)
- Get a timestamp suitable for measurement (similar to `Stopwatch`)
- Create timers

Since this has clock-y behavior, it seems like NodaTime should probably do _something_ about this type.

# What to do about it

n.b.: I only learned of `TimeProvider` the other day, so this suggestion isn't fully thought through.

NodaTime _could_ write an implementation of `TimeProvider` backed by an `IClock`, but:

- NodaTime doesn't have anything to say about the timestamp methods
- The `LocalTimeZone` property is required but I don't think NodaTime can convert between `DateTimeZone` and `TimeZoneInfo` (right?)
- `IClock` doesn't have an API to power `CreateTimer`, so either `IClock` would need to be expanded or NodaTime would need separate implementations backed by a SystemClock and a FakeClock.

As I write this issue, I'm convincing myself that NodaTime should instead make it convenient to use a `TimeProvider` _in place_ of an `IClock` since `TimeProvider` _is_ a clock. It would be nice if NodaTime provided am extension method to use a `TimeProvider` in place of an `IClock`:

```csharp
public static class NodaTimeProviderExtensions
{
    public static Instant GetCurrentInstant(this TimeProvider timeProvider)
        => Instant.FromDateTimeOffset(timeProvider.GetUtcNow());
}
```

This alone lets an application completely replace `IClock` with `TimeProvider`.

It would also be nice to allow creating a timer from NodaTime types rather than TimeSpans:

```csharp
public static ITimer CreateTimer(this TimeProvider timeProvider, TimerCallback callback, object? state, Duration dueTime, Duration period)
    => timeProvider.CreateTimer(callback, state, dueTime.ToTimeSpan(), period.ToTimeSpan());
```

Finally, I don't see a `FakeTimeProvider` or similar for testing, so maybe NodaTime.Testing could implement one? I doesn't seem like NodaTime's "job" to do so, but if the BCL doesn't provide it, someone has to.

**Comment by jskeet** [comment]
I definitely want to do something here, but it's not clear to me what yet.

I expect we may well want to create a TimeProviderClock to *wrap* a TimeProvider and implement IClock, potentially forwarding CreateTimer methods as well. But we'll see closer to the release time.

**Comment by Saancreed** [comment]
> Finally, I don't see a `FakeTimeProvider` or similar for testing, so maybe NodaTime.Testing could implement one? I doesn't seem like NodaTime's "job" to do so, but if the BCL doesn't provide it, someone has to.

@jennings Fyi [there is one](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.time.testing.faketimeprovider?view=dotnet-plat-ext-8.0) in a separate package, [`Microsoft.Extensions.TimeProvider.Testing`](https://www.nuget.org/packages/Microsoft.Extensions.TimeProvider.Testing).

**Comment by x-cubed** [comment]
Now that .Net 8 has been [released](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8), is there more of plan for how NodaTime could work with `TimeProvider`?

**Comment by jskeet** [comment]
It's definitely something I want to get to, but a mixture of work and personal time squeezes means that I desperately need to actually relax a bit over this holiday period. It's possible that I'll get to it - and I'd welcome ideas anyway - but it's unlikely to be very soon.

**Comment by jskeet** [comment]
There's now a draft PR at https://github.com/nodatime/nodatime/pull/1816 - I want to have discussions about the shape of the API before going too much further.

@jennings Thoughts welcome!

**Comment by jskeet** [comment]
There are now extension methods in 3.2.0, just released, all *from* TimeProvider *to* Noda Time types.

I'm tempted to close this issue until we have concrete ideas for anything else. Any thoughts @jennings?

**Comment by jennings** [comment]
@jskeet Sounds great to me, thanks!

**Comment by silkfire** [comment]
Were there ever any plans to add support for the opposite, i.e. how do I create a time provider from a NodaTime instance?

**Comment by jskeet** [comment]
@silkfire: I looked at that initially, but there's enough in there that `IClock` doesn't really cover that I'm not sure it would really work.
