### ISSUE TITLE
Does `SkippedTimeException` use the right base constructor?

### ISSUE THREAD

**Issue by DanCarterGMSL** [nodatime/nodatime#1761]
`SkippedTimeException` inherits from `ArgumentOutOfRangeException`, and calls the base constructor with one string parameter. This parameter is called `paramName`, suggesting that it should be the name of the parameter that is invalid. However what's being passed in looks like an exception message. Should it be using a different base constructor?

`AmbiguousTimeException` seems to have the same problem too.

**Comment by jskeet** [comment]
This is now fixed, and I've cherry-picked it into the 3.1.x branch... so next time we have a patch release, it'll be in that too (rather than waiting for the next minor version).
