### ISSUE TITLE
Typo in comment

### ISSUE THREAD

**Issue by DanCarterGMSL** [nodatime/nodatime#1764]
I was browsing the source code and found that the comment in https://github.com/nodatime/nodatime/blob/main/src/NodaTime/Duration.cs#L68-L69 doesn't really make sense. It looks like it's missing a word, but I'm not quite sure what!

**Comment by jskeet** [comment]
Yes, that comment's unfinished. It's also *very* old, so I'm not sure what I was thinking at the time... I'll see what I can think of.
