### ISSUE TITLE
Custom Pattern Support for text serialization

### ISSUE THREAD

**Issue by apavelm** [nodatime/nodatime#1765]
Currently, NodaTime can deserialize NodaTime types from string only by using the default pattern. 
Discussion was started here: https://github.com/nodatime/nodatime.serialization/issues/110
Why it is needed also mentioned there.

I'm gonna prepare a PR with a small modification that Allows to add such a customization. Feel free to modify it if necessary.

**Comment by jskeet** [comment]
> Currently, NodaTime can deserialize NodaTime types from string only by using the default pattern.

When using TypeConverter - that's a *really, really* important clarification.

**Comment by jskeet** [comment]
One question that could guide both the design and whether it's really a good idea: how would you configure this without Noda Time, if you were using just DateTime and DateTimeOffset? If you wanted to deserialize using type converters with custom patterns there - would it be feasible? If not, I'm not sure that doing so in Noda Time is really sensible.

**Comment by jskeet** [comment]
It looks like you'd want to use `[TypeConverterAttribute]` in the model to specify which one to use for any given property. Any reason that doesn't already work in Noda Time? (We could make `TypeConverterBase` public in a new release, if that makes things simpler.)

**Comment by apavelm** [comment]
> One question that could guide both the design and whether it's really a good idea: how would you configure this without Noda Time, if you were using just DateTime and DateTimeOffset? If you wanted to deserialize using type converters with custom patterns there - would it be feasible? If not, I'm not sure that doing so in Noda Time is really sensible.

I hardly can imagine the case when I will use DateTime in data contract voluntarily. It is never a good idea, I cannot say anything about DateTimeOffset. But basing on my purposes, there is no equivalent in .NET data types for "HH:mm". 
For date+time it gonna be "string" in GeneralIso format for time - string. So no way to use DateTime. Basically, I doubt that this extension will often be used, but to have it will be useful.

> It looks like you'd want to use `[TypeConverterAttribute]` in the model to specify which one to use for any given property. Any reason that doesn't already work in Noda Time? (We could make `TypeConverterBase` public in a new release, if that makes things simpler.)

Sure you can (and it will work), I was thinking about it from the beginning. But I conclude that it won't be logically correct. I mean, it would be a right way if we need to convert NodaType to any other type complex type, but we still need to have string-to-noda conversion, that requires just an additional pattern. For serialization (noda-to-string), it still use the default one (not to break the anything)

**Comment by jskeet** [comment]
To be clear: just because *you* don't want to use DateTime/DateTimeOffset in your models doesn't mean no-one else does, and presumably there's some way of configuring how those are serialized. I believe that to be via custom type converters rather than changing what the default type converters do - so I'm proposing we follow the same pattern for Noda Time.
