### ISSUE TITLE
Incorrect names for Ukrainian aliases

### ISSUE THREAD

**Issue by MykolaLevadnyi** [nodatime/nodatime#1768]
I noticed that the Ukrainian aliases in the package are currently translated from russian names of our cities. This poses a significant concern for me and all Ukrainians, especially given the geopolitical situation involving the invasion of russians.

I understand the importance of language accuracy, so I wanted to kindly request your support in addressing this matter promptly.

List of incorrect aliases:
Europe/Kiev -> Europe/Kyiv
Europe/Uzhgorod -> Europe/Uzhhorod
Europe/Zaporozhye -> Europe/Zaporizhzhia

![image](https://github.com/nodatime/nodatime/assets/47255114/7472f7f9-f9a2-4cd1-b8f2-0710ee13931b)

**Comment by jskeet** [comment]
No, that's the correct set of *aliases* for Europe/Kyiv, which is the canonical ID shown on the left side of your screenshot.

Note that all these IDs (including the IDs for Uzhhorod and Zaporizhzhia) are from the [IANA time zone database](https://www.iana.org/time-zones). While the preferred ID for Kyiv was updated in 2022 (with Europe/Kiev becoming an alias), I think it's unlikely that additional [aliases](https://github.com/eggert/tz/blob/main/backward) would be added (and the old ones would need to be preserved anyway).
