### ISSUE TITLE
Question: FakeClock and AutoAdvance

### ISSUE THREAD

**Issue by Korporal** [nodatime/nodatime#1772]
I'm not clear on how this is actually meant to be used. Does the class allow me to automatically advance the time at a faster rate than normal? That is can I get it to run 10 times faster than the real clock so that if I got `Now` did a `Sleep` for 1 minute and called `'Now' again, it would appear that 10 minutes had actually elapsed?

The docs seem to say no, that the clock will advance every time `Now` is accessed irrespective of the true elapsed system time.

**Comment by jskeet** [comment]
> The docs seem to say no, that the clock will advance every time Now is accessed irrespective of the true elapsed system time.

That's exactly right. The fake clock is *completely* oblivious to system time.

`AutoAdvance` is really only useful if you know that you have code that checks `GetCurrentInstant` multiple times and want to simulate time passing in a linear way. To be honest, most of the time I find that just creating a fake clock for a single instant is fine.

**Comment by Korporal** [comment]
> > The docs seem to say no, that the clock will advance every time Now is accessed irrespective of the true elapsed system time.
> 
> That's exactly right. The fake clock is _completely_ oblivious to system time.
> 
> `AutoAdvance` is really only useful if you know that you have code that checks `GetCurrentInstant` multiple times and want to simulate time passing in a linear way. To be honest, most of the time I find that just creating a fake clock for a single instant is fine.

Thank you Jon, I understand now. What I'm seeking (and have coded a basic version of) is a clock implementation that "runs" X times faster than the real clock. This way I can run unit tests that must test behavior that is date dependent in a much shorter time than actually running over several days.

**Comment by jskeet** [comment]
Right. You could probably implement IClock yourself pretty easily to do that, but that's not what FakeClock does.
