### ISSUE TITLE
Remove polyfil package

### ISSUE THREAD

**Issue by thompson-tomo** [nodatime/nodatime#1797]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
The System.Runtime.CompilerServices.Unsafe package becomes conditional so only added for the older frameworks.

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by jskeet** [comment]
Is this not implemented in https://github.com/nodatime/nodatime/pull/1796?
