### ISSUE TITLE
Missing timezone for Kosovo

### ISSUE THREAD

**Issue by lanesson** [nodatime/nodatime#1798]
No zonelocation info found for XK countrycode, Kosovo.

**Comment by jskeet** [comment]
That's not a Noda Time bug - Noda Time is just propagating the information from https://www.iana.org/time-zones (sourced in [GitHub](https://github.com/eggert/tz)) in zone.tab and iso3166.tab.

I *believe* time zone ID you want is "Europe/Belgrade". I understand that may well not be a palatable ID politically, but it should be regarded as an opaque identifier.

See https://tz.iana.narkive.com/EMmLTRn7/time-zone-for-kosovo for some background, and https://en.wikipedia.org/wiki/XK_(user_assigned_code) which includes:

> ISO affirms that no [code beginning with "X"](https://en.wikipedia.org/wiki/ISO_3166#Codes_beginning_with_%22X%22) will ever be standardised as a country code. ("XK" for [Kosovo](https://en.wikipedia.org/wiki/Kosovo) is a unilateral "user assigned code" and not an ISO 3166 standard country code.) Consequently if/when Kosovo is recognised, this XK code will need to be replaced with one beginning with another letter.

I'll close this now as it's really not something that *this* project is going to take unilateral action on.

**Comment by lanesson** [comment]
Thanks for the quick answer!
