### ISSUE TITLE
Remove IEquatable support from DateTimeZone in favour of ZoneEqualityComparer

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nodatime/nodatime#180]
```
We don't support this properly (see e.g. issue 135), and so it's better not to 
pretend that we do.  We should remove the interface and the Equals/EqualsImpl 
(etc) support from DateTimeZone.
```

Original issue reported on code.google.com by `malcolm.rowe` on 25 Jan 2013 at 9:32

**Comment by malcolmr** [comment]
In summary:

- `IDateTimeZoneProvider` guarantees that a single provider instance will return `DateTimeZone` instances that compare equal for any given ID. `DateTimeZone` instances obtained from different providers (or from a source, or constructed by hand) have no other guarantee. (In particular, this means that `DateTimeZone` itself documents nothing beyond reference equality.)
- Other `DateTimeZone` implementations may choose to have stronger guarantees.
- `DateTimeZone.ForOffset` (and similar) guarantees that fixed `DateTimeZone` instances compare equal if they have the same offset.

**Comment by malcolmr** [comment]
(We should document that `DateTimeZone.Utc` is equal to `DateTimeZone.ForOffset(Offset.Zero)` - we already document the reverse.)
