### ISSUE TITLE
UnparsableValueException and how to migrate old data?

### ISSUE THREAD

**Issue by mmateevadeltek** [nodatime/nodatime#1809]
I have an issue that I ended up with json data stored in database or in archive files that after upgraded to NodaTime 3.1.11.0 becomes invalid and I understand that at the time it has been saved, we used older version and then we did not know that after 2022 this specific zone moved from -6 to -7. So now I have this error:

NodaTime.Text.UnparsableValueException: 'The specified offset is invalid for the given date/time. Value being parsed: '2023-10-12T17:11:51.4256321-06 America/Mazatlan'.'

What are my options to fix that? And I don't even know if that is the only issue, probably I have other invalid dates, too.. Is there a way to upgrade to 3.1.11.0 but somehow be able to fix that incorrect data?

**Comment by jskeet** [comment]
One option would be to download an older NZD file (see https://nodatime.org/unstable/userguide/tzdb), create a `ZonedDateTimePattern` with that provider, and parse the value with that (to a `ZonedDateTime`). You can then use `DateTimeZone.WithZone` to create a `ZonedDateTime` with the *current* `DateTimeZone` for the same ID, and reformat the value for storage.

**Comment by jskeet** [comment]
@mmateevadeltek: Are you look for any more information here, or can we close this issue now?

**Comment by jskeet** [comment]
Closing based on lack of further comments.
