### ISSUE TITLE
Understanding calendar systems and event triggering

### ISSUE THREAD

**Issue by mwpowellhtx** [nodatime/nodatime#1818]
I'm not hundred percent certain I understand the `NodaTime` `Calendar` systems. Specifically I have a case where I want to schedule some _time sensitive actions_, and I wonder if there is such an event triggering mechanism baked into that cake. Would not need to run over multiple days, in fact it is more of a daily scheduling thing; the schedule would reset itself daily and be can be reevaluated depending on system conditions. Would also need for time zone sensitive schedule along these lines. Outside edge cases might be to also understand shortened and lenghtened leap year days, of course, but I assume that perhaps that is understood by the supporting date time instant infrastructure.

**Comment by jskeet** [comment]
There's no event triggering in Noda Time, no. I'd personally recommend polling "reasonably frequently" and acting accordingly - while thinking about what to do if a scheduled time is skipped or ambiguous due to DST changes, for example.

I didn't see anything in your description that actually needs calendar system support beyond the ISO (Gregorian) calendar - do you actually need to support other calendars?

**Comment by mwpowellhtx** [comment]
Thanks for the response. Yes, your recommendation was my plan, absent anything, not knowing what I did not know. But now I do, thank you.

As far as ISO, that, if that; the use case is geared around daily scheduling; notwithstanding DST. So wondered if it was even worth thinking about a custom calendar, what that might gain me in this scenario.

Bare metal, I am starting with some `Duration`, arranging some `Instant`, and figuring in the _time zone_ aspect aligning to _server locality_, that's about it; _timer driven inspection_ thereafter.

**Comment by jskeet** [comment]
Time zones and calendar systems are entirely distinct. Calendar systems are things like Gregorian, Julian, the Hebrew calendar system etc. I can't see why you'd want a custom calendar system here - you're not designing your own set of months etc are you?

It's hard to say more without specific requirements, but I strongly expect that the ISO calendar system is all you'll need on that front.

**Comment by mwpowellhtx** [comment]
True, no, I do not care month over month, per se.

I'm thinking abstractly more along the lines of something like an Outlook or Google calendar; but really the calender is simply there as the substrate; the thing facilitating the event scheduling, triggering around the events and such, which is what I am after ultimately.
