### ISSUE TITLE
Feature Request: Adding Interfaces like Temporal as in Java

### ISSUE THREAD

**Issue by paulushub** [nodatime/nodatime#1838]
Hello,
I have just discovered this library and it is exactly what I want for the port of `Java/GeoAPI` to `C#/.NET`.
Unfortunately, there is no common interface to the implementations of `LocalDate`, `LocalTime` etc as in Java:
>> ---------------------------------
```interface Temporal```

**All Known Implementing Classes:**
HijrahDate, Instant, JapaneseDate, LocalDate, LocalDateTime, LocalTime, MinguoDate, OffsetDateTime, OffsetTime, ThaiBuddhistDate, Year, YearMonth, ZonedDateTime
>> ---------------------------------
Any chance to add the common interface like `Temporal`?

**Comment by jskeet** [comment]
Unlikely, to be honest. There are significant differences in the designs of the two libraries. I'll have a closer look, but I'm NodaTime we're quite strict about what you can do with types, to avoid confusion between machine time and civil time, etc.

As I say, I'll have a look - but my instinct is that this isn't going to be a straightforward change.

**Comment by paulushub** [comment]
Thanks for the reply, and looking into it. 
I will also look into the ISO specification (ISO-19115), a bit expensive for an open source project! 
Currently, I do not know what the actual ISO specification states, and why it is translated into `Temporal` interface in Java. 
Will close this issue for now.
