### ISSUE TITLE
LocalDateTime.MaxIsoValue is NOT equal to System.DateTime.MaxValue.ToLocalDateTime()

### ISSUE THREAD

**Issue by B4rT45** [nodatime/nodatime#1840]
Not sure if this is by design or if it is a bug (potentially in `System.DateTime`) , but either way I would expect these to be the same, and they aren't.

![image](https://github.com/user-attachments/assets/02c9f7a1-873e-45dd-ad42-b979597f8cf7)

**Comment by jskeet** [comment]
It's entirely by design - Noda Time has a slightly wider range due to having greater precision. It would be really weird to have the maximum value stop 99 nanoseconds before the end of the final day.

**Comment by B4rT45** [comment]
Thanks for a quick answer!

I was thinking that this might be the case but at the same time it's a bit weird to have 2 MaxValues to be different - it messes up the code/assumptions/tests as one needs to know that one max localDateTime comes from System.DateTime.MaxValue and the other does not (or we need to make some workaround to discard the last 99 and treat them as equal).

Could this be an enhancement in a form of a new method or a param to the `ToLocalDateTime` method with the default value/behaviour as is ?
Or would you expect this to be handled locally (by clients) ?

**Comment by jskeet** [comment]
I would suggest if you want a static read-only property for "BCL DateTime.MaxValue but as a Local date time", you add that to your own codebase. If there are significant other calls for it I could add it later, but I doubt that it's that common a requirement.

**Comment by B4rT45** [comment]
Thank you!
