### ISSUE TITLE
Documentation says that "Instant supports all the LocalDateTime custom patterns", but code appears to disagree

### ISSUE THREAD

**Issue by HughMacdonald** [nodatime/nodatime#1841]
I'm using NodaTime 3.2.0

In the UserGuide (https://nodatime.org/3.2.x/userguide/instant-patterns), it says:

> [Instant](https://nodatime.org/3.2.x/api/NodaTime.Instant.html) supports all the [LocalDateTime custom patterns](https://nodatime.org/3.2.x/userguide/localdatetime-patterns).

However, in my code, when I try to do:

```
instant.ToString("R", CultureInfo.InvariantCulture);
```
I get:
> NodaTime.Text.InvalidPatternException : The standard format "R" is not valid for the NodaTime.Instant type. If the pattern was intended to be a custom format, escape it with a percent sign: "%R".

This exception comes from here: https://github.com/nodatime/nodatime/blob/d0d2cc86c3bbad6c64c6afa0622f9834e549c796/src/NodaTime/Text/InstantPatternParser.cs#L49

For my use case, I can just hard-code it to be `uuuu'-'MM'-'dd'T'HH':'mm':'ss'.'ffffffff`, so this is not a blocker, but it might be worth either changing the code or the documentation (or I've missed something here)

**Comment by jskeet** [comment]
"R" isn't a custom pattern. It's a *standard* pattern.

**Comment by HughMacdonald** [comment]
Oh... yeah... So I just mis-read the documentation 🤦🏻

Apologies.
