### ISSUE TITLE
Issue installing NodaTime 3.2.0 nuget package into a Visual Studio 2022 project

### ISSUE THREAD

**Issue by bobw1964** [nodatime/nodatime#1842]
I'm currently getting the following issue installing the NodaTime 3.2.0 nuget package into a Visual Studio 2022 project.

NU1108  Cycle Detected. NodaTime -> NodaRime (>= 3.20).       

![image](https://github.com/user-attachments/assets/8c4c5195-a5c9-4ab6-b3e7-21c0ec865c80)

The project is a .Net8.0 project.

No other nuget packages installed. The default console project with nothing added yet.

The project file contains the XML:

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>

**Comment by bobw1964** [comment]
The project file XML, which is not showing on previous comment:

![image](https://github.com/user-attachments/assets/a9818cae-7370-4056-855d-5d9acf0b594b)

**Comment by malcolmr** [comment]
Is your project _also_ called NodaTime?

I'm not entirely sure how Visual Studio dependencies are resolved, but it's possible that adding the NodaTime dependency to your NodaTime project is creating (in effect) a circular dependency.

**Comment by bobw1964** [comment]
Yes it is called NodaTime.
Changing the project name removes the project conflict.
Thanks
