### ISSUE TITLE
WebApi 5: DefaultBodyModelValidator throws StackOverflowException when validating model with LocalTime

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nodatime/nodatime#249]
```
Hi!

I recently upgraded a WebApi project to Visual Studio 2013.

My JavaScript client App is posting a model with a LocalTime to my WebApi 
controller:

public class MyModel {
   public LocalTime Hora { get; set; }
}

POST http://localhost:49165/api/prueba HTTP/1.1
Content-Type: application/json; charset=utf-8
{
  "Hora": "15:15:00"
}

I have configured JsonSerializerSettings with the JsonNet helpers for Noda Time

serializerSettings.ConfigureForNodaTime(NodaTime.DateTimeZoneProviders.Tzdb);


JsonNet is still deserializing correctly the object graph, but as soon as the 
model validation baked in WebApi kicks in 
(DefaultBodyModelValidator.ValidateProperties &  
DefaultBodyModelValidator.ValidateNodeAndChildren), it recursively begins to 
validate the model:

LocalTime => LocalTime.LocalDateTime => LocalDateTime.TimeOfDay => 
LocalTime.LocalDateTime => LocalDateTime.TimeOfDay => ...

The DefaultBodyModelValidator is recursively traversing these properties and 
does not detect infinite recursión although it seems that it has logic to 
handle that situation:

https://github.com/mono/aspnetwebstack/blob/master/src/System.Web.Http/Validatio
n/DefaultBodyModelValidator.cs#L91-94


This didn't happen before upgrading to latest WebApi version and I really don't 
know if the problem is from NodaTime or WebApi.

Any ideas or workaround? Thanks!!!

Germán Fernández






```

Original issue reported on code.google.com by `germanft...@gmail.com` on 29 Oct 2013 at 11:20

**Comment by kentpickard** [comment]
I am running into this issue as well. 

In the model class that I'm trying to deserialize I have a property of type OffsetDateTime.

OffsetDateTime has a property called LocalDateTime of type LocalDateTime.

The LocalDateTime class has a property called TimeOfDay of type LocalTime.  

The LocalTime class has a property named TimeOfDay property of type LocalTime.

So it tries to validate OffsetDateTime -> LocalDateTime -> TimeOfDay -> LocalDateTime -> TimeOfDay -> LocalDateTime and so on.  I think it is this design that's causing infinite recursion while trying to validate a model binding.  

I would imagine the same exact problem would exist with the regular DateTime class (DateTime -> Date -> DateTime) but there is probably some custom code under the covers somewhere in Web API to handle that scenario.  

I'm not sure the best way to handle this or work around it.
