### ISSUE TITLE
Simplify Windows to/from IANA conversion methods

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nodatime/nodatime#274]
```
What situation does this request make simpler?
Since Noda Time contains IANA, Windows, and CLDR data, it can be used to 
convert BCL time zones to or from TZDB time zones.  The data is exposed in the 
API, but sensible conversion methods aren't included.  This could be more 
convenient, such as illustrated here:
http://stackoverflow.com/a/17348822/634824

Can you provide a straw-man example of what you'd want the API to look
like?

string bclZoneId = 
TzdbDateTimeZoneSource.Default.WindowsMapping.TranslateToBcl(tzdbZoneId);

string tzdbZoneId = 
TzdbDateTimeZoneSource.Default.WindowsMapping.TranslateToTzdb(bclZoneId);


We could also consider (in addition) a new method to DateTimeZone with the 
signature:

public DateTimeZone TranslateFor(IDateTimeZoneProvider provider)

Which would give some convenience for those not used to calling into a the 
TzdbDateTimeSource, for example:

DateTimeZone bclZone = 
DateTimeZoneProviders.Tzdb[tzdbZoneId].TranslateFor(DateTimeZoneProviders.Bcl);

DateTimeZone tzdbZone = 
DateTimeZoneProviders.Bcl[bclZoneId].TranslateFor(DateTimeZoneProviders.Tzdb);




```

Original issue reported on code.google.com by `mj1856` on 26 Mar 2014 at 6:08

**Comment by jskeet** [comment]
We can add these later - it shouldn't block 2.0.

**Comment by jskeet** [comment]
Time to finally do this, I think. Let's start with just the `TranslateToBcl` and `TranslateToTzdb` methods - things get really complicated if you put them on `DateTimeZone`, which doesn't currently know its source.

**Comment by robloo** [comment]
Since this is being done, could you support the obsolete windows time zones with a hard-coded value? Just bringing this up again as it might be relevant to #778

**Comment by jskeet** [comment]
@robloo: No, I *definitely* don't want to hard-code anything in the Noda Time codebase itself. If I were to do anything, it would have to be in the data file. But again, I don't think it's worth the complexity - I think it's best if you put that into your app logic instead.

**Comment by robloo** [comment]
@jskeet Ok, fair enough. Seems I'm the only one concerned about this :)
