### ISSUE TITLE
Culture-aware standard formats required for more types

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nodatime/nodatime#276]
```
See http://stackoverflow.com/questions/23019131 for background.

We have culture-aware standard patterns for LocalDate, LocalTime, and 
LocalDateTime using the BCL resources.

We have culture-aware standard patterns for Offset, using our own resources 
(not in as extensible a way as I'd like, admittedly).

We *don't* have any culture-aware standard patterns for:

- Instant (well, there's 'n' which uses the culture group separator, but I 
hardly think that counts - and I'd like to remove it anyway)
- OffsetDateTime
- ZonedDateTime

It's somewhat reasonable not to support this for Instant, but OffsetDateTime 
and ZonedDateTime ought to have more support. Initially we could just use 
whatever the LocalDateTime standard format would be, and append " o<G>" for 
OffsetDateTime, or " z '('o<g>')" for ZonedDateTime. We can come up with more 
customized strategies later.


```

Original issue reported on code.google.com by `jonathan.skeet` on 12 Apr 2014 at 7:47

**Comment by malcolmr** [comment]
Given that 1.4 is intended to be a bridge release, bumping this to 2.0-consider.

**Comment by jskeet** [comment]
For OffsetDateTime and ZonedDateTime this should actually be pretty simple now, using the `l<...>` specifier. For example, we could have `l<g> o<G>` for a standard `g` pattern in `OffsetDateTime`. I haven't tested it yet, but I *think* that should work...

**Comment by jskeet** [comment]
I've been thinking about this more - and as it's really pretty easy to use embedded patterns for this, I think I'd prefer to avoid adding new (and inflexible) standard patterns. We have tests that prove using standard patterns work - e.g. https://github.com/nodatime/nodatime/blob/master/src/NodaTime.Test/Text/OffsetDateTimePatternTest.cs#L102 - so I think we should probably just highlight this in the docs.
