### ISSUE TITLE
Hebrew month names need decent support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nodatime/nodatime#279]
```
Currently we explicitly don't support Hebrew month names in text 
formatting/parsing. Clearly this needs fixing :)
```

Original issue reported on code.google.com by `jonathan.skeet` on 19 Apr 2014 at 5:16

**Comment by malcolmr** [comment]
Given that 1.4 is intended to be a bridge release, bumping this to 2.0-consider.

**Comment by jskeet** [comment]
Any future CLDR support will be in a separate package.

**Comment by jskeet** [comment]
Years later, no-one has actually requested this. It will probably drop out if we ever do CLDR support, and isn't worth trying *without* CLDR support, so I'm closing this issue.
