### ISSUE TITLE
Make it easier to get daylight saving time transitions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nodatime/nodatime#292]
```
For 2.0, please consider adding a method like the one shown here.

http://stackoverflow.com/a/24378695/634824


```

Original issue reported on code.google.com by `mj1856` on 24 Jun 2014 at 4:04

**Comment by jskeet** [comment]
Closing for now as "wontfix" because I agree it's not obviously sufficiently common to warrant doing. We can add it later without breaking anything.
