### ISSUE TITLE
Calculate LocalDate by weekday instance of month

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nodatime/nodatime#293]
```
Many business rules need functions that take "the third Tuesday in July", or 
"the last Saturday in December", etc.

Something like this, but cleaner:
http://stackoverflow.com/a/24391952/634824

```

Original issue reported on code.google.com by `mj1856` on 24 Jun 2014 at 4:41

**Comment by dizzleuk** [comment]
where do you find this functionality?

**Comment by jskeet** [comment]
It's in 2.0 only, in LocalDate.FromYearMonthWeekAndDay. See
https://github.com/nodatime/nodatime/commit/5c03bb98401935508a0604e095456a1170af1fbd
