### ISSUE TITLE
Decide exactly what will be in 1.4.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nodatime/nodatime#311]
```
(marking this as 2.0-consider, because it's tightly coupled to what ends up in 
2.0.0.)

It would be nice to be able to write code that worked in Noda Time 1.x and 2.x. 
 However, due to changes to e.g. IClock for 2.0, that's not currently possible.

When we actually get a bit closer to 2.0.0 and can see what's in it, it'll be 
worth considering whether a 1.4 should exist, to bridge 1.x and 2.x.  

The obvious thing that it could contain so far would be a deprecated IClock.Now 
(not deprecated in 1.3; not present in 2.0) and an additional 
IClock.GetCurrentInstant() [though as Jon points out, adding a method to an 
interface could itself be considered a breaking change].

[It _might_ also be nice to backport some of the new-in-2.0 APIs back to 1.x to 
make sharing code between 1.x and 2.x a little easier: for example, 
Offset.FromSeconds() would be trivial to backport. That's far less important 
than the IClock case, though.]
```

Original issue reported on code.google.com by `malcolm.rowe` on 29 Jul 2014 at 2:03

**Comment by malcolmr** [comment]
We've decided it should exist. See initial analysis/proposal at https://groups.google.com/d/msg/noda-time/NO5NgTAVfUw/aQYuSK2jDi4J.

I'm going to morph this to "decide exactly what goes into 1.4.0", since we'll still have work to do when we're closer to 2.0

**Comment by jskeet** [comment]
http://nodatime.org/2.0.x/api/changes.html should be helpful here.

**Comment by jskeet** [comment]
Reminder: we need to work out what "obsolete" really means. If there's no replacement in 2.0.x (e.g. for specifying the min-days-of-first-week) for a calendar system, do we want to make that obsolete, or are we only aiming at getting developers to a situation where they are in as good a position as they can be for 2.0?

**Comment by jskeet** [comment]
This is now basically done, as 1.4.0 beta 01 is released :)
