### ISSUE TITLE
Consider supporting backzone

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nodatime/nodatime#327]
```
As of TZDB 2014g, there's a new backzone file containing *alternative* data for 
IDs which are present in the rest of the database... this is usually to add 
zone rules for times prior to 1970. Zones which are in backzone are typically 
links elsewhere (e.g. in backward).

We could *consider* supporting these via an extra field in NZD, or by having a 
switch on TzdbCompiler. There may be a certain amount of subtlety in doing so 
though.
```

Original issue reported on code.google.com by `jonathan.skeet` on 2 Sep 2014 at 4:28

**Comment by malcolmr** [comment]
I see we must have discussed this, but I forget the background. Is this really something we want to do for 2.0? (or perhaps we did it already?)

**Comment by jskeet** [comment]
I was trying to remember as well :) I think we decided to look at it enough to work out whether it would be a breaking change, and do it now if so, but otherwise defer.

**Comment by jskeet** [comment]
Looking at this again, I suspect the best approach would be to modify TZDB compiler **if requested** to have a mode where it uses backzone... we could then create two separate NZD files whenever TZDB changes, one for backzone and one for not. I doubt that there are many situations where you'd want to use a mixture within a single provider. We wouldn't ship the backzone version with Noda Time - users would need to grab it from the web site themselves.

If this is an agreeable solution, I'll remove the 2.0 milestone.

@mj1856: Any thoughts? (If you don't reply here, I'll bug you about it in person :)

**Comment by jskeet** [comment]
@mj1856: Ping? (I somehow failed to bug you hard enough in person...)

**Comment by jskeet** [comment]
Closing as we don't think we need this - we can reopen if necessary.

**Comment by mj1856** [comment]
Sorry - I've been ignoring GitHub lately...  Some life issues.

Anyway, - no, I don't think `backzone` has much place in NodaTime.  Also, I don't think `systemv` or `pacificnew` are important either.
