### ISSUE TITLE
Consider dropping .NET 3.5 for 2.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nodatime/nodatime#329]
```
As .NET 4.5 is now a critical Windows Update, support for .NET 4.0+ is now much 
stronger, so we should consider making .NET 4.0 our lowest common denominator. 
That would simplify our Nuget package back down to two binaries (PCL + desktop) 
and open the possibility of using things like ThreadLocal<T>.

If we're going to do it, 2.0 is the time to do it...
```

Original issue reported on code.google.com by `jonathan.skeet` on 9 Sep 2014 at 10:02

**Comment by malcolmr** [comment]
f we're doing this at all, it'll have to be for 2.0.0.

**Comment by malcolmr** [comment]
Note that Mono 4.0 drops support for targeting .NET 3.5, so compiling Noda Time 2.0 using Mono currently requires overriding the target framework version to 4.0 anyway.

(However, the [draft Mono 4.0 release notes](http://www.mono-project.com/docs/about-mono/releases/4.0.0/) currently say "We dropped support for the 2.0, 3.5 **and 4.0** assemblies" (emphasis mine), so we may need to continue doing that overriding if they end up also dropping support for .NET 4.0.)

**Comment by jskeet** [comment]
I'm pretty certain we'll only be supporting 4.5 and .NET Core for 2.x now, and whatever that allows in terms of Mono.
