### ISSUE TITLE
Update website to account for move to GitHub

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime#353]
I did some search-and-replacing in 4c2a98d, but we still have references to Mercurial repositories and the 'hg' command-line in various places.

I think we'll need to rewrite `developer/building.md` and `developer/release-process.md`, but there's also a bunch more search-and-replace to do.

This issue also covers fixing our website autobuild to source from GitHub rather than Google Code.

**Comment by malcolmr** [comment]
We should also replace our use of google-code-prettify (which is hosted on googlecode.com, and used for the code snippets on the front page and user guide) with something else.

**Comment by jskeet** [comment]
Website build is now fixed, as is the benchmark part of the website.
Under www, only building.md and release-process.md refer to hg or Mercurial.
Still working out what to do about prettify.

**Comment by malcolmr** [comment]
Bizarrely we have a partial (broken) local copy of prettify already, which we're not using.

But we also have Pygments' offline stylesheets and some support for that. Which we're also not using.

I'm going to try to clear some of this up.

**Comment by malcolmr** [comment]
Okay, I think we just need to rewrite `developer/building.md` and `developer/release-process.md` now.

**Comment by jskeet** [comment]
Given the latest commits, is it just the release process we still need to do?

**Comment by malcolmr** [comment]
Yup, I think that's all that's left now. We might close this and just slap a TODO at the start of that file, since we'll probably only really work it out when we release 1.4.0/2.0.

**Comment by jskeet** [comment]
@malcolmr I think we had a reasonable stab at this when we did an interim 2.0 pre-release to test something... happy for us to close now?

**Comment by malcolmr** [comment]
sgtm.
