### ISSUE TITLE
Update repository to account for move to GitHub

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime#354]
Things I can think of offhand:

- `.hgtags` should go away.
- `.hgignore` should be moved to `.gitignore` (and possibly changed if the format needs to differ).
- Solution/`csproj` files currently refer to Mercurial.
- We were going to canonicalise line-endings.

**Comment by malcolmr** [comment]
Jon added a `.gitignore` in fa956a9. If it's correct, we can remove `.hgignore`.

**Comment by jskeet** [comment]
Commit ddf37e87 fixes the solution and project files.

**Comment by malcolmr** [comment]
Commits d60bb64..7208243 variously normalise the line endings, so I think we're done here.

**Comment by malcolmr** [comment]
I just replicated some of those changes to the 1.3.x branch. We probably don't need to worry about the other branches, but 1.3.x will be the base for 1.4.x, and cherrypicks will conflict without the line-ending fixes.
