### ISSUE TITLE
Make Noda Time 2.0 build with Mono again

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime#358]
I updated some of the build instructions in 083ee18, and we can now build the 1.3.x branch using Mono 4.0.0-dev.  (Some of the tests fail due to a type initialisation error, but I'm not planning to dig into that just now.)

However, we still can't build `master`.

Problems I'm aware of so far:
- We now depend upon NuGet to fetch various packages, but we haven't documented how to do that, or made it easy. I'm just about to fix that.
- I currently need to override `xbuild` to set `/p:TargetFrameworkVersion='v4.0'` because Mono 4.0 doesn't support building against .NET 3.5, but this breaks the few projects that use v4.5.
- Even after culling those projects from `NodaTime-All.sln`, I see the following:

```
/home/malcolm/git/nodatime/src/NodaTime-All.sln (default targets) ->
(Build target) ->
/home/malcolm/git/nodatime/src/NodaTime.Test/NodaTime.Test.csproj (default targets) ->
/home/malcolm/mono/4.0.0-b7bcd23/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

    Annotations/RoslynHelper.cs(15,38): error CS0012: The type `System.Object' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

I'm _guessing_ that one of the assemblies we're depending on there is in some way incompatible with Mono, but I haven't dug into this yet.

Incidentally, I'm also seeing a large number of:

```
/home/malcolm/git/nodatime/src/NodaTime-All.sln (default targets) ->
(Build target) ->
/home/malcolm/git/nodatime/src/NodaTime.Benchmarks/NodaTime.Benchmarks.csproj (default targets) ->
/home/malcolm/mono/4.0.0-b7bcd23/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

    ../../lib/commandline/CommandLine.cs(118,47): warning CS0436: The type `CommandLine.BaseOptionAttribute' conflicts with the imported type of same name'. Ignoring the imported type definition
```

which I'm guessing is due to Minibench using that library and then incorrectly exporting those types(?).

**Comment by jskeet** [comment]
Ah, joy - I've been fighting against that System.Runtime problem myself today.

Do you know whether using TargetFrameworkVersion of v4.0 is around the CLR, or the whole framework? Minibench uses [System.Collections.Immutable](https://www.nuget.org/packages/System.Collections.Immutable), which targets .NET 4.5 rather than .NET 4.0 (and PCLs) so if you can target 4.5 with the build, that may well help. I suspect that System.Collections.Immutable is responsible one way or another - that was the cause of my issues today.

As for CommandLine - that should be fixable. I've made the types internal in source control, but haven't pushed a new NuGet package yet. (The downside of splitting everything out is that a fix in Minibench now needs to get pushed to NuGet before it affects Noda Time...)

**Comment by malcolmr** [comment]
I'm not sure that I understand the details. The [announcement](http://lists.ximian.com/pipermail/mono-devel-list/2014-October/042145.html) on mono-devel talks about removing the "2.0 and 4.0 profiles", though it turns out that the 4.0 reference assemblies weren't removed.  Later in that thread there's a comment to the effect that Mono doesn't have a "3.5 profile", just that assemblies introduced with .NET 3.5 ship with the 4.0/4.5 profiles.

Hmm, notice that it's using `lib/mono/4.5/Microsoft.CSharp.targets` above, even though I set TargetFrameworkVersion to v4.0. And then it's complaining about a reference to System.Runtime 4.0.0.0.  I'll try v4.5.

The Minibench warnings are just warnings, so I think I can ignore them for now.

**Comment by malcolmr** [comment]
Okay, so the error reported when I force v4.0 is actually the first occurrence of `Microsoft.CodeAnalysis.Compilation`, which I suspect requires v4.5.  Fine.

Trying with v4.5 gets a bit further through `NodaTime.Test`, failing on:

```
DurationTest.Construction.cs(39,56): error CS0103: The name `NanosecondsPerDay' does not exist in the current context
```

Replacing that with `NodaConstants.NanosecondsPerDay` (etc) works: I suspect that cross-assembly `using static` support in Mono 4.0 is broken (though I haven't verified that).

That file is the only one in Test that uses `using static`, so I end up with the following warnings (which might be valid, will take a look later):

```
Tzdb/CldrWindowsZonesParser.cs(33,80): warning CS0618: `System.Xml.XmlReaderSettings.ProhibitDtd' is obsolete: `Use DtdProcessing property instead'
```
```
CalendarSystemTest.cs(16,54): warning CS0414: The private field `NodaTime.Test.CalendarSystemTest.SupportedCalendars' is assigned but its value is never used
Calendars/UmAlQuraYearMonthDayCalculatorTest.cs(20,53): warning CS0414: The private field `NodaTime.Test.Calendars.UmAlQuraYearMonthDayCalculatorTest.Supported' is assigned but its value is never used
TimeZones/TzdbDateTimeZoneTest.cs(17,59): warning CS0414: The private field `NodaTime.Test.TimeZones.TzdbDateTimeZoneTest.AllTzdbZones' is assigned but its value is never used
```

With those changes (build against v4.5 and stop `using static` in tests), I'm down to the following test failures so far:

- The Roslyn tests all fail with `ReflectionTypeLoadException : The classes in the module cannot be loaded`.  I'm not sure what class it's talking about: the failure is deep inside `MSBuildWorkspace.Create()` (i.e. not actually Roslyn).
- Many (all?) of the pattern tests fail with the following, which appears due to a `NullReferenceException` inside `System.Globalization.DateTimeFormatInfo.get_OptionalCalendars()`. (This also happens on the 1.3.x branch.)
```
System.TypeInitializationException : An exception was thrown by the type initializer for NodaTime.Test.Text.DurationPatternTest
  ----> System.TypeInitializationException : An exception was thrown by the type initializer for NodaTime.Test.Text.Cultures
  ----> System.NullReferenceException : Object reference not set to an instance of an object
```
- `NodaTime.TzdbCompiler.Test.Tzdb.PclSupportTest` fails to initialise, apparently because `TimeZoneInfo.GetSystemTimeZones()` is returning more than one zone with the same `StandardName`. We can't build a PCL version using Mono (or couldn't, anyway), so I may skip this test for Mono.

Otherwise, we seem to be passing.

**Comment by malcolmr** [comment]
Raised [Xamarin bug 28976](https://bugzilla.xamarin.com/show_bug.cgi?id=28976) for the `using static` issue.

**Comment by malcolmr** [comment]
[Xamarin bug 28976](https://bugzilla.xamarin.com/show_bug.cgi?id=28976) (`using static`) is fixed in Mono master, and I've asked whether they can backport to 4.0.0.

Raised [Xamarin bug 29039](https://bugzilla.xamarin.com/show_bug.cgi?id=29039) on `CultureInfo.DateTimeFormat` throwing a `NullReferenceException`.

See that bug for details, but it only affects ar-SA; it look like we can work around it by either using `CultureInfo.GetCultures(CultureTypes.AllCultures)` in `NodaTime.Test.Text.Cultures` instead of `CultureInfo.GetCultures(CultureTypes.SpecificCultures)` (and filtering, one assumes), or by more simply just checking whether `CultureInfo.DateTimeFormat` works (in another test like `RuntimeFailsToLookupResourcesForCulture`).

**Comment by malcolmr** [comment]
Sigh, also raised [Xamarin bug 29044](https://bugzilla.xamarin.com/show_bug.cgi?id=29044) for a second `using static` issue: nested types aren't found.  So far, this only affects `src/NodaTime.Test/TimeZones/TzdbZone1970LocationTest.cs`.

Working around that and the ar-SA issue gets us down to the four failures caused by `MSBuildWorkspace.Create()`.  I'll submit a fix for ar-SA; the other one I'll wait to see about.

**Comment by malcolmr** [comment]
I've applied a fix for ar-SA to master and 1.3.x (which allows me to see that 1.3.x now passes all tests with Mono 4.0.0).

**Comment by malcolmr** [comment]
[Xamarin bug 29039](https://bugzilla.xamarin.com/show_bug.cgi?id=29039) and [Xamarin bug 29044](https://bugzilla.xamarin.com/show_bug.cgi?id=29044) are now fixed in Mono master (`a801b37`) and after switching to building against v4.5, we're down to (details above):

- the four Roslyn (`MSBuildWorkspace.Create()` tests failing with `ReflectionTypeLoadException`
- `PclSupportTest` with multiple zones with the same `StandardName`.

The Mono 4.0.0 branch (`c8db1b0`) is still bust (as none of the Mono fixes have been backported).

**Comment by malcolmr** [comment]
I also noticed that `make checkfakepcl` fails with a failure in `NodaTime.Test.Annotations.SecurityTest` that's probably because the test (which is checking annotations) shouldn't be running against the PCL build (?), and that `make release` fails (under Mono master) with apparently-random XML documentation errors; no idea whether that worked in 1.3.x / Mono 3.12.0.

**Comment by malcolmr** [comment]
Looks like Jon _may_ have fixed `NodaTime.Test.Annotations.SecurityTest` in 9f58036.

**Comment by jskeet** [comment]
We now build everything with DNX, which is currently using Mono on Linux anyway.

Maybe remove the Makefile and close this issue?

**Comment by malcolmr** [comment]
Yup. We need to update the building section of the developer guide, but we need to do that in any case.

**Comment by malcolmr** [comment]
Closing. We're going to require the dotnet CLI to build on Linux.
