### ISSUE TITLE
Explore whether we can produce reproducible binaries

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime#359]
Now that we're pushing the website to nodatime/nodatime.org, I've noticed that `bin/NodaTime.Web.dll` is changing on every commit.

This is because the binaries contain embedded timestamp (etc) data that changes on every build.

That's not great for nodatime.org, but it's not good for our releases either, since it means that we can't reproduce a binary that we've built in the past (even if we have the same version of the tools that we built it with).

I'd like to explore how hard it'd be to redact the timestamps, etc, to generate reproducible binaries.  There doesn't seem like there's a pre-existing solution for this, so we might have to see if we can do it by hand as a post-build step.

Glancing at the diffs for `bin/NodaTime.Web.dll`, I see, in file order:
1. `TimeDateStamp` in the PE header is set by the linker.
2. The assembly has a random GUID in the MVID field; see`Module.ModuleVersionId`. (Including a UUID is required by ECMA-335, but there's no really good reason that I can see for generating a version 4 (random) UUID rather than a hash-based UUID; other than probably it's harder to do).
3. The Debug PE data directory contains a timestamp of the debugging information, and then the (CodeView RSDS) debugging data contains a GUID.

It should be fairly easy patch the first two, and I think that suppressing generation of PDB files when building will fix the last (for NodaTime.Web; that's less reasonable for the other binaries).

**Comment by malcolmr** [comment]
It occurs to me that we _might_ be able to do the above without disabling PDB generation, _if_ the PDB file doesn't reference the UUID (in 2), and if removing/redacting the Debug data directory doesn't cause the binary to become undebuggable in practice.

More testing required, but it should be safe to do (1+2+disable PDB generation) for binaries we don't care about debugging, for sure.

**Comment by jskeet** [comment]
The Mono 4 release notes include:

> The compiler will now avoid generating a GUID each time it builds, generating identical builds across recompilations. Following the steps of Roslyn’s new default.

So that sounds like we *may* not need to do a lot...

**Comment by malcolmr** [comment]
Ooh, shiny. Yes, I noticed that Mono was being sensible.

I wonder if Roslyn is now violating the C# spec, or whether it's using a deterministic GUID (per above).

**Comment by jskeet** [comment]
Related:
https://github.com/dotnet/roslyn/issues/372
https://github.com/dotnet/roslyn/issues/312

In particular, the first link gives details of what gets generated (thanks Neal :)

**Comment by jskeet** [comment]
It sounds like `/deterministic` with Roslyn 1.1+ *may* do what we want...

**Comment by jskeet** [comment]
We'll *attempt* to do this for 2.0.
