### ISSUE TITLE
NuGet package for latest TZDB

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#360]
As discussed in mailing list thread "Point Releases".

Probably a separate NuGet package for 1.x and 2.x, released at the same time as the new tzdb is produced.

**Comment by filmor** [comment]
This would be relevant right now, since Turkey surprised us with another nice DST change. How can I help with this?

**Comment by jskeet** [comment]
Well if you want the latest database, you definitely don't need a new nuget package of anything - you can download the .nzd file as described in the docs. If you'd like to think about what you'd *like* the API to look like for "most recent TZDB" I'd be happy to review a pull request - but I don't have a lot of time right now, so I doubt that it'll actually be released imminently.

**Comment by mj1856** [comment]
@filmor Keep in mind the Turkey change hasn't yet been confirmed.  Only if it gets published in a tzdb release would it end up in an nzd file.

**Comment by jskeet** [comment]
Okay, I'd like to get to this pretty soon. A few thoughts/questions:

- If we have this package, do we need any TZDB packaged in NodaTime itself?
- What do we want the package name to be?
- Do we want to take this time to change from "TZDB" to "IANA" everywhere? (I suspect not.)
- Is it possible to target .NET 3.5 and the existing PCL profile within DNX projects? (I would really like to, as we'll need to release NodaTime.Tzdb-1.x regularly.)

**Comment by malcolmr** [comment]
* I think it'd be reasonable to ship the NodaTime 2.0 package without an embedded TZDB, yes. We'd probably need to remove `DateTimeZoneProviders.Tzdb` to do that sensibly(?).
* NodaTime.Tzdb seems like a reasonable package name? (I'm not sure whether we'd want to keep the code in `NodaTime.TimeZones`, or move it to a different namespace, though. Maybe `NodaTime.TimeZones.Tzdb`?)
* No, I think TZDB is a good specific name; it would just be churn to change it. (Searching for [tzdb] brings up the IANA site as the first hit, for example.)

**Comment by jskeet** [comment]
Yes, we'd want to remove `DateTimeZoneProviders.Tzdb`, at which point we'd probably want to consider doing the same for the BCL provider... which only leaves serialization, basically. Hmm.

I'm quite _tempted_ to just make this a tiny package, leaving all the rest of the code in place... moving things around feels like it may be making breaking changes for no real benefit. Hmm again.

I think I'll try to get suitable code in place for the "it's just a single file" solution first, then see how much could be moved.

**Comment by mj1856** [comment]
I agree.  Leave 1.x as it is, and keep making the NZD files for both 1.x and 2.x usage.  Some will still want to use the NZD files or generate their own.

For 2.x, I think removing the embedded copy and producing a separate `NodaTime.Tzdb` package sounds right.

Definitely use the TZDB name.  IANA is just currently hosting it.  I use the terms interchangeably, but I think the most correct term is "tz database", and therefore "tzdb" for short.  IANA adds some credibility, but it's not really owned by them.

I'm really not sure on the 3.5 / DNX question.  I haven't been doing much with it lately.  I think you may need multiple project files.

**Comment by jskeet** [comment]
The 3.5 / DNX question is sorted now. I'm comfortable on that front. We'll definitely want two different projects though.

I've been thinking a bit more about whether to move the code - and it feels slightly wrong, in terms of versioning. A new version of the package should be about new data - and I shouldn't have to take a new version of the package to get bugfixes, for example. I'd also prefer that users didn't have to depend on this package if they're loading the data from a file elsewhere. Basically, separation of concerns, in package form.

So I *think* that for both 1.x and 2.x, the contents of the package should be a single class that exposes two properties - one for the source and one for the provider - and the data resource. That's it. I'll look at the impact of removing the data from NodaTime proper, with an eye to that being the way forward - we'll probably want to have an "empty" time zone provider which only knows how to deal with fixed-offset zones.

**Comment by jskeet** [comment]
Alternative solution - at least for 1.x: build a new 1.3.x build for each TZDB release.

I've resisted this in the past because doing a new release is painful - but if we're *only* building the nuget package, it becomes significantly less so. The action of branching for a new release is particularly annoying, and so is building the API docs and getting them in the right place - but just building and publishing the nuget package is simple. We'd still want to update the website with download links, admittedly.

We might still want to revisit this for 2.0, but that becomes significantly simpler than the 1.x side, because we can make changes to the main part of Noda Time to make it fit well.

**Comment by jskeet** [comment]
Best option from customer's perspective: keep to a single package, and just release a new version of 1.3.x, 1.4.x and 2.0.x each time there's a new TZDB release.

Downsides:

- Hard to implement. Can we do this without rebuilding, simply by downloading the current package, updating the files and pushing a new version? (Unclear.)
- Code and data then versioned together. New patch version could mean code change or data change.

**Comment by jskeet** [comment]
Doing it without rebuilding is going to be tricky.

For 2.x the rebuild process should be pretty straightforward. For 1.x, there are aspects we don't really want to rebuild, in particular the XML documentation which used to be post-processed by SHFB.

I think it'll be something like:

- Work out latest build version for 1.3.x (and new build number)
- Download previous build source zip file
- Copy new NZD file into place
- Edit version files (AssemblyInfo and nuspec) - just for NodaTime.dll
- Zip source up again
- Build DLL
- Download previous build binary zip file
- Copy DLL into place
- Zip binaries up again
- Build nuget package

... and likewise for 1.4.x and 2.0.x.

At that point, we'll have a set of binaries to push to Google Cloud Storage, and a set of nuget packages to push to nuget.

Arguably we should also update the old github branches (and tag them), and possibly even updating version history - but that starts getting really quite painful. I think I'd be happier leaving all of that for now.

We may want to _start_ by only implementing this for 2.x, and doing so to only update the nuget packages (not the downloadable zip files). Just that is going to be quite a bit of work.
