### ISSUE TITLE
Add compatibility tests for data files

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#364]
We have tests that new code can read the nzd file from 2013b, but we don't have any tests that old code can read recent files.

I will create a new project (CompatibilityTesting) which can be targeted to different versions of Noda Time via MSBuild configs, and add a CI step to run the tests.

**Comment by jskeet** [comment]
First port of call: reimplement TzValidate using NodaTime v1.0 (or as early as we can) and see if it produces the same hash.

**Comment by jskeet** [comment]
NZD files were introduced in 1.1, so that's probably the earliest we can realistically hope to target.

**Comment by jskeet** [comment]
Humbug - while the files are as compatible as we can make them, we get different results due to the bug fixed in https://github.com/nodatime/nodatime/commit/f04d357cd0be11ce0a57b8bfd0b0de35cda6c44f

We can remove the name suffix for the sake of checking compatibility though, for the moment - at that point we do get the same result. (Will create a PR for this, obviously.)

**Comment by jskeet** [comment]
Self-merged, but assigning to Malcolm to check that he's happy that this is enough for now.

(Basically, whenever I update tzdb, we'll be checking that the new file produces the same tzvalidate hash, when leaving out the zone names as that was broken previously.)

**Comment by malcolmr** [comment]
LGTM
