### ISSUE TITLE
Add AM/PM property to LocalTime and LocalDateTime

### ISSUE THREAD

**Issue by mj1856** [nodatime/nodatime#366]
The `LocalTime` and `LocalDateTime` structures don't have a property that gives the corresponding AM or PM designator.

This is something that is often calculated incorrectly, so it would be nice if we just exposed it as a property to complement the existing `ClockHourOfHalfDay` property.

It could be implemented as a boolean `localTime.IsPM == true` - or as an enumeration `localTime.Meridiem == Meridiem.PM`

**Comment by jskeet** [comment]
Makes sense. I think I'd rather leave it as a `bool` to make it clear that we're *not* intending to have more complex options of meridiem (which I know exist, but which are a pain).

**Comment by jskeet** [comment]
Punt to 2.1 - we can do it earlier if we want, but it wouldn't block 2.0. (Non-breaking to add later.)

**Comment by jskeet** [comment]
@mj1856: 2 1/2 years later, any more thoughts on this, either in terms of usefulness or naming?

**Comment by mj1856** [comment]
Yeah, not really.  The more I think about it, the more it's probably better handled during text formatting anyway.  Closing.
