### ISSUE TITLE
Historical utc offset / DST ?

### ISSUE THREAD

**Issue by efreeman518** [nodatime/nodatime#367]
Currently using data (from http://timezonedb.com/download) to determine historical gmt offset given a timezone id and a date. 

Does Nodetime include the same historical gmt offest data based on timezone/date?

I am currently using the following code, but I want to confirm Nodatime handles the historical offset:

    public static TimeSpan NodaTimezoneOffset(string timezoneId, DateTime dateTimeLocal)
    {
            IDateTimeZoneProvider timeZoneProvider = DateTimeZoneProviders.Tzdb;
            var timezone = timeZoneProvider[timezoneId];
            DateTime utc = NodaLocaltoUTC(timezoneId, dateTimeLocal);
            Instant instant = Instant.FromDateTimeUtc(utc);
            return timezone.GetUtcOffset(instant).ToTimeSpan();
    }
    public static DateTime NodaLocaltoUTC(string timezoneId, DateTime dateTimeLocal)
    {
            IDateTimeZoneProvider timeZoneProvider = DateTimeZoneProviders.Tzdb;
            var timezone = timeZoneProvider[timezoneId];
            return NodaLocaltoUTC(timezone, dateTimeLocal);
    }

**Comment by efreeman518** [comment]
public static DateTime NodaLocaltoUTC(string timezoneId, DateTime dateTimeLocal)
    {
            IDateTimeZoneProvider timeZoneProvider = DateTimeZoneProviders.Tzdb;
            var timezone = timeZoneProvider[timezoneId];
            return NodaLocaltoUTC(timezone, dateTimeLocal);
    }
    public static DateTime NodaLocaltoUTC(DateTimeZone timezone, DateTime dateTimeLocal)
    {
            LocalDateTime localDateTime = LocalDateTime.FromDateTime(dateTimeLocal);
            var zonedDbDateTime = timezone.AtLeniently(localDateTime);
            return zonedDbDateTime.ToDateTimeUtc();
    }

**Comment by jskeet** [comment]
On 5 June 2015 at 01:36, efreeman518 <notifications@github.com> wrote:

> Currently using data (from http://timezonedb.com/download) to determine
> historical gmt offset given a timezone id and a date.
>
> Does Nodetime include the same historical gmt offest data based on
> timezone/date?
>
Yes. It looks like timezonedb <http://timezonedb.com/about> is just a
reprocessed form of the IANA database <http://www.iana.org/time-zones>,
which Noda Time supports natively.

The big difference between timezonedb as just a CSV file and Noda Time is
that Noda Time understands the *rules* - so it can go arbitrarily far into
the future, too. timezonedb appears to stop at 2038 - and also only goes
back to 1901, judging by a few samples.

Your samples show using Noda Time just as a bridge while using the BCL
types elsewhere in your code. While you obviously *can* use Noda Time like
that, I'd strongly encourage you to use it more widely, as your "de facto"
set of time types - only use the BCL types where you really have to.
Hopefully your code will be a lot clearer that way.

Jon
