### ISSUE TITLE
Instant conversion to seconds/milliseconds since Unix epoch

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#371]
This should be easier than it is. Unclear whether they should be properties (like Nanoseconds and Ticks) or methods (ToSecondsSinceUnixEpoch and ToMillisecondsSinceUnixEpoch).

**Comment by malcolmr** [comment]
Alternative: {To,From}DurationSinceUnixEpoch(), as that's essentially how From{Seconds,Milliseconds,Ticks}SinceUnixEpoch() is implemented already.

**Comment by jskeet** [comment]
We have TimeSinceEpoch already as an internal property - if we have a public one as well, we should remove that internal one.

It's slightly tricky as from a Duration you can get TotalMinutes, TotalSeconds etc - but they're all `double` values.

I think seconds and milliseconds are special here, due to Unix and Java/Javascript representations.

On a side note, Instant.PlusTicks looks a bit specious in a nanosecond-based world... we should probably find every member of our public API containing "tick" in the name, and evaluate it. We may want to keep some to preserve backward-compatibility - we'll need to decide where the bar is. (We *can* break back-compat, but we shouldn't do so lightly.)

**Comment by jskeet** [comment]
.NET 4.6 has added methods to DateTimeOffset:

- static DateTimeOffset FromUnixTimeSeconds(long seconds)
- static DateTimeOffset FromUnixTimeMilliseconds(long milliseconds)
- long DateTimeOffset.ToUnixTimeSeconds()
- long DateTimeOffset.ToUnixTimeMilliseconds()

Maybe we should just fit in with that?

**Comment by ericburcham** [comment]
We have a specific need for this on a project I'm working on for a client.  I'll be implementing it *somewhere* anyway.  With a little guidance, I'll take a swing at doing it on a fork and sending a pull request.

I like the idea of following the DateTimeOffset convention, since there now is one, but I'm happy to implement whatever public surface area you like.

**Comment by jskeet** [comment]
Yes, I suspect following the .NET naming will be the right approach - but I would expect this to only go on the Noda Time 2.0 branch which won't be available for a while... so I suspect you'll need to reimplement it for your project anyway. Will have to investigate what .NET does about rounding - will probably implement something compatible.

**Comment by ericburcham** [comment]
So leave it alone for the time being :)

I'll watch this issue.  If you get around to "ready to develop" on this one, and are too busy working on higher priority stuff, I'll jump in.  I will have learned a bit about the rough edges by that time.  Thanks!

**Comment by jskeet** [comment]
I think it'll be relatively trivial to implement when I get round to it - but that will only be in 2.0... if you need it for 1.x, you might as well implement it (the bits you need) now. If you don't care how instants before 1970 are rounded, that can be as simple as:

```csharp
public static long ToUnixTimeSeconds(this Instant instant)
{
    return instant.Ticks / NodaConstants.TicksPerSecond;
}

public static long ToUnixTimeMilliseconds(this Instant instant)
{
    return instant.Ticks / NodaConstants.TicksPerMillisecond;
}
```

Then when 2.0 comes out and you adopt it, you should just be able to remove the extension methods and recompile :)

**Comment by jskeet** [comment]
Implementing this now for 2.0. Not clear whether we should *also* change the Ticks property to be a method, and FromTIcksSinceUnixEpoch to FromUnixTimeTicks. Any suggestions?

**Comment by malcolmr** [comment]
Having both `FromUnixTimeMilliseconds()` and `FromTIcksSinceUnixEpoch()` seems a bit weird. I'd suggest renaming the latter to `FromUnixTimeTIcks()` as well.

Not sure whether Ticks should be a method; that seems like a separate question.

**Comment by jskeet** [comment]
Done.
