### ISSUE TITLE
Consider all target platforms and dependencies for 2.0.

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#372]
Related to issue #329.

With .NET Core on the horizon, it would seem foolish not to support that. The details of exactly how that should be supported are still changing (or at least being revealed), but NodaTime-2.0.0-alpha20150728 supports it. However, this meant significant changes:

- Json.NET was updated to 7.0.1 (as that supports the same profile)
- Our PCL target has changed quite a bit, and probably doesn't support everything that 1.3.1 did

I'm *hoping* there'll be a way of supporting .NET Core without updating Json.NET quite as far - although "New feature - Added JsonDictionaryContract.DictionaryKeyResolver" suggests that we might be able to fix or just close issue #237 if we do.

It will partly depend on when we release, of course. I suspect there's still another 3-6 months of work on 2.0, by the time we've looked at serialization, revisited bits of the API around time zones etc.

**Comment by mj1856** [comment]
Highly relevant:  http://oren.codes/2015/07/29/targeting-net-core/

**Comment by jskeet** [comment]
Thanks. Not *entirely* sure where all of that leaves us - I need to read through it a few more times, I think. (IMO, MS still has a way to go in streamlining PCL development.)

**Comment by onovotny** [comment]
From what I can see, your current PCL targets .net 4 and SL5 in addition to windows 8. That PCL won't work on .NET Core-based runtimes like .NET Native or CoreCLR.

There are really two options here:
1. Drop .NET 4 and SL5 and support a minimum of net45. This will give you a PCL that will work. 
2. Create a new csproj PCL project using VS 2015 with the UWP tools installed. Select .NET 4.6, Windows Universal 10 and ASPNet 5 as the targets. The resulting PCL project will reference the new .NET Core packages. You can use shared projects or linked files to include all of your existing source files. 

After either of those options, you just need to put an additional copy in `\lib\dotnet` and add the nuspec dependencies to the BCL packages. Adding a reference to my tool, NuSpec.ReferenceGenerator, to your PCL project will do that for you automatically.

**Comment by jskeet** [comment]
Right - the first option is what I believe I've implemented in the Profile259 branch. It's not clear to me whether that means we *have* to update the Json.NET dependency to 7.0.1 or not, although it's probably okay to do so anyway.

**Comment by onovotny** [comment]
That's a tough one. Json.net doesn't currently have a package that lists the correct dependencies either. There's an open issue for that here: https://github.com/JamesNK/Newtonsoft.Json/issues/618. Even the 7.0.1 package is incorrect w.r.t. DNX.

**Comment by jskeet** [comment]
Great - will watch that issue, given that I've previously been just using what Json.NET does as a template :)

**Comment by jskeet** [comment]
Also relevant:
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md

**Comment by onovotny** [comment]
Happy to help you you'd like, just lmk

**Comment by jskeet** [comment]
@onovotny: We're now targeting netstandard1.1 and net45. Is there any benefit in *also* targeting the portable-*, for the sake of people who haven't updated their Nuget clients yet? I'd personally prefer not to, but I thought it worth asking :)

**Comment by onovotny** [comment]
My personal opinion is nope. The only reason to keep using `portable-` is for PCL's "lower" than netstandard1.0, like 328 with net4 and sl5....both of which should go away in my book :)

I'm faily sure this is a short-term issue best solved by having people update to the latest NuGet client for continued support.

**Comment by jskeet** [comment]
That's my view too. In that case, I think we're done here :)
