### ISSUE TITLE
Reconsider year / year-of-era in format patterns

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#374]
It seems that the BCL Calendar.GetYear reports the year of era - and this is also what's used for "y" in a year format. We may want to swap the meaning of "y" and "Y" for Noda Time 2.0 to be in line with this - although I can see it being quite confusing.

There are relatively few calendars with multiple eras, mind you - in the BCL it's just Japanese as far as I'm aware (which we don't support) but Noda Time supports BC/AD in Gregorian/Julian calendars.

(Oh, and for some reason "yyyy" doesn't always mean "4 digits" in the BCL - it sometimes formats to only 2, which is weird. More investigation required.)

**Comment by jskeet** [comment]
Note that there'd probably be a slight performance hit in making "y" mean "year-of-era" - we may need to optimize that a bit more heavily than we currently do.

**Comment by jskeet** [comment]
Looking at http://unicode.org/reports/tr35/tr35-dates.html#Date_Format_Patterns that has:

- y: year - looks like it means "year of era"
- Y: week-year (which we don't support at all in text formatting, but possibly should)
- u: "extended year" this looks like our absolute year
- U: cyclic year name - we don't support, nor are likely to
- r: related Gregorian year - unsupported, but we could support if we wanted to

If we're going to break this for 2.0, I'm tempted to break it to be more in line with TR-35 (which is still BCL-compatible)

**Comment by jskeet** [comment]
Urgh, this also affects our ISO formats etc - should we use "uuuu-MM-dd"?

**Comment by mj1856** [comment]
For clarity, could you give an example of where `yyyy` and `uuuu` would be different?

**Comment by jskeet** [comment]
The simplest example would be for BC dates.

June 21st, 5BC:

yyyy-MM-dd => 0005-06-21
uuuu-MM-dd => -0004-06-21 (note the sign)

None of our other calendars have multiple eras, so even though in theory this is a massively-breaking change, I don't think it will actually affect most people.

**Comment by mj1856** [comment]
I'm good with that.  Thanks for the example.

**Comment by jskeet** [comment]
Looking at TR-35 again, we're actually divergent from it in a number of other ways, such as ddd meaning abbreviated day name (instead of E) so possibly we *should* just be switching Y and y, effectively. I've written most of the code for this now - it's just a matter of chasing a couple more tests, and deciding for sure what we want to do (and writing the docs).

One unanticipated downside is that all our ISO patterns now use "u" instead of "y" in order to roundtrip BC dates. However, the BCL default patterns all use y - so writing out Instant.MinValue for example, you end up with 01/01/9999 or the equivalent, which is a sucky debugging experience. (It's in line with what Java does for java.util.Date, mind you, and I don't remember ever encountering *that* particular issue being a problem there.)

**Comment by jskeet** [comment]
`Instant.MinValue` isn't actually a problem - I had failed to convert one constant to use "uuuu".
