### ISSUE TITLE
Support for culture sensitive date/time in ZoneDateTimePattern for formatting

### ISSUE THREAD

**Issue by aleung61** [nodatime/nodatime#375]
http://stackoverflow.com/questions/31792508/with-nodatime-how-do-i-format-a-zoneddatetime-in-current-culture

I have a `ZonedDateTime` and I want to display it such that the datetime is formatted with the short date and short time configured on the workstation followed by the offset (something like... 05/01/2005 02:30 PM -05:00). I expected something like this would work...

```csharp
var patternDateTimeOffset = ZonedDateTimePattern.CreateWithCurrentCulture("g o<m>", DateTimeZoneProviders.Tzdb);
lblOriginalDateTimeAndOffsetVal.Text = patternDateTimeOffset.Format(zonedDateTime);
```

BUT, it appears that the "g" is not supported in `ZonedDateTimePattern` the way it is in `LocalDateTimePattern`. The code above throws a `NodaTime.Text.InvalidPatternException`.

I could replace the "g" with "MM/dd/yyyy hh:mm", but then it's not using the current culture.

I could use a `LocalDateTimePattern` for the datetime and then concatenate the offset using the `ZonedDateTimePattern`. This works, but seems ugly.

This seems like a pretty common thing. I'm new to NodaTime, so I'm certain I'm missing something. I'm using NodaTime 1.3.1 and targeting .net 4.0. Any help is appreciated.

**Comment by jskeet** [comment]
Thanks for raising this. You're definitely not missing anything, but I'm not sure what the best alternative is.

It's possible that we should have another specifier for "local part" like we do for offset, so you could have `l<g> o<m>` as a specifier, for example. Would need to think about that, both in terms of design and implementation. Hmm.

**Comment by jskeet** [comment]
Thinking about it a bit more, I believe we should be able to manage `l<g>`... we could *potentially* even manage splitting it into date and time parts, so you could write something like `ld<d> o<m> lt<T>` to get a short date pattern, medium offset followed by long time... but we'll see.

We may need to assume that the pattern is responsible for *all* of the appropriate fields - it's currently tricky (in terms of abstraction) to work out which fields the embedded pattern would handle.

I'm not quite sure how this is going to work out in terms of the "bucket" implementation parts, but I'm sure it must be feasible...
