### ISSUE TITLE
Investigate use of abbreviated genitive month names

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#377]
The BCL doesn't use abbreviated genitive month names, for some reason.

Sample code (no Noda Time involved...)

``` csharp
using System;
using System.Globalization;
using System.Linq;

class Test
{
    static void Main()
    {
        var culture = (CultureInfo) CultureInfo.InvariantCulture.Clone();

        culture.DateTimeFormat.AbbreviatedMonthGenitiveNames
            = culture.DateTimeFormat.AbbreviatedMonthNames
                     .Select(x => "Gen" + x)
                     .ToArray();
        culture.DateTimeFormat.MonthGenitiveNames
            = culture.DateTimeFormat.MonthNames
                     .Select(x => "Gen" + x)
                     .ToArray();

        Console.WriteLine(new DateTime(1976, 6, 19).ToString("d MMMM yy", culture));
        Console.WriteLine(new DateTime(1976, 6, 19).ToString("MMMM yy", culture));
        Console.WriteLine(new DateTime(1976, 6, 19).ToString("d MMM yy", culture));
        Console.WriteLine(new DateTime(1976, 6, 19).ToString("MMM yy", culture));
    }
}
```

Expected output:

```
19 GenJune 76
June 76
19 GenJun 76
Jun 76
```

Actual output:

```
19 GenJune 76
June 76
19 Jun 76
Jun 76
```

I haven't found any way of "persuading" the BCL to use the abbreviated genitive names yet. This makes some Noda Time tests fail in cultures which use abbreviated month names in standard patterns. (Notably, Kyrgyzstan under Windows 10.)

For now, I'll simply suppress those particular tests as they _look_ like Noda Time's doing the right thing. It would be nice to understand this better though.

**Comment by javiercampos** [comment]
In http://referencesource.microsoft.com/#mscorlib/system/globalization/datetimeformat.cs,578 we see:

    if ((dtfi.FormatFlags & DateTimeFormatFlags.UseGenitiveMonth) != 0 
                  && tokenLen >= 4) {
            result.Append(
                 dtfi.internalGetMonthName(
                        month, 
                        IsUseGenitiveForm(format, i, tokenLen, 'd')? MonthNameStyles.Genitive : MonthNameStyles.Regular, 
                        false));

Which, I haven't overseen anything, should be (commented the changes):

    if ((dtfi.FormatFlags & DateTimeFormatFlags.UseGenitiveMonth) != 0 
                  && tokenLen >= 3 /* Work for MMM and MMMM */ ) {
            result.Append(
                 dtfi.internalGetMonthName(
                        month, 
                        IsUseGenitiveForm(format, i, tokenLen, 'd')? MonthNameStyles.Genitive : MonthNameStyles.Regular, 
                        tokenLen == 3 /* Abbreviated if MMM */));

Can't test it, but it makes sense to me. Might be worth issuing a bug on connect?

**Comment by jskeet** [comment]
Or on github on the relevant corefx bit, I guess.

The problem is, I don't really know enough about the domain to know whether this *is* a bug. Still, it couldn't hurt to raise it as an issue, I guess. Thanks for digging!

**Comment by javiercampos** [comment]
I don't think the code for Globalization (other than the tests) is already uploaded on corefx, but I haven't really digged there, to be honest

**Comment by malcolmr** [comment]
Not sure there's anything further to do here? (The upstream bug doesn't appear to be getting much traction, and we believe that we're behaving reasonably.)

**Comment by jskeet** [comment]
Agreed, closing as wontfix.

**Comment by jskeet** [comment]
Oddly enough, it does look like it uses genitive month names for year/month patterns, even though in that case I really don't think it should.
I'll stick to our behaviour (which no-one has ever complained about) and skip tests which would fail for YearMonth.
