### ISSUE TITLE
Consider using Sphinx for documentation and hosting it in readthedocs.org

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#378]
Looks like we can co-host versioned API and conceptual documentation, e.g. http://agate.readthedocs.org/en/0.6.0/

Projects to build .NET documentation with Sphinx:
- http://vicancy.github.io/docascode/#/tutorial/docfx_getting_started.md
- https://github.com/rtfd/sphinx-autoapi

**Comment by jskeet** [comment]
Note that we could use readthedocs to generate the help without using readthedocs.org, although the latter is probably a better idea. We'd need to think about what nodatime.org needed to do at that point, of course.

**Comment by jskeet** [comment]
Another repo to watch/investigate: https://github.com/dotnet/docfx

Will see how easily I can get up and running with it.

**Comment by malcolmr** [comment]
Close (like #343) and open a new issue for docfx?
