### ISSUE TITLE
Make DateInterval IEquatable

### ISSUE THREAD

**Issue by SurajGupta** [nodatime/nodatime#380]
This is a feature request to make DateInterval implement IEquatable

**Comment by malcolmr** [comment]
Hm, I wonder, should [2015-01-01, 2015-02-01) == [2015-01-01, 2015-01-31]?

Probably not: while they cover the same range of dates, they're not equivalent (they return a different value for the `Inclusive` property).

**Comment by SurajGupta** [comment]
good question!  I think this is a matter of whether equivalence is based on outcome or how the outcome is expressed.  For example, is 5-2 equivalent to 6-3?  The way these are expressed are not equivalent, but the outcome is (using the vacation analogy, "I'm out jan 1 and back in the office feb 1" versus "I'm out jan 1 thru jan 31st")

My knee jerk reaction was that they should be equivalent because they cover the same date range.  In practice, I would guess that a majority of consumers will operate entirely in a single mode - inclusive or exclusive.  If you are operating in mixed-mode, I would think that the outcome is more important than how it is expressed, from an equivalence POV.

**Comment by malcolmr** [comment]
I think it'd be a bit odd to consider two `DateInterval` values with different `End` dates to be equivalent.

Then again, `DateInterval` is new in 2.0; perhaps it's worth considering whether we should be canonicalising on creation, rather than emulating two slightly different types via a boolean.

**Comment by jskeet** [comment]
I would rather not canonicalize them, as that would basically be making the decision on behalf of the API consumers - whereas I think it's quite reasonable to represent "all of September" as "September 1st inclusive to October 1st exclusive" and "Monday to Friday" as an inclusive range.

I think it makes sense to have the default equality comparison be "naive", but expose an IEqualityComparer which *does* canonicalize.

**Comment by malcolmr** [comment]
Okay, that sounds reasonable. #381 does the first; I'm happy for someone else (or me, just not right now) to pick up the second.

**Comment by malcolmr** [comment]
Added #383 for adding a canonicalising IEqualityComparer.

**Comment by SurajGupta** [comment]
thanks for the quick turnaround on this!
