### ISSUE TITLE
Document complexity of period calculations

### ISSUE THREAD

**Issue by breyed** [nodatime/nodatime#382]
Does `Period.Between`, when called with `PeriodUnits.Days`, take time linear with the number of days returned? Or is it a constant time operation, even for thousands of days? Or some other complexity? Likewise for months and other periods. It would be useful to have this documented.

Sample use case: I need an array of values spanning some range of periods (months, days, etc.). I'll be filling in the array by walking though each period in the range. Should I preallocate the array, or just use a `List` and let it reallocate-expand?

**Comment by jskeet** [comment]
It very much depends on the units you're asking for and the calendar in question. I didn't really follow your example, but in general period arithmetic is very heavily optimized - it's certainly not linear with the number of days returned.

I *think* it would be safe to say it's constant time, but I'd have to double-check everything that the period code does and what all the calendar implementations do... it's not a simple matter.

**Comment by breyed** [comment]
To elaborate on the example, consider a method like this, which gets time-series data rolled up by minute, hour, day, or month:

    int[] GetValues(PeriodUnits units, LocalDateTime start, LocalDateTime end) {
        var values = new List<int>();
        // TODO: For each period from start to end, add a value to values.
        return values.ToArray();
    }

The potential optimization is to replace the `List<int>` with `int[]`.

**Comment by jskeet** [comment]
So you're talking about the cost of a single call to `Period.Between` in order to preallocate the array? Personally I'd just use the list approach until I'd found that it was causing a bottleneck, especially given the weirdnesses you can get with periods... (In order to populate the array, you'd still need to work out an appropriate `Period` to add on each iteration, of course.)

**Comment by breyed** [comment]
Yes, I was wondering if calling `Period.Between` would decrease allocation time from O(log(n)) to O(1)? Population is O(n) anyway, so the overall complexity of the method doesn't change; hence, naive allocation is not likely to be a bottleneck. OTOH, knocking down time complexity is generally a worthwhile gt-micro-optimization (depends on the size of *n* of course). Figured I'd check if there was an easy answer available. Sounds like there isn't, which is understandable.
