### ISSUE TITLE
Add an IEqualityComparer for DateInterval that canonicalises

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime#383]
Split out from #380, in which @jskeet says:

> I think it makes sense to have the default equality comparison be "naive", but expose an IEqualityComparer which does canonicalize.

In other words, while the innate equality comparison considers the range [2001-01-01, 2001-01-31] to be distinct from [2001-01-01, 2001-02-01), this one would consider them equivalent.

(Note that we should handle ranges covering minimum and maximum dates, which may mean that this isn't as simple as canonicalising the range.)

One open question: are empty intervals — e.g. [2001-01-01, 2001-01-01), [2001-02-01, 2001-02-01) — all equivalent? They cover the same set of dates (i.e. none), but have different start dates.

**Comment by jskeet** [comment]
Re empty intervals: https://www.youtube.com/watch?v=vgk-lA12FBk

(Seriously, I can imagine either having two properties, or a method with an optional parameter for whether to treat empty intervals as equal or not.)
