### ISSUE TITLE
NodaTime conflicts with Intenso.TimePeriod of .net TimePeriod Library

### ISSUE THREAD

**Issue by dizzleuk** [nodatime/nodatime#396]
http://www.codeproject.com/Articles/168662/Time-Period-Library-for-NET

There appears to be a conflict between NodaTime and the Time Period Library above. 
The conflict ive spotted is the SystemClock class has the same name in both libraries.

Regards
Dizzle

**Comment by jskeet** [comment]
So use a using alias, e.g.

```csharp
using SystemClock = NodaTime.SystemClock;
```

I really don't see that as a problem. I'm certainly not going to try to guarantee that the short name of each Noda Time type is globally unique. That's why we have namespaces, after all.
