### ISSUE TITLE
Non-Canonical Id in TzdbDateTimeZoneSource.Default.WindowsMapping.MapZones

### ISSUE THREAD

**Issue by Eibwen** [nodatime/nodatime#398]
Discovered this issue because "Asia/Kolkata" is not in the WindowsMapping, but "Asia/Calcutta" is, but everywhere else in NodaTime "Asia/Calcutta" is the canonical id.

The issue is that if you use CanonicalIds and map them to Windows TimeZones using `TzdbDateTimeZoneSource.Default.WindowsMapping.MapZones` there will be errors.

TzDB identifiers in WindowsMapping, which do NOT have their canonicalId in WindowsMapping!:

```
TzdbId_InWindowsMapping     TzCanonicalId
-----------------------     -------------
America/Coral_Harbour       America/Atikokan
America/Louisville          America/Kentucky/Louisville
America/Indianapolis        America/Indiana/Indianapolis
America/Buenos_Aires        America/Argentina/Buenos_Aires
America/Catamarca           America/Argentina/Catamarca
America/Cordoba             America/Argentina/Cordoba
America/Jujuy               America/Argentina/Jujuy
America/Mendoza             America/Argentina/Mendoza
Atlantic/Faeroe             Atlantic/Faroe
Asia/Calcutta               Asia/Kolkata
Asia/Katmandu               Asia/Kathmandu
Asia/Saigon                 Asia/Ho_Chi_Minh
Pacific/Truk                Pacific/Chuuk
Pacific/Ponape              Pacific/Pohnpei
```

Used this LinqPad script to generate that: http://share.linqpad.net/3t6w4k.linq  Using NodaTime 1.3.1 from Nuget.

**Comment by jskeet** [comment]
Hmm. The problem is that these are the identifiers used in CLDR. Are you suggesting we just map them to the canonical ID when constructing the nzd file? That would certainly be fairly easy to do (I think!).

**Comment by mj1856** [comment]
The general issue is that CLDR and TZDB have different definitions of "canonical".

- In TZDB, the canonical zone is one with a `Zone` entry, while those with `Link` entries are non-canonical.

 - TZDB canonical zones can change with each release of TZDB. The canonical zone is the *current* prefered zone identifier.

- In CLDR, the canonical zone is the one that is *first* in the space-delimited array found in the `alias` property of a `/ldblBCP47/keyword/key[@name='tz']/type` entry from the [`bcp47/timezone.xml`](http://www.unicode.org/repos/cldr/trunk/common/bcp47/timezone.xml) file.

  - CLDR canonical zones cannot ever change. Once they are established, they are the "stable identifier" used throughout the rest of the data set.

  - When any TZDB identifier is added to the CLDR, it's appended to any existing associated entry if one is defined, or a new entry is created if it was not already defined.

The question then is, what is Noda Time's `MapZone` intending to reflect?  Is it the raw CLDR data, or is it adjusted to reflect the TZDB notion of canonical?

**Comment by mj1856** [comment]
@Eibwen - Also, does [this logic](http://stackoverflow.com/a/17348822/634824) help you?

**Comment by Eibwen** [comment]
@mj1856, Yes that is one solution to the issue I was having, thanks.  Fairly similar to what i wrote as a work around after discovering it

**Comment by malcolmr** [comment]
(This is a bug, but we're not sure whether it's a documentation bug or implementation bug.)

**Comment by jskeet** [comment]
Okay, so I've looked at this again, and I think the code is okay. The `WindowsZones` class accurately represents what's in CLDR. Given a `TzdbDateTimeZoneSource`, if you want to get a *canonical* TZDB ID from a Windows ID, you just need

```csharp
string tzdbId = source.WindowsMapping.PrimaryMapping[windowsId];
string canonicalId = source.CanonicalIdMap[tzdbId];
```

It's *reasonably* unusual to require this, I believe - so I don't think we need to make it any simpler to do in the API. I will add a note in the `PrimaryMapping` documentation that the returned ID may not be a canonical ID. Does that sound reasonable?

**Comment by jskeet** [comment]
@mj1856: Comments on proposal? Would like to get this issue "done" if possible...

**Comment by mj1856** [comment]
Lgtm.  Thanks!

**Comment by brettpostin** [comment]
@jskeet @mj1856 how would you handle the other way around i.e. get a Windows ID from a canonical tzdb ID when it does not exist in the CLDR?

Example: Asia/Ho_Chi_Minh which is Asia/Saigon in CLDR.

**Comment by jskeet** [comment]
@mj1856: I think it would make sense to check aliases. (I haven't looked at the data here, but I'm assuming that Asia/Saigon is an alias for Asia/Ho_Chi_Minh in TZDB.) I've no idea what the code I wrote ~1 year ago does on that front though. It *may* just work...

**Comment by brettpostin** [comment]
#1393 is exactly what I was looking for thanks.
