### ISSUE TITLE
LocalDate.InZone missing?

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#399]
I could have sworn there was a way of finding out when a particular date started in a time zone, but I can't find it now. Hopefully I'm just failing to find the relevant documentation, but if not, we should at it. (Quite possibly as LocalDate.InZone and DateTimeZone.AtStartOfDay.)

**Comment by malcolmr** [comment]
How about `localDate.AtMidnight().InZoneLeniently(zone)`? Or did you want something else?

**Comment by malcolmr** [comment]
Actually I'm not sure that works in 2.0 due to the way that `InZoneLeniently()` now works; you'd need `InZone(zone, resolver)` using a resolver with the old 1.x behaviour.

**Comment by mj1856** [comment]
We already have a [`DateTimeZone.AtStartOfDay`](http://nodatime.org/1.3.x/api/html/M_NodaTime_DateTimeZone_AtStartOfDay.htm) instance method.

```csharp
LocalDate ld = new LocalDate(2015, 10, 18);
DateTimeZone tz = DateTimeZoneProviders.Tzdb["America/Sao_Paulo"];
ZonedDateTime zdt = tz.AtStartOfDay(ld); // "2015-10-18T01:00:00 America/Sao_Paulo (-02)"
```

It might be nice to invert it and put it on `LocalDate` also.  I don't think resolvers are useful here, as we're not starting with any local time.

**Comment by jskeet** [comment]
Thanks for finding it... I think I was looking in ZonedDateTime for no
obvious reason. But yes, we should put it in LocalDate too.
