### ISSUE TITLE
Duration should be divisible by Duration

### ISSUE THREAD

**Issue by filmor** [nodatime/nodatime#404]
`Duration` objects have all the same dimension so dividing them would lead to a unit-less `float`. This makes it easy to find out "duration in hours" or "duration in days" by just writing `duration / Duration.FroumHours(1)` and `duration / Duration.FromDays(1)` respectively. If this is deemed useful I can prepare a PR for this change.

**Comment by jskeet** [comment]
For 2.0, there are already TotalHours, TotalDays etc. That doesn't mean we *can't* implement division (returing a double) but it removes that particular use case. Do you find it useful for other reasons?

**Comment by filmor** [comment]
It's much more generic. For example we have to count quarter hours and half hours quite often. Sure, this is possible with something like `d.TotalMinutes() / 15.0` but I think `d / Duration.FromMinutes(15)` is nicer "dimensionally". Also, check the `Align` function that I attached to #379. I don't think you would need to expose `Ticks` on `Duration` anymore.

**Comment by jskeet** [comment]
Well, we still want to expose Ticks anyway - or something similar, although now possibly TotalTicks and SubsecondTicks. But yes, that sounds basically reasonable. The simplest implementation would be to just `return (double) d1.ToDecimalNanoseconds() / (double) d2.ToDecimalNanoseconds()` but we may want to do better than that...

**Comment by jskeet** [comment]
Out of interest, would you be looking for a corresponding `Duration op*(Duration, double)` operator? Would kinda make sense...

**Comment by filmor** [comment]
Sure, if just for symmetry. Regarding the implementation, what do you have in mind for a better implementation?

**Comment by jskeet** [comment]
Well, there are various common situations which don't require going via ToDecimal to do the arithmetic. I've started looking at this now.
