### ISSUE TITLE
JSON deserialization shound't fail on Date TokenType

### ISSUE THREAD

**Issue by tugberkugurlu** [nodatime/nodatime#406]
[NodaTime JSON deserialization requires the `TokenType` to be string](https://github.com/nodatime/nodatime/blob/d3a08dd991e0ba1ae535f422489ee64df314f86a/src/NodaTime.Serialization.JsonNet/NodaPatternConverter.cs#L57-L66). However, JSON.NET by default parses the date values and flows them as Date token rather than string. 

## Repro

```csharp
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using NodaTime;
using NodaTime.Serialization.JsonNet;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NodaTimeJson
{
    class Program
    {
        static void Main(string[] args)
        {
            var json = GetContent();
            var serializerSettings = new JsonSerializerSettings();
            serializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
            serializerSettings.Converters.Add(NodaConverters.InstantConverter);
            
            var trip = JsonConvert.DeserializeObject<TripCreationModel>(json, serializerSettings);
        }

        private static string GetContent()
        {
            using (var stream = File.OpenRead(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "file.json")))
            using (var reader = new StreamReader(stream))
            {
                return reader.ReadToEnd();
            }
        }

        public class TripCreationModel
        {
            public string Name { get; set; }
            public Instant StartedAt { get; set; }
            public Instant EndedAt { get; set; }
        }
    }
}
```

You need to install `NodaTime.Serialization.JsonNet` 1.3.1 NuGet package and `file.json` has the below content:

```csharp
{
  "name": "Foo",
  "startedAt": "2015-11-14T12:27:17.389Z",
  "endedAt": "2015-11-14T12:27:45.206Z"
}
```

You will get the below error when you run this:

I got the below error from `JsonConvert.DeserializeObject<T>`:

> An unhandled exception of type 'NodaTime.Utility.InvalidNodaDataException' occurred in Newtonsoft.Json.dll

> Additional information: Unexpected token parsing Instant. Expected String, got Date.

Setting `serializerSettings.DateParseHandling` above to `DateParseHandling.None` solves the problem.

**Comment by jskeet** [comment]
This is already documented in the user guide (http://nodatime.org/1.3.x/userguide/serialization.html) and the `ConfigureForNodaTime` extension method does it automatically.

That's all we can do.

**Comment by tugberkugurlu** [comment]
@jskeet thanks, that makes sense.
