### ISSUE TITLE
Reconsider week calendars

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#408]
Currently we have a situation where only the ISO calendar can be configured in terms of "minimum number of days in the first week of the week-year" and that's still fairly restrictive. The BCL allows you to specify a first-day-of-week and a week rule - although it doesn't have anything which exactly meets ISO-8601.

Perhaps instead of WeekYear and WeekOfWeekYear being properties, they should be methods which accept either a `WeekYearCalculator` or options as parameters? Then we can just have _one_ ISO calendar, and provide flexibility for _all_ calendars. Note that this would also potentially affect text parsing/formatting, and construction from week/week-year.

(We need to decide this before 2.0, as it's a breaking change.)

**Comment by mj1856** [comment]
I agree that it should be a method with a parameter instead of a property.  However, I think instead of an enum like BCL's `CalendarWeekRule`, it should accept a delegate.  This would be similar to how we pass resolvers to `InZone`.

**Comment by jskeet** [comment]
What would the delegate accept? If it's just a `Func<LocalDate, int>` (or similar) then having the delegate means we don't need the method... whereas the resolvers are picked and invoked appropriately only when necessary. Maybe that really *is* all we need - expose appropriate delegate implementations and be done. I was considering an interface though, which effectively exposed some bits of the `WeekYearCalculator`. Maybe I should noodle on that idea and see what it looks like (as a PR straw man).

**Comment by jskeet** [comment]
This is effectively done by removing the properties from LocalDate entirely; instead we have dates on WeekYearRule.
