### ISSUE TITLE
Consider using DNX-based projects for v2

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#409]
Rather than the traditional msbuild-based projects, we could potentially use DNX (project.json) for Noda Time v2. It's probably not worth doing for the 1.x branches, but for v2, it would mean:

- *Potentially* no need for build-changing tools for different environments
- The ability for contributors to work in VS Code
- The ability to build on Linux (e.g. for Travis) with the same toolchain as on Windows
- Possibly a bit less guesswork about requirements for nuspec - it would all be in the project file

Downsides:
- VS support is currently slightly hit-and-miss (I sometimes need to drop down to the command line to run dnu restore)
- Whole toolchain is still pre-v1 - but will probably reach v1 before v2 is released
- (Possibly the biggest blocker) NUnit support for DNX projects isn't really ready yet, whether that's in NUnit itself or in the test runners such as NCrunch, R# and CodeRush

cc @malcolmr @mj1856 for thoughts

**Comment by malcolmr** [comment]
Absent any real information, sounds like a fairly good idea to me, if it works.

Would it handle the dual PCL/non-PCL builds we do?

**Comment by jskeet** [comment]
I believe so. You definitely tell the project.json which versions to build, and each can have different references and #defines, I believe.

I don't think it will support our current 3.5 target though - we might need to only support 4.0+, which we'd been considering anyway.

I'll spike it in a separate branch, and we can see how it goes.

**Comment by jskeet** [comment]
And the current answer is: I'm failing (badly) to refer to anything around System.Xml in a DNX project. I'll wait for VS 2015 update 1 and DNX RC2 and see if they help...

**Comment by jskeet** [comment]
Okay, I spoke too soon. I've made significant progress. Problems now are:

- A few attributes which are suppressing warnings in code analysis. I think I can just lose those attributes, at least for now.
- Designer code for resources which includes attributes we don't have.
- Designer code using reflection in a way that's not CoreCLR-compatible
- Non-designer code using reflection in a way that's not CoreCLR-compatible. This is fixable.

Not sure what to do about the resource code... I may see what happens if I create a new resources file in a DNX project...

**Comment by jskeet** [comment]
This is now done.
