### ISSUE TITLE
LocalDatePattern.Parse throws IndexOutOfRangeException on some dates that match format but are not real dates

### ISSUE THREAD

**Issue by nicklbailey** [nodatime/nodatime#414]
Given a date string like "00/15/1984" and a local date pattern created with the format "M/d/yyyy", calling format.Parse(dateString) throws an index out of range exception, rather than simply returning a failed ParseResult<LocalDate>. 

We haven't tested other Noda pattern types for the same behavior, but wouldn't be surprised if it's there as well.

**Comment by jskeet** [comment]
Hmmm... I'm getting an ArgumentOutOfRangeException with 2.0, but it's a bug anyway...
Thanks, will try to look at it very soon.

**Comment by nicklbailey** [comment]
Good catch, we were on an older version of Noda (1.3.0.0).

Also good that it was still a bug. and didn't waste anyone's time!

**Comment by jskeet** [comment]
I suspect this one will be worth fixing on the 1.3.x branch as well, to be honest. I haven't looked into it yet, but I'm hoping it'll be very simple.

**Comment by jskeet** [comment]
Okay, found the bug. Single character typo :) Fixing in the 2.0 branch now, will then backport.

**Comment by jskeet** [comment]
Fixed in 1.3.x and 2.0 branches.
