### ISSUE TITLE
Interval.ToString() seems to be broken for Interval.End

### ISSUE THREAD

**Issue by seko111** [nodatime/nodatime#421]
Interval.ToString() subtracts an hour from its End member:

Instant startTime = new ZonedDateTime(new LocalDateTime(2015, 11, 5, 9, 0), DateTimeZoneProviders.Tzdb.GetZoneOrNull("CET"), Offset.FromHours(1)).ToInstant();

Instant endTime = new ZonedDateTime(new LocalDateTime(2015, 11, 5, 17, 0), DateTimeZoneProviders.Tzdb.GetZoneOrNull("CET"), Offset.FromHours(1)).ToInstant();

Interval temp = new Interval(startTime, endTime);

temp.Start.ToString() = "2015-11-05T08:00:00Z"
temp.End.ToString() = "2015-11-05T16:00:00Z"
temp.Duration.ToString() = "0:08:00:00"

So the values are okay, but notice that for End, it printed 16:00, whereas it should've printed 17:00.
I've only experienced this with Interval.End. Start and Duration seem to be fine.

Using NodaTime 1.3.1.

**Comment by jskeet** [comment]
No, you asked for 9am to 5pm in CET in winter, which is 8am to 4pm in UTC - hence the "Z" at the end.

**Comment by seko111** [comment]
totally my bad, just realized it as you typed your comment. sorry.
