### ISSUE TITLE
Question about 2.0.0-alpha20150728

### ISSUE THREAD

**Issue by ioan-hancu** [nodatime/nodatime#422]
As I can see this package also supports CoreClr, I would like to make sure if it supports all the features found in 1.3.1 or if there are any exceptions?

**Comment by jskeet** [comment]
That build was really just to test whether or not it worked for CoreCLR. I don't know how many bugs there are in that particular snapshot - please don't treat it as release quality.

(Broadly speaking 2.0 supports almost all the features of 1.3.1, but they're not compatible with each other - see http://nodatime.org/unstable/userguide/migration-to-2.html for more details.)

In general, questions like this are best asked on the mailing list, as this isn't really a bug that needs to be tracked.
