### ISSUE TITLE
Reconsider BCL TimeZoneInfo support in light of .NET Core

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#434]
Previously we've had:
- Pretty decent support for TimeZoneInfo on Windows desktop
- Some support for TimeZoneInfo on Windows PCL build (but with some guesswork)
- Ropey support for TimeZoneInfo on Mono, particularly TimeZoneInfo.Local

There are some assumptions that we'll always see a Windows time zone name in `TimeZoneInfo.Id`, and we use that as a map. That's already broken in some cases with odd localization, but leaving that aside, it ignores non-Windows platforms, whether running on Mono or DNX.

The two contentious aspects are:
- How well can we wrap TimeZoneInfo in a DateTimeZone?
- How well can we guess an IANA ID from a TimeZoneInfo?

**Comment by jskeet** [comment]
Related to #543. Need to untangle these two.

**Comment by malcolmr** [comment]
ftr, the resolution here was:

- require netstandard1.3, which supports `TimeZoneInfo.Id`.
- use that property, not `StandardName`, to map BCL zones (in practice now, just the local one) to TZDB zones.
- handle BCL zones that have TZDB IDs or unknown IDs (the latter, by guessing, as we did on PCL).
