### ISSUE TITLE
Get number of weeks in Week Year

### ISSUE THREAD

**Issue by maggiepint** [nodatime/nodatime#437]
While coding yesterday, it would have been useful to me to be able to ask how many weeks are in the week year. As far as I can tell, there is no support for just asking NodaTime this, and no super simple way to get it. 
Since 12/31 can fall in week 52,53, or 1, that shortcut is out.

I coded around this, but it would be nice to have the functionality built in. I would make a pull request, but I struggle with finding a place in the API that I think it 'fits'. Maybe CalendarSystem.Iso - but then Iso's properties differ from the rest which is bad.

I can see the calculation in WeekYearCalculator. It would be great if it got exposed. Again, happy to do the work if advised on a place to put it.

**Comment by jskeet** [comment]
Happy to look into it - it's likely to just mean a few methods proxying through the layers. We'd expose it in CalendarSystem, basically. (So you'd use `CalendarSystem.Iso.GetWeekYears(2015)` or whatever... something like that.

I'd initially only implement this in v2.0, which means you're unlikely to be able to use it for a while (unless you're using head from github, which is pretty stable, admittedly...). Let me know if that's an issue.

**Comment by maggiepint** [comment]
No need for it right now. I can always manually compute it.
