### ISSUE TITLE
GuessZoneIdByTransitionsUncached failing for Baja California

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#440]
This may well be due to new time zone data - needs investigating.

**Comment by mj1856** [comment]
'America/Santa_Isabel` turned out to be a mistake, was moved to a link.

**Comment by jskeet** [comment]
@mj1856: The issue is that it can't find *any* appropriate time zones - would that really be explained by Santa Isabel? (I haven't investigated yet...)

**Comment by jskeet** [comment]
Currently, Santa Isabel ends up being the best candidate, with a score of 31/105 - well below the 70% we require.

I note that CLDR has:

```xml
<!-- (UTC-08:00) Baja California -->
<mapZone other="Pacific Standard Time (Mexico)" territory="001" type="America/Santa_Isabel"/>
<mapZone other="Pacific Standard Time (Mexico)" territory="MX" type="America/Santa_Isabel"/>
```

... and that *is* the zone which is failing. (i.e. if we mapped by ID, we'd get the right result from CLDR.)

I've had a look at the mail you (Matt) sent to the IANA list a while ago, and that makes sense... but I'm not sure why it's scoring so badly in the current tests. I'd need to look at the exact BCL transitions... time to dig up my explorer project.

**Comment by mj1856** [comment]
The mapping to `America/Santa_Isabel` *was* correct, until 2016a removed the zone entry and replaced it with a link to `America/Tijuana`.

Windows has not yet deprecated `Pacific Standard Time (Mexico) | (UTC-08:00) Baja California`, so the [CLDR trunk](http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml) currently lists it as "Unmappable".  I expect a future Windows update will set `IsObsolete = 1` on the registry entry, and then a future CLDR will drop it entirely.

Ultimately it comes down to the fact that it was a red-herring to begin with.  Either nobody used it, or if they did use it they did so incorrectly - perhaps without knowing.

**Comment by mj1856** [comment]
Note that it's undetermined as of yet whether `"Pacific Standard Time (Mexico)"` will be deprecated or not.  It may just be that we update it to match the data of `"Pacific Standard Time"`.  We're discussing this now internally, and I'll update you when I know more.

**Comment by jskeet** [comment]
Okay, so can I just check I understand...

The Windows time zone ("Pacific Standard Time (Mexico)") is basically a time zone which no-one observes. America/Santa_Isabel *used* to contain mostly-matching data, but is now just a link to the *different* data in America/Tijuana, so as not to break things that know about that ID, although the data is different.

I could add this to the manual overrides list in Noda Time, to use Santa_Isabel. Would that make sense?

**Comment by mj1856** [comment]
Yes - exactly.  That sounds like a good plan for now.  At some point you may be able to remove it.

**Comment by jskeet** [comment]
Ah - just worked out that my plan won't actually work. If we've *got* the known name, we'll map it to Santa Isabel already. The test that's failing is for cases where the standard name has been localized (which can happen, weirdly) and so we have to guess based on just the data in the `TimeZoneInfo` and in TZDB.

If there's no matching time zone available, I think failing really is the right to do. I'll add an exemption to the tests, basically - with regret :(

**Comment by mj1856** [comment]
The `StandardName` should always be considered localized, even if it happens to be English, it's possible it may or may not match the `Id`.  For example, consider the numbered Russian time zones.  ID = `Russia Time Zone 3`, StandardName = `Russia TZ 3 Standard Time`

**Comment by jskeet** [comment]
Hence https://github.com/nodatime/nodatime/blob/master/src/NodaTime.TzdbCompiler/Tzdb/PclSupport.cs

:)

Basically, for PCLs there's no really reliable way of identifying the time zone, which is an *awful* situation to be in. So we have to guess based on offsets - and that's what fails for this time zone (Baja).

**Comment by mj1856** [comment]
Got it.  Yep, then exemption in the tests for now.
