### ISSUE TITLE
Incorrect behavior of comparison operators overloaded for ZonedDateTime

### ISSUE THREAD

**Issue by roman-polunin-medamerica** [nodatime/nodatime#454]
Version: 1.3.1
NodaTime overloads comparison operators for ZonedDateTime, namely < and >.
Behavior of these operators differs from implementation of .CompareTo, and generally looks like a bug, because this breaks sorting logic.

This test should be failing, however it succeeds:

            Assert.IsFalse(zonedInUtc > zoned);
            Assert.IsFalse(zonedInUtc < zoned);
            Assert.IsFalse(zonedInUtc == zoned);

If NodaTime does not support operator-based comparison for any reason, it should throw NotImplementedException, ArgumentException, or some other Noda-specific exception, instead of generating arbitrary false value.

See complete code below:

    [TestClass]
    public class BehaviorTests
    {
        private static DateTimeZone TimeZoneLosAngeles => DateTimeZoneProviders.Tzdb["America/Los_Angeles"];

        [TestMethod]
        public void DifferentZonesCannotBeComparedWithOperator()
        {
            var zone = TimeZoneLosAngeles;
            var source = LocalDateTime.FromDateTime(DateTime.Now);

            var zoned = source.InZoneLeniently(zone);

            // Comprison to self should always work.
            Assert.IsTrue(zoned.Equals(zoned));
            Assert.AreEqual(0, zoned.CompareTo(zoned));
            // ReSharper disable once EqualExpressionComparison
            Assert.IsTrue(zoned == zoned);
            // ReSharper disable once EqualExpressionComparison
            Assert.IsFalse(zoned < zoned);
            // ReSharper disable once EqualExpressionComparison
            Assert.IsFalse(zoned > zoned);

            var zonedInUtc = source.InZoneLeniently(DateTimeZone.Utc);

            // These must all be false, because time zone is different for these dates
            // and NodaTime 1.3.1 requires time zone to be the same for operator-based comparison.
            // Looks like a horrible design, but nevertheless.
            Assert.IsFalse(zonedInUtc > zoned);
            Assert.IsFalse(zonedInUtc < zoned);
            Assert.IsFalse(zonedInUtc == zoned);
            
            // However explicit CompareTo works as it should, because CompareTo converts to Instant.
            Assert.AreEqual(-1, zonedInUtc.CompareTo(zoned));
            Assert.AreEqual(1, zoned.CompareTo(zonedInUtc));

            // Operator-based and CompareTo-based comparison should work properly
            // for ZonedDateTime objects within same time zone.
            var zoned2 = zoned.Plus(Duration.FromHours(1));
            Assert.IsTrue(zoned2 > zoned);
            Assert.AreEqual(1, zoned2.CompareTo(zoned));
            Assert.AreEqual(-1, zoned.CompareTo(zoned2));
            Assert.IsFalse(zoned2 < zoned);
            Assert.IsFalse(zoned2 == zoned);
        }

**Comment by jskeet** [comment]
I agree that it's inconsistent, but it *is* behaving as documented:

> Comparisons of values can be handled in a way which is either calendar and zone sensitive or insensitive. Noda Time implements all the operators (and the `Equals(ZonedDateTime)` method) such that all operators other than `Inequality(ZonedDateTime, ZonedDateTime)` will return false if asked to compare two values in different calendar systems or time zones.

> However, the `CompareTo(ZonedDateTime)` method (implementing `IComparable<T>`) is calendar and zone insensitive; it compares the two global instants in terms of when they actually occurred.

> It's unclear at the time of this writing whether this is the most appropriate approach, and it may change in future versions. In general, it would be a good idea for users to avoid comparing dates in different calendar systems, and indeed most users are unlikely to ever explicitly consider which calendar system they're working in anyway.

I can't change this in the 1.x stream now, as it would be a breaking change, but this has been changed for 2.0:

> `ZonedDateTime` does not implement ordered comparison operators, as there is no obvious natural ordering that works in all cases. Equality is supported however, requiring equality of zone, calendar and date/time. If you want to sort `ZonedDateTime` values, you should explicitly choose one of the orderings provided via the static properties in the `ZonedDateTime.Comparer` nested class (or implement your own comparison).

... although we may still remove even `IEquatable<T>` - see issue #180.

Basically the whole thing is a natural mess :( I thought we had another issue suggesting reimplementing `IComparable<T>` based solely on instant, but I can't find that at the moment...

I'm going to close this as "Will not fix" on the grounds that we really can't change the 1.3.x behaviour now (it's a bug in design rather than implementation) but your comments on the desirable behaviour of 2.0 would be appreciated.
