### ISSUE TITLE
request for LocalDateTimeInterval

### ISSUE THREAD

**Issue by SurajGupta** [nodatime/nodatime#457]
I'd like to make a request for a `LocalDateTimeInterval`, similar to the existing `DateInterval` type but it would represent an interval between two `LocalDateTime`.

Also, wondering if `DateInterval` should be renamed to `LocalDateInterval` to avoid any confusion about the type of interval represented?

**Comment by SurajGupta** [comment]
also happy to submit a pull request - will you accept a pull for one or both of these changes?  Let me know which ones.

**Comment by jskeet** [comment]
I'm not sure about this - it then leads to "What about ZonedDateTimeInterval? What about LocalTimeInterval? What about OffsetDateTimeInterval?" While a date interval is pretty common, my experience is that an interval between LocalDateTimes is relatively rare. Can you give example use cases?

**Comment by SurajGupta** [comment]
I agreed that it could be a slippery slope and I think the bar should be utility and complexity.  `DateInterval` (still think it's better named `LocalDateInterval` because it unambiguously describes the type) has high utility and low complexity - so it's a clear win.  `ZonedDateTimeInterval`, on the other hand, is much higher complexity.  Others will have to argue it's utility - I don't have a use-case.  But right now I'm dealing with a real use-case for `LocalDateTimeInterval` and I think that, because it's  "Local," it has similarly low complexity as `DateInterval`.

I'm creating a type that represents the delta between some numerically observed fact at two times (sometimes the same time, sometimes different times) on two different days.  In my case, time zone does not matter and including it actually makes the problem more difficult to think about.  It's the classic case of using a LocalDateTime, but I want the convenience of having both to represent a range.  I don't need to calculate the difference in time between the two, I'd simply like an interval wrapper class.  So maybe that's an argument against introducing this type?  `DateInterval` has a `Length` property (which seems to be the only value-add aside from a convenience wrapper for two LocalDate objects).  

Thoughts?

**Comment by jskeet** [comment]
`DateInterval` also has a containment check, which is probably the most common use for it.
In your case, it sounds like a `Tuple<LocalDateTime, LocalDateTime>` would be fine.

*If* we end up with more interval classes, I'd consider renaming `DateInterval` to `LocalDateInterval` - but give that that's the only kind of date we have, I think it's still unambiguous at the moment.

**Comment by SurajGupta** [comment]
Good call, totally missed containment check.  

The problem with Tuple is the whole `Item1` `Item2` properties, which are not readable when used in code: `interval.StartDateTime` versus `interval.Item1`.  Also, with a new type you have a proper home for adding future functionality like containment which is not possible with Tuple (you'd have to write extension methods).  Instead of using a Tuple, I'd just go ahead and create my own `LocalDateTimeInterval` class.  I'm happy to do that; just thought that that was broadly useful enough to push it back into NodaTime.

I disagree with your comment about `DateInterval` naming.  You are arguing that it's unambiguous because there aren't other interval types.  A new user of this type would not automatically assume it encapsulates LocalDates just because there are no other interval types.  They would immediately be confused because Noda explicitly tries to differentiate kinds of dates and here Noda is breaking with its convention.  Which kind of "Date" does this interval capture?  They would likely have to look at the source code or use intellisense, which is a smell.  It seem to me that you prefer the name because it's a barrier to adding new interval types.  Personally I don't think that that should be a factor when choosing a name - I think we should optimize for ease of understanding.

**Comment by jskeet** [comment]
What other `Date` type is there in Noda Time? There's no `ZonedDate` or `OffsetDate`, for example. Will certainly consider it, but currently I still favour `DateInterval`.

Note that you've got my motivation backwards: I'm not favouring `DateInterval` *because* it's a barrier to adding new interval types; I'm favouring `DateInterval` *while there aren't* other interval types. That's a significant difference.

**Comment by SurajGupta** [comment]
Sorry, didn't realize there weren't other `Date` types.  Begs the question of why `LocalDate` is not just `Date` - I think there are good reasons for that, because "Local" makes a point about the scope of this type.  The asymmetry between the name of that and the interval object is strange to me, but I respect your opinion.

Good debate!  I'll close this out and create my own wrapper object.  Perhaps someone else can re-open if they find themselves writing the same wrapper.
