### ISSUE TITLE
tzdb 2016b

### ISSUE THREAD

**Issue by mj1856** [nodatime/nodatime#458]
http://www.iana.org/time-zones/repository/releases/tzcode2016b.tar.gz

Release announcement:
http://mm.icann.org/pipermail/tz-announce/2016-March/000036.html

Thanks!

**Comment by jskeet** [comment]
Aha - I'd missed the proper, full release announcement. Had been waiting
for it :)

**Comment by jskeet** [comment]
Pushed now - although I haven't fixed buildweb to use dnx yet. Lots of stuff still in flux, unfortunately. Will get on that...

**Comment by mj1856** [comment]
Thanks!
