### ISSUE TITLE
Update NodaTime 1.3.x to Tzdb 2016b

### ISSUE THREAD

**Issue by girishnuli** [nodatime/nodatime#465]
I am using the nuget package of nodatime 1.3.1 in a universal windows app. I believe this uses the 2015 tzdb. Is there a way to update this package to use the latest tzdb without actually rewriting my code to manually load the latest tzdb as shown here: http://nodatime.org/1.3.x/userguide/tzdb.html

Alternately, would it be possible to update the database by downloading the source code for 1.3.x branch and replacing the tzdb.nzd file with the latest version (http://nodatime.org/tzdb/tzdb2016b.nzd) and rebuilding the project as a PCL?

Thanks.

**Comment by jskeet** [comment]
I won't be releasing an update to 1.3.1 just for 2016b, no. It would be simpler for you to download the nzd file yourself and bundle it within your UWA, then create the provide from that - it's really pretty simple.

I do intend to create a package (one for 1.x and one for 2.x) which will be updated every time there's a new nzd file, but I haven't done that yet.
