### ISSUE TITLE
Partial Instants do not parse correctly

### ISSUE THREAD

**Issue by ubercow** [nodatime/nodatime#466]
When using a partial ISO 8601 Instant like "2015-05-01", NodaTime fails to parse.

```csharp
var pattern = InstantPattern.ExtendedIsoPattern;

var good = pattern.Parse("2015-05-01T00:00:00Z");
Console.WriteLine(good.Value.ToString());
// => 2015-05-01T00:00:00Z

var bad = pattern.Parse("2015-05-01");
// An unhandled exception of type 'NodaTime.Text.UnparsableValueException' occurred in NodaTime.dll
//
// Additional information: The value string does not match a quoted string in the pattern. Value being parsed: '2015-05-01^'. (^ indicates error position.)
```

For comparison, in JodaTime:
```java
Instant i = Instant.parse("2015-05-01");
System.out.println(i.toString());
// 2015-05-01T07:00:00.000Z
```

**Comment by jskeet** [comment]
This is working as intended. `ExtendedIsoPattern` is documented as:

> Returns an invariant instant pattern which is ISO-8601 compatible, providing up to 7 decimal places of sub-second accuracy. (These digits are omitted when unnecessary.) This corresponds to the text pattern "yyyy'-'MM'-'dd'T'HH':'mm':'ss;FFFFFFF'Z'".

That's clearly not the format of your data. You can create your own instant pattern:

```csharp
var pattern = InstantPattern.CreateWithInvariantCulture("yyyy-MM-dd");
Console.WriteLine(pattern.Parse("2015-05-01").Value);
```

Or personally I would parse it as a `LocalDate` to start with, as that's a more reasonable interpretation of what you actually have. You can then convert that to an instant:

```csharp
var date = LocalDatePattern.IsoPattern.Parse("2015-05-01").Value;
Console.WriteLine(date.AtMidnight().InUtc().ToInstant());
```

**Comment by ubercow** [comment]
Is there a way to parse flexibly that I am missing then?

What I'm looking to do here is make the time optional, defaulting to 00:00:00Z if not specified.

**Comment by jskeet** [comment]
You can have a number of patterns, and try using each one to parse until you find one that's successful.

We have internal code to do that already, but I'm not sufficiently convinced I'm happy with the API to make it public. Feel free to use it as an example for your own code though:

https://github.com/nodatime/nodatime/blob/master/src/NodaTime/Text/Patterns/CompositePattern.cs

**Comment by ubercow** [comment]
Cool thanks for the help :smile:
