### ISSUE TITLE
NuGet Refresh?

### ISSUE THREAD

**Issue by neal007** [nodatime/nodatime#468]
Hello, I see there is great activity on this awesome project but the nuget package is a year old.  Any chance of refreshing nuget for us?

Thank you.

**Comment by jskeet** [comment]
Not yet, no. 2.0 isn't ready yet, basically.
1.3.1 is still perfectly good, although you should pick up a new version of TZDB as documented at http://nodatime.org/1.3.x/userguide/tzdb.html

I hope 2.0 will be ready this year, but there's still quite a lot to do in terms of build and packaging - in particular, we're using DNX (soon dotnet cli) and so won't be able to release until that's all released. We're also moving to using docfx for building the web site.

A new feature for 1.3.1 users which I *do* expect to ship "soonish" is a new package, possibly called NodaTime.Tzdb, which will just contain the TZDB data, and will be updated every time there's a new TZDB data release.

If you're looking for another interim 2.0 alpha release, I could potentially do *that* much earlier than the 2.0 full release, of course.

**Comment by neal007** [comment]
Thank you, if possible, it would be easier on us users if you could refresh the 1.x with the new TZDB while the 2.0 branch is in work.  1.x works fine for me, I just prefer to keep the TZDB updated in the easiest way, ala nuget updates.  Thanks again.

**Comment by jskeet** [comment]
Well that's what the new package will be for. I don't want to do a 1.3.2 which is *just* an updated TZDB. It  will be much better to use the new NodaTime.Tzdb package and keep that up-to-date. I hope to get that done within the next few weeks.

**Comment by jskeet** [comment]
See #469 for a PR for the 1.3.1-targeting package. Your opinion would be welcome as to whether this will fix the issue.

(We'll need to add documentation for how to use it appropriately, e.g. entries in packages.config.)

**Comment by neal007** [comment]
I'll certainly entertain the beta but I think it would help the users if a nuget push could occur any time the TZDB is updated as it's just easier on us to update nuget packages in a solution and not have to deal with the intricacies. I'm sure 99% of us are using an outdated TZDB which for the most part isn't an issue, it is just not up to date.

**Comment by jskeet** [comment]
@neal007: That's the whole point - there'll be a nuget push *of the new package* every time TZDB is updated. That's what I've been saying. But the point is that pushing a nuget package of `NodaTime.Tzdb` is going to be *much, much* less work than pushing an update of `NodaTime`, which involves a lot of hassle around documentation etc. I'm simply not prepared to do a new release of the `NodaTime` package *just* for the data - it's not a good use of my time, compared with making sure that the `NodaTime.Tzdb` package works and can be updated really easily.

**Comment by neal007** [comment]
No worries, the package is hugely appreciated.  Just asking....

**Comment by jskeet** [comment]
Update on this, having looked at various options - I'm now considering a periodic just-TZDB 1.x update Nuget package, without regenerating the API documentation (which is a large part of the pain, as our tooling has moved on a lot). For 2.0 I'm still hoping to separate it out into two packages.

No immediate ETA on the 1.3.2, but unless it takes more time than I expect, I'm hopeful for "in April".

**Comment by neal007** [comment]
Thank you, that will help your users have up to date databases which is important. NuGet is supposed to make things easier on "us" but of course at your expense - we appreciate your hard work.

**Comment by jskeet** [comment]
Now released 1.3.2 :)

**Comment by neal007** [comment]
Thank you!
