### ISSUE TITLE
Unable to map timezone id 'E. Europe Standard Time'

### ISSUE THREAD

**Issue by alineutron** [nodatime/nodatime#470]
Hey

We are using 'E. Europe Standard Time' but its missing in default tzdbsource below is the test code

```c#
[TestFixture]
	public class IanaTimeZoneProviderTest
	{
		[Test]
		public void ShouldReturnIanaTimeZoneForEasternEuropian()
		{
			var target = new IanaTimeZoneProvider();

			var result = target.WindowsToIana("E. Europe Standard Time");
			//i just hard coded Europe/Helsinki 
			Assert.AreEqual(result, "Europe/Helsinki");
		}
	}

	public interface IIanaTimeZoneProvider
	{
		string WindowsToIana(string windowsZoneId);
	}

	public class IanaTimeZoneProvider : IIanaTimeZoneProvider
	{
		private readonly TzdbDateTimeZoneSource _tzdbSource;

		public IanaTimeZoneProvider()
		{
			_tzdbSource = TzdbDateTimeZoneSource.Default;
		}
		
		public string WindowsToIana(string windowsZoneId)
		{
			var tzi = TimeZoneInfo.FindSystemTimeZoneById(windowsZoneId);
			var tzid = _tzdbSource.MapTimeZoneId(tzi);
			return _tzdbSource.CanonicalIdMap[tzid];
		}
	}

Any idea?

**Comment by jskeet** [comment]
How does it fail, exactly? I'd expect it to map to Europe/Chisinau, based on https://github.com/nodatime/nodatime/blob/master/data/cldr/windowsZones-29.xml.

Which version of Noda Time are you using, btw? Can you print out `_tzdbSource.VersionId` and include it in this issue?

**Comment by jskeet** [comment]
Ooh, it looks like "E. Europe Standard Time" was only actually mapped in CLDR v29, so you should try using http://nodatime.org/tzdb/tzdb2016c.nzd which uses it.

**Comment by mj1856** [comment]
Right.  This one is new.

Also, this brings up a good point.  Due to release cycle variations, it's common to need to manually adjust the mappings.  We may want to consider having an "overrides" file of some kind.  Either that, or we can use the dev/trunk version of the mapping file instead of the release version.

**Comment by jskeet** [comment]
@mj1856: Not quite sure what you mean by that - do you mean use an unreleased CLDR data file? I'd be pretty nervous about that.

**Comment by alineutron** [comment]
@jskeet it worked by using tzdb2016c. Thanks for your quick response guys :+1:
