### ISSUE TITLE
Make sure we use 2.0 as the assembly version in v2.*

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#471]
Unfortunately we use 1.0 for 1.0, 1.1 for 1.1 etc for AssemblyVersion. That leads to binding redirects and annoyance. We should have used 1.0 for everything. At least we can get it right for 2.0.

See https://codingforsmarties.wordpress.com/2016/01/21/how-to-version-assemblies-destined-for-nuget/ for details.

**Comment by jskeet** [comment]
Not as convinced as I was before that this is the right thing to do. Could be swayed either way. We should look at more than just that one blog post. Would be interesting to talk with the .NET Core folks - and we should see what the framework does.

**Comment by onovotny** [comment]
@jskeet maybe the discussion here will sway your opinion: https://github.com/Reactive-Extensions/Rx.NET/issues/205

**Comment by jskeet** [comment]
@onovotny Well it's left me more bewildered and concerned than before, certainly :) I have other concerns about the effect SemVer can have, which I'm going to blog about when I get the time. Fundamentally, versioning is a horrible mess :( Trying to reason about what to do in .NET without fully understanding the .NET Core approach in the same depth that you do is making it trickier still.

If the approach you're suggesting in that issue is the one that ends up being suggested, I think there's going to *have* to be some tooling support for automating it. The idea of doing it all manually is foul.

**Comment by onovotny** [comment]
I think most libraries don't have to worry about it to the extent that CoreFX and Rx do. It really only becomes an issue if you have multiple outputs of the same library that have a different public surface area.

Otherwise, it's still beneficial to increment some part of the AssemblyVersion to match things so that people can be sure they get the right version. Binding redirects do suck, but MSBuild's automatic creation of them should help most cases.

**Comment by jskeet** [comment]
Mmm. It really depends on what sort of compatibility you're going for. I used to believe that within a single major version number, you should really just be able to copy the dll in place... but that's clearly not going to work in many cases. Maybe "Your code will still build and work, but you need to let the package manager resolve stuff" is good enough.

**Comment by onovotny** [comment]
Where it gets messy is when dealing with systems of extensibility that do not use NuGet. Individual apps/websites are easy. But plugins are tough.... which version of the assembly was loaded? Was it the most recent, etc? Hard to do anything if the assembly version is the same, at least with diff versions, you have a chance at redirects.

**Comment by jskeet** [comment]
// cc @jtattermusch given https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/VersionInfo.cs

**Comment by jskeet** [comment]
- Not going to try the really complicated version that Rx uses
- Not going to try to "outsmart" dotnet cli

In other words, we put the version we want in project.json (or csproj) and let the toolchain do the right thing. (And yes, a 2.1.0 netstandard1.1 assembly will have "different" (more and less) functionality than a 2.0.0 net45 assembly.)
