### ISSUE TITLE
Reconsider IsoDayOfWeek vs DayOfWeek

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#472]
All our calendars use normal week days. We don't support non-7-day weeks etc.

Maybe keep the name IsoDayOfWeek for the enum (it has different values to the BCL DayOfWeek, after all) but ditch the separation between the enum and the integer property in 2.0?

**Comment by malcolmr** [comment]
I'm not entirely sure I follow what you're proposing to change here?

**Comment by jskeet** [comment]
Currently we have `int DayOfWeek` and `IsoDayOfWeek IsoDayOfWeek` properties in `LocalDate`, along with `CalendarSystem.UsesIsoDayOfWeek`. Basically we've made thing too complicated in the expectation of having non-ISO days.

A few options here:

- Remove IsoDayOfWeek entirely, and use the BCL DayOfWeek enum
- Keep IsoDayOfWeek but change LocalDate.DayOfWeek to be of type IsoDayOfWeek, and remove the IsoDayOfWeek property
- Leave everything as it is
- Just remove LocalDate.DayOfWeek

Probably worth looking at this in person in front of a laptop...

**Comment by malcolmr** [comment]
Ah, I see.

I'm sympathetic to making `LocalDate.DayOfWeek` be typed as `IsoDayOfWeek` (and removing the  `IsoDayOfWeek` property), with the caveat that that would need to be a breaking change between 1.x and 2.0 that we can't really bridge in a 1.4.

**Comment by jskeet** [comment]
Right, we'll do this - and yes, it'll be breaking.
