### ISSUE TITLE
Consider including CLDR mapping overrides at time of NZD release

### ISSUE THREAD

**Issue by mj1856** [nodatime/nodatime#473]
(Mentioned in #470, but worth its own discussion.)

When we update our NZD files for each TZDB release, we're including CLDR mappings for conversion to Windows time zones.  We use the current shipping production release for this.

While this seems like the right thing to do, it can unfortunately lead to errors.  The problem is, CLDR is on a [strict bi-annual release cadence](http://cldr.unicode.org/index#TOC-General-Schedule-).  This doesn't align well with either TZDB or Windows time zone releases.

TZDB releases on an as-needed basis, either when there is sufficient critical mass, or when reacting to a short-notice change by a government.

For Windows, traditionally, tz/dst hotfixes are released as necessary to react to changes, then cumulative updates are done in August and December.  This is a bit in flux, and the team is working on improvements to be more streamlined.  Either way, it doesn't align with CLDR's strict schedule.

This means that there's an interm period where CLDR maintainers know about a change and commit it [to the dev trunk here](http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml), until the final release version comes out.  Sometimes this delay is significant.

Consider recent events as an example.  TZDB introduced three new time zones in 2016b, `Europe/Astrakhan`, `Europe/Ulyanovsk` and `Asia/Barnaul`.  These aren't in CLDR 29, because CLDR 29 was released with TZDB 2016a data.  They are, however, in the dev version, mapping as best as possible to the current Windows time zones.  Additionally, [Windows will release an update on April 12th](https://blogs.technet.microsoft.com/dst2007/2016/03/15/time-zone-updates-for-russia/) that will add 4 new time zones.  After those are released, CLDR mappings will likely change once again.  However, none of these CLDR changes will be *released* until CLDR 30 comes out on September 15th.

It would seem to make sense to include in Noda Time's NZD files some delta of changes that we review manually.  That may also require NZD releases more frequently than just with each TZDB release, potentially.

**Comment by jskeet** [comment]
Okay, I can see the problem - but I'm not sure what solution you're proposing. If you're suggesting we should take whatever's currently checked into the `dev` trunk, that suggests it's basically unchecked data.

We could do this *manually* by taking changes we expected to be "good" ones, but that's a lot of work and a judgement call.

We could add a way that users could build their own NZD file from an existing one and a new CLDR mapping. We could add a way for users to do that at runtime, not building a new NZD file but just getting a TzdbDateTimeZoneSource/Provider.

Any suggestions?

**Comment by mj1856** [comment]
FYI, both May's Windows TZ data and the upcoming June release will add even more time zones to Windows, and IANA added more in 2016b and 2016d.  None of these are included in CLDR 29.

CLDR has the April ones in their dev trunk, but missed May's, so I've opened a ticket here: http://unicode.org/cldr/trac/ticket/9484

June's changes are even more extensive, and requires significant updates to CLDR, so I've submitted a ticket for that too. http://unicode.org/cldr/trac/ticket/9485

Yes - it's a lot of work to figure out what the "current" valid data is, given Windows, IANA, and CLDR all being on different release cadences.  However, NodaTime uses data from all three, and I think just snapping to the cycle of one of them seems rather arbitrary.  At minimum, I'd like to know that the current IANA version matches the most readily available CLDR data, reflecting the most readily available Windows data, at the time of the IANA release.  Even if the CLDR data is not fully released, the typical user of NodaTime should be shielded from such concerns.  They just want to know that the Noda Time APIs works.

As a use case, consider that if I call `DateTimeZoneProviders.Tzdb.GetSystemDefault()`, and my time zone is set to `"Easter Island Standard Time"` it should indeed map back to `Pacific/Easter`.

I think the best way to do this is to let the NZD builder include an overrides file.  We should maintain the set we think are valid, and use those for the NZD files we publish.  We're in a better position than most to make the determination.  I can contribute in this area, and make sure they align with Microsoft's POV as well.  If some disagree, they can change the overrides in their own NZD files.

**Comment by mj1856** [comment]
FYI - I'm dealing with this internally at MS now as well - for those teams using NodaTime.

**Comment by jskeet** [comment]
Definitely happy to add an override file ability.

I take your point about the cadence being slightly arbitrary, but syncing on IANA feels like it makes the most sense as the primary source of data.

I don't _think_ this would require any code changes in the 1.x line; I can just update the 2.0 branch with the new NZD generation code, and 1.3.x will still be able to read it. We can introduce a new property in `WindowsZones` for the override file, and obviously *that* won't be available in 1.x, but I don't think that should be a blocker. It would mean that 1.x users wouldn't be able to differentiate between nzd files with an override and those without subverting the file format a little.

Any preference on the override file format? JSON? XML? Just name=value lines?

**Comment by mj1856** [comment]
Probably would be easiest just to use the same xml format as the existing cldr file.  Then just some logic such that the data in the override file takes precedence if the same IANA zone is in both files.

**Comment by jskeet** [comment]
Righto. Will get on that. The updated version info could be specified in the file in the same way, too - so no other changes required.
