### ISSUE TITLE
FromYearMonthWeekAndDay should accept negative values for offsets from the end.

### ISSUE THREAD

**Issue by scshunt** [nodatime/nodatime#474]
The current unstable code features `LocalTime.FromYearMonthWeekAndDay`, which can get you, say, the third Monday in May. But it can't get you the last Monday in May, and it should accept negative offsets to mean offset-from-end in this scenario.

**Comment by jskeet** [comment]
Hmm... I'm really not sure about that. Given that "last X in Y" is a common scenario, I think it would make sense to have a date adjuster for that - but I don't think it should try to make `FromYearMonthWeekAndDay` broader. It's not like there *is* a 0th Monday in June, or a 10th Monday in June.

**Comment by scshunt** [comment]
On Tue, Apr 5, 2016 at 2:04 PM, Jon Skeet <notifications@github.com> wrote:

> Hmm... I'm really not sure about that. Given that "last X in Y" is a
> common scenario, I think it would make sense to have a date adjuster for
> that - but I don't think it should try to make FromYearMonthWeekAndDay
> broader. It's not like there *is* a 0th Monday in June, or a 10th Monday
> in June.
>

For a little more context, the iCalendar spec (RFC 5545) handles
recurrences this way, and that is the particular reason that I was thinking
of to do it like this. It has different behaviour from currently, though,
because specifying the 5th Monday, say, will not fall back to the 4th in a
month with only 4. You must explicitly specify the -1st (i.e. last) Monday
to get that behaviour.

Sean

**Comment by jskeet** [comment]
Right - I don't think I want to copy that behaviour, but we should make it easy to emulate. Of course, others may want to chip in with other opinions :)

**Comment by jskeet** [comment]
Closing as "I don't think we should implement this."
