### ISSUE TITLE
Caution use of DateTimeKind.Unspecified cross platform

### ISSUE THREAD

**Issue by neal007** [nodatime/nodatime#475]
I was one that found a bug long ago in Xamarin's implementation when we learned of .NET DateTime issues with DateTimeKind Unspecified and converting to NSDate in iOS.  Not all platforms know of this "Unspecified" Kind and have problems with its use.  I noticed when working with NodaTime and ZonedTime the LocalDateTime really only has a path ToDateTimeUnspecified from what I recall.  I'm not even sure why the .NET BCL created this situation and I know it's a problem in System.Data.DataSets as well.  If you live in the land of pure .NET then it's probably fine but I know iOS has a problem and I'm not sure about Android but we have to take measures to avoid DateTimeKind Unspecified now.  We even use C# 6 initializers as such:

DateTime FakeDate { get; set; } = DateTime.SpecifyKind(DateTime.MinValue, DateTimeKind.Utc); 

This ensures our dates are initialized to a kind other than Unspecified.

Here is more info if interested.  This is not really an "issue" but a FYI from my experience and my avoidance of this "Kind" at all costs.

https://developer.xamarin.com/guides/cross-platform/macios/unified/overview/#Converting_DateTime_to_NSDate

**Comment by jskeet** [comment]
A `Kind` of `Unspecified` is the most appropriate option in some cases, however - where there *is* no known time zone. It maps fairly clearly to `LocalDateTime` in Noda Time. A kind of either `Utc` or `Local` would simply be wrong in this case.

I wouldn't advise avoiding `Unspecified` everywhere - I'd just advise being aware of it. (Of course, I'd advise using Noda Time instead, but that's a different matter.)

Having "kinds" of `DateTime` is broken to start with, IMO - but given that situation, I'm glad `Unspecified` exists.
