### ISSUE TITLE
period calculation?

### ISSUE THREAD

**Issue by Peperud** [nodatime/nodatime#487]
```c#
var period = NodaTime.Period.Between(
                NodaTime.LocalDateTime.FromDateTime(DateTime.Now.AddDays(-70)),
                NodaTime.LocalDateTime.FromDateTime(DateTime.Now));

Console.WriteLine("Days:{0}, Weeks:{1}, Months:{2}", period.Days, period.Weeks, period.Months);
```
Two dates 70 days apart. And the output is: 
***Days:10, Weeks:0, Months:2***

**Comment by mj1856** [comment]
Yes, that's correct, although you may get a different answer depending on when you run it.

Assuming ran today, April 14th, 2016, then 70 days ago would be February 4th, 2016.

So, Feb 4th + 2 months would be April 4th, + 10 days would be April 14th.

If you were looking for a different permutation of the fields, consider passing a `PeriodUnits` value.  For example, passing `PeriodUnits.AllDateUnits` would give the results as 2 months, 1 week and 3 days.

The default if you don't pass it is `PeriodUnits.YearMonthDay`.
