### ISSUE TITLE
Consider adding 360day calendar

### ISSUE THREAD

**Issue by janslav** [nodatime/nodatime#504]
Custom calendars apparently are not an open extension point atm, so in accordance with the documentation I'm requesting this feature.
Even though a 360 day calendar may sound silly, it's actually being used in financial circles and as such needs to be represented in .NET code often.

https://en.wikipedia.org/wiki/360-day_calendar

If this is not the correct place for feature requests, please let me know.

Thanks
Jan S.

**Comment by jskeet** [comment]
Will have a look, although at first glance it doesn't look like a great fit as a CalendarSystem, given that "To derive such a calendar from the standard Gregorian calendar, certain days are skipped."

Can you give more details about what the usage of such a calendar would look like?

(Note that this would only be for 2.0 anyway.)

**Comment by janslav** [comment]
what's the best implementation fit I'll gladly leave to you.
The typical usage of this is a difference between two dates, as the wiki article says. It's not that the days don't exist, it's just that they aren't considered in the difference calculation: There's 1 day between the 30thJan and 1st Feb, same as between 31thJan and 1st Feb.

**Comment by jskeet** [comment]
Right - that sounds like it shouldn't be done as a `CalendarSystem`, at which point it wouldn't *need* to be done in Noda Time itself - if it's really about "take these two regular dates, and compute the difference between them in days" then that can live outside the main assembly with no problems. I have no issue with potentially adding it if it's of use to multiple people - but it does make it less of a "you can't do it without full Noda Time support" situation than adding a regular calendar.

**Comment by janslav** [comment]
Well it's a date/time-related feature request to a date/time related library. Obviously like with anything, people can do stuff themselves, and then they don't need libraries. 
I'm just saying that this is a non-trivial calculation (not totally completely trivial anyway :) so financial peoples would probably gladly see it implemented, that's all.

**Comment by jskeet** [comment]
> Obviously like with anything, people can do stuff themselves, and then they don't need libraries. 

No, there's a fundamental difference between this feature request (where if you have the code already, you can use Noda Time perfectly easily) and a feature request for a calendar system which you simply *can't* implement in a way that works with Noda Time, outside Noda Time itself. (You can implement your own time zones, for example - but you can't implement your own calendar.) It could also have required API changes which would *have* to get into 2.0... whereas it sounds like this could go into 2.1 fairly easily.

The fact that there are 5 different methods (according to wikipedia) is somewhat alarming, I have to say. Will need to see how it pans out after a bit more investigation.

I think if we're going to think about useful finance operations, we should probably think about what else is needed at the same time.

**Comment by jskeet** [comment]
Punting this to 2.1.

**Comment by jskeet** [comment]
Closing due to the lack of further requests for this since 2016. (We can reopen if it becomes more important, of course.)
