### ISSUE TITLE
Revisit System.Runtime.Numerics dependency in Testing

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#510]
I'm having to add a dependency on System.Runtime.Numerics in NodaTime.Testing for no obvious reason; without it, tests on Linux/coreclr busy-hang (I believe due to type loading problems).

This may well be a bug in Linux/coreclr; we should check this again when RC2 is out.

**Comment by leo90skk** [comment]
new results?

**Comment by jskeet** [comment]
Haven't had time to look.
