### ISSUE TITLE
InvalidPatternException when trying to format a Duration using the "S" pattern

### ISSUE THREAD

**Issue by kawazoe** [nodatime/nodatime#526]
I was recently trying to get the total amount of seconds for a Duration instance without any leading zeros. It seemed like the "S" pattern was refused for no reason, while other variants like "SS" and even "S." would work correctly. After some investigations, I stumbled on what seems to be the cause for this InvalidPatternExeption. The DurationPatternParser [refuses single character patterns](https://github.com/nodatime/nodatime/blame/master/src/NodaTime/Text/DurationPatternParser.cs#L54) besides the "o" pattern.

It feels very weird to accept patterns like "S." and not just "S". I have not studied all other pattern cases, so I am not sure if it should explicitly refuses single character patterns like it currently does of if only some pattern components should be added to the exclusion list.

**Comment by jskeet** [comment]
Any single-character pattern is interpreted as a standard pattern, and "S" isn't a valid standard pattern for durations. You can use "%S" as the pattern instead, where "%" is really just there to say "I only want to specify a single character, but it's still a custom pattern."
