### ISSUE TITLE
Potential Travis Build change

### ISSUE THREAD

**Issue by rheh** [nodatime/nodatime#530]
The travis build file includes the following comment:

> Although TzdbCompiler is portable, the tests aren't, as they check against Windows standard time zone IDs. For Mono we run against the Release configuration due to  https://bugzilla.xamarin.com/show_bug.cgi?id=36257

According to bugzilla this issue is now fixed.  Thus should the aforementioned issue to resolved too?

**Comment by jskeet** [comment]
It depends on whether that fix has made it to the version we use on Travis. Will have a look.

**Comment by jskeet** [comment]
Just checked, we're still on 4.2.3 on Travis, so we can't do it yet.

**Comment by jskeet** [comment]
Will look at this when trying to move to csproj as per #685.

**Comment by jskeet** [comment]
We're not specifically requesting debug builds, but I don't expect to be able to run under net451 on Linux any time soon. Closing as obsolete, at least for now.
