### ISSUE TITLE
ASP.NET Core Model Binders

### ISSUE THREAD

**Issue by TheBeardedLlama** [nodatime/nodatime#534]
Hey @jskeet are you aware of an implementation of/already working on aspnet core model binders for nodatime types?

(apologies if this is not the right forum to ask this question; feel free to kickban)

**Comment by jskeet** [comment]
There's PR #368 which I haven't tried at all myself, and is waiting for various other things to settle before it gets committed. That would probably be your best starting point.

**Comment by TheBeardedLlama** [comment]
Thank you for the pointer! I'm reading through it now.

Apologies for not looking harder :(
