### ISSUE TITLE
Q: Interest in using StyleCop.Analyzers?

### ISSUE THREAD

**Issue by fubar-coder** [nodatime/nodatime#540]
Is it interesting for the deveopers to use something like [StyleCop.Analyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers)?

I used it after seeing that [StyleCop](https://stylecop.codeplex.com/) seemed to be abandoned. Now that the original StyleCop project is alive again thanks to Chris Dahlberg, I'm not sure which system to use. StyleCop requires R# for code fixes, while StyleCop.Analyzers integrates nicely with Visual Studio using the Analyzer API, but this seems currently broken...

**Comment by jskeet** [comment]
Not sure what this has to do with Noda Time particularly, to be honest... but personally if I were going to write an analyzer now, I'd make it a Roslyn analyzer directly, rather than writing a StyleCop rule.

**Comment by fubar-coder** [comment]
I'm asking, because you're already using StyleCop, which was - between 2014 and 2016 - quite dead. And the StyleCop.Analyzers are StyleCop rules as Roslyn analyzers.

**Comment by jskeet** [comment]
Oh, the `Settings.StyleCop` file? Haven't touched that in years - never used it myself. Very happy to just delete it.
