### ISSUE TITLE
Investigate use of TimeZoneInfo.Id in .NET Core

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#543]
It looks like Id is now a supported property, when it wasn't before in PCLs.
However, we'll need to work out what to do about its behaviour on OS-X and Linux...

**Comment by SCKelemen** [comment]
So does this project work on .NET Core 1.0 or Windows 10 IoT Core?

**Comment by jskeet** [comment]
Noda Time itself targets .NET Standard 1.1 for v2.0, and PCL profile 259 for v1.3.2. You should be able to use v1.3.2 from .NET Core 1.0, you'll just need an "imports" line. It should work fine from Windows 10 IoT core, although I haven't tried that myself.

**Comment by jskeet** [comment]
Do we even support BclDateTimeZone in netstandard1.1? If not, that's less of an issue. I'm pretty sure that TimeZoneInfo.AdjustmentRules (or whatever it's called) still isn't in .NET Core in general.

However, we do need to work out how to map the system local time zone onto TZDB...

**Comment by jskeet** [comment]
So work to do: try mapping ID to Windows name, and if not, try it as a TZDB ID. (This is in TzdbDateTimeZoneSource.) If we can use ID instead of StandardName, so much the better.

**Comment by jskeet** [comment]
Just tried, and we can't use `Id` in the netstandard11 build. So we're back to using `StandardName` there. What will be interesting is what is used for `StandardName` when using .NET Core (where the ID would be the same as the TZDB ID).

**Comment by jskeet** [comment]
Just found we *could* use Id in netstandard13. Maybe that's what we should target instead.
