### ISSUE TITLE
Time zone db returning 404

### ISSUE THREAD

**Issue by mark-porter** [nodatime/nodatime#548]
I appreciate this is not a coding issue but the latest time zone db served from http://nodatime.org/tzdb/latest.txt returns as url "http://nodatime.org/tzdb/tzdb2016f.nzd" is returning 404. It appears like the nzd files are all returning 404.

**Comment by malcolmr** [comment]
Confirmed. Jon: is this a result of https://github.com/nodatime/nodatime.org/commit/c7bdc5aca39257f1265e2152816f62d5a2a9def0?

The files all appear to be in the source directory: https://github.com/nodatime/nodatime.org/tree/master/wwwroot/tzdb

**Comment by jskeet** [comment]
Eek! Thanks for pointing it out. The file is in the right place, so I think it's just a matter of configuring ASP.NET core to serve nzd files. Will look at that right now.

**Comment by jskeet** [comment]
Fixed now - thanks so much for reporting.
