### ISSUE TITLE
Consider making static *Pattern properties less wordy

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#556]
Which of these looks more sensible?

``` csharp
var brief = LocalDatePattern.Iso;
var full = LocalDatePattern.IsoPattern;
```

Currently we have the latter. Going to the former would be a breaking change (although we could _add_ the former, and maybe make the latter obsolete... certainly for 1.4).

**Comment by malcolmr** [comment]
In isolation, `LocalDatePattern.Iso` looks better to me, though note that that would also imply the existence of e.g. `PeriodPattern.Roundtrip`.

And of course we do also have `DateTimeFormatInfo.ShortTimePattern`, albeit that that's a bare string.

**Comment by jskeet** [comment]
Yup, let's do this.
