### ISSUE TITLE
Consider returning a custom error page on 404 errors

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime#557]
At present, if you go to e.g. http://nodatime.org/unstable/api/html/F_NodaTime_TimeZones_Resolvers_LenientResolver.htm, you'll get a blank page in Chrome. Which is a bit confusing.

This is because the server is responding with a 404 with no body (Content-Length: 0), which is a **totally reasonable thing to do**. However, due to what I believe is [crbug.com/424871](http://crbug.com/424871), Chrome just displays a blank page in that situation.

We could make this a little less confusing by adding a custom 404 page, even if it's just the Apache-style:

```
Content-Type: text/html

<!DOCTYPE html><title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL /foo was not found on this server.
```

**Comment by jskeet** [comment]
Chrome now returns

> No webpage was found for the web address: http://nodatime.org/unstable/api/html/F_NodaTime_TimeZones_Resolvers_LenientResolver.htm

However, we could still potentially serve a nicer page if we wanted to.

**Comment by malcolmr** [comment]
Given that Chrome is fixed, I think we're probably okay as we are.
