### ISSUE TITLE
Missing Windows time zones

### ISSUE THREAD

**Issue by beefo** [nodatime/nodatime#560]
Looks like there are a few new Windows time zones missing.
As per windows updates:
- [https://support.microsoft.com/en-us/kb/3112148](https://support.microsoft.com/en-us/kb/3112148)
- [Time zone changes for Russia in Windows](https://support.microsoft.com/en-us/kb/3148851)
- [June 2016 DST and time zone update for Windows](https://support.microsoft.com/en-us/kb/3162835)

.Net console app:

```
var tzdbSource = NodaTime.TimeZones.TzdbDateTimeZoneSource.Default;
            foreach (var tzi in TimeZoneInfo.GetSystemTimeZones())
            {
                var tzid = tzdbSource.MapTimeZoneId(tzi);
                if (tzid == null) {
                    Console.WriteLine($"Unknown {tzi.Id}");
                }
            }
```

Produces:

```
Unknown Aleutian Standard Time
Unknown Marquesas Standard Time
Unknown UTC-09
Unknown Pacific Standard Time (Mexico)
Unknown UTC-08
Unknown Easter Island Standard Time
Unknown Haiti Standard Time
Unknown Cuba Standard Time
Unknown Turks And Caicos Standard Time
Unknown Tocantins Standard Time
Unknown Saint Pierre Standard Time
Unknown Mid-Atlantic Standard Time
Unknown West Bank Standard Time
Unknown Astrakhan Standard Time
Unknown Altai Standard Time
Unknown W. Mongolia Standard Time
Unknown Tomsk Standard Time
Unknown Aus Central W. Standard Time
Unknown Transbaikal Standard Time
Unknown Lord Howe Standard Time
Unknown Bougainville Standard Time
Unknown Norfolk Standard Time
Unknown Sakhalin Standard Time
Unknown Kamchatka Standard Time
Unknown Chatham Islands Standard Time
```

Note: This also appears to be an issue with the the [Unicode CLDR](http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml) which seems to be out of date date.

**Comment by jskeet** [comment]
Yes, until recently we had no way of adding those zones. As of #532 we can now add in extra mappings independently of CLDR, but we haven't had a release where we do so yet. (I'd envisage publishing a "vanilla" nzd file, and one with an override applied.) I'm going to rely on @mj1856 to provide the appropriate override files :)

Note that if you use a more recent version of the zone data than the one that ships in the release (i.e. use 2016f), that *may* remove some of those unknowns, but I haven't checked.

**Comment by beefo** [comment]
@jskeet I was unable to find version 2016f of windowZones.xml only [2016d](http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml). Could you share a link to version 2016f?

**Comment by jskeet** [comment]
The nzd file for 2016f uses the 2016d data, but the default with the 1.3.2 release was only 2016c, so there may have been some benefits there. I haven't checked.

**Comment by beefo** [comment]
Ah, I see. Thanks for clearing that up.
FYI, I have reported the missing Windows time zone mappings to the Unicode CLDR team.

**Comment by mj1856** [comment]
I have created the overrides [here](https://gist.github.com/mj1856/85da329b72f298a5824abfb25c7f1dfd) but I've not had a chance to fully test yet.  Will do soon, as soon as I get some time to focus on this again, but feel free to try for yourself.  Thanks.

**Comment by jskeet** [comment]
With 1.3.3 this gives (today):

Unknown Mid-Atlantic Standard Time
Unknown Kamchatka Standard Time

Note that the code won't work with 2.0 as we don't have MapTimeZoneId any more - it could be rewritten though.

**Comment by ml21** [comment]
"Sao Tome Standard Time" absent too

**Comment by jskeet** [comment]
Given that this doesn't seem to be causing problems for folks on a regular basis, I'll close this issue now. We still haven't added in any overrides or released a separate NZD file with any, but we can if we need to.
