### ISSUE TITLE
Support for C++/CLI

### ISSUE THREAD

**Issue by fubar-coder** [nodatime/nodatime#561]
I'll create a pull request for this (special) use case. C++/CLI (since 2013, tools version 13?) can consume net45 assemblies, but NuGet support for C++/CLI is worse than for C++/native.

**Comment by fubar-coder** [comment]
Any estimated time frame for a new build? Otherwise we'll just use our private feed with a NuGet package version `2.0.0-alpha20160727`, which should be updatable by the official package.

**Comment by jskeet** [comment]
I can do a new build in the next couple of days, but it would still only be alpha of course.

**Comment by jskeet** [comment]
Presumably I need this in NodaTime.Testing and NodaTime.Serialization.JsonNet as well?

**Comment by fubar-coder** [comment]
It shouldn't be necessary, because using NodaTime.Testing from a C# or VB assembly should be sufficient. Newtonsoft.Json currently doesn't support C++/CLI, so I guess that it's not necessary for NodaTime.Serialization.JsonNet. However, I'll try to get the PR for C++/CLI merged as soon as possible (and when James NK approves...).

**Comment by jskeet** [comment]
I've pushed 2.0.0-alpha20160729 - if you could check that it works for you and report back, we can close this :)

**Comment by fubar-coder** [comment]
Works as expected. Thank you very much!
