### ISSUE TITLE
Make Noda Time easier to use from PowerShell

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#563]
Apparently PowerShell makes it easier to work with types that have one of:
- A static Parse method
- A constructor accepting a string parameter

We don't have either of those options at the moment, having explicitly rejected using (e.g.) `LocalDate.Parse` before the v1 release, in favour of using patterns. It would be unusual to have a `Parse` method but make it use a fixed pattern regardless of system culture, but that's what I'd _want_ in such a method, particularly for PowerShell scripting.

If there's some way that we can expose something for PowerShell to use that doesn't make other developers expect culture-variable parsing, that would be good.

**Comment by malcolmr** [comment]
Would it need to be on the `LocalDate` type itself, or could we have e.g.

```csharp
namespace NodaTime.PowerShell
{
    public static class LocalDate
    {
        NodaTime.LocalDate Parse(String input) {}
    }
}
```

(or similar)

**Comment by jskeet** [comment]
Good question - not sure. Will need to do more research on that...

**Comment by jskeet** [comment]
Closing due to lack of demand. If we ever get PowerShell users *asking* about Noda Time, it'll be easy enough to reinstate this.

**Comment by Nephiaust** [comment]
Here's one now :D

All I am trying to do is convert a unix/C datetime into a powershell compatible one. but no.... everything has to be hard, stupid incompatible standards

Examples of the date times I am trying to convert
`initialRegistrationDate  : Mon Mar 08 10:59:45 ACST 2021
lastRenewalAttemptDate   : Wed Aug 02 10:52:46 ACST 2023
nextRenewalAttemptDate   : Mon Jan 29 10:52:46 ACST 2024
registrationExpireDate   : Thu Aug 01 10:47:45 ACST 2024
registrationFailedReason : Successful.
outOfComplianceStartDate : Thu Jan 01 05:30:00 IST 1970`

**Comment by Nephiaust** [comment]
This is what I have done in the mean time....

```
Function ConvertFrom-WeirdDateFormat{
    param (
        [Parameter(Mandatory)][String]$Date
    )
    [DateTime]$ProcessedDate = [DateTime]($Date.Split(" ")[3] + " " + $Date.Split(" ")[2] + "/" + $Date.Split(" ")[1] + "/" + $Date.Split(" ")[5])
    Switch ($Date.Split(" ")[4]){
        "IST" {
            # Indian Standard Time
            $ProcessedDate = $ProcessedDate.AddHours(-5)
            $ProcessedDate = $ProcessedDate.AddMinutes(-30)
            break
        }
        "ACST" {
            # Australian Central Standard Time
            $ProcessedDate = $ProcessedDate.AddHours(-9)
            $ProcessedDate = $ProcessedDate.AddMinutes(-30)
            break
        }
        "ACDT" {
            # Australian Central Daylight Savings Time
            $ProcessedDate = $ProcessedDate.AddHours(-10)
            $ProcessedDate = $ProcessedDate.AddMinutes(-30)
            break
        }
        "UTC" {
            # Universal Time Coordinate
            $ProcessedDate = $ProcessedDate.AddHours(0)
            $ProcessedDate = $ProcessedDate.AddMinutes(0)
            break
        }
        default {
            # Throw an error because this is a hack to covert the datetime to something usuable
            $ErrorMsg = "Unknown timezone - " + $Date.Split(" ")[4]
            throw $ErrorMsg
            break
        }
    }
    return $ProcessedDate
}
```

**Comment by jskeet** [comment]
It's not clear to me what the concrete proposal here is. We don't parse based on time zone abbreviations due to potential ambiguity etc, and that remains my position - but if there's another proposal here, I'm happy to hear it. (It's not clear yet how this would be specific to PowerShell either.)

**Comment by Nephiaust** [comment]
> It's not clear to me what the concrete proposal here is. We don't parse based on time zone abbreviations due to potential ambiguity etc, and that remains my position - but if there's another proposal here, I'm happy to hear it. (It's not clear yet how this would be specific to PowerShell either.)

Is all good. I withdraw my +1 for the change :D
