### ISSUE TITLE
Create Nuget when tz db changes

### ISSUE THREAD

**Issue by mantzas** [nodatime/nodatime#575]
NodaTime v1.3.2 has tz db 2016d. 
Currently we have 2016f.

### Proposal

- Create for each release of tz db a new nuget

or 

- Create a static configuration method that accepts a path to the NodaZoneData file so that we can just provide a path in order to use the new file and replace the internal db with the new one.

Thanks

**Comment by jskeet** [comment]
Creating a new NodaTime release on every new tzdb release is feasible, but significant work, both up-front and over time.

It's pretty easy to create an `IDateTimeZoneProvider` based on a file though - we show how to do it in the user guide: http://nodatime.org/1.3.x/userguide/tzdb.html

I wouldn't want to have a *static* method as that suggests modifying global state, which would be a bad idea IMO.

We've also been considering having a separate package for just the data, but that would then need to depend on NodaTime itself - there are dependency issues in making it work as seamlessly as I'd like. See https://codeblog.jonskeet.uk/2016/03/28/versioning-conundrum-for-noda-time-help-requested/

**Comment by mantzas** [comment]
Thanks we will look into the user guide to accomplish this.

Would it make sense to have two complete separate packages? 
One the "core" that contains all the code and one the "data" that would contain all the data(tz).
"data" nuget could be released independently from the core code.
End users could update the "data" nuget to be up to date with tzdb and only update the core nuget when needed.

The data could contain a provider which could be used by the core.
Does that make any sense?

**Comment by jskeet** [comment]
Yes, that's exactly what I was proposing - the tricky bit is which way dependencies go, and whether we need one package for 1.0 and one for 2.0 etc. Have a look at the blog post :)

**Comment by mantzas** [comment]
ok, i added a idea to the blog.
since this will be developed i am closing the issue.
