### ISSUE TITLE
What about MinValue and MaxValue on LocalDateTime?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nodatime/nodatime#58]
```
When working with DateTime it's often useful to be able to refer to MinValue 
and MaxValue either as placeholder values or as open ended bounds in a query 
for values within a given range.

It would be nice if LocalDateTime had MinValue and MaxValue static properties 
because that would make it easier when porting old code over from .NET.

Even nicer would be an additional LocalDateTime.Undefined property for those of 
us who like the 'null value pattern'.

```

Original issue reported on code.google.com by `HighTech...@gmail.com` on 18 Apr 2012 at 6:46

**Comment by roji** [comment]
@jskeet is there a chance this would be reconsidered? Min/MaxValues seem to have been added for most other types in NodaTime ([LocalDate](https://github.com/nodatime/nodatime/issues/898), [LocalTime](https://github.com/nodatime/nodatime/issues/356), Instant...), LocalDateTime seems to stick out as the odd one. This would specifically help me in mapping to PostgreSQL infinity values (justl ike in #898).

**Comment by roji** [comment]
Well, I guess there's also ZonedDateTime and OffsetDateTime, Period, and probably some others which lack these. It would be helpful for me if these could be added...

**Comment by roji** [comment]
Sounds less trivial than I was hoping :sweat_smile: Thanks for giving this your time @jskeet!
