### ISSUE TITLE
Add Deconstruct methods to support C# 7 deconstruction

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#585]
Obvious examples:
- `ParseResult<T>`  - two overloads, one `Deconstruct(out bool success, out T value, out Exception error)`
- `LocalDate` - `Deconstruct(out int year, out int month, out int day)`
- `LocalTime` - `Deconstruct(out int hour, out int minute, out int second)`

We'll want to be careful with this, but it could be really nice...

([C# 7 feature description](https://github.com/dotnet/roslyn/blob/master/docs/features/deconstruction.md))

**Comment by jskeet** [comment]
Punting for the moment in an effort to get 2.0 out.

**Comment by carlosschults** [comment]
Can I take a shot at this?

**Comment by jskeet** [comment]
Go for it :)

**Comment by carlosschults** [comment]
Let's discuss here and try to decide for exactly which types are we adding deconstruct methods. Once we've  decided this, we could close these issue and open individual issues for each type.

Does that make sense?

**Comment by jskeet** [comment]
I suspect it'll make sense to just keep a single issue anyway, to be honest - we could quite possibly get it all done in a single PR, possibly with one commit per type. I don't want to introduce too much issue churn :)

As a starting point, I'd suggest:

- LocalDate:
  - year/month/day
  - year/month/day/calendar
- LocalTime
  - hour/minute/second (subsecond becomes trickier with units)
- LocalDateTime
  - year/month/day/hour/minute/second
  - *Maybe* the equivalent with a calendar?
  - *Maybe* LocalDate/LocalTime?
- ZonedDateTime
  - year/month/day/hour/minute/second/DateTimeZone
  - *Maybe* LocalDate, LocalTime, DateTimeZone (and offset?)
- OffsetDateTime
  - year/month/day/hour/minute/second/Offset
  - *Maybe* LocalDate/LocalTime/Offset
- OffsetDate
  - year/month/day/Offset
  - Maybe the same with a calendar
- OffsetTime
  - hour/minute/second/Offset
- Interval
  - Start/End (nullable instants)
- DateInterval
  - Start/End (local dates)
- Instant, Duration, Period, DateTimeZone
  - Nothing?

**Comment by carlosschults** [comment]
> Maybe LocalDate/LocalTime/DateTimeZone (and offset?)

I was thinking about LocalDateTime/DateTimeZone/Offset. Makes sense?

**Comment by jskeet** [comment]
Yup, that works, and is cleaner. Will put that in the list. (Easier to edit the earlier comment than reproduce.)

**Comment by carlosschults** [comment]
You're worried about overloads with too much parameters. So, regarding types that are "composed" of other types (such as LocalDateTime being LocalDate + LocalTime) I think it would make sense to go with the less granular option, e.g:

- LocalTime
    - year/month/day: OK
    - year/month/day/calendar: OK
- LocalDateTime
     - LocalDate/LocalTime: OK
     - Same as above with a calendar: OK
     - year/month/day/hour/minute/second: unnecessary(?) since we could split into LocalDate and LocalTime and then slit again if needed.

What do you think?

**Comment by jskeet** [comment]
Yup, let's do that as a starting point, and we can always add more later. Will update again.

**Comment by jskeet** [comment]
Just looking at Interval, currently Start/End are just Instant, not nullable. Let's overload that for nullable and non-nullable, with the non-nullable throwing for infinite intervals.

**Comment by jskeet** [comment]
Closing, as we're done as far as we want for the moment.
