### ISSUE TITLE
About DateInterval.cs

### ISSUE THREAD

**Issue by mystcreater** [nodatime/nodatime#602]
Hi,

I'm a little bit confuse because when I look at gitup project, I can see the class DateInterval.cs but when I download the binaries from the project website, there is no such type.

Can you help me?

Thanks

**Comment by jskeet** [comment]
Yes, there aren't any stable releases with DateInterval yet. It's going to be in 2.0. You could use an alpha build of 2.0 from nuget.org if you want - but the API may still change a bit before the final release.

**Comment by mystcreater** [comment]
Thanks Jon. By the way, you will soon have 1 million on StackOverflow. I'm wondering how they will display this value :D

**Comment by jskeet** [comment]
Closing this as no further work is required, other than releasing 2.0 :)
