### ISSUE TITLE
Promote v2 to release?

### ISSUE THREAD

**Issue by freever** [nodatime/nodatime#603]
Hi guys

I'm using 2.0.0-alpha20160729 in one of my packages and this prevents me from creating a release version of my package on nuget. Any idea when version 2 will come out of prerelease?

Adrian

**Comment by jskeet** [comment]
We're actively working on it, but it's not ready yet. There are some issues around the time zone SPI that we want to get fixed, and a few niggles - then the new documentation generation.

I *hope* it will be some time in Q1.

**Comment by freever** [comment]
Thanks Jon!
