### ISSUE TITLE
LocalTime text parsing doesn't support ISO 8601 formats

### ISSUE THREAD

**Issue by lundmikkel** [nodatime/nodatime#607]
According to the [ISO 8601 standard regarding times](https://en.wikipedia.org/wiki/ISO_8601#Times):

> either the seconds, or the minutes and seconds, may be omitted from the basic or extended time formats for greater brevity but decreased accuracy: [hh]:[mm], [hh][mm] and [hh] are the resulting reduced accuracy time formats.

These formats are not supported by the `LocalTimePattern.ExtendedIsoPattern`, nor does it seem to be possible at all using a normal pattern text. Furthermore, you cannot even create your own `IPattern<LocalTime>` because the return type `ParseResult<T>` is sealed and only has private constructors (unless you make the pattern a wrapper around the three patterns: `"HH"`, `"HH':'mm"`, and `"HH':'mm':'ss;FFFFFFF"`).

Only including the necessary digits is already supported, but only with fractional seconds. It doesn't seem to be possible with minutes nor seconds.

**Comment by jskeet** [comment]
Right - at the moment this would be a bit of a pain.

We should be able to support it without too much hassle though - we already have the internal mechanism for a composite pattern, where on parsing we try to parse one pattern then another. That would handle parsing, but wouldn't do what you _might_ want for formatting, where you format to the shortest form that doesn't lose information. That will require a bit more code. Not hard to do, but not supported yet. I don't think this should block the 2.0 release - I think I'd expose that as a separate pattern - but it's definitely a useful thing to implement at some point... thanks for raising it.

**Comment by lundmikkel** [comment]
It would be nice to be able to specify it in the pattern. I'm in a situation, where I would like to require minutes, but not seconds. A convention with capital letters as known from fractional seconds could maybe make sense, i.e. `"HH':'mm':'SS;FFFFFFF"`. Not sure if that conflicts with anything else though.

Slightly off topic: it seems that the custom pattern documentation for LocalTime's hours (`h` and `hh`) has a wrong example, which uses capital letters.

**Comment by jskeet** [comment]
Raised #608 for the docs issue. I don't *think* I want to introduce whole extra format specifiers for this, but I may just make sure there are all the patterns you might want...

**Comment by jskeet** [comment]
(This shouldn't have been closed yet, as the type is still internal.)
