### ISSUE TITLE
Detect and remove redundant casts

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime#622]
When looking into #419, I noticed that we have some cases (well, at least one) where we redundantly cast a variable to the same type.

For example, in https://github.com/nodatime/nodatime/blob/cb92068/src/NodaTime/Offset.cs#L410, we have:

```csharp
public static Offset FromMilliseconds(int milliseconds)
{
    Preconditions.CheckArgumentRange(nameof(milliseconds), milliseconds, MinMilliseconds, MaxMilliseconds);
    return new Offset((int) milliseconds / MillisecondsPerSecond);
}
```

(I'm guessing this may have been confused with the `FromTicks(long)` implementation, which returns `new Offset((int)(ticks / TicksPerSecond))`; however, there `ticks` (and `TicksPerSeconds`) are both `long`, so we do need to cast the expression.)

Here, `milliseconds` is already `int`, so unless I'm missing something, this cast can have no effect (`MillisecondsPerSecond` is also `int`, though even if it were `long` the cast here would be irrelevant). It would be nice to detect and remove any redundant casts that we have, since they can mislead readers into thinking that a type coercion is being made where none is.

**Comment by jskeet** [comment]
Could probably do this with a Roslyn analyzer. Might just take a bit of work to do it...

**Comment by malcolmr** [comment]
If we do do this at some point, we can repeat the analysis in #419 to see how many `(long)` casts are no longer needed, were we to change the types of some constants. (That wouldn't actually show whether we'd fixed any bugs, but it might highlight whether or not that change was a good tradeoff at all.)

**Comment by jskeet** [comment]
It turns out that the CodeRush cleanup I did this without me realizing - although I don't think I spotted any occurrences. It does mean that I should be able to repeat the #419 analysis reasonably easily though, just by changing the types of all relevant constants and running cleanup again.

**Comment by jskeet** [comment]
Just tried converting things to long - lots of casts to `int` were required; enough that I got bored.
This would also be a big breaking change, which would be unfortunate for no/little benefit. Closing.
