### ISSUE TITLE
Issue when i try to running with a Plugin in CRM 2016 online

### ISSUE THREAD

**Issue by armore2000** [nodatime/nodatime#629]
Hi to all, 
i have this message when try to use the  library in a plugin in a CRM 2016.
I add the reference and i use ILMERGE to add the NodaTime library in my dll.
I get this message -> Inheritance security rules violated while overriding member: 'NodaTime.Instant.System.Runtime.Serialization.ISerializable.GetObjectData(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)'. Security accessibility of the overriding method must match the security accessibility of the method being overriden. 
Thanks in advance

**Comment by armore2000** [comment]
i should resolved , i had this row in AssemblyInfo
[assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level1)]

**Comment by jskeet** [comment]
Glad you've managed to fix it - will close this.
