### ISSUE TITLE
Unresolved references showing up in Visual Studio 2015

### ISSUE THREAD

**Issue by epsitec** [nodatime/nodatime#632]
If I include the NodaTime v2.0.0-alpha20160729 NuGet package into a .NET Standard 1.3
portable class library, Visual Studio displays three warnings after closing and reopening the project:

> The referenced component 'NodaTime' could not be found.			
> The referenced component 'System.Xml' could not be found.			
> The referenced component 'System.Numerics' could not be found.			

![image](https://cloud.githubusercontent.com/assets/3872435/22051980/5f0930a0-dd47-11e6-820b-60bfdfaf6e5d.png)

[Here](https://github.com/epsitec/rnd-nodatime-ref) is a minimal [example project](https://github.com/epsitec/rnd-nodatime-ref) which demonstrates the issue.

Has this something to do with the tooling, or is there something wrong with the nuget package itself?

**Comment by jskeet** [comment]
It looks like you're using the "csproj + project.json for dependencies" approach, which I'm less familiar with than "project.json + xproj for Visual Studio" but I'd still expect this to be okay. Will clone the project and have a look...

**Comment by epsitec** [comment]
I see this strange behaviour only after I close and reopen Visual Studio. First time, all is nice and clean.

**Comment by epsitec** [comment]
@onovotny any idea?

**Comment by onovotny** [comment]
Based on the following nuspec for the package:

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
    <metadata>
        <id>NodaTime</id>
        <version>2.0.0-alpha20160729</version>
        <title>Noda Time</title>
        <authors>Jon Skeet</authors>
        <owners>Jon Skeet</owners>
        <licenseUrl>http://www.apache.org/licenses/LICENSE-2.0</licenseUrl>
        <projectUrl>http://nodatime.org/</projectUrl>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <description>Noda Time is a date and time API acting as an alternative to the built-in DateTime/DateTimeOffset etc types built into the .NET framework.</description>
        <summary>Noda Time is an alternative date and time API for .NET. It helps you to think about your data more clearly, and express operations on that data more precisely.</summary>
        <tags>date,time,timezone,calendar,nodatime</tags>
        <dependencies>
            <group targetFramework=".NETFramework4.5" />
            <group targetFramework=".NETStandard1.1">
                <dependency id="System.Diagnostics.Debug" version="4.0.11" />
                <dependency id="System.Globalization" version="4.0.11" />
                <dependency id="System.Linq" version="4.1.0" />
                <dependency id="System.Resources.ResourceManager" version="4.0.1" />
                <dependency id="System.Runtime.Extensions" version="4.1.0" />
                <dependency id="System.Runtime.Numerics" version="4.0.1" />
                <dependency id="System.Runtime.Serialization.Xml" version="4.1.1" />
                <dependency id="System.Threading" version="4.0.11" />
                <dependency id="System.Xml.XmlSerializer" version="4.0.11" />
            </group>
        </dependencies>
        <frameworkAssemblies>
            <frameworkAssembly assemblyName="System.Xml" targetFramework=".NETFramework4.5" />
            <frameworkAssembly assemblyName="System.Numerics" targetFramework=".NETFramework4.5" />
        </frameworkAssemblies>
    </metadata>
</package>
```

I can't see why the tooling would be pulling in the references. There's likely a bug in its processing of the frameworkAssembly stuff.

That said, I think it's unlikely to be fixed in 2015 as all of the .NET Standard/.NET Core tooling work is being done in VS 2017.

@Emgarten, any ideas?

**Comment by emgarten** [comment]
The references are coming from NodaTime.targets.
https://github.com/nodatime/nodatime/blob/0d3ee7ac949941706a1cbfc8e5e2c3cc65c20490/packaging/NodaTime.targets#L12-L13

From what I see Visual Studio 2015 or MSBuild is ignoring the condition on the ItemGroup, which should be false for C# and they are added anyways. When I delete the reference elements in my global packages folder copy of the targets file the problem goes away.

NuGet restore ignores all *frameworkAssembly* assets from packages if the project target framework is *netstandard* or *netcoreapp*. For these cross platform frameworks everything must come from packages. So you don't need to worry about them coming in there.
https://github.com/NuGet/NuGet.Client/blob/a2ea65df94a7df96ecf49f4404411e338bcdb8f0/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/LockFileUtils.cs#L128-L139

**Comment by jskeet** [comment]
@emgarten: For those of us less fluent in the details of MSBuild and NuGet, does that suggest my packaging is broken, or that this particular way of using .NET Core (csproj+project.json) is just not quite working?

**Comment by emgarten** [comment]
The packaging and repro project all look correct to me. I think Visual Studio is only partially evaluating the NodaTime.targets file and getting an incorrect result.

Updating the targets file to use a Choose/When instead of a condition on ImportGroup solved the issue for me, and it appears to still work as expected in a C++ project.

Here's the updated targets file I tried: https://github.com/nodatime/nodatime/pull/633

**Comment by epsitec** [comment]
Thanks a lot @emgarten! And @jskeet, does this mean you will push updated NuGet packages of NodaTime in the near future?

**Comment by jskeet** [comment]
@epsitec: Yes, I think we're pretty much ready for a beta build.
@malcolmr: Anything you think we should definitely address before a beta? (I think *most* of the rest of the work is additive. I don't mind some breaking changes post-beta, but I'd like to avoid them if it's easily avoidable.)

**Comment by malcolmr** [comment]
@jskeet I think we're ready. We've got some open issues on organisational stuff (DocFX, the serialization repo), but I don't think those block a beta (and we decided not to do #360, so we don't need a TZDB-data package).

**Comment by jskeet** [comment]
Beta is now in nuget :)

**Comment by epsitec** [comment]
Great, I updated our packages to the new beta and the incorrect references disappeared. Thanks a lot.

**Comment by jskeet** [comment]
Hooray - thanks for the confirmation, @epsitec.
