### ISSUE TITLE
Move website to HTTPS

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime#635]
We should serve nodatime.org from HTTPS (and preferably then only serve 301 redirects from HTTP, with appropriate HSTS [and Content-Security-Policy?] headers).

(Filing this to track the request, but we have no plans to do this immediately.)

**Comment by jskeet** [comment]
We're now on HTTPS and redirecting - not sure about HSTS though.

**Comment by malcolmr** [comment]
HSTS is a good idea iff we can be confident that all requests to the domain can go over HTTPS for a particular time period.

Enabling HSTS does two things:

1. It instructs browsers to treat certificate errors as fatal.
2. It instructs browsers to pre-emptively upgrade HTTP URLs to HTTPS.

The latter is likely to be more useful: after visiting nodatime.org once, any HTTP links you click on for the next _max-age_ time will be client-side redirected to HTTPS, which is more secure, but also slightly faster.

(max-age is typically set to at least six months, though you'd normally start with a smaller value in case you discover something broken.)

**Comment by jskeet** [comment]
Okay... how can I tell whether it's already in place? It's possible that the redirect extension is doing that for us.

**Comment by malcolmr** [comment]
Ah, I wondered if that's what you were asking. No, it's not.

The easiest way to verify is via `curl`: look for the `Strict-Transport-Security` header (which should ideally appear on both HTTP and HTTPS requests, though just the latter would probably be okay in practice).

Note that we cannot assert `includeSubDomains` unless we want to include everything under *.nodatime.org (which we definitely can't do _now_, until we set up HTTPS for blog.nodatime.org, which I'll follow up about separately).

**Comment by jskeet** [comment]
Looks like there's an HSTS site extension we could use, if we decide to...
https://github.com/estei/hsts-site-extension
