### ISSUE TITLE
Can't use ZonedDateTime format specifier 'x' on it's own.

### ISSUE THREAD

**Issue by mthamil** [nodatime/nodatime#636]
I have a use case where I just want the abbreviation of the timezone associated with a ZonedDateTime. It appears that it is not possible to create a format string with just "x".
```c#
    ZonedDateTimePattern.CreateWithCurrentCulture("x", DateTimeZoneProviders.Tzdb);
```
throws an exception:
```
    The standard format "x" is not valid for the NodaTime.ZonedDateTime type.
```

Should this be supported? Is there a way to get the abbreviation directly using the `DateTimeZone`? I didn't see one, since `ToString()` and `Id` return the full zone name. It would make more sense to me to have a `ToString(string)` overload that can take a zone-related format specifier.

**Comment by jskeet** [comment]
x is not a standard format string, so you need to use % to turn the pattern
into a custom pattern:

ZonedDateTimePattern.CreateWithCurrentCulture("%x", DateTimeZoneProviders.Tzdb);

That should work fine.

Jon

**Comment by mthamil** [comment]
Oh, jeez, sorry. Thanks, that works great!
