### ISSUE TITLE
Issue on http://nodatime.org/developer/building

### ISSUE THREAD

**Issue by glittle** [nodatime/nodatime#653]
Just a quick note... this is what I see at [http://nodatime.org/developer/building](http://nodatime.org/developer/building)

![image](https://cloud.githubusercontent.com/assets/85186/23132888/57328312-f74c-11e6-851f-461a1e1fccd0.png)

I can fix the 'hidden' sample text by turning off the 'color' for 'pre':
![image](https://cloud.githubusercontent.com/assets/85186/23132931/80c6fdca-f74c-11e6-8f7b-16d3d54964d2.png)

**Comment by jskeet** [comment]
Thanks - filed https://github.com/nodatime/nodatime/issues/654; will try to
fix it tonight. I admit CSS is generally a bit of a mystery to me - but we
recently changed all code in the user guide from white-on-black to
black-on-white. I suspect this is code written in a different way, e.g.
with an HTML <code> tag instead of Markdown.
<sigh>

Jon

**Comment by jskeet** [comment]
Btw, those build docs are somewhat out of date - if you've got .NET Core installed (SDK 1.0.0-preview2-003121) it should open and build in VS2015 just fine. We'll be updating to the VS2017 tooling when that's released.

**Comment by glittle** [comment]
Yes, without .NET Core installed it has a 'few' (1451) errors!

**Comment by glittle** [comment]
Is this the one that is needed to compile?  https://github.com/dotnet/core/releases/tag/1.0.0

**Comment by jskeet** [comment]
Looks like it, yes.

**Comment by jskeet** [comment]
Fixed now, but you may need to force refresh (e.g. Shift-F5) to get the new stylesheets and Javascript.

**Comment by glittle** [comment]
Yup, looks good:
![image](https://cloud.githubusercontent.com/assets/85186/23139870/e07a383a-f76b-11e6-8936-5ee40331efcf.png)
