### ISSUE TITLE
Unseal NodaPatternConverter

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#656]
While most of the time we wouldn't expect to derive from it, when specifying a particular converter for a property using `[JsonConverter]`, you have to identify a converter by type... which is much more easily done if you can just subclass `NodaPatternConverter`.

**Comment by jskeet** [comment]
Alternative approach: keep `NodaPatternConverter` sealed, but introduce a new abstract base class which just delegates.

Sample implementation on http://stackoverflow.com/questions/42351272

**Comment by Xcodo** [comment]
:+1:
