### ISSUE TITLE
Accessing DocFx generated xrefmap.yml for NodaTime

### ISSUE THREAD

**Issue by josh-green** [nodatime/nodatime#693]
We're migrating our documentation to DocFx and are trying to cross reference the NodaTime API. Is the xrefmap.yml for each version of the API generated and hosted or is it excluded by the nodatime website route mapping? I wasn't able to see any explicit exclusion but also couldn't locate it on the nodatime.org site.

Any guidance would be appreciated!

**Comment by jskeet** [comment]
Gosh, didn't know how all of that could work. I can't see an `xrefmap.yml` in my local version - is this a new feature of docfx? (Perhaps I just need to update the version I'm using...)

**Comment by jskeet** [comment]
(I'd definitely like to make this work for you :)

**Comment by josh-green** [comment]
It was generated by default under the root of the `_site` folder for us. We were looking to use it as described [here](https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html?q=xref#cross-reference-between-projects) by adding an xref in the format "http://nodatime.org/1.3.x/xrefmap.yml".

**Comment by jskeet** [comment]
Okay - will look into it, thanks. It could be that I'm just not copying it as part of my build for some reason. (The fact that there are multiple versions may complicate things too...)

**Comment by jskeet** [comment]
Ah, it looks like we *are* generating them, but all at the top level - see 
https://github.com/nodatime/nodatime.org/blob/master/docfx/1.3.x.xrefmap.yml

... and I suspect we're not serving them at the moment because ASP.NET Core needs to be told to allow them. Will sort that out, then give you the URL to look for.

**Comment by jskeet** [comment]
Right, it's deployed now. The file you want is
http://nodatime.org/1.3.x.xrefmap.yml

Let me know if you have any further problems.

**Comment by josh-green** [comment]
Thanks for this, a great enhancement to our documentation!
