### ISSUE TITLE
Front page links to downloadable archives are wrong

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime#696]
```html
<h6>Source and binary archives are available for download</h6>
<ul>
  <li><a href="https://storage.googleapis.com/nodatime/releases/NodaTime-1.3.4-src.zip">NodaTime-1.3.4-src.zip</a></li>
  <li><a href="https://storage.googleapis.com/nodatime/releases/NodaTime-1.3.4-src-src.zip">NodaTime-1.3.4-src-src.zip</a></li>
  <li><a href="downloads/">All downloads</a></li>
</ul>
```

The first link works, but is supposed to be the second; the second doesn't work.

The links on `/downloads/` appear correct.

**Comment by malcolmr** [comment]
I suspect this is as simple as being non-deterministic as to whether `LatestRelease` selects the `.zip` or `-src.zip` object in https://github.com/nodatime/nodatime/blob/ba88ea6da72480b4c3618a025a215658ef3617ce/src/NodaTime.Web/Models/GoogleStorageReleaseRepository.cs#L73.

**Comment by jskeet** [comment]
Yup, it's an easy fix - now implemented, but can't easily test on the train.
