### ISSUE TITLE
Should create tags (/releases) for TZDB-only releases

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime#704]
The TZDB-only releases 1.3.3 and 1.3.4 don't currently have Git tags, and don't appear in e.g. https://github.com/nodatime/nodatime/releases. They probably should do.

**Comment by jskeet** [comment]
There's nothing to tag, really - we don't make any commits back into github with these "TZDB-only" updates. We potentially *could* do so, but at the moment I think it's okay to just update the version history.

**Comment by malcolmr** [comment]
It's still useful to be able to check out the code that was packaged in 1.3.4, though, rather than have to guess that it was the same as 1.3.2.

**Comment by jskeet** [comment]
Hmm. One downside is that if we *do* create a tag and someone checks out the code, they'll get the old version of tzdb.nzd.

Maybe we should actually create appropriate commits in the different branches and tag them.

**Comment by malcolmr** [comment]
SGTM. I like the idea of being able to regenerate the build from the repository (assuming the same NuGet dependencies).

**Comment by jskeet** [comment]
Given that this is going to get more and more involved with the 2.0 and then 1.4 branches, I think I'll create a whole subdirectory of build/ specifically for this. But maybe not today :)

**Comment by jskeet** [comment]
I've created the relevant tags/commits/releases for 1.3.3 and 1.3.4, but I haven't (yet) written the scripts to do this automatically for the future.

**Comment by jskeet** [comment]
We now have scripts for 1.3.x and 2.0.x that do a local commit and create a tag, and output what should be done afterwards (with GCS and github). It only creates tags rather than releases though. I suggest we do that manually for the next TZDB release or two, and see how much further we want to automate it.

**Comment by jskeet** [comment]
Closing this for now - we can create new issues for the remaining automation once we see what's needed.
