### ISSUE TITLE
Update our web site dependency packages

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#711]
We're using old versions of Zepto, jQuery, Foundation etc - and almost certainly not using them in a way that's idiomatic for ASP.NET Core. (We should just be able to list them somewhere, I suspect....)

**Comment by jskeet** [comment]
Okay, I've looked into this a bit.

In order to update to Foundation 6 (the current version) we'll need to tweak all our styles. I'm not competent to do this on my own (even though it's really just the _Layout that needs tweaking...

**Comment by jskeet** [comment]
There's now a "bower" branch which is ugly as heck, but a reasonable start. Once we know what files we want, we can work out how to actually merge into master.

A few notes, so that Malcolm can have a go at making it look pretty:

- highlight-js is in a handlib directory as the Bower package is more a "package for making Javascript" than a ready-to-go highlighter, I think
- I've just noticed that we still have the foundicon fonts in the fonts directory. I think they can go now.
- Likewise images/conversions.png may well be redundant...
- Eventually we may want to remove the lib directory from git, so it's just restored on build
- On startup, the site looks on Google Cloud Storage for releases and TZDB files. The simplest way of handling that is to download a service account json file and set GOOGLE_APPLICATION_CREDENTIALS for it, or using `gcloud auth application-default login`; either way, let me know an account that needs access to the storage bucket. Maybe we should have a way of developing the site without this...
- You'll need a `docfx` directory which is normally built with `buildweb.sh`, but it's simplest just to grab a copy from https://github.com/nodatime/nodatime.org
- The files you'll want to edit most are likely to be:
  - Views/Documentation/Doc.cshtml
  - Views/Home/Index.cshtml
  - Views/Shared/_Layout.cshtml
  - wwwroot/css/main.css

**Comment by malcolmr** [comment]
Having spent a little time with this tonight, I think I'm going to try dealing with this a slightly different way:

- while we could theoretically use Bower to pull foundation, Bower itself doesn't intend to give you a prebuilt binary, and Foundation 6 requires a load of build support, so I'd suggest instead that we download the prebuilt version from http://foundation.zurb.com/sites/download/ instead (which is where we originally pulled the version we're using, which I think is 4.2.1).
- we might find it easier to upgrade to Foundation 5 first: there's a [migration guide for that](http://foundation.zurb.com/sites/docs/v/5.5.3/upgrading.html).
- it might be nice to pull together the various snippets we have into `site.js`, then actually use the bundled/minified output in production mode.

**Comment by jskeet** [comment]
All makes sense to me :)
