### ISSUE TITLE
nodatime.org/api/ and /userguide/ "latest" redirects still use 1.3.x

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime#753]
```sh
$ curl -si http://nodatime.org/api/ | grep Location
Location: http://nodatime.org/1.3.x/api/
$ curl -si http://nodatime.org/userguide/ | grep Location
Location: http://nodatime.org/1.3.x/userguide/
```

Now that 2.0 is out, these version-less URLs should redirect to 2.0.x.

**Comment by jskeet** [comment]
Ouch. I thought I'd fixed those. Will send a PR in a minute.
It probably won't be deployed until I'm on top of the more general web site issues though...
