### ISSUE TITLE
Consider 2.0.1 release

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#774]
Think about what we'd want in a 2.0.1 release, and add commits here to merge in. (This is a task list so we can tick when we've merged each part.)

- [ ] 0330fa6d1dfbf062a12cbd6261b7bde170f72f8a which stops Mono from breaking on Linux with Feb 29th rules
- [ ] fe702128f1a6b4fff253f2676e7b2d5639b7b0a2 which fixes #801 (LocalDate constructor validation)
- [ ] 2d48b2998434d8c4fc478a923f7f5281a6d5bfe2 which fixes #807 (LocalTime constructor validation)

**Comment by malcolmr** [comment]
#777 introduces a new method, so I think it would have to be in a 2.1.0?

**Comment by jskeet** [comment]
Well, it's a new method but it's not new *functionality*. But your back-compat argument makes sense. It also fits in with semver.org:

> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API. It MUST be incremented if any public API functionality is marked as deprecated. [...]

Will remove #777 from the list.
