### ISSUE TITLE
IsoDayOfWeekExtensions.ToIsoDayOfWeek naming error

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#776]
It should obviously be ToDayOfWeek.

**Comment by cypressious** [comment]
This means, a `ToIsoDayOfWeek`, that actually does what the name says, can't be added, right?

**Comment by jskeet** [comment]
No, that method already exists: http://nodatime.org/2.0.x/api/NodaTime.Extensions.DayOfWeekExtensions.html#NodaTime_Extensions_DayOfWeekExtensions_ToIsoDayOfWeek_System_DayOfWeek_

It's fine for both to exist because they have different parameter types.

**Comment by cypressious** [comment]
I see, thanks.
