### ISSUE TITLE
Obsolete Windows Zone ID <-> TZDB Zone ID (IANA) Mapping

### ISSUE THREAD

**Issue by robloo** [nodatime/nodatime#778]
I am mapping Windows TZInfo IDs to IANA zone IDs in my project using nodatime. I think this project is great for things like this and really appreciate your work! However, old/obsolete time zones are not mapped. This really needs to be supported since I have no control over what a user's windows OS version is, if they are updated to the latest zones (commonly changed by windows updates), or what they might even select in the UI (old entries are still enumerated by TimeZoneInfo.GetSystemTimeZones() with no flag indicating 'Old' zones other than the display name ending in 'Old' which doesn't work since this string is localized).

The root issue has nothing to do with your library, the issue is these obsolete zones aren't in the underlying CLDR "windowsZones.xml" data. I've been having a discussion with yoshito on the CLDR team about this and would really appreciate input from other projects. I think it would be very useful to include obsolete TZInfo mapping information in the CLDR data and then to NodaTime itself. This may require some changes to data structures and it would be best for other input on this from projects that use it directly.

The CLDR ticket is: http://unicode.org/cldr/trac/ticket/10117

**Comment by jskeet** [comment]
I can see the appeal, although I find it interesting that my tests that make sure all time zones on my Windows system *are* mapped still work - with a very few hard-coded exceptions.

I think we'd probably want to have an "obsolete mapping" section in the NZD file. Would you propose mapping those obsolete zone IDs to other Windows IDs, or directly to TZDB IDs?

**Comment by robloo** [comment]
> I can see the appeal, although I find it interesting that my tests that make sure all time zones on my Windows system are mapped still work - with a very few hard-coded exceptions.

Well there aren't too many obsolete zones -- maybe a dozen by yoshito's estimate. Perhaps the hard-coded exceptions you have cover the zones that are exposed with the windows version you are running on the test system. This is part of the issue though, there is different registry data (and therefore different results) depending on the version of Windows the code is running on.

I have a unit test as well that fails which is what got me started on this whole topic. The latest results of this test now have failures at the following (note, some are simply newly added with the Windows 10 Creators Update)

**New for Windows 10 Creators Update**

Id = "Magallanes Standard Time"
DisplayName = "(UTC-03:00) Punta Arenas"

Id = "Saratov Standard Time"
DisplayName = "(UTC+04:00) Saratov"

Id = "UTC+13"
DisplayName = "(UTC+13:00) Coordinated Universal Time+13"

**Obsolete but still listed**

Id = "Mid-Atlantic Standard Time"
DisplayName = "(UTC-02:00) Mid-Atlantic - Old"

Id = "Kamchatka Standard Time"
DisplayName = "(UTC+12:00) Petropavlovsk-Kamchatsky - Old"

The topic of this issue is for the Obsolete but still listed zones. These are zones that still exist in the registry from past installations but are no longer added with newer versions of windows. Since Windows doesn't delete time zones from the registry, they will still appear after each update even when you have the newer zones as well. They would also appear if the system is running an older version of the OS.

Note that the two obsolete zones above are what has been deprecated since Windows 10 was first released. Ideally we would need to support all the way back to at least Windows 7 though.

> I think we'd probably want to have an "obsolete mapping" section in the NZD file. 

Yes, I'm trying to get this added by the CLDR team to the "WindowsZones.xml" data file directly. Then everyone else can benefit from this discussion. I'm not sure it will be successful but let's see. That's where other's opinions on data structures might help too.

> Would you propose mapping those obsolete zone IDs to other Windows IDs, or directly to TZDB IDs?

Can we make the assumption that an obsolete Windows zone will always be replaced by a newer zone? It seems like a safe assumption right now but who knows in the future. It might be better to just treat an obsolete Windows ID as a completely separate time zone which was my initial thinking. So I would propose mapping obsolete Windows IDs directly to TZDB IDs.

That said, I have to convert both ways TZDB_ID<->Windows_ID.  So it would seem we never want a TZDB ID to map to an obsolete windows zone; however, it's possible a system only has an obsolete zone. Then it might also make sense to have the obsolete windows zone to new Windows zone information (perhaps as another Dictionary). Then I could do the initial mapping TZDB_ID->Windows_ID, check if the windows ID actually exists on the system, and if not, check if any equivalent windows IDs exist.

This probably needs to be thought through a bit more so any other ideas are more than welcome.

**Comment by jskeet** [comment]
Yes, I would probably add it as an extra field in the NZD file, and a separate dictionary in `TzdbDateTimeZoneSource`. I probably wouldn't change any *default* lookups, but we could add a method which considers default time zones as well - I'll look at that when I get to it.

I think we can probably just use our existing data, loading all the CLDR files we have, and taking the most recent target of any ID that isn't in the current file.

**Comment by robloo** [comment]
This was closed CLDR as _wontfix_. CLDR ticket is: http://unicode.org/cldr/trac/ticket/10117

> As per comment by Gresla comment 10, there are only two zones impacted by this, and this is dealing with historic timezone support. This would require a schema change in CLDR, and for historic timezone support, which is also not support in Windows timezone anyways. 
It would not be a high priority for us.
> - kristi

Seems like you might want to follow suite. Although, you could add some special code to handle the two given cases:

Kamchatka Standard Time (UTC+12:00) Petropavlovsk-Kamchatsky - Old
Mid-Atlantic Standard Time (UTC-02:00) Mid-Atlantic - Old

**Comment by jskeet** [comment]
Thanks for the update. I'll take another look at the structure we've got and see how hard it would be to add information for these obsolete zones. I wouldn't want them to be confused with the current ones though.

**Comment by jskeet** [comment]
Closing for now, as if CLDR doesn't deem it a problem, it's probably not big enough to be worth adding to our file format. We can definitely revisit this if it becomes a more pressing issue, e.g. due to later versions of Windows removing a bunch of zones.
