### ISSUE TITLE
Make Instant and Duration blittable

### ISSUE THREAD

**Issue by buybackoff** [nodatime/nodatime#789]
Could you please add sequential layout to all struct so that arrays of them will be pinnable? The fact that DateTime in .NET is not blittable is a major inconvenience - I often need to pin arrays of them for native interop and have to convert them to `long[]`.

Hopefully Nodatime is stable enough at v.2 to rely on the layout of Duration and Instant. Attribute properties `Pack = 4, Size = 12` are also needed to guarantee deterministic memory layout.

**Comment by jskeet** [comment]
Pinning is one thing - but I'm not sure I want users relying on the internal representation, or that representation not changing in a new minor release. There could easily be small modifications.

Can you go into more detail about *exactly* what you'd be wanting to do? Note that some structs also contain reference types (possibly only `ZonedDateTime`), which affects the size.

**Comment by buybackoff** [comment]
I have a fast native compressor that requires arrays to be pinned to use PInvoke. [This is how](https://github.com/Spreads/Spreads/blob/master/src/Spreads.Core/Serialization/CompressedArrayBinaryConverter.cs#L136) I handle `DateTime` now. For `Instant` I will have to do the same if it has auto layout. I already have a dependency on Nodatime in that project, so this issue is not blocking and I could add another special case, but I prefer not to do so. And actually that would not be meaningful if, as you say, the layout could change.

`Instant` and `Duration` are the only two struct that I care. And Duration only because `Instant` has it as a field. They are probably simple and robust enough to set the `int+long` layout in stone and rely on it in the future?

**Comment by jskeet** [comment]
I still wouldn't want to set that in stone, no. I'd be happy enough to specify the `StructLayout`, but I wouldn't want to view it as a breaking change for that to be affected by later changes. I don't have any *plans* to change it, but within the 1.x timeline I believe we made some representational changes like this (and massive representational changes in 2.x).

Oh - and I'd also want to check that using a layout of sequential doesn't create performance problems. I may need to reverse the order of the fields before doing it, for example.

**Comment by buybackoff** [comment]
StructLayout with proper Pack/Size will be just enough. And as far as I understand, auto layout puts long before int and has padding to IntPtr, therefore Pack=4 and Size = 12 are needed to make it "blittable" and not just "pinnable". In an array every other element will have `long` field not aligned to IntPtr on x64, and every 6th elements will cross a cache line boundary.

Currently the actual size is 16 (`Unsafe.SizeOf<NodaTime.Instant>()`). You may consider putting `long` before `int` and add `int` padding at the end. That **will not** increase memory size compared to the current design, avoids any alignment issues and reserves space for any future modifications. In that case explicit layout will be even more appropriate and will actually match to the current `auto` one. I do not like the size 12 for the alignment reasons, and the mentioned compressor will compress empty padding by near 100% due to byte shuffling.

I think adding a reserved padding is just enough to set the current implementation in stone - it could be considered as a layout version of zero (some bits of it at least, other bits could be used for additional functionality). If ever the layout will have to change, persisted data will not have to be re-encoded to the new format, only code will require some changes.

**Comment by jskeet** [comment]
If the layout changes later, that may well be due to very different representation changes. I'm certainly not going to guarantee that persisted raw data will be valid across minor versions.

Will look at the rest when I get some time, but it's not likely to be very soon.

**Comment by buybackoff** [comment]
OK, thanks! In the meantime I will just create a blittable wrapper with `long + int + int`.

**Comment by jskeet** [comment]
I think I'll want to tie this to the [C# 7.2 blittable types feature](https://github.com/dotnet/csharplang/pull/206/files).

I don't intend to give any guarantees about long-term stability of bitwise representation, but there are still interop benefits from the types being blittable.

**Comment by jskeet** [comment]
Blittable types didn't make it into C# 7.2 in the end.

@buybackoff: Is this whole issue something that you think I should keep around, or would you be happy for me to close it? I'm somewhat nervous of even specifying a `StructLayout` as I can see it being quite brittle.

**Comment by buybackoff** [comment]
I am storing time and duration now as unix utc nanos in Int64, and use
Nodatime for historical time zone calculations. Please close the issue if
you wish. Thanks for looking into this!

**Comment by jskeet** [comment]
Thanks - I'll close it for now, but we can always revisit if there's more demand.
