### ISSUE TITLE
NodaTime 2.0 binary serialization using Orleans

### ISSUE THREAD

**Issue by jkonecki** [nodatime/nodatime#803]
I'm using NodaTime in a project based on Microsoft Orleans. I've started getting `System.Security.VerificationException` exceptions after upgrading from NodaTime 1.3 to 2.0.
Orleans uses custom serializer. I didn't have any problems with 1.3

![image](https://cloud.githubusercontent.com/assets/1775247/25445015/0241fae0-2aa5-11e7-90a9-303edc4711dd.png)

**Comment by jkonecki** [comment]
[HelloWorld.zip](https://github.com/nodatime/nodatime/files/959148/HelloWorld.zip)
Repro attached. Please open HelloWorld.SeparateProcess.sln and follow instructions from readme:

>   Orleans client and Orleans silo host are configured in two different projects, and hence Orleans client and silo host are running in separate processes.
> To start this sample, you need to set both project OrleansClient and OrleansSiloHost as Startup project. 
> You can do this by going to the 'Properties' option for HelloWorld.SeparateProcess.sln, abd under 'Common Properties' -> 'Startup Project', choose 'Multiple startup projects'. Set OrleansClient and OrleansSiloHost to 'Start'

**Comment by jskeet** [comment]
Is there no way of reproducing this just by asking Orleans to serialize an object without any sort of networking?

**Comment by jkonecki** [comment]
Possibly - let me try

**Comment by jskeet** [comment]
Much appreciated - if you don't make progress, I should have time to try tonight.

**Comment by jkonecki** [comment]
[orleans.zip](https://github.com/nodatime/nodatime/files/959254/orleans.zip)

Please open `src\Orleans.sln`
I've added a unit test in `test\DefaultCluster.Tests\SerializationTests\SerializationTests.cs` - `Serialization_NodaTime()`.
If you debug the test you will get the exception thrown in Orleans source code which I hope will help you.

**Comment by jkonecki** [comment]
I did some more testing and found out that the breaking change was introduced in package *2.0.0-alpha20150728*. Previous package *2.0.0-alpha20140808* works fine. That should narrow it down to a year ;-)

**Comment by jskeet** [comment]
Right, thanks. Will give that a try.

**Comment by jskeet** [comment]
Okay, well I've reproduced the issue, but given the complexities of Orleans (and the codegen side) it's *really* hard to tell what's going on. Do you know anyone on the Orleans team that might be able to help?

**Comment by jskeet** [comment]
@gabikliot any thoughts on how to debug this? Could it have the same cause as https://github.com/dotnet/orleans/issues/2049?

**Comment by ReubenBond** [comment]
The issue is with how I'm creating the `DynamicMethod` used to copy the `LocalDate` field.

@jskeet, this is not a NodaTime question, but maybe you can shed some light on how the CLR works for me? I created a StackOverflow question for it: http://stackoverflow.com/questions/43646430/creating-a-dynamicmethod-to-set-a-readonly-field-on-any-type

Here's the repro: [Repro.zip](https://github.com/nodatime/nodatime/files/960073/Repro.zip)

**Comment by jskeet** [comment]
Unfortunately, I don't have an answer to that - it seems pretty reasonable for the CLR to prohibit this kind of thing, to be honest.
