### ISSUE TITLE
Can create LocalTime with 60 or 61 seconds

### ISSUE THREAD

**Issue by DmitryMak** [nodatime/nodatime#807]
I expect this to throw ArgumentOutOfRangeException, but it doesn't:

new LocalTime(13, 58, 61);

Instead it creates instance that represents 13:59:01

NodaTime (2.0.0)

**Comment by jskeet** [comment]
Ooh, that's definitely a new one. Will investigate.

**Comment by jskeet** [comment]
Found the bug; writing tests for the 5 identical cases.
