### ISSUE TITLE
Latest Version not Compatible with Portable Library (Profile 259)

### ISSUE THREAD

**Issue by SpiegelSoft** [nodatime/nodatime#822]
When I try to upgrade from Version 1.3.4 to Version 2.0.1, the system fails with a message that Profile 259 is not supported, although it was supported in Version 1.3.4.

**Comment by jskeet** [comment]
We've moved from PCLs to netstandard - we support netstandard1.3 at the moment.

Are you referring to NodaTime *from* a PCL? If so, I don't honestly know what the support for that is like at the moment - I'll try to find out. If it's just a problem of our netstandard support being too high a level (i.e. not netstandard1.0) then I can *try* to work out a way of reducing it. If it's a matter of this kind of interop just not being support, I'm not sure what the best approach is.

For the moment I'd suggest just sticking with 1.3.4 - is there anything in 2.0 that you specifically want, or was it just a matter of (understandably) wanting to be on the latest release?

**Comment by jskeet** [comment]
I looked into this briefly, and no, I don't believe there's any way of doing this. I'd stick with 1.3.x - I really don't expect to start building PCLs in addition to netstandard libraries.
