### ISSUE TITLE
Add OffsetDateTime.InZone(tz) ?

### ISSUE THREAD

**Issue by mj1856** [nodatime/nodatime#843]
Currently:
```csharp
ZonedDateTime zdt = offsetDateTime.ToInstant().InZone(tz);
```

Any reason not to add `InZone` directly on `OffsetDateTime`?
```csharp
ZonedDateTime zdt = offsetDateTime.InZone(tz);
```

**Comment by jskeet** [comment]
Could do. Would you expect it to just do that, or validate that in the given zone it still has the original offset?

**Comment by jskeet** [comment]
Just looking over the issue list again - Matt, any more thoughts on the validation question? To put it another way, here are two implementations:

**No validation**

```csharp
public ZonedDateTime InZone(DateTimeZone zone) =>
    ToInstant().InZone(Preconditions.CheckNotNull(zone, nameof(zone));
```

**With validation that original offset is result offset**

```csharp
public ZonedDateTime InZone(DateTimeZone zone)
{
    Preconditions.CheckNotNull(zone, nameof(zone));
    var zoned = ToInstant().InZone(zone);
    Preconditions.CheckArgument(zoned.Offset == Offset, nameof(zone),
        "Offset incorrect for specified zone"); // TODO - better error message
    return zoned;
}
```

**Comment by mj1856** [comment]
IMHO, offset validation isn't necessary here.  At least, I wouldn't be thinking about that when I called this function, because it's convertible to Instant.

**Comment by jskeet** [comment]
Fair enough. Will whip up a PR... Maybe not while jetlagged though.
