### ISSUE TITLE
NodaTime negative impact on serialisation perf

### ISSUE THREAD

**Issue by willdean** [nodatime/nodatime#844]
I'm not trying to be a pain about perf, but I've seen NodaTime appear in some new profile results, and on investigation, it seems that using `ConfigureForNodaTime` settings has a significant impact on Json.NET serialisation performance, *even when you're not serialising NodaTime types*.

I have a simple benchmark that does some variants of 
`JsonConvert.SerializeObject(new { tm = _instant }, _settings);` 

Sometimes _tm is set to a `DateTime` rather than a `Instant`, and I either do or don't include `_settings` in the call.

These are the results:
```
                           Method |       Mean |    Error |    StdDev | Scaled | ScaledSD |  Gen 0 | Allocated |
--------------------------------- |-----------:|---------:|----------:|-------:|---------:|-------:|----------:|
 SerializeDateTimeWithoutSettings |   890.2 ns | 11.56 ns |  10.81 ns |   1.00 |     0.00 | 0.3605 |   1.11 KB |
  SerializeInstantWithOutSettings | 1,719.1 ns | 34.18 ns |  33.57 ns |   1.93 |     0.04 | 0.5093 |   1.57 KB |
    SerializeDateTimeWithSettings | 3,286.9 ns | 64.51 ns | 104.17 ns |   3.69 |     0.12 | 0.4196 |    1.3 KB |
     SerializeInstantWithSettings | 2,863.0 ns | 57.10 ns |  72.21 ns |   3.22 |     0.09 | 0.5226 |   1.62 KB |
```
Obviously these aren't all serialising to the same text: the two `DateTime` versions are the same, but `Instant` only serialises properly if you include `_settings` - without it you get the members of Duration separately serialised.

It seems pretty obvious from the DotTrace picture below what the problem is - `NodaConverterBase` needs to find a smarter way to answer the `CanConvert` question than reaching for the reflection sledgehammer.  The obvious thing feels like a static dictionary cache of results, but one would need to think a bit about concurrency and whether there was some pathological bazillion-types scenario which could cause it to explode in length.

I think this is quite important because of the way that it impacts non NodaTime types so badly.

![nt2](https://user-images.githubusercontent.com/1306085/26902965-296dfc78-4bd3-11e7-9ade-1cc0beefa924.PNG)

**Comment by jskeet** [comment]
There was a PR raised about this on the serialisation repo, but attempts to
improve it didn't get anywhere. Happy to have a look, but it may be an
issue of Json.NET simply calling it far more than is reasonable.

**Comment by willdean** [comment]
@jskeet I'll go and look that up, thanks.  It's grim as it is - I already have too many sets of Json.net options for different things, I don't want to have to double that list by trying to guess if I need NT or not in there each time.

**Comment by jskeet** [comment]
Have been thinking about this overnight, and we may be able to just use reference comparisons due to the kind of types we're converting. Need to check properly.

**Comment by jskeet** [comment]
Closing here as I've re-raised in the serialization repo.
