### ISSUE TITLE
Incorrect mappings for some years in timezone "America/Los_Angeles" of TZDB provider?

### ISSUE THREAD

**Issue by kazakm** [nodatime/nodatime#845]
I see unexpected results for some years (e.g. 1963 and 1974) when trying to validate whether a date represents a correct local date when I use timezone "America/Los_Angeles" of TZDB provider . The logic works as expected when I use "America/Vancouver" timezone.

The following code demonstrate the problem where tests 1, 2 and 4 fail.

Please advise.

``` C#
[TestCase("America/Los_Angeles", "1963-04-28 01", ExpectedResult = true)]
[TestCase("America/Los_Angeles", "1963-04-28 02", ExpectedResult = false)]
[TestCase("America/Los_Angeles", "1974-04-28 01", ExpectedResult = true)]
[TestCase("America/Los_Angeles", "1974-04-28 02", ExpectedResult = false)]
[TestCase("America/Los_Angeles", "1974-04-28 03", ExpectedResult = true)]
[TestCase("America/Los_Angeles", "1985-04-28 01", ExpectedResult = true)]
[TestCase("America/Los_Angeles", "1985-04-28 02", ExpectedResult = false)]
[TestCase("America/Los_Angeles", "1985-04-28 03", ExpectedResult = true)]
[TestCase("America/Vancouver", "1963-04-28 01", ExpectedResult = true)]
[TestCase("America/Vancouver", "1963-04-28 02", ExpectedResult = false)]
[TestCase("America/Vancouver", "1974-04-28 01", ExpectedResult = true)]
[TestCase("America/Vancouver", "1974-04-28 02", ExpectedResult = false)]
[TestCase("America/Vancouver", "1974-04-28 03", ExpectedResult = true)]
[TestCase("America/Vancouver", "1985-04-28 01", ExpectedResult = true)]
[TestCase("America/Vancouver", "1985-04-28 02", ExpectedResult = false)]
[TestCase("America/Vancouver", "1985-04-28 03", ExpectedResult = true)]
public bool IsLocalDateValid(string timeZone, string localDate)
{
	var timeZoneMapping = DateTimeZoneProviders.Tzdb[timeZone].MapLocal(
		LocalDateTime.FromDateTime(DateTime.ParseExact(localDate, "yyyy-MM-dd HH", null)));
	return timeZoneMapping.Count > 0;
}
```

**Comment by jskeet** [comment]
Before I start looking anything up, where do your expectations come from?

**Comment by kazakm** [comment]
https://www.timeanddate.com/time/change/usa/los-angeles
https://www.timeanddate.com/time/change/canada/vancouver

**Comment by jskeet** [comment]
Thanks, will look into it. Is this using the latest release?

**Comment by kazakm** [comment]
Yes - 2.0.2

**Comment by jskeet** [comment]
I believe timeanddate.com is just wrong here. If you look at the rules here:
https://github.com/eggert/tz/blob/master/northamerica#L480

These are the relevant ones:

```
Rule	CA	1950	1966	-	Apr	lastSun	1:00	1:00	D
Rule	CA	1950	1961	-	Sep	lastSun	2:00	0	S
Rule	CA	1962	1966	-	Oct	lastSun	2:00	0	S
```

As you can see, the "spring forward" rule occurs at 1am, not 2am.

I suspect timeanddate.com is using old data, from before [this commit](https://github.com/eggert/tz/commit/e88b8147d88b56e771f7e1738ae83d3fdf69cb09). That commit was part of the 2016g release.

**Comment by kazakm** [comment]
Thank you very much for your clarification!

**Comment by jskeet** [comment]
It's always fun to investigate this sort of thing :)
