### ISSUE TITLE
Migration 1.3 => 2.0 - Operator '<' cannot be applied to operands of type 'ZonedDateTime' and 'ZonedDateTime'

### ISSUE THREAD

**Issue by eriksteinebach** [nodatime/nodatime#846]
Hi, 

I am migrating our site from 1.3 to 2.0 and I am running in the error "Operator '<' cannot be applied to operands of type 'ZonedDateTime' and 'ZonedDateTime'". Which makes sense as I can see [here](http://nodatime.org/2.0.x/api/changes.html) that the operator < has been removed. 

I am comparing two ZonedDateTime objects (with the same timezone) with each other.  I can't figure out why this would be a problem? Maybe for objects in different timezones. How do I compare these values in NodaTime 2.0? I think I could use ZonedDateTime.Comparer.Local.Compare, but this doesn't really improve the readability of the code. Is there a better way?

Thanks!

**Comment by jskeet** [comment]
Well how do you *want* to compare them? Basically there's no clear unambiguous way of doing it - particularly for values in different zones but for the same instant, which aren't equal but aren't more or less than each other either.

**Comment by eriksteinebach** [comment]
One example:
We have assignments, where for the start time is stored in the database in the time of the professor (together with his timezone). 

This code is shows a list of future assignments for a student:

var now = SystemClock.Instance.Now.InZone(userTimeZone);
Repo.Assignments.Where(x => ...).Where(x => x.GetStartTime(userTimeZone) > now).ToList() 

public static ZonedDateTime GetStartTime(this Assignment assignment, DateTimeZone userTimeZone)
        {
            var creatorTimeZone = DateTimeZoneProviders.Tzdb.GetZoneOrNull(assignment.CreatorTimeZoneId);
            var creatorStartTime = LocalDateTime.FromDateTime(assignment.CreatorLocalStartTime).InZoneStrictly(creatorTimeZone);
            return creatorStartTime.WithZone(userTimeZone);
        }

This works in 1.3 (as far as I know), but how would I do this in 2.0?

**Comment by jskeet** [comment]
To be honest, I'd avoid converting the current instant into a `ZonedDateTime` - just compare instants instead:

```csharp
var now = SystemClock.Instance.GetCurrentInstant();
var assignments = Repo.Assignments
    .Where(x => ...)
    .Where(x => x.GetStartTime(userTimeZone).ToInstant() > now)
    .ToList()
```

**Comment by eriksteinebach** [comment]
Makes sense, thanks. To go a little furtther, now I have a course and the assignment in that course and I want to check if the assignment start time is between the start/end time of the course. So in that case I should instead of converting all to ZonedTimeZones (like I do in 1.3), convert to Instants and compare those?

**Comment by jskeet** [comment]
Either that, or use `ZonedDateTime.Comparer.Instant` to compare the values.
