### ISSUE TITLE
Should document equality and ordering consistently

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nodatime/nodatime#85]
```
The way that equality and ordering are documented for types is inconsistent: in 
some cases, we document equality on Equals(object) explicitly [e.g. 
OffsetDateTime, Period]; in some cases, on the class [DateTimeZone, somewhat]; 
in some cases, not really at all [Duration, though the class documentation 
implies an obvious equality].

Ordering is even less-well documented.

We should be consistent about how and where we document both equality and 
ordering for types.
```

Original issue reported on code.google.com by `malcolm.rowe` on 13 Jul 2012 at 8:29

**Comment by jskeet** [comment]
Let's get this one done. I suspect that documenting equality and ordering in the class description, then adding a note in the equality/ordering methods. I'll add another comment here with a check list of classes to do this for.

**Comment by jskeet** [comment]
Comparable and/or equatable types:

- [ ] AnnualDate
- [ ] Duration
- [ ] Instant
- [ ] LocalDate
- [ ] LocalDateTime
- [ ] LocalTime
- [ ] Offset

Just equatable

- [ ] DateInterval
- [ ] Interval
- [ ] OffsetDate
- [ ] OffsetDateTime
- [ ] OffsetTime
- [ ] Period
- [ ] MapZone, Country
- [ ] ZoneInterval
- [ ] ZonedDateTime
