### ISSUE TITLE
API docs use <pre><code> for inline code

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime#865]
For some reason, the generated API documentation is using `<pre>` elements for inline code, which looks awful.

e.g. given

```csharp
/// <summary>
/// Returns a Persian (also known as Solar Hijri) calendar system implementing the behaviour of the
/// BCL <code>PersianCalendar</code> from .NET 4.6 onwards (and Windows 10), and the astronomical
/// system described in Wikipedia and Calendrical Calculations.
/// </summary>
```
— https://github.com/nodatime/nodatime/blob/cb717e2/src/NodaTime/CalendarSystem.cs#L679,L683

we end up with:

```html
<div class="markdown level1 summary">
Returns a Persian (also known as Solar Hijri) calendar system implementing the behaviour of the
BCL <pre><code>PersianCalendar</code></pre> from .NET 4.6 onwards (and Windows 10), and the astronomical
system described in Wikipedia and Calendrical Calculations.
</div>
```

which looks fairly awful: http://nodatime.org/2.0.x/api/NodaTime.CalendarSystem.html#NodaTime_CalendarSystem_PersianArithmetic

**Comment by lundmikkel** [comment]
Isn't `<c>` used for inline code, @jskeet?

**Comment by jskeet** [comment]
@lundmikkel: Are you talking in the XML documentation or the HTML output? It's docfx that's turning it into `<pre><code>...</code></pre>`.

**Comment by lundmikkel** [comment]
Ah. Yes, I'm talking about XML documentation.

**Comment by jskeet** [comment]
Right. No problem then :)

**Comment by jskeet** [comment]
It's possible that using `<c>` instead of `<code>` would fix this, actually. Will give it a try.

**Comment by jskeet** [comment]
And indeed, it looks like that's the case. This should be easy to fix - at least for the unstable branch. Slightly more work to do across all versions...
