### ISSUE TITLE
Fix documentation about the PCL profile

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime#867]
We still have plenty of documentation about a "PCL" version of Noda Time, but from 2.0, that really should be the netstandard1.3 version (vs. the net45 version).

Basically, anything in the 2.0.x or unstable documentation that refers to "PCL" should probably be updated to refer to ".NET Standard 1.3" (I think?). I'm not entirely sure how we should refer to the net45 version - ".NET Framework 4.5"? (though there's some overlap, since AIUI netstandard1.3 implies version 4.5 of the .NET framework?).

(We still use the `PCL` constant to disable code that doesn't build in netstandard1.3, but that's purely internal.)

**Comment by malcolmr** [comment]
(Or should we instead be talking about ".NET Core 1.0"?)

**Comment by jskeet** [comment]
Yes, we should definitely do this - and talk about ".NET Standard 1.3" vs ".NET 4.5". (In particular, we *don't* target .NET Core - targeting netstandard1.3 allows us to work on .NET Core, but other platforms such as UWP will use the netstandard1.3 assembly too.)

**Comment by jskeet** [comment]
It may be worth updating the preprocessor symbol at the same time, to a) simplify the project files; b) make the code mean what it says; c) make it easier to find "PCL" where it's in comments instead...
