### ISSUE TITLE
Serializing with StringEnumConverter fails to Deserialize

### ISSUE THREAD

**Issue by Lavinski** [nodatime/nodatime#872]
Note this is without using `nodatime.serialization`

It appears the constructor for `LocalDate` is expecting an `int` for `Calendar` (looks like it can only be iso). However, when using `StringEnumConverter` this constructor fails to match and an exception is thrown.

**Comment by jskeet** [comment]
What does the code look like? What is `StringEnumConverter`? Which `LocalDate` constructor are you talking about? Which version of Noda Time are you using?
 We're missing a lot of context for this.

If you're trying to serialize and deserialize JSON, I would *strongly* recommend using `NodaTime.Serialization.JsonNet` - or writing your own equivalent for the JSON parser you're using - rather than assuming it will just work as if it were a regular mutable entity.

I strongly suspect I'm going to close this as basically an unsupported scenario, but more information would make it a lot easier to tell.

**Comment by Lavinski** [comment]
Hi Jon, thanks for the response. I'll try and be a bit more clear about what the issue is.

First I'd like to note that we are using `NodaTime.Serialization.JsonNet`, it's pretty clear this is the preferred and best way to serialise dates as JSON. Without `NodaTime.Serialization.JsonNet` any changes to constructors, properties or structure would break things when deserializing. 

However, along the way, we discovered this issue. So I thought I'd make a record of it here.

*Versions*
`NodaTime 2.0.3`
`Json.Net 10.0.3`

*Issue Description*
A standard Json.Net serializer cannot deserialize a `LocalDate` with the `StringEnumConverter`. This could be a common failure case which produces a poor error message. Or if the settings cannot be changed for any reason would mean NodaTime types cannot be serialised.

*Code to reproduce*
```
var settings = new JsonSerializerSettings();
settings.Converters.Add(new StringEnumConverter());

var localDate = new NodaTime.LocalDate();
var json = JsonConvert.SerializeObject(localDate, settings).Dump();
//Output: {"year":1,"month":1,"day":1,"calendar":"Iso"}

JsonConvert.DeserializeObject<LocalDate>(json, settings).Dump();
//Exception: FormatException
```
*Stacktrace*
```
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.String.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonFormatterConverter.GetTokenValue[T](Object value)
   at Newtonsoft.Json.Serialization.JsonFormatterConverter.ToInt32(Object value)
   at System.Runtime.Serialization.SerializationInfo.GetInt32(String name)
   at NodaTime.LocalDate..ctor(SerializationInfo info)
```

**Comment by jskeet** [comment]
I think I'd just stop at "A standard Json.NET serializer cannot deserialize a `LocalDate`".

Thanks for recording it for posterity (hopefully making it discoverable for others) - but I don't think there's anything we really want to do here to change the code.
