### ISSUE TITLE
DateInterval operators still contain references to endpoint inclusion

### ISSUE THREAD

**Issue by lundmikkel** [nodatime/nodatime#878]
This is true for the [== operator](https://github.com/nodatime/nodatime/blob/master/src/NodaTime/DateInterval.cs#L74-L78), the [!= operator](https://github.com/nodatime/nodatime/blob/master/src/NodaTime/DateInterval.cs#L98-L102), and the [Equals method](https://github.com/nodatime/nodatime/blob/master/src/NodaTime/DateInterval.cs#L111-L115).

**Comment by jskeet** [comment]
Humbug - not sure how I missed that. Thanks, will fix and backport, then regenerate all documentation. (There's no reason we'd want to keep the 2.0 docs like that.)
