### ISSUE TITLE
Confusing naming for NodaTime.Extensions.IsoDayOfWeekExtensions.ToIsoDayOfWeek

### ISSUE THREAD

**Issue by samcic** [nodatime/nodatime#880]
From: http://nodatime.org/2.0.x/api/NodaTime.Extensions.IsoDayOfWeekExtensions.html

This extension method takes an IsoDayOfWeek and returns a DayOfWeek. I would have hence thought it should be named "ToDayOfWeek" rather than "ToIsoDayOfWeek". Perhaps I'm missing something obvious...

**Comment by jskeet** [comment]
Duplicate of https://github.com/nodatime/nodatime/issues/776
