### ISSUE TITLE
Website considers 2.1.0-beta01 as newer than 2.1.0

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime#905]
See http://nodatime.org/downloads/. The betas released for 2.1.0 and 1.4.0 appear before the unsuffixed final release, even though the date is later.

(I think this is why the front page still lists the beta as "latest".)

Sorting by version number does make sense, but the beta/RC releases should precede the final releases.

**Comment by jskeet** [comment]
Humbug. I suspect we never spotted that before because we didn't have the pre-release zip files in GCS.
Simple temporary solution: I'll remove the 2.1.0-beta01 zip files. I'll try to fix the actual bug amongst all the other web site fixes tomorrow.
