### ISSUE TITLE
Clock time resolution

### ISSUE THREAD

**Issue by zedr0n** [nodatime/nodatime#907]
I am using NodaTime to timestamp events in event sourced architecture so I rely on this timestamp to then replay events in the correct order. I've noticed an intermittent issue where the time is not advancing. From my log I see

<pre>CreateAccountCommand! -> CreateAccountHandler
@Account : 
AccountCreated( 2017-07-10T23:08:53.8881636Z )

CreatePurchaseCommand! -> CreatePurchaseHandler
@Purchase : 
PurchaseCreated( 2017-07-10T23:08:53.8881636Z ) </pre>
I've managed to fix it by autoadvancing time in my Time provider class 
<pre>
            var now = _clock.GetCurrentInstant();
            // if we process events faster than clock ticks
            // manually increment the time
            if (now.CompareTo(_current) <= 0)
                _current = _current.PlusNanoseconds(1);
            else
                _current = now;
</pre>

but I am wondering if I am missing something here and I'm not using the clock instance properly?
 
In fixed log I see
<pre> CreateAccountCommand! -> CreateAccountHandler
@Account : 
AccountCreated( 2017-07-11T17:36:20.6231303Z )

CreatePurchaseCommand! -> CreatePurchaseHandler
@Purchase : 
PurchaseCreated( 2017-07-11T17:36:20.623130301Z ) </pre>

**Comment by jskeet** [comment]
That's not really a Noda Time issue - it's just the resolution of the system clock. `SystemClock.Instance` just uses `DateTime.UtcNow.Ticks` behind the scenes - Noda Time can't provide a more accurate clock than that, unless you want to use NTP or similar.

**Comment by zedr0n** [comment]
I see, thanks, it just should take more time to process the command really, in-between the two there was a write to DB ( this in inmemory instance so not hitting the disk but still ) so it seems like the clock stalled

**Comment by jskeet** [comment]
The clock isn't "running" at all - every time you ask for an instant, it checks `DateTime.UtcNow`. But the system clock resolution may be as coarse as 15ms. (It's more typically 1ms these days, I believe, but it's environment-specific.)

**Comment by zedr0n** [comment]
Yes, seems like stackoverflow answers for DateTime states similar resolution. Just a bit unfortunate when Instants are up to 1ns so I assume same accuracy from clock. But as you say, it's not Nodatime issue in the end unless some additional logic is implemented to check if datetime.utc now is the same between calls.
