### ISSUE TITLE
Duration patterns with only one "total" value and no sign are invalid

### ISSUE THREAD

**Issue by icalvo** [nodatime/nodatime#913]
"D" and "HH", for example, are invalid patterns (you must use "-D" or "-HH", thus allowing for negative durations).

**Comment by jskeet** [comment]
Well they're not invalid patterns as such - they just don't include the sign at all. I'm not sure what you're suggesting here - should we reject them entirely? That would be a breaking change which could affect code which will always work properly (because it only ever formats non-negative values).

**Comment by icalvo** [comment]
Duration.CreateWithInvariantCulture("HH") throws an InvalidPatternException, so it seems that the code does not agree with you. Same with "D".

**Comment by jskeet** [comment]
I only tried `HH` which *does* work for me, but `D` doesn't. But `D` not working is fine, because that's being treated as a standard pattern, as it's a single character - you'd need to use `%D`, which works fine.

Which version of Noda Time are you using? (I'm testing with 2.2.0.)

**Comment by icalvo** [comment]
Yes, I was trying "H", not "HH", sorry. Then the problem I see is that "D" and "H" are not Standard Duration Patterns (the only one is "o"), so they shouldn't need escaping when using DurationPattern.Create. Now I must know every Standard Pattern (not only the ones for the Noda type I'm using) to know what to escape. Also you'll need to be careful, when adding a new Standard Pattern, that it doesn't match any of the Custom Patterns for every Noda type, otherwise it'll be a breaking change.

**Comment by icalvo** [comment]
On second thought, adding a new Standard Pattern is a breaking change anyway. But the other argument stands :)

**Comment by jskeet** [comment]
No, it's never a breaking change to add a standard pattern, because by definition *any* single-character pattern is treated as a standard pattern. That's what the `%` character is there for - it allows the use of a single-character custom pattern. I'll clarify the user guide on that front when I get a chance. (A whole section on standard vs custom patterns wouldn't go amiss.)

**Comment by icalvo** [comment]
The fundamental bit that is lacking in the documentation is that a single character is ALWAYS interpreted as a Standard Pattern even if it would make sense as a Custom Pattern.

**Comment by jskeet** [comment]
Indeed. That's somewhat implicit in the description of `%`:

> Escape to force a single-character custom pattern to be treated as such.

... but I'll make it more explicit. I think we can close this issue now...
