### ISSUE TITLE
Instant API documentation incorrectly defines Instant as a 'number of ticks'

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime#922]
> An instant is defined by an integral number of 'ticks' since the Unix epoch (typically described as January 1st 1970, midnight, UTC, ISO calendar), where a tick is equal to 100 nanoseconds. There are 10,000 ticks in a millisecond.
— http://nodatime.org/2.2.x/api/NodaTime.Instant.html

(I don't have time to fix this right now, and we should also check for other occurrences.)

**Comment by jskeet** [comment]
Whoops - well spotted. I'll fix occurrences I can find today.

**Comment by malcolmr** [comment]
Thanks. I think this is probably okay to just fix going forward.
