### ISSUE TITLE
Coverage measurement appears to have stalled

### ISSUE THREAD

**Issue by malcolmr** [nodatime/nodatime#925]
Coveralls appears to be stuck: https://coveralls.io/github/nodatime/nodatime?branch=master

Not sure whether it's completely broken, or we've misconfigured something.

**Comment by jskeet** [comment]
OpenCover doesn't support portable pdbs and the newer dotnet sdk basically. In google-cloud-dotnet we've moved to dotCover and codecov... We could potentially do the same here.

**Comment by jskeet** [comment]
Fixed to use dotcover/codecov in #954.
