### ISSUE TITLE
Improve benchmark navigation and display

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime#937]
The benchmark display we currently have is reasonably functional, but far from pretty.

Currently, the data model is all in-memory, which should make it fairly easy to do all kinds of cool things without worrying about accessing too much data. If/when we move to something like Spanner, we'll need to revisit all the visualizations, but that can wait...

I'm very happy to go over the data model in more detail with interested parties. The code is just ASP.NET Core, in a pretty simple way. Ideas for other styles of navigation and visualization welcome - pull requests even more welcome!

**Comment by SacuL** [comment]
Hi @jskeet ,

I'm looking for a project I can contribute as a learning experience. 
So I've read the contribution guidelines and found this issue.
What do you think about this issue, is it still relevant? Should I start with it?

Thanks,

Lucas.

**Comment by jskeet** [comment]
Absolutely. Have a look round https://nodatime.org/benchmarks to get a feel for the current UI in all its crude form. The code is in https://github.com/nodatime/nodatime/tree/master/src/NodaTime.Web - if you run it locally you probably won't be able to get at the benchmark data, but I can work out a workaround for that (maybe loading it from a local directory, and I can give you a zip file to expand?).

But take your time - there's no rush. If you end up feeling it's not a good fit for you, that's absolutely fine.

**Comment by SacuL** [comment]
Great! I'll take a look around the code and get back to you about the bechmark data.

Thanks.

**Comment by shaddu** [comment]
Hi @jskeet ,

I will like to help in this issue if no one is working on it.

THanks

**Comment by jskeet** [comment]
@shaddu: That's fantastic! There's one potential difficulty with working on it right now, which is that we're right at the bleeding edge - most projects require Visual Studio 2019 preview 2 (and the corresponding .NET Core SDK). If that's not a problem for you, I can have a look at either loading the benchmark data locally, or sorting out something similar for you.

**Comment by shaddu** [comment]
@jskeet  I can see  Visual Studio 2019 preview and can install it along with .Net Core SDK. How to make sure that it is a preview 2 ?

**Comment by jskeet** [comment]
If you just download the latest preview, it'll be fine :) I'll see if I can find some time later on today to work out an easy way of loading the benchmarks locally.

**Comment by jskeet** [comment]
@shaddu: #1288 (which I'll merge shortly) supports loading the benchmarks locally, and has a link to a large zip file with our current set of benchmarks.

To stop the site from attempting to load things from Google Cloud Storage, just set the `DISABLE_GCS` environment variable to anything - or edit Startup.cs :)
Do let me know if you run into any issues :)

**Comment by shaddu** [comment]
@jskeet  After few issues I am finally able to run the project :) with vs2019 & .net core sdk 3.0. Still one strange issue that `env.ContentRootPath` is evaluating to my NodaTime.Web directory but the docfx & benchmarks folder are in build folder. So for now i have changed the path for docfx , should i extract the benchmarks in build folder and change the path for it also ?

**Comment by jskeet** [comment]
Could you clarify what you mean by "in build folder"? I'd normally have both of those directories directly in `NodaTime.Web`.

**Comment by shaddu** [comment]
`build` folder is the folder in the root directory and the `docfx` folder was also only under `build` folder and not `NodaTime.Web`

![d-structure](https://user-images.githubusercontent.com/16138402/53264863-a4f50b00-36d4-11e9-9516-8209672806ce.png)

**Comment by jskeet** [comment]
Ah, I see. That docfx folder isn't the one you want, but you could either run buildapidocs.sh from build, or just create an empty docfx directory in NodaTime.Web - that should be fine. For benchmarks, just unzip the file there yourself :)

**Comment by shaddu** [comment]
@jskeet able to run the project, do you have any specific ideas for new themes :) or should i experiment all along

**Comment by jskeet** [comment]
It's not so much about themes, as usability for exploring benchmarks. Whatever you think might work well :)
