### ISSUE TITLE
Parsing and formating same value doesn’t work

### ISSUE THREAD

**Issue by Msirkovsky** [nodatime/nodatime#969]
I would like to represent date and time in ZonedDateTime and serialize value like this "2017-09-07T11:13:12:03+02".
I can format the ZonedDateTime but if I try to parse back formatted string I get this exception:

> "The specified offset is invalid for the given date/time"

I believe that this code should work. Am I missing something?
I use version 2.2.0
```
var pattern = ZonedDateTimePattern
    .CreateWithInvariantCulture("yyyy-MM-ddTHH:mm:ss:ffo<G>", DateTimeZoneProviders.Tzdb);
            
var pragueTime = DateTimeZoneProviders.Tzdb["Europe/Prague"];
var zonedDate = SystemClock.Instance.GetCurrentInstant().InZone(pragueTime);

var str = pattern.Format(zonedDate); //str = 2017-09-07T11:13:12:03+02
var zonedDateParsed = pattern.Parse(str); 
            
//this throw exception "The specified offset is invalid for the given date/time. Value being parsed: '2017-09-07T11:11:16:12+02"
var val = zonedDateParsed.GetValueOrThrow(); 

```

Thank you.

**Comment by jskeet** [comment]
The problem is that your format doesn't actually indicate a time zone - just a UTC offset. Because of that, the time zone is assumed to be the same as the template value (UTC), and the offset is then validated.

Your options are:

- Include the zone ID in your format string
- Use `OffsetDateTime` instead of `ZonedDateTime`, if you really only want to persist the offset

**Comment by malcolmr** [comment]
Or presumably set the timezone in the template value (`ZonedDateTimePattern.Create(..., ZonedDateTime templateValue)`) if it's known out-of-band (such as if it's a user's preferred timezone)?

(Which might mean creating a pattern on every parse operation, but I don't think that can be helped.)

**Comment by jskeet** [comment]
@malcolmr: Yup, that would do it too - although I'd definitely suggest parsing as an `OffsetDateTime` instead and then converting it into a particular zone.
