### ISSUE TITLE
nodatime.org https issues

### ISSUE THREAD

**Issue by mj1856** [nodatime/nodatime#998]
Due to [Google's https mandate](https://security.googleblog.com/2016/09/moving-towards-more-secure-web.html), visiting http://nodatime.org in Chrome gives a security info icon:

![image](https://user-images.githubusercontent.com/1396388/31787954-136706ce-b4c2-11e7-92fe-4a0a9d37ebd4.png)

My understanding is that this also affects search engine rankings.

Visiting https://nodatime.org gives a cert warning, because it just has the *.azurewebsites.net wildcard cert installed.

We need:
- A custom SSL certificate for nodatime.org
- A redirect from http to https

There are lots of approaches to both, but I recommend doing what I did recently, which is:
1. Install the [Azure Let's Encrypt](http://www.siteextensions.net/packages/letsencrypt) site extension
2. Install the [Redirect HTTP to HTTPS](http://www.siteextensions.net/packages/RedirectHttpToHttps/) site extension

There are some guides here:
https://github.com/sjkp/letsencrypt-siteextension/wiki/How-to-install
and here:
https://www.troyhunt.com/everything-you-need-to-know-about-loading-a-free-lets-encrypt-certificate-into-an-azure-website/

**Comment by mj1856** [comment]
If you want me to do it, add me as an co-admin on your azure subscription and I'll take care of it all.

**Comment by jskeet** [comment]
Will probably give it a try myself when I get a chance (maybe over the weekend) and default back to adding you if I run into problems - it's probably useful for me to know about anyway  :)

**Comment by jskeet** [comment]
Yikes - I've got about half way there now (the extension is installed, but I haven't configured everything yet). It doesn't help that the Azure portal keeps changing, so the UI I'm using doesn't quite match any of the installation guides :(

Need to shop now, but will finish up later with any luck.

**Comment by jskeet** [comment]
Scratch that - done a lot more, and https://nodatime.org now lives!

**Comment by jskeet** [comment]
Redirect extension now installed too. 

That currently also redirects http://nodatime.org/tzdb/index.txt to https://nodatime.org/tzdb/index.txt, but the links served on that URL are http... we should probably update those to HTTPS as well. Hopefully the redirection itself won't cause customer problems; I think it's better to do *everything* via HTTPS if we possibly can. Will close this and file a separate issue for HTTP URLs served.
